import test from 'node:test';
import assert from 'node:assert/strict';
import { ALPHA_SOCIAL_CONTEXT_SCHEMA, alphaSocialReferences, isAlphaSocialContext, mapAlphaPublicActor, readAlphaSocialResponse, type AlphaSocialContext } from './projection';
import { ALPHA_SCHEMA, type AlphaAccount } from '../alpha-persistence/contract';
import { PROGRAM_SCHEMA } from '../contract';
import { createProgramPrivateSpace, validateProgramData, validateProgramEnvelope } from '../program-data';
import { materializeAccount } from '../alpha-persistence/program-adapter';
import { publishProgramFlow, createProgramProposal } from '../publication';
const owner='11111111-1111-4111-8111-111111111111';
const alias=(n:number)=>`member-22222222-2222-4222-8222-${String(n).padStart(12,'0')}`;
function fixture(count=3){const account:AlphaAccount={schema:ALPHA_SCHEMA,ownerId:owner,revision:0,source:{schema:PROGRAM_SCHEMA,actorId:owner,revision:0},space:createProgramPrivateSpace(),legacyReceipts:[],legacyUndo:[]};const context:AlphaSocialContext={schema:ALPHA_SOCIAL_CONTEXT_SCHEMA,revision:0,ownActorId:alias(1),actors:Array.from({length:count},(_,i)=>({id:alias(i+1),name:`Member ${i+1}`})),public:{flows:[],versions:[],posts:[],replies:[],reactions:[],proposals:[]}};return {account,context};}
test('nine service actors materialize empty foreign spaces but never validate as local envelope',()=>{const f=fixture(9);assert(isAlphaSocialContext(f.context));const e=materializeAccount(f.account,alphaSocialReferences(f.context,owner));assert(validateProgramData(e.data));assert.equal(Boolean(validateProgramEnvelope(e)),false);assert(validateProgramEnvelope(e,{allowAlphaProjection:true}));assert.equal(e.data.actors.length,9);assert.deepEqual(e.data.spaces[alias(2)],createProgramPrivateSpace());assert.equal(e.data.activeActorId,owner);});
test('public alias mapping changes identity slots only, not content strings or ids',()=>{const f=fixture();const data=materializeAccount(f.account,alphaSocialReferences(f.context,owner)).data;const r=publishProgramFlow(data,{actorId:owner,requestId:'pub',title:owner,summary:alias(1),category:'test',situations:[],source:{kind:'user-text',label:'own',url:null,checkedAt:null},items:[{id:'item',title:'T',description:'',completionCriteria:'',sourceUrl:null,schedule:{kind:'undated'},subchecks:[]}]},'2026-09-21T00:00:00.000Z');if(!r.ok)throw Error(r.reason);const mapped=mapAlphaPublicActor(r.data.public,owner,alias(1));assert.equal(mapped.flows[0].ownerId,alias(1));assert.equal(mapped.versions[0].createdBy,alias(1));assert.equal(mapped.versions[0].title,owner);assert.equal(mapped.versions[0].summary,alias(1));assert.equal(mapped.versions[0].id,r.result);});
test('browser projection rejects third-party proposals but trusted server projection accepts',()=>{const f=fixture();let data=materializeAccount(f.account,alphaSocialReferences(f.context,owner)).data;const p=publishProgramFlow(data,{actorId:alias(2),requestId:'pub',title:'T',summary:'',category:'test',situations:[],source:{kind:'user-text',label:'own',url:null,checkedAt:null},items:[{id:'item',title:'T',description:'',completionCriteria:'',sourceUrl:null,schedule:{kind:'undated'},subchecks:[]}]},'2026-09-21T00:00:00.000Z');if(!p.ok)throw Error(p.reason);data=p.data;const proposed=createProgramProposal(data,{actorId:alias(3),requestId:'proposal',flowId:data.public.flows[0].id,baseVersionId:p.result,itemId:'item',reason:'Private review',patch:{title:'New'}},'2026-09-21T00:00:00.000Z');if(!proposed.ok)throw Error(proposed.reason);f.context.public=mapAlphaPublicActor(proposed.data.public,owner,alias(1));assert(!isAlphaSocialContext(f.context));assert(isAlphaSocialContext(f.context,{server:true}));});
test('combined read refuses foreign owner or unknown alias metadata',()=>{const f=fixture();assert(readAlphaSocialResponse({ok:true,value:f},owner));assert.equal(readAlphaSocialResponse({ok:true,value:f},'other'),null);assert(!isAlphaSocialContext({...f.context,email:'private@example.com'}));assert(!isAlphaSocialContext({...f.context,actors:[{id:owner,name:'UUID exposure'}]}));});
