import test from 'node:test';
import assert from 'node:assert/strict';
import { ALPHA_SOCIAL_CONTEXT_SCHEMA, alphaSocialReferences, type AlphaSocialContext } from './projection';
import { createAlphaLocalRecovery, alphaRecoveryKey, validateAlphaRecovery } from '../alpha-persistence/local-recovery';
import { ALPHA_SCHEMA, type AlphaAccount, type AlphaRecovery } from '../alpha-persistence/contract';
import { PROGRAM_SCHEMA } from '../contract';
import { createProgramPrivateSpace } from '../program-data';
import { isAccountForOwner } from '../alpha-auth/account-access';
const owner='11111111-1111-4111-8111-111111111111',alias='member-22222222-2222-4222-8222-222222222222';
function fixture(){const account:AlphaAccount={schema:ALPHA_SCHEMA,ownerId:owner,revision:0,source:{schema:PROGRAM_SCHEMA,actorId:owner,revision:0},space:createProgramPrivateSpace(),legacyReceipts:[],legacyUndo:[]};const context:AlphaSocialContext={schema:ALPHA_SOCIAL_CONTEXT_SCHEMA,revision:3,ownActorId:alias,actors:[{id:alias,name:'Member'}],public:{flows:[],versions:[],posts:[],replies:[],reactions:[],proposals:[]}};const value:AlphaRecovery={schema:'flowme-alpha-recovery/1',ownerId:owner,confirmed:account,references:alphaSocialReferences(context,owner),pending:{schema:'flowme-alpha-social-command/1',kind:'social',requestId:'reaction',expectedRevision:0,expectedPublicRevision:3,intent:{type:'reaction-set',targetKind:'post',targetId:'post',desired:true}},draft:null};return value;}
test('social recovery persists exact owner references and pending dual revision',()=>{const values=new Map<string,string>(),writes:string[]=[];const storage={getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>{writes.push(k);values.set(k,v);},removeItem:(k:string)=>{writes.push(k);values.delete(k);}};const a=createAlphaLocalRecovery(storage,isAccountForOwner);assert(a.load(owner).ok);const value=fixture();assert(a.save(value));const reopened=createAlphaLocalRecovery(storage,isAccountForOwner);assert.deepEqual(reopened.load(owner),{ok:true,value});assert(writes.every(k=>k.startsWith('flow:poc:personal-workspace:v1:')));assert.equal(writes.length,1);});
test('foreign owner and corrupt reference schema cannot be restored or repaired by write',()=>{const value=fixture();assert.equal(Boolean(validateAlphaRecovery(value,'other',isAccountForOwner)),false);const corrupt=structuredClone(value);(corrupt.references!.social as any).schema='wrong';assert.equal(Boolean(validateAlphaRecovery(corrupt,owner,isAccountForOwner)),false);const values=new Map([[alphaRecoveryKey(owner),JSON.stringify(corrupt)]]);let writes=0;const port=createAlphaLocalRecovery({getItem:k=>values.get(k)??null,setItem:()=>{writes++;},removeItem:()=>{writes++;}},isAccountForOwner);assert.equal(port.load(owner).ok,false);assert.equal(port.save(value),false);assert.equal(port.reset(owner),false);assert.equal(writes,0);});
test('unconfirmed recovery may not invent a trusted reference context',()=>{const value=fixture();value.confirmed=null;assert(!validateAlphaRecovery(value,owner,isAccountForOwner));});
