export type FlowContentSelectionTier =
  | 'p0_apply_to_ux12'
  | 'p1_evaluate_next'
  | 'p2_hold_or_support'
  | 'merge_or_replace';

export type FlowContentSelectionOrigin =
  | 'current_31'
  | 'current_32'
  | 'runtime_diversity_addition'
  | 'creator_source_breadth_addition'
  | 'creator_interaction_8';

export type FlowContentSelectionAudit = {
  id: string;
  title: string;
  origin: FlowContentSelectionOrigin;
  tier: FlowContentSelectionTier;
  category: string;
  interactionScore: number;
  executionScore: number;
  uiFitScore: number;
  riskScore: number;
  supplySignalScore: number;
  totalScore: number;
  reason: string;
  ux12Action: string;
};

export type AdditionalSourceLead = {
  title: string;
  category: string;
  sourceUrl: string;
  interactionSignal: string;
  flowPotential: string;
  useFor: 'new_candidate' | 'source_replacement' | 'supporting_evidence';
};

export const flowContentSelectionAudits: FlowContentSelectionAudit[] = [
  {
    id: 'computer-skills-source-rounds',
    title: '컴활 2급 실기 기출 회차 풀이표',
    origin: 'creator_interaction_8',
    tier: 'p0_apply_to_ux12',
    category: '공부/자격증',
    interactionScore: 5,
    executionScore: 5,
    uiFitScore: 5,
    riskScore: 5,
    supplySignalScore: 5,
    totalScore: 5,
    reason: '댓글, 오류 제보, 회차별 파일, 유튜브 링크가 있어 제작자-사용자 상호작용과 실행 단위가 모두 강하다.',
    ux12Action: '회차 표 + 오늘 풀 회차 캘린더 + 오답/재풀이 상세를 대표 공부 Flow로 넣는다.',
  },
  {
    id: 'computer-skills-practical-5day',
    title: '컴활 2급 실기 5일 실습 커리큘럼',
    origin: 'creator_interaction_8',
    tier: 'p0_apply_to_ux12',
    category: '공부/자격증',
    interactionScore: 4,
    executionScore: 5,
    uiFitScore: 5,
    riskScore: 5,
    supplySignalScore: 5,
    totalScore: 4.8,
    reason: '5일차 시리즈, 숙제, 자료, 후기 흐름이 있어 시험일 기준 타임라인으로 바로 변환된다.',
    ux12Action: '시험 D-5~D-1 일정과 자료/숙제 체크리스트를 생성하는 대표 study timeline으로 검증한다.',
  },
  {
    id: 'new-apartment-precheck',
    title: '신축 아파트 입주 사전점검 체크',
    origin: 'creator_interaction_8',
    tier: 'p0_apply_to_ux12',
    category: '주거/입주',
    interactionScore: 4,
    executionScore: 5,
    uiFitScore: 5,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4.6,
    reason: '준비물, 구역별 하자 점검, 대행업체 판단, 보완 요청까지 결정형 체크리스트 구조가 선명하다.',
    ux12Action: '사진은 선택으로 두고 하자 위치/메모/제출 상태를 중심으로 decision checklist UX를 검증한다.',
  },
  {
    id: 'washer-tub-clean-monthly',
    title: '세탁기 통세척 월간 관리',
    origin: 'current_31',
    tier: 'p0_apply_to_ux12',
    category: '가전 관리',
    interactionScore: 3,
    executionScore: 5,
    uiFitScore: 5,
    riskScore: 5,
    supplySignalScore: 5,
    totalScore: 4.6,
    reason: '사용자 입력이 시작일/반복/세탁기 종류로 가볍고 반복 관리 수요가 넓다.',
    ux12Action: '반복 루틴 대표 후보로 유지하되 방법/준비물/링크는 메모에 넣는다.',
  },
  {
    id: 'lg-aircon-filter-biweekly',
    title: '에어컨 필터 2주 청소',
    origin: 'current_31',
    tier: 'p0_apply_to_ux12',
    category: '가전 관리',
    interactionScore: 3,
    executionScore: 5,
    uiFitScore: 5,
    riskScore: 5,
    supplySignalScore: 5,
    totalScore: 4.6,
    reason: '브랜드 공식 기준과 2주 반복이 명확해 반복 Flow의 기본형을 검증하기 좋다.',
    ux12Action: '캘린더에는 필터 청소 1개, 상세에는 물세척/교체 확인/송풍 건조 체크를 둔다.',
  },
  {
    id: 'wedding-12-month-timeline',
    title: '결혼 준비 D-300 타임라인',
    origin: 'current_31',
    tier: 'p0_apply_to_ux12',
    category: '생활 이벤트',
    interactionScore: 4,
    executionScore: 5,
    uiFitScore: 4,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4.6,
    reason: '기준일 타임라인, 많은 준비 항목, 사용자 수요가 강하다. 다만 UI 밀도 검증이 필요하다.',
    ux12Action: '기준일 이동과 D-day 상세 표시를 검증하는 대표 timeline으로 유지한다.',
  },
  {
    id: 'moving-d30-checklist',
    title: '이사 D-30 체크리스트',
    origin: 'current_31',
    tier: 'p0_apply_to_ux12',
    category: '생활 이벤트',
    interactionScore: 3,
    executionScore: 5,
    uiFitScore: 4,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4.5,
    reason: '이사일 기준 일정과 체크리스트가 FlowMe 캘린더 검증에 직접 맞는다.',
    ux12Action: '현재 moving UX 연속 후보로 유지하고 캘린더 밀도와 상세 sheet를 검증한다.',
  },
  {
    id: 'used-car-buying-check',
    title: '중고차 후보 점검 체크',
    origin: 'current_31',
    tier: 'p0_apply_to_ux12',
    category: '차량/구매',
    interactionScore: 4,
    executionScore: 5,
    uiFitScore: 4,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4.5,
    reason: '완료보다 구매/보류/거절 결정이 핵심이라 FlowMe 차별점을 검증하기 좋다.',
    ux12Action: '사진 증빙 기본값은 빼고 체크리스트와 구매/보류/거절 버튼을 우선한다.',
  },
  {
    id: 'japan-esim-setup-before-departure',
    title: '일본 eSIM 출국 전 등록 체크',
    origin: 'creator_interaction_8',
    tier: 'p0_apply_to_ux12',
    category: '여행 준비',
    interactionScore: 4,
    executionScore: 5,
    uiFitScore: 5,
    riskScore: 4,
    supplySignalScore: 4,
    totalScore: 4.5,
    reason: '구매, QR 등록, 출국 전 설정, 도착 후 데이터 ON 단계가 날짜와 잘 맞는다.',
    ux12Action: '출국일 기준 D-2/D-1/도착일 캘린더와 메모 링크 UX를 검증한다.',
  },
  {
    id: 'alt-phone-sk7-self-activation',
    title: '알뜰폰 SK7 셀프개통 체크',
    origin: 'runtime_diversity_addition',
    tier: 'p0_apply_to_ux12',
    category: '통신/디지털 준비',
    interactionScore: 4,
    executionScore: 5,
    uiFitScore: 5,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4.6,
    reason: '유심 준비, 번호이동 사전동의, 셀프개통 완료, 유심 교체/재부팅처럼 기존 생활관리 후보와 다른 온라인 절차형 실행 단위가 선명하다.',
    ux12Action: '개통 예정일 알림 + 페이지 안 순서형 체크리스트를 검증하되 개인정보 입력값은 저장하지 않는다.',
  },
  {
    id: 'infant-health-checkup-prep',
    title: '영유아 건강검진 예약 준비',
    origin: 'runtime_diversity_addition',
    tier: 'p0_apply_to_ux12',
    category: '육아/행정',
    interactionScore: 3,
    executionScore: 5,
    uiFitScore: 5,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4.5,
    reason: '검진 가능 기간, 기관 예약, 문진표/발달선별 작성, 등록번호 전달이 공식 안내 기반의 방문 준비 타임라인으로 잘 나뉜다.',
    ux12Action: '의료 기록 UI로 확장하지 않고 D-14/D-10/D-3/D-1/D-Day 방문 준비 일정과 공식 출처 분리를 검증한다.',
  },
  {
    id: 'dog-adoption-first-week',
    title: '강아지 입양 첫 주 체크',
    origin: 'current_31',
    tier: 'p0_apply_to_ux12',
    category: '반려동물',
    interactionScore: 4,
    executionScore: 5,
    uiFitScore: 4,
    riskScore: 4,
    supplySignalScore: 4,
    totalScore: 4.4,
    reason: '입양일 기준 준비물/환경/병원/등록 흐름이 명확하다. 건강 판단은 boundary가 필요하다.',
    ux12Action: '입양일 타임라인과 첫 주 체크리스트를 반려동물 대표 후보로 넣는다.',
  },
  {
    id: 'college-dorm-move-in-checklist',
    title: '대학교 기숙사 입사 준비물 체크',
    origin: 'runtime_diversity_addition',
    tier: 'p1_evaluate_next',
    category: '학생/생활전환',
    interactionScore: 5,
    executionScore: 5,
    uiFitScore: 4,
    riskScore: 5,
    supplySignalScore: 5,
    totalScore: 4.8,
    reason: '최신 기숙사 공지와 학기별 PDF가 입사일, 제출서류, 반입금지 물품, D-Day 접수와 시설점검을 학교별로 다르게 안내해 기존 이사·결혼과 다른 학생 생활 전환 UX를 만든다.',
    ux12Action: '입사일 기준 timeline 후보로 보되, 첫 행동은 최신 학교별 공식 공지 확인으로 두고 개인 준비물 예시는 보조 메모로만 둔다.',
  },
  {
    id: 'elementary-school-entry-d30',
    title: '초등학교 입학 D-30 준비 체크',
    origin: 'runtime_diversity_addition',
    tier: 'p1_evaluate_next',
    category: '학부모/입학준비',
    interactionScore: 4,
    executionScore: 5,
    uiFitScore: 4,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4.5,
    reason: '입학식 날짜 기준 취학통지, 예비소집, 먼저 살 물건, 학교 안내 전 보류, 이름표, 등교 동선이 선명하다. 공식 안내와 학부모 체크리스트를 분리해야 한다.',
    ux12Action: 'D-30 캘린더와 준비물 체크를 함께 보여주되 구매 추천 UI가 아니라 공식 안내 확인, 보류 항목 분리, 이름 붙이기 중심으로 만든다.',
  },
  {
    id: 'kids-printable-squishy-craft',
    title: '아이 도안 스퀴시 만들기 준비',
    origin: 'runtime_diversity_addition',
    tier: 'p1_evaluate_next',
    category: '육아/도안놀이',
    interactionScore: 4,
    executionScore: 5,
    uiFitScore: 5,
    riskScore: 4,
    supplySignalScore: 4,
    totalScore: 4.4,
    reason: '도안 저장, 출력, 재료 준비, 놀이 당일 실행이 명확해 기존 육아 행정/독서 후보와 다른 제작자 자료형 Flow를 검증할 수 있다.',
    ux12Action: '원문 도안을 복제하지 않고 도안 링크와 재료 체크, 놀이 날짜만 남기는 lightweight checklist UX를 본다.',
  },
  {
    id: 'anydesk-remote-setup-check',
    title: 'AnyDesk 원격 접속 준비 체크',
    origin: 'runtime_diversity_addition',
    tier: 'p1_evaluate_next',
    category: '디지털/원격지원',
    interactionScore: 4,
    executionScore: 5,
    uiFitScore: 4,
    riskScore: 3,
    supplySignalScore: 4,
    totalScore: 4,
    reason: '설치, ID 확인, 연결 수락, 세션 종료가 짧은 절차형 Flow에 맞는다. 다만 원격접속 보안과 민감 정보 미저장 boundary가 필요하다.',
    ux12Action: '캘린더보다 순서형 체크리스트로 표시하고 AnyDesk 주소/비밀번호/인증값은 입력 필드로 저장하지 않는다.',
  },
  {
    id: 'remote-help-session-precheck',
    title: '원격 도움 세션 권한 사전 체크',
    origin: 'runtime_diversity_addition',
    tier: 'p1_evaluate_next',
    category: '디지털/원격지원',
    interactionScore: 4,
    executionScore: 5,
    uiFitScore: 4,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4.3,
    reason: '공식 remote-help 문서들이 screen share, one-time remote control, repeated management를 분리하므로 특정 도구 설치보다 권한 선택과 closeout checklist가 더 강한 FlowMe artifact다.',
    ux12Action: 'trust/scope 확인을 첫 카드로 두고, permission method 선택, access value 미저장, close/review access를 4단계 체크로 보여준다. remote ID/password/code/link/token은 저장하지 않는다.',
  },
  {
    id: 'naver-search-advisor-site-readiness',
    title: 'Naver Search Advisor 사이트 준비 체크',
    origin: 'runtime_diversity_addition',
    tier: 'p1_evaluate_next',
    category: '디지털/검색설정',
    interactionScore: 4,
    executionScore: 5,
    uiFitScore: 4,
    riskScore: 4,
    supplySignalScore: 4,
    totalScore: 4.2,
    reason: 'Naver-first search-console setup has a concrete access/status/revisit artifact, but it must not become SEO scoring, DNS automation, or account integration.',
    ux12Action: 'site unit/access method를 첫 카드로 두고, ownership method status, robots/noindex readiness, sitemap/RSS/request status, revisit memo를 보여준다. ask developer/host admin은 정상 상태로 둔다.',
  },
  {
    id: 'fridge-cleanout-weekly-plan',
    title: '냉장고 파먹기 7일 재고 소진',
    origin: 'runtime_diversity_addition',
    tier: 'p1_evaluate_next',
    category: '집밥/식재료',
    interactionScore: 3,
    executionScore: 4,
    uiFitScore: 4,
    riskScore: 4,
    supplySignalScore: 4,
    totalScore: 3.8,
    reason: '재고 파악과 7일 메뉴 후보는 Flow화 가능하지만 절약 금액/효과 주장과 식단 관리로 커지지 않게 제한해야 한다.',
    ux12Action: '소진할 재료 3개와 7일 메뉴 후보 시트만 두고 영양/절약 보장 문구는 제외한다.',
  },
  {
    id: 'balcony-fall-vegetable-calendar',
    title: '베란다 가을 채소 파종·수확 캘린더',
    origin: 'runtime_diversity_addition',
    tier: 'p1_evaluate_next',
    category: '베란다텃밭/채소',
    interactionScore: 3,
    executionScore: 5,
    uiFitScore: 5,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4.4,
    reason: '월별 파종·수확 캘린더와 빛/물/통풍 체크가 있어 관엽식물 물주기와 다른 재배형 Flow를 검증할 수 있다.',
    ux12Action: '채소별 행이 있는 작은 시트와 파종/수확 후보일 캘린더를 함께 보여주되 매일 관찰 입력은 만들지 않는다.',
  },
  {
    id: 'self-wall-paint-weekend',
    title: '주말 셀프 벽 페인팅 준비',
    origin: 'runtime_diversity_addition',
    tier: 'p1_evaluate_next',
    category: '집꾸미기/셀프시공',
    interactionScore: 3,
    executionScore: 5,
    uiFitScore: 4,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4.2,
    reason: '준비물과 D-3/D-1/당일 작업 순서가 선명해 주말 프로젝트형 체크리스트 대표 후보가 된다.',
    ux12Action: '작업 날짜와 공간만 받아 준비/보양/칠하기/건조/정리 체크를 만들고 제품별 세부 정보는 메모에 둔다.',
  },
  {
    id: 'freelancer-income-tax-docs',
    title: '프리랜서 종합소득세 서류 준비',
    origin: 'runtime_diversity_addition',
    tier: 'p2_hold_or_support',
    category: '프리랜서/세금준비',
    interactionScore: 3,
    executionScore: 4,
    uiFitScore: 4,
    riskScore: 3,
    supplySignalScore: 4,
    totalScore: 3.6,
    reason: '서류 준비 체크리스트로는 가능하지만 세무 판단으로 보이면 위험하다. 공식/전문가 확인 boundary가 강해야 한다.',
    ux12Action: '신고 서비스가 아니라 자료 모으기 Flow로만 유지하고, 세액 계산/절세 판단 UI는 제외한다.',
  },
  {
    id: 'computer-license-2nd-written',
    title: '컴활 2급 필기 단기 공부',
    origin: 'current_31',
    tier: 'merge_or_replace',
    category: '공부/자격증',
    interactionScore: 4,
    executionScore: 4,
    uiFitScore: 4,
    riskScore: 5,
    supplySignalScore: 5,
    totalScore: 4.3,
    reason: '좋은 후보지만 제작자 상호작용 2개와 중복된다.',
    ux12Action: '별도 대표보다 컴활 study cluster 안에서 필기/실기 탭 또는 source variant로 합친다.',
  },
  {
    id: 'computer-skills-written-3day',
    title: '컴활 2급 필기 3일 회차 플랜',
    origin: 'creator_interaction_8',
    tier: 'merge_or_replace',
    category: '공부/자격증',
    interactionScore: 4,
    executionScore: 4,
    uiFitScore: 4,
    riskScore: 5,
    supplySignalScore: 5,
    totalScore: 4.3,
    reason: '댓글/PDF 공유 맥락은 강하지만 필기 단기 공부 후보와 겹친다.',
    ux12Action: '컴활 대표 Flow의 필기 variant로 합치고 단독 P0에서는 제외한다.',
  },
  {
    id: 'chiangmai-solo-trip-packing',
    title: '치앙마이 혼자 여행 준비물 체크',
    origin: 'runtime_diversity_addition',
    tier: 'p1_evaluate_next',
    category: '여행/장기체류',
    interactionScore: 4,
    executionScore: 5,
    uiFitScore: 4,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4.4,
    reason: '원문에 댓글, PDF 체크리스트, 유심/eSIM, GLN, 보험, 필터 샤워기 같은 준비물 단서가 있어 일반 여행 체크리스트보다 상황성이 강하다.',
    ux12Action: 'P1에서 혼자/장기체류 태그가 있는 checklist UX로 보고, 상품 링크는 메모로 내린다.',
  },
  {
    id: 'computer-skills-written-3day-summary',
    title: '컴활 2급 필기 3일 요약 플랜',
    origin: 'runtime_diversity_addition',
    tier: 'merge_or_replace',
    category: '공부/자격증',
    interactionScore: 4,
    executionScore: 4,
    uiFitScore: 4,
    riskScore: 5,
    supplySignalScore: 5,
    totalScore: 4.3,
    reason: '원문은 강하지만 기존 컴활 대표 Flow와 주제가 겹친다. 짧은 3일/PDF variant로 병합하는 편이 낫다.',
    ux12Action: '기존 컴활 study cluster 안에서 시험 직전 3일 플랜 variant로 둔다.',
  },
  {
    id: 'lease-contract-report-deadline',
    title: '주택 임대차계약 신고 준비',
    origin: 'runtime_diversity_addition',
    tier: 'p1_evaluate_next',
    category: '주거/행정',
    interactionScore: 4,
    executionScore: 5,
    uiFitScore: 4,
    riskScore: 3,
    supplySignalScore: 5,
    totalScore: 4.2,
    reason: '계약일 기준 30일 마감과 온라인 신고 절차가 선명하지만 법/행정 정보라 최신 공식 출처 보강이 필요하다.',
    ux12Action: '계약일 마감 캘린더 + 준비물 체크 + 공식 링크 분리 UX를 P1에서 검증한다.',
  },
  {
    id: 'stuckyi-overwater-prevention',
    title: '스투키 과습 방지 관리',
    origin: 'current_31',
    tier: 'p1_evaluate_next',
    category: '식물 관리',
    interactionScore: 4,
    executionScore: 4,
    uiFitScore: 5,
    riskScore: 5,
    supplySignalScore: 4,
    totalScore: 4.3,
    reason: '물주기보다 보류 판단이 핵심이라 루틴 상태 UX에 좋다.',
    ux12Action: 'P1로 두고 완료/보류 상태가 루틴에서 자연스러운지 검증한다.',
  },
  {
    id: 'japan-trip-packing',
    title: '일본 여행 준비물 체크',
    origin: 'current_31',
    tier: 'p1_evaluate_next',
    category: '여행',
    interactionScore: 4,
    executionScore: 4,
    uiFitScore: 4,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4.2,
    reason: '여행 준비 체크리스트 공급은 많지만 eSIM 후보가 더 실행 단위가 선명하다.',
    ux12Action: '여행 packing variant로 보관하고 eSIM/출국 D-7과 병합 가능성을 본다.',
  },
  {
    id: 'everland-family-trip-prep',
    title: '에버랜드 가족 방문 준비물 체크',
    origin: 'creator_interaction_8',
    tier: 'p1_evaluate_next',
    category: '여행/외출',
    interactionScore: 4,
    executionScore: 4,
    uiFitScore: 4,
    riskScore: 5,
    supplySignalScore: 4,
    totalScore: 4.2,
    reason: '준비물 리스트와 가족 공유 체크가 좋지만 특정 장소 Flow라 범용 대표성은 낮다.',
    ux12Action: '여행/외출 카테고리의 장소형 Flow 후보로 P1에 둔다.',
  },
  {
    id: 'after-move-address-report',
    title: '이사 후 전입신고·확정일자',
    origin: 'current_31',
    tier: 'p1_evaluate_next',
    category: '생활 이벤트',
    interactionScore: 3,
    executionScore: 4,
    uiFitScore: 4,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4.1,
    reason: '공식/행정 행동이 명확하지만 사용자가 자주 반복하는 컨텐츠는 아니다.',
    ux12Action: '이사 Flow의 하위 action으로 넣고 단독 대표에서는 제외한다.',
  },
  {
    id: 'travel-d7-checklist',
    title: '출국 7일 전 여행 준비',
    origin: 'current_31',
    tier: 'p1_evaluate_next',
    category: '여행',
    interactionScore: 3,
    executionScore: 4,
    uiFitScore: 4,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4.1,
    reason: '좋은 timeline이지만 eSIM/packing 같은 제작자 후기형 후보와 경쟁한다.',
    ux12Action: '여행 대표군에서는 eSIM과 비교 후 하나만 P0로 유지한다.',
  },
  {
    id: 'baby-food-four-week-menu',
    title: '초기 토핑 이유식 4주 식단표',
    origin: 'current_31',
    tier: 'p1_evaluate_next',
    category: '육아/식단',
    interactionScore: 2,
    executionScore: 5,
    uiFitScore: 4,
    riskScore: 3,
    supplySignalScore: 5,
    totalScore: 4.1,
    reason: '식단표 export에는 좋지만 건강/육아 민감도 때문에 기록 앱처럼 보이면 안 된다.',
    ux12Action: '캘린더 식단표 export 중심으로 P1에서 검증하고 반응 기록은 기본에서 뺀다.',
  },
  {
    id: 'child-weekend-play-rotation',
    title: '아이 주말 놀이 로테이션',
    origin: 'current_31',
    tier: 'p1_evaluate_next',
    category: '육아/놀이',
    interactionScore: 2,
    executionScore: 4,
    uiFitScore: 5,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4.1,
    reason: '놀이 카드 교체 UX에는 좋지만 사용자 상호작용 소스가 더 필요하다.',
    ux12Action: 'i-누리/제작자 놀이 자료를 더 찾아 콘텐츠 카드형 후보로 둔다.',
  },
  {
    id: 'picture-book-reading-routine',
    title: '그림책 읽기 루틴 + 질문 카드',
    origin: 'current_31',
    tier: 'p1_evaluate_next',
    category: '육아/독서',
    interactionScore: 2,
    executionScore: 4,
    uiFitScore: 5,
    riskScore: 5,
    supplySignalScore: 4,
    totalScore: 4.1,
    reason: '질문 카드 UX는 좋지만 현재 원문은 상호작용 신호보다 공식 자료 성격이 강하다.',
    ux12Action: '콘텐츠 카드형 UX 검증 후보로 두고 제작자 독서 루틴을 추가 조사한다.',
  },
  {
    id: 'korean-history-3-week',
    title: '한능검 3주 공부 플랜',
    origin: 'current_31',
    tier: 'p1_evaluate_next',
    category: '공부/자격증',
    interactionScore: 3,
    executionScore: 4,
    uiFitScore: 4,
    riskScore: 5,
    supplySignalScore: 5,
    totalScore: 4.1,
    reason: '3주 플랜은 명확하지만 컴활 후보군보다 자료/상호작용 신호가 약하다.',
    ux12Action: '공부 카테고리 확장 시 시험일 이동 UX 후보로 둔다.',
  },
  {
    id: 'water-purifier-filter-cycle',
    title: '정수기 필터 교체 주기 관리',
    origin: 'current_31',
    tier: 'p1_evaluate_next',
    category: '가전 관리',
    interactionScore: 2,
    executionScore: 4,
    uiFitScore: 4,
    riskScore: 5,
    supplySignalScore: 4,
    totalScore: 3.9,
    reason: '필터별 표와 다음 알림은 좋지만 모델/주기 입력이 늘어난다.',
    ux12Action: '가전 프로필형 P1 후보로 두고 모델 선택을 단순화한다.',
  },
  {
    id: 'car-maintenance-schedule',
    title: '자동차 소모품 교체 스케줄',
    origin: 'current_31',
    tier: 'p1_evaluate_next',
    category: '차량/관리',
    interactionScore: 2,
    executionScore: 4,
    uiFitScore: 3,
    riskScore: 5,
    supplySignalScore: 5,
    totalScore: 3.9,
    reason: '기간과 km를 함께 관리해야 해서 입력 복잡도가 높다.',
    ux12Action: '차량 프로필 하위 표+알림 구조로만 실험한다.',
  },
  {
    id: 'vehicle-inspection-prep',
    title: '자동차 정기검사 준비 체크',
    origin: 'current_31',
    tier: 'p1_evaluate_next',
    category: '차량/행정',
    interactionScore: 2,
    executionScore: 4,
    uiFitScore: 4,
    riskScore: 5,
    supplySignalScore: 4,
    totalScore: 3.9,
    reason: '공식 일정/예약은 명확하지만 사용자 상호작용형 컨텐츠는 아니다.',
    ux12Action: '차량 행정 P1 후보로 두고 검사 문자/만료일 입력 UX를 검증한다.',
  },
  {
    id: 'passport-issue-prep',
    title: '여권 발급 준비물 체크',
    origin: 'current_31',
    tier: 'p1_evaluate_next',
    category: '여행/행정',
    interactionScore: 2,
    executionScore: 4,
    uiFitScore: 4,
    riskScore: 5,
    supplySignalScore: 4,
    totalScore: 3.9,
    reason: '공식 준비물 체크로는 좋지만 FlowMe 차별점은 약하다.',
    ux12Action: '여행 준비 Flow의 공식 확인 하위 카드로 둔다.',
  },
  {
    id: 'washer-self-clean-decision',
    title: 'LG 통돌이 세탁기 셀프 분해청소 판단 Flow',
    origin: 'creator_interaction_8',
    tier: 'p1_evaluate_next',
    category: '가전 관리',
    interactionScore: 4,
    executionScore: 3,
    uiFitScore: 3,
    riskScore: 3,
    supplySignalScore: 4,
    totalScore: 3.8,
    reason: '사용자 경험은 좋지만 셀프 분해 지시처럼 보이면 위험하다.',
    ux12Action: '셀프 작업 가이드가 아니라 업체 예약/보류 판단 Flow로만 둔다.',
  },
  {
    id: 'monstera-care-routine',
    title: '몬스테라 물주기·분갈이 루틴',
    origin: 'current_31',
    tier: 'p1_evaluate_next',
    category: '식물 관리',
    interactionScore: 3,
    executionScore: 4,
    uiFitScore: 4,
    riskScore: 5,
    supplySignalScore: 3,
    totalScore: 3.8,
    reason: '식물 루틴으로 가능하지만 스투키 후보가 더 실행 판단이 선명하다.',
    ux12Action: '식물 카테고리에서는 스투키를 우선하고 몬스테라는 variant로 둔다.',
  },
  {
    id: 'regular-aircon-clean-home',
    title: '벽걸이 에어컨 셀프 청소',
    origin: 'current_31',
    tier: 'p1_evaluate_next',
    category: '가전 관리',
    interactionScore: 2,
    executionScore: 4,
    uiFitScore: 3,
    riskScore: 4,
    supplySignalScore: 4,
    totalScore: 3.8,
    reason: '가전 관리 수요는 강하지만 셀프 분해/청소 위험 경계가 필요하다.',
    ux12Action: '필터 청소/업체 판단 하위 Flow로 제한한다.',
  },
  {
    id: 'plank-30-day-challenge',
    title: '30일 플랭크 챌린지',
    origin: 'current_31',
    tier: 'p1_evaluate_next',
    category: '운동/챌린지',
    interactionScore: 2,
    executionScore: 4,
    uiFitScore: 4,
    riskScore: 3,
    supplySignalScore: 5,
    totalScore: 3.8,
    reason: '30일 표는 좋지만 운동 민감도와 원문 신뢰도 때문에 대표보다는 보조 후보가 맞다.',
    ux12Action: '운동 카테고리에서는 영상 원문/중단 조건이 확실한 후보만 승격한다.',
  },
  {
    id: 'thankyou-bubu-no-jump-home-workout',
    title: 'ThankyouBUBU 점프 없는 홈트 영상',
    origin: 'current_32',
    tier: 'p1_evaluate_next',
    category: '운동/홈트',
    interactionScore: 4,
    executionScore: 4,
    uiFitScore: 4,
    riskScore: 3,
    supplySignalScore: 5,
    totalScore: 4,
    reason: '단일 유튜브 follow-along 영상은 원본 링크와 반복 캘린더로 바로 실행할 수 있지만 운동 민감도 때문에 중단 조건이 필요하다.',
    ux12Action: '동작 순서를 새로 만들지 않고 원본 영상 열기, 반복 일정, 완료/몸 상태 메모만 검증한다.',
  },
  {
    id: 'kids-dino-footprint-art',
    title: '아이 공룡 발자국 미술 놀이',
    origin: 'runtime_diversity_addition',
    tier: 'p1_evaluate_next',
    category: '육아/놀이',
    interactionScore: 3,
    executionScore: 4,
    uiFitScore: 4,
    riskScore: 5,
    supplySignalScore: 4,
    totalScore: 4,
    reason: '주말 놀이 준비물과 활동 순서가 짧아 가볍게 저장 가능하고, 기존 가전/이사 후보와 다른 가족 활동 순간을 검증한다.',
    ux12Action: '캘린더 일정 1개와 준비물/놀이 체크 상세를 보여주고 교육 기록/사진 증빙은 기본에서 제외한다.',
  },
  {
    id: 'banana-peanut-recipe-video',
    title: '바나나 땅콩버터 빵 영상 따라하기',
    origin: 'runtime_diversity_addition',
    tier: 'p1_evaluate_next',
    category: '요리/레시피',
    interactionScore: 3,
    executionScore: 4,
    uiFitScore: 4,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4,
    reason: '짧은 제작자 레시피 영상은 원본 링크, 재료, 조리 체크만 있으면 충분해 체크리스트형 Flow 다양성 검증에 좋다.',
    ux12Action: '요리 날짜/분량/알림만 받고 원본 영상 링크와 조리 메모를 상세에 둔다. 칼로리/식단 기록은 제외한다.',
  },
  {
    id: 'thankyou-bubu-arm-30day',
    title: '땅끄부부 팔뚝살 30일 챌린지',
    origin: 'creator_interaction_8',
    tier: 'p1_evaluate_next',
    category: '운동/챌린지',
    interactionScore: 5,
    executionScore: 3,
    uiFitScore: 4,
    riskScore: 3,
    supplySignalScore: 5,
    totalScore: 3.8,
    reason: '상호작용은 강하지만 정확한 원본 영상 URL과 안전 boundary가 필요하다.',
    ux12Action: 'exact video URL 확보 후 운동 루틴 후보로 재평가한다.',
  },
  {
    id: 'puppy-vaccination-schedule',
    title: '강아지 예방접종 일정표',
    origin: 'current_31',
    tier: 'p2_hold_or_support',
    category: '반려동물',
    interactionScore: 3,
    executionScore: 4,
    uiFitScore: 3,
    riskScore: 2,
    supplySignalScore: 4,
    totalScore: 3.5,
    reason: '일정표로는 좋지만 접종 날짜가 앱 처방처럼 보일 위험이 크다.',
    ux12Action: '병원에서 확정한 일정 저장 Flow로만 제한하고 대표 후보에서는 제외한다.',
  },
  {
    id: 'homelearn-reading-challenge',
    title: '예비초 독서 챌린지 책 목록',
    origin: 'current_31',
    tier: 'p2_hold_or_support',
    category: '육아/독서',
    interactionScore: 1,
    executionScore: 3,
    uiFitScore: 3,
    riskScore: 5,
    supplySignalScore: 3,
    totalScore: 3.2,
    reason: '도서 목록은 넓고 사용자가 바로 따라 할 실행 단위가 약하다.',
    ux12Action: '주간 독서 루틴의 추천 도서 소스로만 사용한다.',
  },
  {
    id: 'cat-litter-box-clean',
    title: '고양이 화장실 청소 루틴',
    origin: 'current_31',
    tier: 'p2_hold_or_support',
    category: '반려동물',
    interactionScore: 2,
    executionScore: 3,
    uiFitScore: 4,
    riskScore: 4,
    supplySignalScore: 2,
    totalScore: 3.1,
    reason: '루틴은 가능하지만 FlowMe가 없으면 안 되는 이유가 약하다.',
    ux12Action: '가족 공유 루틴 후보로만 둔다.',
  },
  {
    id: 'air-purifier-filter-seasonal',
    title: '공기청정기 필터 계절 관리',
    origin: 'current_31',
    tier: 'p2_hold_or_support',
    category: '가전 관리',
    interactionScore: 1,
    executionScore: 3,
    uiFitScore: 3,
    riskScore: 5,
    supplySignalScore: 3,
    totalScore: 3,
    reason: '공식 정보는 있으나 사용자 상호작용/Flow 특수성이 약하다.',
    ux12Action: '공기청정기 프로필 하위 알림으로만 둔다.',
  },
  {
    id: 'robot-vacuum-monthly-care',
    title: '로봇청소기 브러시·센서 월간 관리',
    origin: 'current_31',
    tier: 'p2_hold_or_support',
    category: '가전 관리',
    interactionScore: 1,
    executionScore: 3,
    uiFitScore: 3,
    riskScore: 5,
    supplySignalScore: 3,
    totalScore: 3,
    reason: '관리 항목은 있으나 대표 Flow로 보기에는 실행 임팩트가 낮다.',
    ux12Action: '가전 관리 확장 후보로만 유지한다.',
  },
  {
    id: 'humidifier-daily-weekly-clean',
    title: '가습기 매일 비우고 주간 세척',
    origin: 'current_31',
    tier: 'p2_hold_or_support',
    category: '가전 관리',
    interactionScore: 1,
    executionScore: 3,
    uiFitScore: 3,
    riskScore: 4,
    supplySignalScore: 3,
    totalScore: 2.9,
    reason: '청소 습관으로는 가능하지만 매일 알림 피로가 커질 수 있다.',
    ux12Action: '수요 확인 전까지 보류한다.',
  },
  {
    id: 'car-cabin-filter-replace',
    title: '자동차 에어컨 필터 셀프 교체',
    origin: 'current_31',
    tier: 'p2_hold_or_support',
    category: '차량/관리',
    interactionScore: 1,
    executionScore: 3,
    uiFitScore: 3,
    riskScore: 4,
    supplySignalScore: 3,
    totalScore: 2.9,
    reason: '셀프 교체보다 차량 소모품 스케줄 안의 한 항목이 맞다.',
    ux12Action: '단독 후보에서 제외하고 차량 유지관리 표에 병합한다.',
  },
  {
    id: 'monthly-budget-close',
    title: '월말 가계부 결산 루틴',
    origin: 'current_31',
    tier: 'p2_hold_or_support',
    category: '돈 관리',
    interactionScore: 1,
    executionScore: 3,
    uiFitScore: 3,
    riskScore: 2,
    supplySignalScore: 3,
    totalScore: 2.6,
    reason: '금융/재무 조언처럼 보일 위험이 있고 사용자 상호작용 신호가 약하다.',
    ux12Action: '재무 카테고리는 대표 검증에서 제외한다.',
  },
  {
    id: 'emergency-fund-account',
    title: '비상금 통장 만들기 체크',
    origin: 'current_31',
    tier: 'p2_hold_or_support',
    category: '돈 관리',
    interactionScore: 1,
    executionScore: 2,
    uiFitScore: 3,
    riskScore: 2,
    supplySignalScore: 3,
    totalScore: 2.4,
    reason: '상품/재무 판단으로 오해될 가능성이 크다.',
    ux12Action: '현재 단계에서는 제외한다.',
  },
  {
    id: 'first-kimjang-weekend-checklist',
    title: '초보 김장 주말 체크리스트',
    origin: 'runtime_diversity_addition',
    tier: 'p1_evaluate_next',
    category: '계절음식/집안행사',
    interactionScore: 2,
    executionScore: 5,
    uiFitScore: 4,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4,
    reason: '전날 절임, 당일 버무리기, 보관 전환처럼 단계가 선명하고 기존 생활 이벤트/가전 루틴과 다른 계절 음식 프로젝트 축을 연다.',
    ux12Action: '레시피 앱처럼 만들지 않고 D-3/D-1/당일/보관 전환 체크와 원문 비율 메모를 검증한다.',
  },
  {
    id: 'passport-renewal-online-pickup',
    title: '여권 재발급 온라인 신청·수령 준비',
    origin: 'runtime_diversity_addition',
    tier: 'p1_evaluate_next',
    category: '여행/공식행정',
    interactionScore: 3,
    executionScore: 5,
    uiFitScore: 5,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4.4,
    reason: '공식 출처 기반으로 온라인 가능 조건, 사진 준비, 신청, 방문 수령을 가볍게 분리할 수 있다.',
    ux12Action: '출국일/만료일 기준 타임라인과 공식 출처 메모를 만들고 여권번호·주민등록번호는 저장하지 않는다.',
  },
  {
    id: 'car-inspection-renewal-window',
    title: '자동차 정기·종합검사 예약 준비',
    origin: 'runtime_diversity_addition',
    tier: 'p1_evaluate_next',
    category: '차량/공식검사',
    interactionScore: 3,
    executionScore: 5,
    uiFitScore: 5,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4.4,
    reason: '중고차 구매와 다른 공식 유지관리 마감형 Flow로, 검사 만료일과 예약/결과/재검사 기한이 명확하다.',
    ux12Action: '공식 검사 일정 캘린더와 결과서 메모 중심으로 검증하고 정비 판단은 외부로 둔다.',
  },
  {
    id: 'beginner-camping-packing-sheet',
    title: '초보 캠핑 준비물 시트',
    origin: 'runtime_diversity_addition',
    tier: 'p1_evaluate_next',
    category: '캠핑/여가준비',
    interactionScore: 2,
    executionScore: 5,
    uiFitScore: 5,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4.2,
    reason: '캠핑 준비물은 매번 복사해 쓰는 작은 표와 출발 전 체크가 자연스러워 FlowMe의 sheet artifact를 검증하기 좋다.',
    ux12Action: '출발일/인원/캠핑 형태만 받고 기본 장비·안전·동반자 추가 품목 행을 켜고 끄는 UX를 검증한다.',
  },
  {
    id: 'free-appliance-pickup-reservation',
    title: '폐가전 무상방문수거 예약 준비',
    origin: 'runtime_diversity_addition',
    tier: 'p1_evaluate_next',
    category: '정리/방문수거',
    interactionScore: 3,
    executionScore: 5,
    uiFitScore: 5,
    riskScore: 5,
    supplySignalScore: 5,
    totalScore: 4.6,
    reason: '이사/정리 상황에서 수거 가능 품목 확인, 예약, 전날 철거/통로 준비, 당일 수거 확인이 선명하다.',
    ux12Action: '공식 예약 링크와 전날 준비 체크를 중심으로 두고 수거 가능 품목 판단은 공식 사이트로 보낸다.',
  },
  {
    id: 'piano-carol-sheet-7day-practice',
    title: '아이 피아노 캐롤 악보 7일 연습',
    origin: 'creator_source_breadth_addition',
    tier: 'p1_evaluate_next',
    category: '음악/악보연습',
    interactionScore: 4,
    executionScore: 4,
    uiFitScore: 4,
    riskScore: 5,
    supplySignalScore: 4,
    totalScore: 4.2,
    reason: '무료 악보 PDF, 댓글/이웃추가 상호작용, 난이도 선택, 목표일 전 연습 흐름이 있어 제작자 자료형 Flow를 검증하기 좋다.',
    ux12Action: '악보 파일은 복제하지 않고 원문 링크와 7일 연습 캘린더만 보여준다.',
  },
  {
    id: 'cat-adoption-first-week-setup',
    title: '초보 집사 고양이 입양 첫 주 준비',
    origin: 'creator_source_breadth_addition',
    tier: 'p1_evaluate_next',
    category: '반려묘/입양준비',
    interactionScore: 3,
    executionScore: 5,
    uiFitScore: 4,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4.2,
    reason: '입양일 전후 준비물, 안전 공간, 병원 질문, 첫 주 관찰로 나뉘어 생활 전환 Flow로 적합하다.',
    ux12Action: '건강 판단을 제외하고 입양일 기준 타임라인과 첫 주 관찰 메모를 검증한다.',
  },
  {
    id: 'jeonse-contract-precheck-docs',
    title: '전세계약 전 서류 10단계 확인',
    origin: 'creator_source_breadth_addition',
    tier: 'p1_evaluate_next',
    category: '주거/계약전점검',
    interactionScore: 3,
    executionScore: 5,
    uiFitScore: 5,
    riskScore: 3,
    supplySignalScore: 5,
    totalScore: 4.2,
    reason: '계약 전/당일/입주 후로 나뉘는 문서 확인 흐름이 명확하고 보류가 정상 결과로 필요하다.',
    ux12Action: '법률 판단이나 안전 점수화 없이 문서 체크와 보류 메모만 제공한다.',
  },
  {
    id: 'goodnotes-template-study-setup',
    title: '굿노트 무료 속지 공부 세팅',
    origin: 'creator_source_breadth_addition',
    tier: 'p1_evaluate_next',
    category: '디지털필기/템플릿',
    interactionScore: 4,
    executionScore: 3,
    uiFitScore: 4,
    riskScore: 5,
    supplySignalScore: 4,
    totalScore: 4,
    reason: '무료 PDF 템플릿과 댓글 피드백 흐름이 있어 제작자 자료 저장 후 첫 사용까지의 짧은 Flow를 검증할 수 있다.',
    ux12Action: '다운로드, 앱 가져오기, 첫 페이지 작성, 7일 뒤 유지/교체 결정으로 제한한다.',
  },
  {
    id: 'macaron-template-baking-day',
    title: '마카롱 도안 베이킹 데이 준비',
    origin: 'creator_source_breadth_addition',
    tier: 'p1_evaluate_next',
    category: '베이킹/도안자료',
    interactionScore: 4,
    executionScore: 4,
    uiFitScore: 4,
    riskScore: 4,
    supplySignalScore: 5,
    totalScore: 4.2,
    reason: '도안 PDF, 댓글/좋아요 요청, 재료 준비, 출력, 당일 베이킹 체크가 결합되어 자료형 콘텐츠와 짧은 프로젝트를 함께 검증한다.',
    ux12Action: '도안 자체 복제 없이 D-5/D-3/D-1/당일 프로젝트 체크로 보여준다.',
  },
];

export const additionalSourceLeads: AdditionalSourceLead[] = [
  {
    title: '세무사 합격수기 공부법 정리본',
    category: '공부/자격증',
    sourceUrl: 'https://blog.naver.com/PostView.naver?blogId=mylittlestudy&logNo=223669028721',
    interactionSignal: '정리본 PDF와 댓글 비밀번호 공유 요청 구조가 보인다.',
    flowPotential: '긴 수험 기간을 주차별 공부량/회독/오답 표로 바꿀 수 있다.',
    useFor: 'new_candidate',
  },
  {
    title: '위생사 합격후기와 마지막 정리본',
    category: '공부/자격증',
    sourceUrl: 'https://blog.naver.com/PostView.naver?blogId=dhrtntnzh&logNo=222168543290',
    interactionSignal: '마지막 정리본, 후속 곤충 특징 자료, 댓글 비밀번호 공유 흐름이 있다.',
    flowPotential: '시험 전 2주 문제풀이/정리본/당일 확인 플랜으로 변환 가능하다.',
    useFor: 'new_candidate',
  },
  {
    title: '식품기사 실기 기출문제 공유와 수정본',
    category: '공부/자격증',
    sourceUrl: 'https://blog.naver.com/PostView.nhn?blogId=dhrtntnzh&logNo=222236302719',
    interactionSignal: '기출 PDF, 비밀댓글 비밀번호, 계산문제 정정 요청이 있다.',
    flowPotential: '기출 회차/계산문제/정정 확인/시험 전 재풀이 표로 만들기 좋다.',
    useFor: 'new_candidate',
  },
  {
    title: '전기기사 실기 단답 정리 PDF 공유',
    category: '공부/자격증',
    sourceUrl: 'https://blog.naver.com/PostView.naver?blogId=marryme0_0&logNo=223487229778',
    interactionSignal: '공감과 비밀댓글로 PDF 비밀번호를 공유하는 사용자 반응이 있다.',
    flowPotential: '33개년 단답 회독표와 시험 전 암기 체크리스트로 변환 가능하다.',
    useFor: 'new_candidate',
  },
  {
    title: '오픽 독학 IH 후기와 PDF 자료',
    category: '공부/어학',
    sourceUrl: 'https://blog.naver.com/PostView.naver?blogId=keemeveryoung&logNo=223778285260',
    interactionSignal: '하트/댓글 후 자료 비밀번호 공유 구조가 보인다.',
    flowPotential: '질문 유형별 스크립트 연습, 롤플레이, 모의답변 루틴으로 만들 수 있다.',
    useFor: 'new_candidate',
  },
  {
    title: '치앙마이 장기여행 준비물 체크리스트',
    category: '여행',
    sourceUrl: 'https://blog.naver.com/PostView.nhn?blogId=mat_zip_diary&logNo=223137520451',
    interactionSignal: '체크리스트 파일, 댓글 이벤트, 실제 장기여행 구매/사용 후기가 있다.',
    flowPotential: '출국 D-7 준비물, 환전/GLN/eSIM, 현지 위험 대비 메모로 변환 가능하다.',
    useFor: 'new_candidate',
  },
];

export const flowContentSelectionSummary = {
  totalEvaluated: flowContentSelectionAudits.length,
  p0Count: flowContentSelectionAudits.filter((item) => item.tier === 'p0_apply_to_ux12').length,
  p1Count: flowContentSelectionAudits.filter((item) => item.tier === 'p1_evaluate_next').length,
  holdCount: flowContentSelectionAudits.filter((item) => item.tier === 'p2_hold_or_support').length,
  mergeCount: flowContentSelectionAudits.filter((item) => item.tier === 'merge_or_replace').length,
  additionalLeadCount: additionalSourceLeads.length,
};

export const selectedFlowContentP0Ids = flowContentSelectionAudits
  .filter((item) => item.tier === 'p0_apply_to_ux12')
  .map((item) => item.id);
