export type KoreanFlowUserReviewStatus = 'representative' | 'promote' | 'conditional' | 'hold';

export type KoreanFlowSourceQuality =
  | 'strong_creator'
  | 'clear_official'
  | 'usable_but_ai_like'
  | 'too_broad'
  | 'source_unclear'
  | 'needs_exact_source';

export type KoreanFlowContentUserReview = {
  candidateId: string;
  userScore: number;
  status: KoreanFlowUserReviewStatus;
  sourceQuality: KoreanFlowSourceQuality;
  sourceIssue?: string;
  conversionNote: string;
  uxAction: string;
};

export const koreanFlowContentUserReviews: KoreanFlowContentUserReview[] = [
  {
    candidateId: 'wedding-12-month-timeline',
    userScore: 5,
    status: 'representative',
    sourceQuality: 'strong_creator',
    conversionNote: '결혼 준비는 기준일 타임라인과 체크리스트가 가장 자연스러운 대표 후보다.',
    uxAction: 'D-day 일정 여러 개를 만들되 캘린더 안에는 짧은 행동 제목만 표시한다.',
  },
  {
    candidateId: 'computer-license-2nd-written',
    userScore: 5,
    status: 'representative',
    sourceQuality: 'strong_creator',
    conversionNote: '본인 경험과 공부 흐름이 잘 정리되어 있어 진도표와 시험일 캘린더로 옮기기 좋다.',
    uxAction: '기출 회차/오답/재풀이일은 표로, 시험일과 공부 블록은 캘린더로 분리한다.',
  },
  {
    candidateId: 'dog-adoption-first-week',
    userScore: 5,
    status: 'representative',
    sourceQuality: 'strong_creator',
    conversionNote: '입양 첫 주는 준비물, 환경 정리, 병원/등록 같은 실행 단위가 명확하다.',
    uxAction: '입양일 기준 타임라인과 첫 주 체크리스트를 함께 보여준다.',
  },
  {
    candidateId: 'college-dorm-move-in-checklist',
    userScore: 4.6,
    status: 'promote',
    sourceQuality: 'clear_official',
    sourceIssue: '학교별 최신 기숙사 공지와 학기별 PDF가 우선이다. 블로그 체크리스트나 개인 준비물 예시는 보조 실행 단서로만 써야 한다.',
    conversionNote: '최신 기숙사 공지에서 입사일, 제출서류, 반입금지 물품, 첫날 물품, D-Day 접수와 시설점검 순서를 확인하는 생활 전환 Flow로 적합하다.',
    uxAction: 'D-14 최신 공지 확인을 첫 카드로 두고 D-10 제출서류, D-7 첫날 물품, D-5 반입금지, D-Day 입사 절차를 한 화면에서 비교하게 한다.',
  },
  {
    candidateId: 'elementary-school-entry-d30',
    userScore: 4.5,
    status: 'promote',
    sourceQuality: 'clear_official',
    sourceIssue: '공식 취학통지·예비소집 안내를 기준으로 삼고, 블로그 준비물 체크는 보조 실행 단서로만 써야 한다.',
    conversionNote: '초등 입학은 학부모가 실제로 찾는 시기성 콘텐츠이고 D-30 흐름이 선명하다. 구매 추천보다 취학통지 확인, 학교 안내 전 보류, 이름 붙이기, 등교 연습으로 좁혀야 한다.',
    uxAction: '입학식 날짜만 넣으면 D-30부터 D-1까지 준비 체크가 생기고, 상세에는 먼저 살 것과 학교 안내 후 살 것이 분리된다.',
  },
  {
    candidateId: 'kids-printable-squishy-craft',
    userScore: 4.3,
    status: 'promote',
    sourceQuality: 'strong_creator',
    conversionNote: '도안 배포형 제작자 콘텐츠는 원문 링크, 출력, 재료 준비, 놀이 당일 체크로 바로 실행 가능하다. 기존 육아 기록형 후보와 다르다.',
    uxAction: '도안 자체를 복제하지 않고 원문 링크/출력 여부/재료 체크/놀이 날짜만 제공한다.',
  },
  {
    candidateId: 'anydesk-remote-setup-check',
    userScore: 4.2,
    status: 'conditional',
    sourceQuality: 'strong_creator',
    sourceIssue: '블로그 설명과 공식 AnyDesk 연결 문서를 분리해서 보여줘야 한다.',
    conversionNote: '디지털 설치/원격지원은 캘린더보다 순서형 체크리스트가 맞다. 민감한 ID/비밀번호 저장을 막는 boundary가 핵심이다.',
    uxAction: '설치, 주소 확인, 연결 수락, 세션 종료/보안 확인 4단계만 두고 인증값은 저장하지 않는다.',
  },
  {
    candidateId: 'remote-help-session-precheck',
    userScore: 4.3,
    status: 'conditional',
    sourceQuality: 'clear_official',
    sourceIssue: 'AnyDesk, TeamViewer, Chrome Remote Desktop, Zoom, Quick Assist 공식 문서의 공통 permission ladder를 써야 하며 특정 원격 도구 설치 후보로 보이면 안 된다.',
    conversionNote: '원격 도움은 설치 체크보다 trust/scope 확인, screen share only, one-time remote control, repeated management 선택, 민감 access value 미저장, close/review access가 핵심이다.',
    uxAction: '첫 action은 요청자와 범위 확인으로 시작하고, 두 번째 action에서 permission method를 고른다. remote ID, password, access code, session link, token, screenshot, support chat, device list는 입력/복사/내보내기 대상이 아니다.',
  },
  {
    candidateId: 'naver-search-advisor-site-readiness',
    userScore: 4.2,
    status: 'conditional',
    sourceQuality: 'clear_official',
    sourceIssue: 'Naver Search Advisor 공식 문서의 site unit, ownership verification, crawl readiness, diagnosis/report 흐름을 써야 하며 SEO 점수나 랭킹 개선 후보로 보이면 안 된다.',
    conversionNote: '검색 콘솔 setup은 sitemap 제출보다 site unit/access method 선택이 먼저다. HTML file/tag method status, robots/noindex readiness, sitemap/RSS/request status, revisit memo만 남기는 hybrid artifact가 맞다.',
    uxAction: '첫 action은 사이트 단위와 접근권한 선택으로 두고, ask developer/host admin을 정상 상태로 보여준다. verification value, DNS value, HTML tag content, OAuth grant, API key, credential, sitemap file은 입력/복사/저장 대상이 아니다.',
  },
  {
    candidateId: 'fridge-cleanout-weekly-plan',
    userScore: 4.1,
    status: 'conditional',
    sourceQuality: 'usable_but_ai_like',
    sourceIssue: '절약 금액과 효과 주장보다 재고 소진 실행표만 남겨야 한다.',
    conversionNote: '냉장고 파먹기는 식단 관리가 아니라 재고 파악, 7일 메뉴 후보, 장보기 보류 판단으로 만들면 FlowMe 입력 복잡도에 맞는다.',
    uxAction: '시작일과 소진할 재료 3개만 받고 작은 시트로 7일 메뉴 후보와 보류 구매를 관리한다.',
  },
  {
    candidateId: 'balcony-fall-vegetable-calendar',
    userScore: 4.3,
    status: 'promote',
    sourceQuality: 'strong_creator',
    sourceIssue: '지역/온도/베란다 방향에 따라 재배 시기는 달라지므로 수확 보장처럼 보이면 안 된다.',
    conversionNote: '베란다 텃밭은 기존 관엽식물 루틴과 달리 파종·생육·수확 후보일이 있어 캘린더와 작은 시트가 함께 필요한 좋은 변형이다.',
    uxAction: '키울 채소 1~3개와 시작 월만 받아 파종/수확 후보일을 만들고, 채소별 재배 팁은 메모로 보낸다.',
  },
  {
    candidateId: 'self-wall-paint-weekend',
    userScore: 4.2,
    status: 'promote',
    sourceQuality: 'strong_creator',
    conversionNote: '셀프 페인팅은 준비물, 보양, 경계 칠, 롤러 칠, 건조/정리 순서가 명확해 주말 프로젝트형 체크리스트로 적합하다.',
    uxAction: '작업 날짜와 공간만 넣으면 D-3/D-1/당일 체크가 생기고, 제품별 건조 시간과 색상 링크는 메모에 둔다.',
  },
  {
    candidateId: 'freelancer-income-tax-docs',
    userScore: 3.8,
    status: 'conditional',
    sourceQuality: 'usable_but_ai_like',
    sourceIssue: '세무 판단, 절세 조언, 신고 의무 판단으로 확장되면 FlowMe 범위를 넘는다. 국세청/세무사 확인 링크가 필요하다.',
    conversionNote: '프리랜서 세금 콘텐츠는 신고 서비스가 아니라 자료 준비 체크리스트로 제한하면 Flow화 가능하다.',
    uxAction: '마감일 기준 소득자료/경비증빙/확인 질문/누락 항목만 관리하고 세액 계산 UI는 만들지 않는다.',
  },
  {
    candidateId: 'washer-tub-clean-monthly',
    userScore: 4.5,
    status: 'representative',
    sourceQuality: 'strong_creator',
    conversionNote: '월 1회 관리 루틴으로 적합하다. 방법/준비물/영상 링크는 메모로 보내야 한다.',
    uxAction: '저장 화면은 시작일, 반복 주기, 세탁기 종류만 받고 상세에 체크리스트 3개를 둔다.',
  },
  {
    candidateId: 'lg-aircon-filter-biweekly',
    userScore: 4.5,
    status: 'representative',
    sourceQuality: 'clear_official',
    conversionNote:
      '2주 루틴은 캘린더 item 1개와 내부 체크리스트 3개가 맞다. 외부 캘린더에는 체크리스트를 메모로 넘긴다.',
    uxAction: '캘린더에는 필터 청소 1개만 보이고, 상세에서 필터 물세척/교체 확인/송풍 건조를 체크한다.',
  },
  {
    candidateId: 'used-car-buying-check',
    userScore: 4.5,
    status: 'representative',
    sourceQuality: 'strong_creator',
    sourceIssue: '원문이 다소 산만하므로 FlowMe가 핵심 점검 순서만 정리해야 한다.',
    conversionNote: '완료보다 구매/보류/거절 결정이 핵심이다.',
    uxAction: '체크리스트 완료 버튼보다 구매/보류/거절 상태 버튼을 우선한다.',
  },
  {
    candidateId: 'picture-book-reading-routine',
    userScore: 4.5,
    status: 'representative',
    sourceQuality: 'clear_official',
    conversionNote: '책별 Flow보다 독서 루틴에 질문 카드가 꽂히는 구조가 적합하다.',
    uxAction: '캘린더에는 읽기 루틴 1개, 상세에는 오늘 책과 질문 카드만 둔다.',
  },
  {
    candidateId: 'travel-d7-checklist',
    userScore: 4.5,
    status: 'representative',
    sourceQuality: 'strong_creator',
    sourceIssue: 'AI 느낌은 있지만 사이트 방향이 FlowMe와 유사해 참고 가치가 있다.',
    conversionNote: '출국 7일 전부터 당일까지 일정 + 체크리스트로 좋다.',
    uxAction: '출국일 기준 일정으로 만들고, 규정성 정보는 공식 링크 확인 메모로 분리한다.',
  },
  {
    candidateId: 'moving-d30-checklist',
    userScore: 4.5,
    status: 'promote',
    sourceQuality: 'usable_but_ai_like',
    sourceIssue: 'AI 생성 느낌이 있어 대표 노출 전 더 좋은 제작자 원문을 찾는 편이 좋다.',
    conversionNote: '이사일 기준 타임라인과 체크리스트로 적합하다.',
    uxAction: 'D-30 같은 표기는 상세/메모에서만 쓰고 캘린더에는 행동 제목만 둔다.',
  },
  {
    candidateId: 'after-move-address-report',
    userScore: 4.5,
    status: 'promote',
    sourceQuality: 'clear_official',
    conversionNote: '단순 체크가 아니라 전입신고/확정일자 일정과 제출 체크가 필요하다.',
    uxAction: '행정 Flow는 체크리스트 + 공식 링크 + 처리 상태를 중심에 둔다.',
  },
  {
    candidateId: 'japan-trip-packing',
    userScore: 4.5,
    status: 'promote',
    sourceQuality: 'strong_creator',
    conversionNote: '일본 여행 준비는 단순 체크리스트와 일정형 모두 가능하다.',
    uxAction: '출국일 기준으로 eSIM/환전/교통/짐 체크를 배치한다.',
  },
  {
    candidateId: 'japan-esim-setup-before-departure',
    userScore: 4.6,
    status: 'promote',
    sourceQuality: 'strong_creator',
    conversionNote: '여행 준비물 전체가 아니라 eSIM 설정이라는 짧은 디지털 준비 Flow라 기존 후보 반복을 깨는 데 좋다.',
    uxAction: '출국일 기준 D-3/D-2/D-1/D-Day 일정과 상세 메모만 둔다.',
  },
  {
    candidateId: 'alt-phone-sk7-self-activation',
    userScore: 4.6,
    status: 'promote',
    sourceQuality: 'strong_creator',
    conversionNote: '가전/여행 준비와 달리 사용자가 막히기 쉬운 온라인 절차를 순서형 체크리스트로 옮기는 후보라 반복 패턴을 깨는 데 좋다.',
    uxAction: '개통 예정일과 유심/번호이동 여부만 받고, 개인정보 입력값은 저장하지 않는 체크리스트로 둔다.',
  },
  {
    candidateId: 'infant-health-checkup-prep',
    userScore: 4.5,
    status: 'promote',
    sourceQuality: 'clear_official',
    conversionNote: '육아 건강 기록이 아니라 검진 예약, 문진표, 등록번호, 방문 준비로 좁히면 가볍게 실행 가능하다.',
    uxAction: '검진 예정일 기준 D-14/D-10/D-3/D-1/D-Day 일정과 공식 출처 카드만 둔다.',
  },
  {
    candidateId: 'chiangmai-solo-trip-packing',
    userScore: 4.4,
    status: 'promote',
    sourceQuality: 'strong_creator',
    conversionNote: '일반 여행 준비물이 아니라 혼자 장기체류 상황의 통신/결제/보험/생활용품 체크라 사용자 순간이 뚜렷하다.',
    uxAction: '출국일/체류기간/도시만 받고 상품 추천은 메모 링크로 내려 체크리스트 중심으로 둔다.',
  },
  {
    candidateId: 'computer-skills-written-3day-summary',
    userScore: 4.3,
    status: 'conditional',
    sourceQuality: 'strong_creator',
    sourceIssue: '기존 컴활 대표 Flow와 겹치므로 단독 대표보다 시험 직전 3일 variant로 다루는 편이 낫다.',
    conversionNote: '원문에 1일차 1과목, 2일차 2과목, 3일차 월단위 재풀이와 PDF가 있어 짧은 타임라인으로는 좋다.',
    uxAction: '자료 링크 메모와 3일 캘린더만 두고 별도 공부 기록 앱으로 키우지 않는다.',
  },
  {
    candidateId: 'lease-contract-report-deadline',
    userScore: 4.2,
    status: 'conditional',
    sourceQuality: 'strong_creator',
    sourceIssue: '법/행정성 정보라 public 승격 전 최신 공식 안내로 보강해야 한다.',
    conversionNote: '계약일 기준 30일 마감, 계약서/인증수단 준비, 접수/필증 확인은 FlowMe에 잘 맞는다.',
    uxAction: '계약일 기준 마감 캘린더와 준비물 체크만 두고 개인정보와 법적 판단은 저장하지 않는다.',
  },
  {
    candidateId: 'child-weekend-play-rotation',
    userScore: 4.5,
    status: 'promote',
    sourceQuality: 'needs_exact_source',
    sourceIssue: '원문 링크가 열리지 않아 대체 원문이 필요하다.',
    conversionNote: '주말 놀이 로테이션 Flow로는 매우 좋다.',
    uxAction: '놀이 루틴에 이번 주 콘텐츠 카드를 연결한다.',
  },
  {
    candidateId: 'kids-dino-footprint-art',
    userScore: 4.3,
    status: 'promote',
    sourceQuality: 'clear_official',
    conversionNote: '아이 놀이 카테고리에서 주말 일정, 준비물, 놀이 체크만 남기는 샘플로 적합하다.',
    uxAction: '교육 기록 UI로 키우지 말고 놀이 날짜와 준비물 체크, 원문 링크만 둔다.',
  },
  {
    candidateId: 'stuckyi-overwater-prevention',
    userScore: 4.5,
    status: 'promote',
    sourceQuality: 'strong_creator',
    conversionNote: '물주기보다 물주기 보류 판단이 FlowMe에 잘 맞는다.',
    uxAction: '완료 옆에 오늘은 보류 상태를 둔다.',
  },
  {
    candidateId: 'plank-30-day-challenge',
    userScore: 4.5,
    status: 'promote',
    sourceQuality: 'usable_but_ai_like',
    sourceIssue: 'Flow 구조는 명확하지만 AI 생성 느낌의 원문은 지양한다.',
    conversionNote: '30일 챌린지로 명확하며 캘린더 반복에 적합하다.',
    uxAction: '매일 item 1개와 원문 영상/방법 링크만 둔다.',
  },
  {
    candidateId: 'thankyou-bubu-no-jump-home-workout',
    userScore: 4.5,
    status: 'promote',
    sourceQuality: 'strong_creator',
    conversionNote: '단일 follow-along 영상은 운동표를 새로 만들지 않고 원본 영상 링크와 반복 캘린더로 옮기는 것이 적합하다.',
    uxAction: '저장 화면은 시작일/요일/시간대만 받고, 실행 상세에는 원본 영상 링크, 완료 여부, 몸 상태 메모, 중단 조건만 둔다.',
  },
  {
    candidateId: 'banana-peanut-recipe-video',
    userScore: 4.4,
    status: 'promote',
    sourceQuality: 'strong_creator',
    conversionNote: '짧은 레시피 영상은 원본 영상 링크와 조리 체크리스트만 있으면 충분해 FlowMe의 가벼운 입력 원칙과 잘 맞는다.',
    uxAction: '요리 날짜/분량/알림 시간만 받고, 칼로리나 식단 기록은 기본에서 제외한다.',
  },
  {
    candidateId: 'korean-history-3-week',
    userScore: 4.5,
    status: 'promote',
    sourceQuality: 'usable_but_ai_like',
    sourceIssue: 'AI 생성 느낌이 있어 대체 후기 원문도 찾아야 한다.',
    conversionNote: '3주 공부 플랜은 시험일 변경 시 일정 자동 이동이 중요하다.',
    uxAction: '주차별 진도와 기출 회독을 표와 캘린더로 분리한다.',
  },
  {
    candidateId: 'monstera-care-routine',
    userScore: 4,
    status: 'conditional',
    sourceQuality: 'usable_but_ai_like',
    sourceIssue: '원문이 AI 작성 느낌이고 제작자 노하우인지 불명확하다.',
    conversionNote: '식물 관리 루틴 자체는 FlowMe에 잘 맞는다.',
    uxAction: '식물명별 주기 템플릿과 보류 판단을 중심으로 둔다.',
  },
  {
    candidateId: 'water-purifier-filter-cycle',
    userScore: 4,
    status: 'conditional',
    sourceQuality: 'too_broad',
    sourceIssue: '내용이 많고 3~6개월 같은 범위 반복은 기본 저장값으로 애매하다.',
    conversionNote: '정수기 옵션을 입력하면 필터별 체크리스트로 접근 가능하다.',
    uxAction: '캘린더에는 교체 확인 item 1개, 상세에는 갈아야 할 필터 목록을 둔다.',
  },
  {
    candidateId: 'car-maintenance-schedule',
    userScore: 4,
    status: 'conditional',
    sourceQuality: 'usable_but_ai_like',
    sourceIssue: '차량 소모품은 기간과 km를 함께 관리해야 한다.',
    conversionNote: 'Flow화하기 좋지만 item 수가 많아 저장 구조 설계가 필요하다.',
    uxAction: '차량 프로필에 기간 알림과 주행거리 입력을 함께 붙인다.',
  },
  {
    candidateId: 'baby-food-four-week-menu',
    userScore: 4,
    status: 'conditional',
    sourceQuality: 'usable_but_ai_like',
    sourceIssue: '원문이 복잡하고 AI 느낌이 있다. 사용자 상호작용 원문을 더 찾아야 한다.',
    conversionNote: '기록 앱보다 주차별 이유식 만들기/식단표 export로 접근해야 한다.',
    uxAction: '매주 이유식 만들기 item 1개와 레시피/냉동보관 메모를 둔다.',
  },
  {
    candidateId: 'cat-litter-box-clean',
    userScore: 4,
    status: 'conditional',
    sourceQuality: 'source_unclear',
    sourceIssue: '원문에서 해당 내용을 찾기 어렵다.',
    conversionNote: '의미는 있으나 사용자가 어디까지 관리해야 하는지 불명확하다.',
    uxAction: '가족 공유 체크가 필요한 집에 한정해 가볍게 둔다.',
  },
  {
    candidateId: 'regular-aircon-clean-home',
    userScore: 4,
    status: 'conditional',
    sourceQuality: 'usable_but_ai_like',
    sourceIssue: 'AI 생성 느낌이 있다.',
    conversionNote: '연 1회 루틴 item에 체크리스트와 방법/영상 링크를 붙이는 구조가 맞다.',
    uxAction: '셀프 분해 안내는 위험할 수 있으므로 준비/업체 판단을 분리한다.',
  },
  {
    candidateId: 'homelearn-reading-challenge',
    userScore: 4,
    status: 'conditional',
    sourceQuality: 'too_broad',
    sourceIssue: '원문 내용이 많아 사용자가 바로 Flow로 연결할지는 의문이다.',
    conversionNote: '독서 루틴에 책 이름 선택 체크리스트를 붙이는 정도가 적합하다.',
    uxAction: '목록 전체를 캘린더화하지 않고 주간 독서 루틴과 선택 도서만 둔다.',
  },
  {
    candidateId: 'passport-issue-prep',
    userScore: 4,
    status: 'conditional',
    sourceQuality: 'usable_but_ai_like',
    sourceIssue: 'AI 생성 느낌이 있다.',
    conversionNote: '여권 발급 준비물 체크리스트로는 좋다.',
    uxAction: '최신 규정은 공식 링크 확인을 강하게 표시한다.',
  },
  {
    candidateId: 'puppy-vaccination-schedule',
    userScore: 4,
    status: 'conditional',
    sourceQuality: 'needs_exact_source',
    sourceIssue: '원 컨텐츠 기준 Flow 예시가 아직 제대로 만들어지지 않았다.',
    conversionNote: '접종 일정은 timeline으로 만들면 좋다.',
    uxAction: '별점/도움됨 UX는 참고하고, 접종 판단은 수의사 확인으로 분리한다.',
  },
  {
    candidateId: 'vehicle-inspection-prep',
    userScore: 4,
    status: 'conditional',
    sourceQuality: 'too_broad',
    sourceIssue: '원문에 내용이 많아 여러 Flow로 쪼개질 가능성이 높다.',
    conversionNote: '정기검사 전 준비 체크로는 좋다.',
    uxAction: '검사 문자 안내를 Flow로 저장하는 진입점을 우선한다.',
  },
  {
    candidateId: 'car-cabin-filter-replace',
    userScore: 3.5,
    status: 'hold',
    sourceQuality: 'usable_but_ai_like',
    sourceIssue: '원 컨텐츠가 매력적이지 않고 AI 생성 느낌이 강하다.',
    conversionNote: '셀프 교체 Flow로 가능하지만 대표 후보는 아니다.',
    uxAction: '차량 프로필 하위 소모품 루틴으로만 둔다.',
  },
  {
    candidateId: 'monthly-budget-close',
    userScore: 3.5,
    status: 'hold',
    sourceQuality: 'usable_but_ai_like',
    sourceIssue: 'AI 생성 느낌이 있고 사용자 상호작용이 보이지 않는다.',
    conversionNote: '월 1회 결산 루틴은 가능하지만 지금 대표로는 약하다.',
    uxAction: '재무 조언 없이 체크와 표 export만 제공한다.',
  },
  {
    candidateId: 'air-purifier-filter-seasonal',
    userScore: 3,
    status: 'hold',
    sourceQuality: 'too_broad',
    sourceIssue: '복합 정보가 많고 특정 Flow에 집중되지 않으며 이미지/상호작용이 약하다.',
    conversionNote: '필터 교체 일부만 Flow화할 수 있다.',
    uxAction: '대표 후보에서 내리고 더 명확한 제품/제작자 원문을 찾는다.',
  },
  {
    candidateId: 'robot-vacuum-monthly-care',
    userScore: 3,
    status: 'hold',
    sourceQuality: 'usable_but_ai_like',
    sourceIssue: '일부 관리 항목은 Flow화할 필요가 낮고 AI 생성 느낌이 있다.',
    conversionNote: '브러시 교체 주기 등 일부만 유의미하다.',
    uxAction: '중요도 기준으로 Flow화할 항목과 메모로 둘 항목을 분리한다.',
  },
  {
    candidateId: 'humidifier-daily-weekly-clean',
    userScore: 3,
    status: 'hold',
    sourceQuality: 'usable_but_ai_like',
    sourceIssue: 'Flow화가 꼭 필요한지 불명확하고 사용자 상호작용이 보이지 않는다.',
    conversionNote: '매일/주간 체크는 가능하지만 대표 후보로는 약하다.',
    uxAction: '사용자 수요가 확인될 때까지 보류한다.',
  },
  {
    candidateId: 'emergency-fund-account',
    userScore: 3,
    status: 'hold',
    sourceQuality: 'usable_but_ai_like',
    sourceIssue: 'AI 생성 느낌이 있고 금융 민감 영역이다.',
    conversionNote: '체크리스트화는 가능하지만 P0 대표 후보로는 부적합하다.',
    uxAction: '금융상품 추천/수익 보장처럼 보이지 않도록 제외 또는 보류한다.',
  },
  {
    candidateId: 'first-kimjang-weekend-checklist',
    userScore: 4.2,
    status: 'promote',
    sourceQuality: 'usable_but_ai_like',
    sourceIssue: '원문은 구조가 좋지만 AI 작성 흔적이 있어 대표 승격 전 더 강한 제작자/공식 보조 출처가 있으면 좋다.',
    conversionNote: '김장은 계절 음식 프로젝트라 기존 가전/여행/결혼과 다른 사용자 순간을 보여준다. 전날 절임, 당일 버무리기, 보관 전환이 캘린더와 체크로 잘 나뉜다.',
    uxAction: '염도 계산기나 레시피 앱으로 확장하지 않고 D-3/D-1/당일/보관 전환 체크만 보여준다.',
  },
  {
    candidateId: 'passport-renewal-online-pickup',
    userScore: 4.4,
    status: 'promote',
    sourceQuality: 'clear_official',
    conversionNote: '여권 재발급은 여행 전 공식 행정 Flow로 적합하다. 온라인 가능 조건, 사진 준비, 신청, 방문 수령이 명확하다.',
    uxAction: '출국일과 만료일만 받아 신청/수령 체크를 만들고 개인정보·여권번호는 저장하지 않는다.',
  },
  {
    candidateId: 'car-inspection-renewal-window',
    userScore: 4.3,
    status: 'promote',
    sourceQuality: 'clear_official',
    conversionNote: '자동차 정기·종합검사는 중고차 구매와 다른 공식 마감형 차량 Flow다. 검사 만료일, 예약, 검사 당일, 재검사 기한으로 나뉜다.',
    uxAction: '검사 판정/정비 판단은 외부에 두고 만료일 기준 캘린더와 결과서 메모만 제공한다.',
  },
  {
    candidateId: 'beginner-camping-packing-sheet',
    userScore: 4.1,
    status: 'conditional',
    sourceQuality: 'usable_but_ai_like',
    sourceIssue: '원문은 실행 구조가 좋지만 상호작용 신호가 약하다. 실제 캠핑 커뮤니티/제작자 체크리스트 보조 출처를 더 찾으면 좋다.',
    conversionNote: '캠핑 준비는 매번 복사해 쓰는 작은 시트가 자연스럽다. 인원/계절/아이·반려동물 여부에 따라 행을 켜고 끄는 UX를 검증할 수 있다.',
    uxAction: '캘린더보다 준비물 표를 먼저 보여주고, 안전·조명·전기 항목은 기본 강조한다.',
  },
  {
    candidateId: 'free-appliance-pickup-reservation',
    userScore: 4.2,
    status: 'promote',
    sourceQuality: 'clear_official',
    conversionNote: '폐가전 방문수거는 이사/정리 상황에서 공식 예약 절차와 전날 준비 체크가 모두 필요한 좋은 절차형 후보다.',
    uxAction: '수거 희망일 기준 예약 전/전날/당일 체크를 만들고, 수거 가능 품목 판단은 공식 사이트 링크로 보낸다.',
  },
  {
    candidateId: 'piano-carol-sheet-7day-practice',
    userScore: 4.1,
    status: 'conditional',
    sourceQuality: 'strong_creator',
    conversionNote: '무료 악보/PDF 나눔은 제작자 상호작용이 있고 7일 연습 캘린더로 옮기기 쉽다. 악보 자체가 아니라 원문 링크와 연습 일정만 다루는 것이 맞다.',
    uxAction: '연주 목표일, 난이도, 연습 시간대만 받고 D-7 저장부터 D-1 녹음 체크까지 보여준다.',
  },
  {
    candidateId: 'cat-adoption-first-week-setup',
    userScore: 4.2,
    status: 'conditional',
    sourceQuality: 'strong_creator',
    sourceIssue: '건강/접종 판단은 수의사 확인으로 분리해야 한다.',
    conversionNote: '고양이 입양은 준비물과 첫 주 적응 체크가 날짜 기준으로 나뉘어 Flow화 근거가 좋다. 기존 강아지 후보와 비교해 반려묘 특화 첫 주 UX를 볼 수 있다.',
    uxAction: '입양일 기준 D-3/D-1/입양 후 3일/7일 체크와 병원 질문 메모만 둔다.',
  },
  {
    candidateId: 'jeonse-contract-precheck-docs',
    userScore: 4.3,
    status: 'conditional',
    sourceQuality: 'strong_creator',
    sourceIssue: '법률 판단처럼 보이면 안 된다. 공식 자료 링크와 보류 메모가 필요하다.',
    conversionNote: '전세계약 전 확인은 사용자 수요가 크고 계약 전/당일/입주 후 흐름이 선명하다. 다만 FlowMe는 문서 확인 체크와 질문 메모만 제공해야 한다.',
    uxAction: '체크리스트와 보류 결과를 중심에 두고 계약 안전 점수나 법률 결론은 만들지 않는다.',
  },
  {
    candidateId: 'goodnotes-template-study-setup',
    userScore: 3.9,
    status: 'conditional',
    sourceQuality: 'strong_creator',
    conversionNote: '무료 속지/템플릿 콘텐츠는 저장 후 실행 저니가 약해 FlowMe가 보완할 수 있다. 다만 지속 반복보다 다운로드-가져오기-첫 사용에 가까운 짧은 체크다.',
    uxAction: '템플릿 파일을 복제하지 않고 원문 링크, 사용 앱, 첫 사용일, 일주일 뒤 유지/교체만 둔다.',
  },
  {
    candidateId: 'macaron-template-baking-day',
    userScore: 4,
    status: 'conditional',
    sourceQuality: 'strong_creator',
    sourceIssue: '레시피 성공 보장이나 식품 안전 판단은 제외해야 한다.',
    conversionNote: '마카롱 도안 PDF는 제작자 자료형 콘텐츠와 베이킹 프로젝트가 결합된 후보라 새로운 축을 보여준다. 도안 링크, 재료, 출력, 당일 결과 메모가 명확하다.',
    uxAction: '도안 자체를 복제하지 않고 D-5 도안 확인, D-3 재료, D-1 출력, 당일 결과 메모로 제한한다.',
  },
];

export const koreanFlowContentUserReviewById = new Map(
  koreanFlowContentUserReviews.map((review) => [review.candidateId, review]),
);

export const representativeKoreanFlowContentIds = koreanFlowContentUserReviews
  .filter((review) => review.status === 'representative')
  .map((review) => review.candidateId);
