import type { KoreanFlowContentCandidate } from './korean-flow-content-candidates';
import type {
  KoreanFlowContentUserReview,
  KoreanFlowSourceQuality,
  KoreanFlowUserReviewStatus,
} from './korean-flow-content-user-review';

type FlowItem = KoreanFlowContentCandidate['flowItems'][number];

export type KoreanFlowContentSourceRefresh = {
  candidateId: string;
  decision: 'replaced_source' | 'officialized_source' | 'kept_with_hold';
  refreshedAt: string;
  sourceTitle: string;
  sourceUrl: string;
  sourceType: KoreanFlowContentCandidate['sourceType'];
  sourceQuality: KoreanFlowSourceQuality;
  status: KoreanFlowUserReviewStatus;
  userScore: number;
  fitScore: number;
  sourceSignal: string;
  demandSignal: string;
  conversionNote: string;
  uxAction: string;
  flowItems: FlowItem[];
  memo: string;
  uxNote: string;
  sourceBoundary: string;
  rubric: {
    userNeedFit: number;
    executionClarity: number;
    contentFidelity: number;
    portability: number;
    cognitiveLoad: number;
    copySpecificity: number;
    sourceSafety: number;
    operability: number;
  };
  simulation: {
    calendar: string;
    detail: string;
    exportMemo: string;
    failureSignal: string;
    verdict: string;
  };
};

const refreshedAt = '2026-06-03';

export const koreanFlowContentSourceRefreshes: KoreanFlowContentSourceRefresh[] = [
  {
    candidateId: 'air-purifier-filter-seasonal',
    decision: 'officialized_source',
    refreshedAt,
    sourceTitle: '삼성전자서비스 공기청정기 필터 교환 방법/교환 주기 안내',
    sourceUrl: 'https://www.samsungsvc.co.kr/solution/37614',
    sourceType: 'brand_support',
    sourceQuality: 'clear_official',
    status: 'promote',
    userScore: 4.2,
    fitScore: 4.3,
    sourceSignal: '세척 필터와 교체 필터를 구분하고, 모델별 사용설명서 확인과 필터 리셋이 실행 단위로 나뉜다.',
    demandSignal: '공기청정기는 필터 알림이 뜬 뒤에야 관리하는 경우가 많아, 보유 제품 루틴으로 옮기기 좋다.',
    conversionNote: '기존 광범위 블로그 대신 브랜드 공식 문서 기준으로 줄이면 Flow가 선명해진다.',
    uxAction: '제품명과 마지막 필터 리셋일만 받고, 캘린더에는 필터 확인 1개만 둔다.',
    flowItems: [
      { title: '세척 필터 먼지 제거하기', schedule: '매월 1회', memo: '먼지거름필터처럼 세척 가능한 필터만 분리해 먼지를 제거하고 완전히 말린다.', completion: '세척 필터가 마른 뒤 재장착됨' },
      { title: '교체 필터 알림 확인하기', schedule: '필터 알림 또는 6~12개월', memo: '탈취/집진 필터처럼 교체형 필터는 모델별 사용설명서와 필터 알림을 우선한다.', completion: '교체/유지 결정 완료' },
      { title: '필터 리셋 처리하기', schedule: '청소 또는 교체 직후', memo: '제품별 리셋 버튼 조작이 다르므로 원문 또는 사용설명서를 확인한다.', completion: '필터 알림 리셋 완료' },
    ],
    memo: '필터명, 모델명, 구매 링크, 리셋 방법만 메모에 둔다.',
    uxNote: '여러 필터를 각각 캘린더에 펼치지 말고, 상세 내부 체크리스트로 묶는다.',
    sourceBoundary: '모델별 필터 종류와 리셋 방식은 사용설명서 우선이다.',
    rubric: { userNeedFit: 4, executionClarity: 4, contentFidelity: 4, portability: 4, cognitiveLoad: 4, copySpecificity: 4, sourceSafety: 5, operability: 4 },
    simulation: {
      calendar: '공기청정기 필터 확인',
      detail: '세척 필터, 교체 필터, 리셋 체크 3개만 표시',
      exportMemo: '모델명, 공식 링크, 필터 리셋 방법, 구매 링크',
      failureSignal: '필터별 주기를 모두 개별 일정으로 만들면 캘린더가 과밀해진다.',
      verdict: '공식 기준으로 보강되면 조건부에서 추가 검증 후보로 올릴 수 있다.',
    },
  },
  {
    candidateId: 'robot-vacuum-monthly-care',
    decision: 'officialized_source',
    refreshedAt,
    sourceTitle: '삼성전자서비스 로봇청소기 에러모드 조치방법',
    sourceUrl: 'https://www.samsungsvc.co.kr/solution/21257',
    sourceType: 'brand_support',
    sourceQuality: 'clear_official',
    status: 'conditional',
    userScore: 3.8,
    fitScore: 3.9,
    sourceSignal: '파워브러시, 바퀴, 장애물 센서, 추락방지 센서, 먼지통 같은 점검 위치가 명확하다.',
    demandSignal: '청소기 성능 저하나 에러가 생겼을 때만 필요한 트러블슈팅 성격이 강하다.',
    conversionNote: '월간 관리 Flow로 억지 확장하지 말고 에러 예방 점검 루틴으로 축소해야 한다.',
    uxAction: '제품 관리 하위 루틴으로 두고 대표 후보에서는 제외한다.',
    flowItems: [
      { title: '브러시와 바퀴 이물질 제거하기', schedule: '월 1회 또는 에러 발생 시', memo: '전원을 끄고 파워브러시, 측면솔, 바퀴에 걸린 실과 머리카락을 제거한다.', completion: '브러시/바퀴 이물질 제거 완료' },
      { title: '센서창 부드러운 천으로 닦기', schedule: '월 1회', memo: '장애물 센서와 추락방지 센서창에 쌓인 먼지를 닦는다.', completion: '센서창 닦기 완료' },
      { title: '먼지통 장착 상태 확인하기', schedule: '먼지통 비운 뒤', memo: '먼지통이 제대로 삽입되지 않으면 에러가 날 수 있으므로 장착음을 확인한다.', completion: '먼지통 장착 확인' },
    ],
    memo: '에러 코드별 대응은 원문 링크로 둔다.',
    uxNote: '정기 루틴보다는 문제 발생 시 바로 여는 제품 도움말 Flow가 더 자연스럽다.',
    sourceBoundary: '제품 모델이 다르면 에러 코드와 조치가 달라질 수 있다.',
    rubric: { userNeedFit: 3, executionClarity: 4, contentFidelity: 4, portability: 3, cognitiveLoad: 4, copySpecificity: 4, sourceSafety: 5, operability: 4 },
    simulation: {
      calendar: '로봇청소기 브러시·센서 점검',
      detail: '브러시, 센서창, 먼지통 3개 체크',
      exportMemo: '공식 에러 코드 링크와 모델명',
      failureSignal: '매주 일정으로 만들면 사용자가 귀찮아하고 해제할 가능성이 높다.',
      verdict: 'Flow화는 가능하지만 대표 후보가 아니라 제품 프로필 보조 루틴이다.',
    },
  },
  {
    candidateId: 'humidifier-daily-weekly-clean',
    decision: 'officialized_source',
    refreshedAt,
    sourceTitle: '위닉스 올바른 가습기 사용설명서',
    sourceUrl: 'https://kr.object.ncloudstorage.com/w2r-commerce-winix/manual/202412/241217073857277-603a575c0c7f445387708be2cf41f23a.pdf',
    sourceType: 'brand_support',
    sourceQuality: 'clear_official',
    status: 'conditional',
    userScore: 3.7,
    fitScore: 3.8,
    sourceSignal: '제품 설명서에 세척 주기, 본체 세척, 열탕/식기세척 가능 여부 같은 모델별 기준이 있다.',
    demandSignal: '겨울철 반복 사용 제품이라 위생 루틴 가치는 있지만, 제품별 차이가 크다.',
    conversionNote: '건강 조언이 아니라 제품 설명서 기반 세척 알림으로 제한해야 한다.',
    uxAction: '사용 계절을 입력받고, 시즌이 끝나면 루틴을 자동 일시정지할 수 있어야 한다.',
    flowItems: [
      { title: '물통 비우고 헹구기', schedule: '사용일 매일', memo: '남은 물을 버리고 물통을 헹군 뒤 새 물을 넣는다.', completion: '묵은 물 없음' },
      { title: '본체와 분무부 세척하기', schedule: '주 2회 기준으로 확인', memo: '초음파 진동자 등 민감 부위는 설명서에 맞는 도구로 닦는다.', completion: '세척 후 재조립 완료' },
      { title: '세척 가능 부품 구분하기', schedule: '첫 저장 시', memo: '열탕 소독이나 식기세척기 사용 가능 부품인지 설명서에서 확인한다.', completion: '세척 가능 부품 메모 완료' },
    ],
    memo: '제품별 금지 세척법과 부품별 세척 가능 여부를 메모 상단에 둔다.',
    uxNote: '매일 체크가 부담스러울 수 있으므로 사용일만 체크하는 계절형 루틴이 필요하다.',
    sourceBoundary: '위생/건강 효과를 보장하지 않고 제품 관리로만 표현한다.',
    rubric: { userNeedFit: 3, executionClarity: 4, contentFidelity: 4, portability: 3, cognitiveLoad: 3, copySpecificity: 4, sourceSafety: 5, operability: 4 },
    simulation: {
      calendar: '가습기 물통 비우기',
      detail: '매일 물통, 주간 본체 세척, 부품별 금지 세척법',
      exportMemo: '사용설명서 링크와 모델명',
      failureSignal: '매일/주 2회/월간이 한 화면에 섞이면 사용자가 루틴을 끈다.',
      verdict: '제품별 설명서가 있으면 가능하지만 P0 대표 후보는 아니다.',
    },
  },
  {
    candidateId: 'water-purifier-filter-cycle',
    decision: 'replaced_source',
    refreshedAt,
    sourceTitle: '정수기 필터 교체 방법과 교체 주기',
    sourceUrl: 'https://pihamadam.tistory.com/267',
    sourceType: 'creator_blog',
    sourceQuality: 'strong_creator',
    status: 'promote',
    userScore: 4.3,
    fitScore: 4.4,
    sourceSignal: '침전, 프리카본, RO/나노, 후카본처럼 필터별 교체 주기가 나뉘고 코크/출수구, 자가 살균, 물맛·냄새 확인이 별도 관리 단서로 있다.',
    demandSignal: '필터별 다음 교체일과 구매/배송 링크가 연결되는 반복 관리 과제다.',
    conversionNote: '원문의 필터별 주기를 시트 행으로 옮기고, 사용자는 정수기 모델·필터 구성·마지막 교체일만 채운다.',
    uxAction: '캘린더보다 필터 주기표를 먼저 보여주고, 가까운 교체 행만 알림으로 연결한다.',
    flowItems: [
      { title: '침전 필터 교체 확인', schedule: '3~6개월', memo: '모래, 녹물 등 큰 입자를 거르는 첫 단계 필터의 마지막 교체일을 적는다.', completion: '교체일 또는 유지 결정 기록' },
      { title: '프리카본 필터 확인', schedule: '6~12개월', memo: '염소, 화학물질, 냄새 제거 필터의 마지막 교체일과 다음 확인일을 적는다.', completion: '다음 확인일 저장' },
      { title: 'RO/나노 필터 확인', schedule: '12~24개월', memo: '핵심 정수 필터는 제조사 안내와 렌탈사 기준을 우선한다.', completion: '교체 예약 또는 구매 링크 저장' },
      { title: '후카본 필터 확인', schedule: '9~12개월', memo: '정수 마지막 단계의 물맛·냄새 개선 필터를 프리카본과 분리해 기록한다.', completion: '후카본 다음 확인일 저장' },
    ],
    memo: '코크/출수구 청소, 자가 살균 실행 여부, 물맛·냄새 변화, 필터 구매 링크, 렌탈사 연락처를 메모에 둔다.',
    uxNote: '사용자는 표 행에서 마지막 교체일과 다음 확인일만 채우고, 코크/출수구와 물맛·냄새는 상태 메모로 남긴다.',
    sourceBoundary: '교체 주기와 정수 성능 판단은 최종적으로 제조사/렌탈사 기준을 우선한다.',
    rubric: { userNeedFit: 4, executionClarity: 4, contentFidelity: 5, portability: 4, cognitiveLoad: 4, copySpecificity: 4, sourceSafety: 5, operability: 4 },
    simulation: {
      calendar: '정수기 필터 교체 확인',
      detail: '침전/프리카본/RO·나노/후카본 행과 다음 확인일 표시',
      exportMemo: '모델명, 필터 구성, 마지막 교체일, 코크/출수구, 물맛·냄새 메모',
      failureSignal: '프리카본과 후카본을 한 행으로 묶으면 원문의 필터별 주기 차이가 사라진다.',
      verdict: '필터별 주기표가 먼저 보이면 sheet-first Flow로 검증하기 좋다.',
    },
  },
  {
    candidateId: 'fridge-cleanout-weekly-plan',
    decision: 'replaced_source',
    refreshedAt: '2026-06-08',
    sourceTitle: "월 10만 원 식비 절약, 제가 성공한 '냉장고 파먹기' 7일 식단 플랜",
    sourceUrl: 'https://smilellama.tistory.com/entry/%EC%9B%94-10%EB%A7%8C-%EC%9B%90-%EC%8B%9D%EB%B9%84-%EC%A0%88%EC%95%BD-%EC%A0%9C%EA%B0%80-%EC%84%B1%EA%B3%B5%ED%95%9C-%EB%83%89%EC%9E%A5%EA%B3%A0-%ED%8C%8C%EB%A8%B9%EA%B8%B0-7%EC%9D%BC-%EC%8B%9D%EB%8B%A8-%ED%94%8C%EB%9E%9C-%EC%95%8C%EB%9C%B0-%EC%9E%A5%EB%B3%B4%EA%B8%B0-%ED%8C%81-%ED%8F%AC%ED%95%A8',
    sourceType: 'creator_blog',
    sourceQuality: 'strong_creator',
    status: 'conditional',
    userScore: 4.2,
    fitScore: 4.2,
    sourceSignal: '원문은 냉장고 지도 작성, 이번 주 메인 요리 2~3개 선정, 추가 구매 리스트 제한, 1~2일차 신선 재료 소진, 3~4일차 남은 재료 변형, 5~6일차 냉동실 활용, 7일차 싹쓸이 데이로 실행 단계를 나눈다.',
    demandSignal: '냉장고 속 남은 재료를 먼저 쓰고 장보기를 줄이는 과제는 시작일, 재고 재료, 7일 메뉴 후보, 사지 말 것 목록이 있으면 바로 실행할 수 있다.',
    conversionNote: '절약 금액을 보장하지 않고 원문의 7일 재고 소진 순서만 작은 시트로 옮긴다. 사용자는 소진할 재료 3개와 보류할 구매만 채운다.',
    uxAction: '캘린더가 아니라 7일 행이 있는 시트로 보여주고, 각 행에는 사용할 재료와 장보기 보류 여부만 남긴다.',
    flowItems: [
      { title: '냉장고 지도와 우선 소진 재료 고르기', schedule: 'D-Day', memo: '냉장·냉동·채소칸을 훑고 금방 시드는 재료, 개봉한 반찬, 냉동 재료 중 이번 주 먼저 쓸 3개를 고른다.', completion: '우선 소진 재료 3개 선택' },
      { title: '7일 메뉴 후보를 2~3개 메인으로 묶기', schedule: 'D-Day', memo: '완벽한 식단표가 아니라 하나의 메인 재료를 2~3끼로 돌려 쓰는 후보만 적는다.', completion: '7일 메뉴 후보 작성' },
      { title: '추가 구매와 사지 말 것 분리하기', schedule: 'D+1~D+6', memo: '부재료나 필수 재료만 추가 구매에 두고, 이미 있는 계란·두부·냉동만두처럼 중복 구매할 품목은 보류 목록에 둔다.', completion: '오늘 구매/보류 결정' },
      { title: '7일차 남은 재료 처리하기', schedule: 'D+7', memo: '남은 자투리 채소나 냉동 재료는 비빔밥, 부침개, 볶음밥, 소분 냉동 중 하나로 처리한다.', completion: '남은 재료 처리 방향 결정' },
    ],
    memo: '월 절약 금액, 식단 성공률, 영양 처방은 Flow에 넣지 않는다. 원문 링크와 사용자가 고른 재료/메뉴/사지 말 것 목록만 남긴다.',
    uxNote: '집밥 Flow는 작은 시트가 맞다. 사용자가 직접 메뉴명을 바꾸고, 구매 보류 항목을 오늘 장보기 전에 확인할 수 있어야 한다.',
    sourceBoundary: '개인 경험 기반 콘텐츠다. 절약 금액, 건강 효과, 식단 균형을 보장하지 않고 재고 소진 실행표로만 다룬다.',
    rubric: { userNeedFit: 4, executionClarity: 4, contentFidelity: 4, portability: 5, cognitiveLoad: 4, copySpecificity: 4, sourceSafety: 4, operability: 4 },
    simulation: {
      calendar: '냉장고 재료 먼저 쓰기',
      detail: 'D-Day 재고 3개, D+1~D+6 메뉴 후보, 구매 보류 목록, D+7 남은 재료 처리',
      exportMemo: '원문 링크, 우선 소진 재료, 7일 메뉴 후보, 사지 말 것 목록',
      failureSignal: '월 절약 금액이나 영양 식단으로 커지면 사용자가 입력해야 할 정보가 과해진다.',
      verdict: '7일 재고 소진 순서가 선명해 sheet-first 후보로 유지하되 조건부 승격이 맞다.',
    },
  },
  {
    candidateId: 'freelancer-income-tax-docs',
    decision: 'officialized_source',
    refreshedAt: '2026-06-08',
    sourceTitle: '국세청 종합소득세 개요',
    sourceUrl: 'https://nts.go.kr/nts/cm/cntnts/cntntsView.do?cntntsId=7664&mi=2224',
    sourceType: 'official',
    sourceQuality: 'clear_official',
    status: 'conditional',
    userScore: 3.9,
    fitScore: 4.0,
    sourceSignal: '국세청 안내는 장부 기록·보관, 총수입금액과 필요경비, 기준경비율/단순경비율, 신고하지 않을 경우의 불이익처럼 공식 확인이 필요한 판단 영역을 분리한다.',
    demandSignal: '프리랜서는 5월 신고 전에 소득 자료, 경비 증빙, 홈택스 확인 질문을 모아야 하지만 세액 판단은 공식 신고 화면이나 세무대리인 확인이 필요하다.',
    conversionNote: '블로그식 절세 요약 대신 공식 안내 링크를 기준으로 서류 준비 체크만 남긴다. Flow는 신고 대행이나 세액 계산을 하지 않는다.',
    uxAction: '마감일 기준 자료 모으기, 경비 증빙 폴더, 공식 확인 질문, 제출 전 누락 체크 4단계로 제한한다.',
    flowItems: [
      { title: '소득 자료 위치 모으기', schedule: '마감 14일 전', memo: '지급명세서, 플랫폼 정산 내역, 원천징수 관련 자료가 어디에 있는지만 메모한다.', completion: '소득 자료 위치 메모' },
      { title: '경비 증빙 폴더 나누기', schedule: '마감 10일 전', memo: '카드 내역, 세금계산서, 현금영수증, 구독료, 장비 구매 내역을 판단 없이 후보 폴더로 분류한다.', completion: '경비 후보 폴더 정리' },
      { title: '홈택스/세무대리인 확인 질문 쓰기', schedule: '마감 7일 전', memo: '기장의무, 경비 인정, 누락 자료처럼 판단이 필요한 항목은 질문으로 남기고 Flow가 답하지 않는다.', completion: '확인 질문 목록 작성' },
      { title: '제출 전 누락 항목 체크', schedule: '마감 2일 전', memo: '자료가 모였는지와 공식 링크를 열어봤는지만 확인한다. 세액과 신고 방식은 외부에서 확정한다.', completion: '누락/보류 항목 결정' },
    ],
    memo: '국세청 종합소득세 안내, 홈택스, 세무대리인 연락처를 메모 상단에 둔다. 주민등록번호, 세액, 계좌번호는 저장하지 않는다.',
    uxNote: '세무 Flow는 action checklist까지만 안전하다. 금액 계산이나 절세 판단으로 보이는 UI는 제외한다.',
    sourceBoundary: '기장의무, 경비 인정, 신고 의무, 세액 산출은 국세청/홈택스/세무 전문가 확인을 우선한다.',
    rubric: { userNeedFit: 3, executionClarity: 4, contentFidelity: 5, portability: 4, cognitiveLoad: 4, copySpecificity: 4, sourceSafety: 5, operability: 4 },
    simulation: {
      calendar: '종합소득세 서류 모으기',
      detail: '소득 자료, 경비 증빙, 공식 확인 질문, 누락 체크',
      exportMemo: '국세청 링크, 홈택스 확인 위치, 세무대리인 질문 목록',
      failureSignal: '세액 계산이나 절세 추천을 넣으면 FlowMe 범위를 넘고 리스크가 커진다.',
      verdict: '공식 링크 기반의 조건부 서류 준비 Flow로 유지한다.',
    },
  },
  {
    candidateId: 'first-kimjang-weekend-checklist',
    decision: 'officialized_source',
    refreshedAt: '2026-06-08',
    sourceTitle: '식약처 김장철, 절임배추 안전하게 사용하세요',
    sourceUrl: 'https://impfood.mfds.go.kr/CFBBB02F02/getCntntsDetail?cntntsSn=281730',
    sourceType: 'official',
    sourceQuality: 'clear_official',
    status: 'conditional',
    userScore: 4.1,
    fitScore: 4.1,
    sourceSignal: '식약처 안내는 절임배추를 받은 후 당일 사용하는 것이 좋고, 상온에서 1일 이상 보관했다면 세척 후 사용하는 것이 바람직하다는 위생 경계를 제공한다.',
    demandSignal: '김장은 전날 절임, 당일 버무리기, 보관 전환이 있는 계절 프로젝트지만 위생/보관 판단은 공식 안전 안내와 분리해야 한다.',
    conversionNote: '레시피 비율을 확정하지 않고 공식 절임배추 사용 경계를 보조 출처로 붙인다. Flow는 D-3/D-1/당일/보관 전환 체크만 제공한다.',
    uxAction: '배추 수와 김장 날짜만 받고, 절임배추 수령/당일 사용/보관 전환 확인을 강조한다.',
    flowItems: [
      { title: '김장 분량과 장보기 수량 정하기', schedule: 'D-3', memo: '배추 포기 수와 부족 재료를 원문 레시피 메모로만 남기고, 보관/위생은 식약처 안내를 확인한다.', completion: '장보기 수량과 부족 재료 확정' },
      { title: '절임배추 수령 시간 확인하기', schedule: 'D-1', memo: '절임배추는 받은 뒤 당일 사용하는 것을 기본으로 두고, 부득이하게 보관했다면 공식 안내 기준을 확인한다.', completion: '수령 시간과 사용일 확인' },
      { title: '김장 당일 버무리기 체크', schedule: '김장 당일', memo: '헹굼, 배수, 양념 버무리기 순서는 원문 메모를 참고하되 안전 판단은 공식 안내를 우선한다.', completion: '버무리기 완료와 용기 담기' },
      { title: '실온 starter와 저온 보관 전환', schedule: '김장 후', memo: '실온에 오래 두지 않도록 보관 위치와 다음 확인일을 정한다.', completion: '보관 위치와 다음 확인일 저장' },
    ],
    memo: '레시피 비율은 원문 링크, 절임배추 위생은 식약처 링크로 분리한다. 발효 성공, 염도, 위생 안전을 보장하지 않는다.',
    uxNote: '김장은 생활 프로젝트 후보로 좋지만 대표 승격 전에는 공식 위생 보조 출처가 화면에 같이 보여야 한다.',
    sourceBoundary: '절임배추 보관, 세척, 위생 판단은 식약처 안내를 우선한다. 발효 결과나 식품 안전을 Flow가 확정하지 않는다.',
    rubric: { userNeedFit: 4, executionClarity: 4, contentFidelity: 4, portability: 4, cognitiveLoad: 4, copySpecificity: 4, sourceSafety: 5, operability: 4 },
    simulation: {
      calendar: '절임배추 수령과 김장 당일 체크',
      detail: 'D-3 수량, D-1 수령/보관, 당일 버무리기, 보관 전환',
      exportMemo: '식약처 절임배추 안내, 레시피 원문 링크, 보관 위치',
      failureSignal: '염도 계산기나 발효 성공 보장으로 만들면 생활 체크리스트 범위를 넘는다.',
      verdict: '공식 위생 경계를 붙인 조건부 계절 프로젝트 후보로 유지한다.',
    },
  },
  {
    candidateId: 'beginner-camping-packing-sheet',
    decision: 'replaced_source',
    refreshedAt: '2026-06-08',
    sourceTitle: '캠핑 초보 준비물 리스트, 카테고리별 필수·선택 장비 완전정리',
    sourceUrl: 'https://hackf.tistory.com/231',
    sourceType: 'creator_blog',
    sourceQuality: 'strong_creator',
    status: 'conditional',
    userScore: 4.2,
    fitScore: 4.2,
    sourceSignal: '원문은 숙박, 취사, 조명·전력, 의복·위생, 안전·응급으로 준비물을 나누고 계절별 추가 품목, 인원별 양, 방수 백, 차량 로딩 순서, 구급키트와 화재 대비를 정리한다.',
    demandSignal: '첫 캠핑은 출발일, 인원, 캠핑 형태에 따라 준비물 표를 복사하고 필요 없는 행을 끄는 sheet artifact 수요가 분명하다.',
    conversionNote: '막연한 캠핑 팁 대신 카테고리별 필수/선택 표와 안전 행을 Flow 시트로 옮긴다. 장비 구매 추천이나 가격 판단은 제외한다.',
    uxAction: '캘린더보다 준비물 표를 먼저 보여주고, 숙박·취사·조명·위생·안전 탭 또는 그룹 행으로 접는다.',
    flowItems: [
      { title: '캠핑 형태와 인원 기준 고르기', schedule: 'D-7', memo: '오토캠핑/차박/글램핑, 인원, 계절을 선택하고 필요한 장비 그룹만 켠다.', completion: '준비 기준 확정' },
      { title: '숙박·취사·조명 필수품 체크', schedule: 'D-5', memo: '텐트, 침낭, 매트, 버너, 연료, 코펠, 랜턴, 보조배터리처럼 없으면 현장에서 곤란한 품목을 먼저 확인한다.', completion: '핵심 장비 준비 상태 표시' },
      { title: '위생·안전·응급 품목 확인', schedule: 'D-3', memo: '물티슈, 쓰레기봉투, 구급키트, 비상 연락처, 소화기/물통, 방수 보관을 별도 그룹으로 체크한다.', completion: '안전 품목 체크 완료' },
      { title: '짐 싣기와 빠진 품목 최종 점검', schedule: 'D-1', memo: '무거운 것은 아래, 먼저 꺼낼 텐트/타프는 접근 쉬운 위치에 두고 빠진 품목을 보류/대여로 표시한다.', completion: '차량 로딩과 보류 항목 결정' },
    ],
    memo: '구매 링크, 장비 브랜드, 가격 추천은 넣지 않는다. 고캠핑/소비자 안전 정보 링크와 개인 보유 장비 메모만 둔다.',
    uxNote: '캠핑 Flow는 반복 복사 가능한 sheet-first 후보가 맞다. 안전 그룹은 기본 펼침으로 두는 것이 낫다.',
    sourceBoundary: '캠핑장 규정, 화기 사용, 전기 사용, 날씨와 안전 판단은 캠핑장/공식 안전 안내를 우선한다.',
    rubric: { userNeedFit: 4, executionClarity: 5, contentFidelity: 4, portability: 5, cognitiveLoad: 4, copySpecificity: 4, sourceSafety: 4, operability: 4 },
    simulation: {
      calendar: '캠핑 준비물 최종 점검',
      detail: '숙박, 취사, 조명·전력, 위생, 안전 그룹별 준비 상태',
      exportMemo: '출발일, 인원, 캠핑 형태, 보유 장비, 보류/대여 품목',
      failureSignal: '모든 장비를 한 화면에 펼치면 초보 사용자가 핵심 품목과 선택 품목을 구분하지 못한다.',
      verdict: '시트형 대표 후보로 가능하지만 실제 UI에서는 그룹 접기와 안전 강조가 필요하다.',
    },
  },
  {
    candidateId: 'monstera-care-routine',
    decision: 'replaced_source',
    refreshedAt,
    sourceTitle: '몬스테라 키우기 겨울철 실내 공기정화식물 관리법',
    sourceUrl: 'https://ocppyong.com/153',
    sourceType: 'creator_blog',
    sourceQuality: 'strong_creator',
    status: 'promote',
    userScore: 4.3,
    fitScore: 4.4,
    sourceSignal: '겨울철 물주기, 온도, 통풍, 잎 끝 마름/노랗게 변함 같은 관찰 신호가 루틴으로 나뉜다.',
    demandSignal: '초보 식물 사용자는 정답 주기보다 물주기 전 확인과 보류 판단이 필요하다.',
    conversionNote: 'AI 느낌 원문 대신 실제 관리 경험이 있는 식물 루틴 글을 기준으로 재작성한다.',
    uxAction: '물주기 완료보다 오늘은 보류 상태를 같은 무게로 둔다.',
    flowItems: [
      { title: '겉흙 마름 보고 물주기 결정하기', schedule: '7~10일마다 확인', memo: '흙이 마르지 않았으면 물주기를 보류하고 통풍만 확인한다.', completion: '물주기 또는 보류 선택' },
      { title: '잎끝 마름과 노란 잎 보기', schedule: '2주마다', memo: '온도, 빛, 물주기 중 무엇이 바뀌었는지 짧게 메모한다.', completion: '이상 없음 또는 위치 조정 기록' },
      { title: '봄 분갈이 필요 확인하기', schedule: '봄 시작 전', memo: '뿌리 과밀, 배수, 새흙 보충 필요 여부를 확인한다.', completion: '분갈이 필요 여부 결정' },
    ],
    memo: '사진은 선택으로 두고, 기본은 물주기/보류/위치 조정만 둔다.',
    uxNote: '식물 Flow는 캘린더 알림이 “물을 주세요”가 아니라 “물 줄지 확인”이어야 한다.',
    sourceBoundary: '집의 온도/빛/화분 상태에 따라 달라지므로 고정 주기가 아니라 확인 알림으로 둔다.',
    rubric: { userNeedFit: 4, executionClarity: 4, contentFidelity: 4, portability: 4, cognitiveLoad: 4, copySpecificity: 4, sourceSafety: 4, operability: 4 },
    simulation: {
      calendar: '몬스테라 물 줄지 확인',
      detail: '물주기/보류 토글과 잎 상태 메모',
      exportMemo: '겨울 관리 원문 링크와 위치/화분 메모',
      failureSignal: '정해진 날짜마다 물주기만 표시하면 과습을 유도할 수 있다.',
      verdict: '실제 관리 경험 원문으로 바꾸면 FlowMe에 잘 맞는다.',
    },
  },
  {
    candidateId: 'cat-litter-box-clean',
    decision: 'replaced_source',
    refreshedAt,
    sourceTitle: '비마이펫 고양이 화장실 청소 방법 및 주기',
    sourceUrl: 'https://v.daum.net/v/PZgm7hSgLk?vfrom_area=channel_ranking',
    sourceType: 'creator_blog',
    sourceQuality: 'strong_creator',
    status: 'conditional',
    userScore: 4.0,
    fitScore: 4.1,
    sourceSignal: '배설물 제거, 주변 정리, 전체 모래 교체, 세척 주기가 실행 단위로 나뉜다.',
    demandSignal: '반려묘 집사는 매일 반복되는 집안일을 가족과 나눠 체크할 필요가 있다.',
    conversionNote: '원문 불명확 문제는 반려동물 전문 콘텐츠로 교체하면 해결된다.',
    uxAction: '혼자 쓰는 루틴보다 가족 공유 체크가 있을 때 가치가 커진다.',
    flowItems: [
      { title: '배설물 덩어리 제거하기', schedule: '매일 1~2회', memo: '스쿱으로 배설물과 오염된 모래를 제거한다.', completion: '오늘 배설물 제거 완료' },
      { title: '모래 높이와 냄새 확인하기', schedule: '주 1회', memo: '부족한 모래를 보충하고 냄새가 심하면 전체 교체일을 앞당긴다.', completion: '보충/유지 결정' },
      { title: '화장실 세척과 전체 교체하기', schedule: '모래 종류별 주기', memo: '전체 모래를 버리고 화장실을 세척한 뒤 완전히 말린다.', completion: '전체 교체 완료' },
    ],
    memo: '모래 종류, 교체 주기, 구매 링크, 담당 가족을 메모에 둔다.',
    uxNote: '매일 반복이지만 단순하고 가족 분담이 가능해 루틴 UX 검증에 좋다.',
    sourceBoundary: '배변 이상은 건강 문제일 수 있어 진단처럼 표현하지 않는다.',
    rubric: { userNeedFit: 4, executionClarity: 4, contentFidelity: 4, portability: 4, cognitiveLoad: 4, copySpecificity: 4, sourceSafety: 4, operability: 4 },
    simulation: {
      calendar: '고양이 화장실 청소',
      detail: '오늘 배설물 제거, 주간 보충, 전체 교체 예정',
      exportMemo: '모래 종류와 구매 링크',
      failureSignal: '전체 교체 주기를 단일 정답으로 고정하면 모래 종류 차이를 놓친다.',
      verdict: '좋지만 개인/가족 루틴 성격이라 대표 P0보다는 조건부가 맞다.',
    },
  },
  {
    candidateId: 'puppy-vaccination-schedule',
    decision: 'replaced_source',
    refreshedAt,
    sourceTitle: '멍맵 강아지 예방접종 스케줄 완벽 가이드',
    sourceUrl: 'https://mungmap.co.kr/guide/puppy-vaccination-schedule',
    sourceType: 'creator_blog',
    sourceQuality: 'strong_creator',
    status: 'conditional',
    userScore: 4.1,
    fitScore: 4.1,
    sourceSignal: '생후 6~8주부터 연간 부스터까지의 접종 표, 접종 전 체크리스트, 병원 상담 안내가 함께 있다.',
    demandSignal: '입양 직후 보호자가 접종 기록과 다음 병원 예약을 놓치지 않으려는 수요가 있다.',
    conversionNote: '원문은 실제 일정 표가 있어 Flow화 가능하지만, 날짜 확정과 이상 반응 판단은 수의사 확인으로 분리해야 한다.',
    uxAction: '생일/입양일 기준 임시 일정을 만들고, 병원 확인 후 확정 상태로 바꾸게 한다.',
    flowItems: [
      { title: '이전 접종 기록 확인하기', schedule: '입양 당일~3일', memo: '분양/입양 서류, 접종수첩, 병원 기록을 모아 첫 병원에 보여준다.', completion: '기록 확인 또는 없음 표시' },
      { title: '동물병원에서 다음 접종일 확정하기', schedule: '첫 병원 방문일', memo: '일반 참고표가 아니라 수의사가 정한 다음 날짜를 캘린더에 저장한다.', completion: '다음 접종 예약일 저장' },
      { title: '광견병/연간 접종 확인하기', schedule: '병원 안내 기준', memo: '지자체 지원 기간이 있으면 지역 공지를 함께 확인한다.', completion: '연간 접종 일정 저장' },
    ],
    memo: '접종 종류 설명은 접고, 캘린더에는 병원에서 확정한 날짜만 올린다.',
    uxNote: '민감 영역이라 “예상 일정”과 “병원 확정 일정” 상태가 구분되어야 한다.',
    sourceBoundary: '접종 종류와 간격은 수의사 판단 우선이며, Flow는 기록과 예약 관리만 한다.',
    rubric: { userNeedFit: 4, executionClarity: 4, contentFidelity: 3, portability: 4, cognitiveLoad: 3, copySpecificity: 4, sourceSafety: 5, operability: 4 },
    simulation: {
      calendar: '강아지 다음 접종 병원 확인',
      detail: '기록 확인, 병원 확정일, 연간 접종 메모',
      exportMemo: '원문 링크와 병원명/전화번호',
      failureSignal: '앱이 접종 날짜를 확정 처방처럼 보이면 위험하다.',
      verdict: 'Flow화는 가능하지만 대표 후보 전에는 공식/수의사 기준 보강이 더 필요하다.',
    },
  },
  {
    candidateId: 'moving-d30-checklist',
    decision: 'replaced_source',
    refreshedAt,
    sourceTitle: '자리톡 이사 준비 체크리스트 완벽 가이드',
    sourceUrl: 'https://refund-v0.zaritalk.com/moving_checklist',
    sourceType: 'creator_blog',
    sourceQuality: 'strong_creator',
    status: 'representative',
    userScore: 4.7,
    fitScore: 4.8,
    sourceSignal: 'D-100, D-60, D-30, D-14, D-7, D-1, D-Day 같은 기준일 단계가 바로 Flow 구조가 된다.',
    demandSignal: '이사는 날짜, 업체, 공과금, 주소변경, 전입신고가 얽혀 있어 캘린더화 가치가 높다.',
    conversionNote: '기존 AI 느낌을 줄이고, 단계가 분명한 실제 서비스형 콘텐츠로 대체한다.',
    uxAction: 'D-day 표기는 상세에 두고 캘린더에는 업체 예약, 공과금 정산 같은 행동 제목만 둔다.',
    flowItems: [
      { title: '이사업체 후보와 견적 정리하기', schedule: 'D-30', memo: '방문견적/비대면 견적, 포함 서비스, 추가비 조건을 비교한다.', completion: '후보 2~3곳과 예약 여부 정리' },
      { title: '인터넷·도시가스·공과금 이전 예약하기', schedule: 'D-14~D-7', memo: '설치일과 철거일이 이사일과 겹치지 않게 예약한다.', completion: '이전/정산 예약 완료' },
      { title: '전입신고와 주소변경 처리하기', schedule: 'D-Day~D+7', memo: '전입신고, 우편물 주소변경, 첫 고지서 확인을 묶어 체크한다.', completion: '전입/주소변경 처리 완료' },
    ],
    memo: '견적표와 업체 연락처는 표, 행정 링크는 메모에 둔다.',
    uxNote: 'FlowMe의 캘린더 UX 검증에 가장 적합한 대표 타임라인이다.',
    sourceBoundary: '임대차/전입 관련 공식 기한은 정부24/관할 기관 확인을 연결한다.',
    rubric: { userNeedFit: 5, executionClarity: 5, contentFidelity: 4, portability: 5, cognitiveLoad: 4, copySpecificity: 5, sourceSafety: 4, operability: 4 },
    simulation: {
      calendar: '이사업체 견적 받고 예약하기',
      detail: '견적 비교, 예약일, 업체 연락처',
      exportMemo: '원문 링크, 정부24/도시가스 확인 링크, 업체 후보표',
      failureSignal: 'D-30 텍스트가 캘린더 안에 크게 보이면 사용자가 행동을 못 읽는다.',
      verdict: '대표 P0로 승격해 UX12에 계속 둔다.',
    },
  },
  {
    candidateId: 'baby-food-four-week-menu',
    decision: 'officialized_source',
    refreshedAt,
    sourceTitle: '임신육아종합포털 어린이집 이유식 식단표',
    sourceUrl: 'https://info.childcare.go.kr/info_html5/pnis/search/PnisFileDownload.jsp?STCODE=41390000210&flag=DNLL&wkyymm=202601',
    sourceType: 'official',
    sourceQuality: 'clear_official',
    status: 'promote',
    userScore: 4.2,
    fitScore: 4.3,
    sourceSignal: '월령별 식단, 하루 제공 횟수, 사용 가능한 식품, 새 식품 추가 간격 같은 식단표 구조가 있다.',
    demandSignal: '사용자는 알레르기 기록 앱보다 일별 식단표를 캘린더/표로 옮기길 원한다.',
    conversionNote: '복잡한 반응 기록 Flow가 아니라 식단표 export 중심으로 재작성한다.',
    uxAction: '월령과 시작 주차를 고르면 식단표가 캘린더/표로 들어가게 한다.',
    flowItems: [
      { title: '이번 주 이유식 식단표 저장하기', schedule: '매주 시작일', memo: '월령에 맞는 식단표에서 이번 주 메뉴만 캘린더/표로 옮긴다.', completion: '이번 주 메뉴 저장 완료' },
      { title: '새 식품 추가 간격 확인하기', schedule: '새 재료 시작일', memo: '새 식품은 한 번에 여러 개 넣지 않고 간격을 두는 원문 주의사항을 확인한다.', completion: '새 재료 일정 확인' },
      { title: '소금·조미료 사용 여부 확인하기', schedule: '조리 전', memo: '식단표의 월령별 조미 원칙을 메모 상단에 둔다.', completion: '조리 전 주의 확인' },
    ],
    memo: '메뉴, 재료, 원문 식단표 링크만 남기고 건강 판단/증상 기록은 기본에서 뺀다.',
    uxNote: '유아 카테고리는 달력에 메뉴를 넣는 사용감 검증이 핵심이다.',
    sourceBoundary: '개별 아이의 발달/알레르기 판단은 보호자와 전문가 확인으로 분리한다.',
    rubric: { userNeedFit: 4, executionClarity: 4, contentFidelity: 5, portability: 5, cognitiveLoad: 4, copySpecificity: 4, sourceSafety: 5, operability: 4 },
    simulation: {
      calendar: '오늘 이유식 메뉴 확인',
      detail: '메뉴, 재료, 새 재료 여부, 원문 링크',
      exportMemo: '식단표 출처와 월령 주의사항',
      failureSignal: '피부/구토/설사 기록을 기본으로 띄우면 앱 목적이 의료 기록처럼 보인다.',
      verdict: '공식 식단표 기반이면 좋은 추가 검증 후보가 된다.',
    },
  },
  {
    candidateId: 'child-weekend-play-rotation',
    decision: 'officialized_source',
    refreshedAt,
    sourceTitle: 'i-누리 놀이이해자료 종이컵 놀이, 해 봐야 알아요!',
    sourceUrl: 'https://i-nuri.go.kr/board/boardFile/download/27/630/26158.do',
    sourceType: 'official',
    sourceQuality: 'clear_official',
    status: 'promote',
    userScore: 4.4,
    fitScore: 4.4,
    sourceSignal: '종이컵이라는 준비물 하나에서 쌓기, 자르기, 꾸미기 등 놀이 확장이 나온다.',
    demandSignal: '부모는 주말마다 새 놀이를 검색하기보다 준비물과 놀이 카드만 받고 싶어 한다.',
    conversionNote: '원문 링크 문제는 i-누리 공식 자료로 보강하고, 주말 놀이 카드 구조로 바꾼다.',
    uxAction: '캘린더에는 주말 놀이 1개, 상세에는 준비물과 놀이 변형 카드만 둔다.',
    flowItems: [
      { title: '이번 주 놀이 준비물 꺼내기', schedule: '토요일 오전', memo: '종이컵, 가위, 색연필처럼 집에 있는 준비물만 먼저 꺼낸다.', completion: '준비물 확인 완료' },
      { title: '아이 반응대로 놀이 하나 고르기', schedule: '놀이 시작', memo: '쌓기, 굴리기, 꾸미기 중 아이가 먼저 잡는 놀이를 선택한다.', completion: '오늘 놀이 선택' },
      { title: '다음 주 놀이 카드 바꾸기', schedule: '놀이 후', memo: '잘 먹힌 놀이와 싫어한 놀이만 짧게 메모한다.', completion: '다음 놀이 후보 저장' },
    ],
    memo: '교육 설명보다 준비물과 변형 놀이 링크가 중요하다.',
    uxNote: '아이 놀이 Flow는 콘텐츠 카드 교체 UX를 검증하기 좋다.',
    sourceBoundary: '발달 평가나 교육 효과 보장이 아니라 놀이 아이디어로만 제공한다.',
    rubric: { userNeedFit: 4, executionClarity: 4, contentFidelity: 4, portability: 4, cognitiveLoad: 4, copySpecificity: 4, sourceSafety: 5, operability: 4 },
    simulation: {
      calendar: '토요일 종이컵 놀이',
      detail: '준비물, 놀이 변형 3개, 다음 후보',
      exportMemo: 'i-누리 자료 링크',
      failureSignal: '자료 전체를 읽으라고 하면 Flow가 아니라 문서 링크가 된다.',
      verdict: '공식 자료 기반으로 보강되어 추가 검증 후보 유지.',
    },
  },
  {
    candidateId: 'homelearn-reading-challenge',
    decision: 'officialized_source',
    refreshedAt,
    sourceTitle: '홈런 독서챌린지 권장도서 리스트',
    sourceUrl: 'https://www.home-learn.co.kr/front/doc/%ED%99%88%EB%9F%B0%EB%8F%85%EC%84%9C%EC%B1%8C%EB%A6%B0%EC%A7%80_%EA%B6%8C%EC%9E%A5%EB%8F%84%EC%84%9C_%EB%A6%AC%EC%8A%A4%ED%8A%B8.pdf',
    sourceType: 'official',
    sourceQuality: 'clear_official',
    status: 'conditional',
    userScore: 3.9,
    fitScore: 4.0,
    sourceSignal: '권장도서 목록은 풍부하지만 원문 자체가 읽기 순서나 일정을 강하게 제시하지 않는다.',
    demandSignal: '부모가 책 목록을 고르고 주간 독서 루틴에 꽂아 쓰는 용도로는 가능하다.',
    conversionNote: '원문은 공식 도서 목록이라 신뢰도는 있지만 너무 넓다. 책 목록 전체를 Flow화하지 말고 4주 독서 루틴에 선택 도서만 붙인다.',
    uxAction: '첫 저장에서 책 4권만 고르게 하고 나머지는 더보기로 둔다.',
    flowItems: [
      { title: '이번 달 읽을 책 4권 고르기', schedule: '월초', memo: '권장도서 목록에서 아이 연령에 맞는 책 4권만 선택한다.', completion: '이번 달 책 4권 선택' },
      { title: '이번 주 책 읽고 한 질문 남기기', schedule: '주 1회', memo: '책을 읽은 뒤 아이가 기억한 장면이나 질문 하나만 메모한다.', completion: '읽기 완료와 질문 1개 기록' },
      { title: '다음 책으로 넘기기', schedule: '주말', memo: '이번 책이 너무 어렵거나 재미없으면 다음 책으로 바꾼다.', completion: '다음 책 확정' },
    ],
    memo: '도서 목록 URL과 선택한 책 제목만 둔다.',
    uxNote: '책 목록형 원문은 전체 변환보다 사용자 선택 UX가 중요하다.',
    sourceBoundary: '학습 효과나 독서 수준 판정으로 표현하지 않는다.',
    rubric: { userNeedFit: 4, executionClarity: 3, contentFidelity: 3, portability: 4, cognitiveLoad: 3, copySpecificity: 4, sourceSafety: 4, operability: 4 },
    simulation: {
      calendar: '이번 주 책 읽기',
      detail: '선택한 책, 질문 카드, 다음 책',
      exportMemo: '도서 목록 링크와 선택 책 4권',
      failureSignal: '권장도서 전체를 일정으로 만들면 압도감이 커진다.',
      verdict: '조건부 유지. 사용자 선택형으로만 좋다.',
    },
  },
  {
    candidateId: 'plank-30-day-challenge',
    decision: 'replaced_source',
    refreshedAt,
    sourceTitle: '플랭크 30일 챌린지 계획표 공유',
    sourceUrl: 'https://khj2510.tistory.com/entry/%ED%94%8C%EB%9E%AD%ED%81%AC-30%EC%9D%BC-%EC%B1%8C%EB%A6%B0%EC%A7%80-%EA%B3%84%ED%9A%8D%ED%91%9C-%EA%B3%B5%EC%9C%A0',
    sourceType: 'creator_blog',
    sourceQuality: 'strong_creator',
    status: 'conditional',
    userScore: 4.0,
    fitScore: 4.0,
    sourceSignal: 'Day 1~30 초 단위 계획표, 휴식일, 자세 체크포인트가 있어 30일 캘린더로 옮기기 쉽다.',
    demandSignal: '운동 챌린지는 시작일과 매일 알림만 있으면 사용자가 바로 실행할 수 있다.',
    conversionNote: '검색 URL 임시 후보를 정확한 일자별 표가 있는 원문으로 보강했다. 다만 운동 효과 표현은 Flow에서 제거한다.',
    uxAction: 'Day별 목표 초수와 휴식일만 캘린더에 넣고, 자세/주의 문구는 메모로 보낸다.',
    flowItems: [
      { title: '오늘 목표 초수 플랭크 하기', schedule: 'Day 1~30 매일', memo: '원문 표의 오늘 목표 초수와 체크포인트만 확인하고 무리하면 시간을 줄인다.', completion: '오늘 목표 초수 실행 또는 조정 표시' },
      { title: '통증 있으면 오늘 중단하기', schedule: '실행 중', memo: '허리 통증, 어지러움, 호흡 불편이 있으면 완료 대신 중단을 선택한다.', completion: '중단/완료 상태 선택' },
      { title: '휴식일에는 스트레칭만 하기', schedule: 'Day 7, 19, 27', memo: '원문 휴식일에는 플랭크를 강제로 완료시키지 않고 회복/스트레칭으로 표시한다.', completion: '휴식일 체크' },
    ],
    memo: 'Day별 초수표, 자세 체크포인트, 휴식일만 남기고 효과/식단 설명은 기본 UI에서 숨긴다.',
    uxNote: '운동 Flow는 매일 목표 1개와 휴식일 구분이면 충분하다. 컨디션 기록은 기본 입력에서 제외한다.',
    sourceBoundary: '운동 효과 보장 금지. 통증/어지러움/기존 질환 악화 시 중단 문구를 둔다.',
    rubric: { userNeedFit: 4, executionClarity: 4, contentFidelity: 3, portability: 4, cognitiveLoad: 4, copySpecificity: 4, sourceSafety: 4, operability: 4 },
    simulation: {
      calendar: '플랭크 Day 1 - 20초',
      detail: '오늘 초수, 자세 체크포인트, 완료/중단 선택',
      exportMemo: '30일 표 원문 링크와 통증 시 중단 조건',
      failureSignal: '효과 보장 문구나 식단 처방을 Flow 안에 넣으면 위험하고 복잡해진다.',
      verdict: '실제 표 기반으로 보강 완료. 대표보다는 조건부 운동 UX 검증 후보가 맞다.',
    },
  },
  {
    candidateId: 'korean-history-3-week',
    decision: 'replaced_source',
    refreshedAt,
    sourceTitle: '한국사능력검정 준비기간: 1~2급 3주 플랜',
    sourceUrl: 'https://hidell.tistory.com/2085',
    sourceType: 'creator_blog',
    sourceQuality: 'strong_creator',
    status: 'conditional',
    userScore: 3.9,
    fitScore: 3.9,
    sourceSignal: '0일차 실력 체크, 1~3주차 목표, Day 1~21 범위, 기출/오답 회독 흐름이 확인된다.',
    demandSignal: '시험일 기준 주차별 공부와 기출 회독을 캘린더/표로 옮기는 수요는 크다.',
    conversionNote: '검색 URL 임시 후보를 실제 3주 플랜 원문으로 교체했다. 합격 보장 문구는 Flow에서 제거한다.',
    uxAction: '시험일 기준으로 Day 0~21 일정을 생성하고, 기출/오답은 체크리스트가 아니라 상세 메모로 둔다.',
    flowItems: [
      { title: '최근 기출 1회분으로 실력 체크하기', schedule: 'Day 0', memo: '시간을 재지 않고 풀어 약한 시대와 틀린 이유를 메모한다.', completion: '약한 시대/오답 이유 기록' },
      { title: '선사~조선 전기 흐름 잡기', schedule: 'Day 1~7', memo: '원문 범위에 맞춰 선사, 삼국, 고려, 조선 전기를 훑고 주말에 기출 1회분을 푼다.', completion: '1주차 범위와 기출 1회 완료' },
      { title: '조선 후기~근현대 기출 회독하기', schedule: 'Day 8~14', memo: '근현대 비중을 높이고 최근 기출 3~5회차에서 해당 파트를 골라 푼다.', completion: '2주차 범위와 근현대 기출 완료' },
      { title: '실전 모의와 오답만 다시 보기', schedule: 'Day 15~21', memo: '실전 모의 2회와 오답노트, 약점 시대 30문제를 마무리한다.', completion: '모의/오답/약점 문제 완료' },
    ],
    memo: '원문 플랜, 공식 시험일, 기출 링크를 메모에 둔다. 합격 가능성 문구는 노출하지 않는다.',
    uxNote: '공부 Flow는 시험일 변경 시 Day 0~21 일정이 같이 이동해야 한다.',
    sourceBoundary: '합격 보장 금지. 개인 후기와 공식 시험 정보를 분리한다.',
    rubric: { userNeedFit: 4, executionClarity: 3, contentFidelity: 2, portability: 4, cognitiveLoad: 3, copySpecificity: 4, sourceSafety: 4, operability: 4 },
    simulation: {
      calendar: '한능검 Day 1 - 선사~삼국',
      detail: '오늘 범위, 기출 문제 수, 오답 메모',
      exportMemo: '3주 플랜 원문과 공식 시험/기출 링크',
      failureSignal: '“공부하기”만 반복되면 사용자가 뭘 해야 하는지 모른다.',
      verdict: '실제 플랜 기반으로 보강 완료. 시험일 이동 UX 검증 후보로 유지한다.',
    },
  },
  {
    candidateId: 'car-cabin-filter-replace',
    decision: 'officialized_source',
    refreshedAt,
    sourceTitle: '기아 렌터카 정비서비스 가이드',
    sourceUrl: 'https://rental.kia.com/m/customerService/carServiceGuide',
    sourceType: 'brand_support',
    sourceQuality: 'clear_official',
    status: 'conditional',
    userScore: 3.9,
    fitScore: 4.0,
    sourceSignal: '엔진오일, 항균필터, 와이퍼블레이드처럼 소모품별 교환 주기와 서비스 기준이 있다.',
    demandSignal: '차량 보유자는 주행거리와 기간이 섞인 소모품 알림을 놓치기 쉽다.',
    conversionNote: 'AI 느낌 셀프 교체 글 대신 브랜드 정비 기준으로 차량 소모품 루틴에 합친다.',
    uxAction: '단독 대표 후보가 아니라 차량 프로필의 항균필터 행으로 둔다.',
    flowItems: [
      { title: '항균필터 교체 주기 확인하기', schedule: '6~12개월 또는 계절 전', memo: '차량 모델과 서비스 기준에 맞춰 다음 교체일을 잡는다.', completion: '다음 교체일 저장' },
      { title: '호환 필터 구매 여부 확인하기', schedule: '교체 7일 전', memo: '차량 연식과 필터 방향을 확인하고 구매 링크를 메모한다.', completion: '구매/정비 예약 결정' },
      { title: '교체 후 냄새와 풍량 확인하기', schedule: '교체 직후', memo: '송풍을 켜고 냄새/풍량이 정상인지 확인한다.', completion: '교체 후 확인 완료' },
    ],
    memo: '차량명, 연식, 필터 모델, 정비소 예약 링크를 둔다.',
    uxNote: '차량 소모품은 개별 Flow보다 차량 프로필 표가 맞다.',
    sourceBoundary: '차량별 구조가 다르므로 무리한 분해는 정비소 기준을 우선한다.',
    rubric: { userNeedFit: 4, executionClarity: 4, contentFidelity: 3, portability: 4, cognitiveLoad: 3, copySpecificity: 4, sourceSafety: 4, operability: 4 },
    simulation: {
      calendar: '자동차 항균필터 교체 확인',
      detail: '교체 주기, 필터 모델, 구매/예약',
      exportMemo: '차량 모델과 브랜드 기준 링크',
      failureSignal: '셀프 분해 방법을 일반화하면 차량별 차이를 놓친다.',
      verdict: '보류에서 조건부로 올리되 차량 프로필 하위로 제한한다.',
    },
  },
  {
    candidateId: 'car-maintenance-schedule',
    decision: 'officialized_source',
    refreshedAt,
    sourceTitle: '기아 렌터카 정비서비스 가이드',
    sourceUrl: 'https://rental.kia.com/m/customerService/carServiceGuide',
    sourceType: 'brand_support',
    sourceQuality: 'clear_official',
    status: 'promote',
    userScore: 4.2,
    fitScore: 4.3,
    sourceSignal: '엔진오일, 항균필터, 와이퍼 등 소모품별 기간/거리 기준이 표 형태로 관리된다.',
    demandSignal: '소모품은 마지막 교체일과 주행거리를 함께 입력해야 다음 알림이 의미 있다.',
    conversionNote: '차량 소모품 Flow는 표가 먼저이고, 캘린더는 다음 교체 알림만 만든다.',
    uxAction: '기간만 입력받지 말고 현재 주행거리와 마지막 교체 km를 같이 받는다.',
    flowItems: [
      { title: '엔진오일 다음 교체 기준 계산하기', schedule: '마지막 교체 후 12개월 또는 거리 기준', memo: '마지막 교체일과 현재 주행거리를 함께 입력한다.', completion: '다음 교체 기준 저장' },
      { title: '와이퍼와 항균필터 계절 전 확인하기', schedule: '장마/여름 전', memo: '줄무늬, 소음, 냄새, 풍량 저하를 확인한다.', completion: '교체/유지 결정' },
      { title: '정비 예약 또는 구매 링크 저장하기', schedule: '교체 필요 시', memo: '정비소 예약 링크나 소모품 구매 링크를 메모한다.', completion: '예약 또는 구매 링크 저장' },
    ],
    memo: '소모품별 마지막 교체일, 교체 km, 다음 알림일이 핵심이다.',
    uxNote: '차량 관리 UX는 캘린더보다 표+다음 알림 구조가 맞다.',
    sourceBoundary: '정비 기준은 차종/연식/사용 조건에 따라 달라지므로 제조사 설명서와 정비소 확인을 우선한다.',
    rubric: { userNeedFit: 4, executionClarity: 4, contentFidelity: 4, portability: 5, cognitiveLoad: 4, copySpecificity: 4, sourceSafety: 4, operability: 4 },
    simulation: {
      calendar: '엔진오일 교체 확인',
      detail: '마지막 교체 km, 현재 km, 다음 기준',
      exportMemo: '소모품표와 정비소 링크',
      failureSignal: '기간 알림만 있으면 주행거리 많은 사용자를 놓친다.',
      verdict: '추가 검증 후보로 올릴 수 있다.',
    },
  },
  {
    candidateId: 'vehicle-inspection-prep',
    decision: 'officialized_source',
    refreshedAt,
    sourceTitle: 'TS한국교통안전공단 정기검사 대상·기준·유효기간 안내',
    sourceUrl: 'https://main.kotsa.or.kr/portal/contents.do?menuCode=01010200',
    sourceType: 'official',
    sourceQuality: 'clear_official',
    status: 'promote',
    userScore: 4.4,
    fitScore: 4.5,
    sourceSignal: '정기검사, 종합검사, 검사기간, 과태료 기준처럼 공식 일정과 상태가 명확하다.',
    demandSignal: '검사 기간을 놓치면 비용이 발생하므로 캘린더 알림 가치가 크다.',
    conversionNote: '넓은 블로그를 공식 검사 기간 확인 Flow로 축소하면 강해진다.',
    uxAction: '만료일을 넣으면 검사 가능 기간과 예약 체크를 만든다.',
    flowItems: [
      { title: '검사 유효기간 확인하기', schedule: '만료 90일 전', memo: 'TS 또는 자동차365에서 내 차량 검사 기간을 확인한다.', completion: '검사 가능 기간 저장' },
      { title: '검사소 예약하기', schedule: '만료 30일 전', memo: '예약 가능한 검사소, 시간, 수수료를 확인한다.', completion: '검사 예약 완료' },
      { title: '전구·타이어·와이퍼 사전 확인하기', schedule: '검사 7일 전', memo: '간단한 불합격 요인을 방문 전 확인한다.', completion: '사전 점검 완료' },
    ],
    memo: '차량번호, 검사 만료일, 예약 링크, 공식 안내 링크를 둔다.',
    uxNote: '행정/차량 Flow 중 캘린더 적합도가 높다.',
    sourceBoundary: '검사 기준과 과태료는 공식 공단 안내를 우선한다.',
    rubric: { userNeedFit: 5, executionClarity: 5, contentFidelity: 5, portability: 5, cognitiveLoad: 4, copySpecificity: 5, sourceSafety: 5, operability: 4 },
    simulation: {
      calendar: '자동차 검사 예약하기',
      detail: '검사 가능 기간, 예약 링크, 사전 점검',
      exportMemo: 'TS 공식 링크와 차량번호',
      failureSignal: '블로그식 긴 설명을 그대로 넣으면 공식 기한 확인이 묻힌다.',
      verdict: '공식 기반으로 대표 후보 후보군에 넣을 수 있다.',
    },
  },
  {
    candidateId: 'monthly-budget-close',
    decision: 'kept_with_hold',
    refreshedAt,
    sourceTitle: '토스뱅크 통장 쪼개기/목적별 관리 글',
    sourceUrl: 'https://www.tossbank.com/articles/split-save-account',
    sourceType: 'commerce',
    sourceQuality: 'clear_official',
    status: 'hold',
    userScore: 3.4,
    fitScore: 3.6,
    sourceSignal: '목적별 통장, 비상금, 여행비, 월세 같은 분리 관리 예시는 있지만 금융상품 소개 성격이 강하다.',
    demandSignal: '월말 결산 루틴 자체는 가능하지만 FlowMe 대표 컨텐츠로는 금융 민감도와 상품 유도성이 부담이다.',
    conversionNote: '실제 원문으로 바꿔도 금융상품 맥락이 강해 보류가 맞다.',
    uxAction: '재무 조언 없이 개인 체크표/엑셀 export로만 제한한다.',
    flowItems: [
      { title: '이번 달 고정비 합계 확인하기', schedule: '월말', memo: '월세, 통신, 보험, 구독 금액만 분류한다.', completion: '고정비 합계 입력' },
      { title: '목적별 통장 잔액 확인하기', schedule: '월말', memo: '생활비, 비상금, 여행비 같은 이름만 확인한다. 상품 추천은 하지 않는다.', completion: '잔액 확인 완료' },
      { title: '다음 달 자동이체 금액 확인하기', schedule: '월급일 전', memo: '금액과 이체일만 저장한다.', completion: '자동이체 확인' },
    ],
    memo: '상품명/금리/추천 문구는 기본 메모에서 제외한다.',
    uxNote: '돈 관리 Flow는 민감해서 P0 UX 검증용으로 부적합하다.',
    sourceBoundary: '금융상품 추천, 수익 보장, 저축 강요처럼 보이지 않게 제한한다.',
    rubric: { userNeedFit: 3, executionClarity: 4, contentFidelity: 3, portability: 4, cognitiveLoad: 3, copySpecificity: 4, sourceSafety: 4, operability: 4 },
    simulation: {
      calendar: '월말 지출 합계 확인',
      detail: '고정비, 변동비, 자동이체 금액',
      exportMemo: '상품 추천 없이 개인 결산표만',
      failureSignal: '특정 금융상품 CTA가 Flow CTA처럼 보이면 플랫폼 신뢰가 떨어진다.',
      verdict: '실제 원문 확인 후에도 보류 유지.',
    },
  },
  {
    candidateId: 'emergency-fund-account',
    decision: 'kept_with_hold',
    refreshedAt,
    sourceTitle: '토스뱅크 통장 쪼개기/목적별 관리 글',
    sourceUrl: 'https://www.tossbank.com/articles/split-save-account',
    sourceType: 'commerce',
    sourceQuality: 'clear_official',
    status: 'hold',
    userScore: 3.3,
    fitScore: 3.5,
    sourceSignal: '비상금, 여행비, 경조사비처럼 목적별 계좌 예시는 있으나 상품 설명 성격이 크다.',
    demandSignal: '월급일 자동이체 확인 루틴은 가능하지만 금융 추천처럼 오해될 수 있다.',
    conversionNote: '실제 컨텐츠 확인 후에도 FlowMe 대표 컨텐츠보다는 보류가 맞다.',
    uxAction: '금액 목표만 입력받고 상품/금리/은행명 선택은 노출하지 않는다.',
    flowItems: [
      { title: '월급일 비상금 이체 여부 확인하기', schedule: '월급일', memo: '정해둔 금액이 옮겨졌는지만 확인한다.', completion: '이체 완료/건너뜀 선택' },
      { title: '비상금 사용 여부 적기', schedule: '월말', memo: '사용이 있었다면 금액과 이유만 적는다.', completion: '사용/미사용 기록' },
      { title: '목표 금액까지 남은 금액 보기', schedule: '월말', memo: '현재 잔액과 목표 금액 차이만 계산한다.', completion: '남은 금액 확인' },
    ],
    memo: '은행/상품/금리 설명은 Flow에서 제외한다.',
    uxNote: '사용자 입력 복잡도가 높고 금융 민감도 때문에 당장 UX 검증용으로는 낮다.',
    sourceBoundary: '저축 상품 추천이나 재무 조언을 하지 않는다.',
    rubric: { userNeedFit: 3, executionClarity: 4, contentFidelity: 3, portability: 3, cognitiveLoad: 3, copySpecificity: 4, sourceSafety: 4, operability: 4 },
    simulation: {
      calendar: '비상금 이체 확인',
      detail: '이체 여부, 사용 여부, 남은 금액',
      exportMemo: '금융 조언 없는 개인 목표 메모',
      failureSignal: '금액 입력이 많아지면 캘린더/리마인더보다 무거워진다.',
      verdict: '보류 유지.',
    },
  },
  {
    candidateId: 'passport-issue-prep',
    decision: 'officialized_source',
    refreshedAt,
    sourceTitle: '외교부 여권안내 사진 규격 및 접수기관 안내',
    sourceUrl: 'https://www.passport.go.kr/',
    sourceType: 'official',
    sourceQuality: 'clear_official',
    status: 'promote',
    userScore: 4.3,
    fitScore: 4.4,
    sourceSignal: '사진 규격, 접수기관, 방문 전 확인 같은 공식 체크 항목이 있다.',
    demandSignal: '여권 발급은 사진/신분증/방문기관을 놓치면 재방문 비용이 생긴다.',
    conversionNote: 'AI 느낌 블로그 대신 공식 여권 안내 링크 기준으로 다시 만든다.',
    uxAction: '방문 예정일 전날 체크리스트와 공식 링크 확인만 둔다.',
    flowItems: [
      { title: '여권사진 규격 확인하기', schedule: '방문 7일 전', memo: '사진 촬영일, 크기, 얼굴 방향 등 공식 사진 규격을 확인한다.', completion: '사진 준비 완료' },
      { title: '신분증과 신청서류 챙기기', schedule: '방문 전날', memo: '신청자 유형에 맞는 서류를 공식 안내에서 확인한다.', completion: '서류 체크 완료' },
      { title: '접수기관 업무시간 확인하기', schedule: '방문 전날', memo: '접수처 주소와 업무시간은 변경될 수 있어 방문 전 확인한다.', completion: '방문기관 확인 완료' },
    ],
    memo: '공식 여권안내 URL과 접수기관 전화번호를 메모 상단에 둔다.',
    uxNote: '행정 Flow는 공식 링크와 준비물 체크만 있으면 충분하다.',
    sourceBoundary: '최신 규정은 외교부 여권안내와 접수기관 확인을 우선한다.',
    rubric: { userNeedFit: 4, executionClarity: 5, contentFidelity: 5, portability: 4, cognitiveLoad: 4, copySpecificity: 5, sourceSafety: 5, operability: 4 },
    simulation: {
      calendar: '여권 신청 서류 챙기기',
      detail: '사진, 신분증, 접수기관 확인',
      exportMemo: '외교부 링크와 방문기관',
      failureSignal: '블로그 요약만 믿게 만들면 최신 규정 리스크가 생긴다.',
      verdict: '공식 기반으로 추가 검증 후보가 된다.',
    },
  },
  {
    candidateId: 'travel-d7-checklist',
    decision: 'replaced_source',
    refreshedAt,
    sourceTitle: 'TripOnMap 출발 7일 전 체크리스트',
    sourceUrl: 'https://triponmap.tistory.com/3',
    sourceType: 'creator_blog',
    sourceQuality: 'strong_creator',
    status: 'representative',
    userScore: 4.6,
    fitScore: 4.6,
    sourceSignal: 'D-7, D-3, D-1/당일로 여권, 비자, eSIM, 환전, 입국서류 확인이 나뉜다.',
    demandSignal: '출국 직전 준비는 날짜와 실패 비용이 뚜렷해 캘린더/체크리스트 전환 가치가 높다.',
    conversionNote: 'AI 느낌이 있던 기존 출처 대신 실행 순서가 분명하고 공식 확인 경계를 적은 원문으로 교체한다.',
    uxAction: '출국일 기준으로 D-7/D-3/D-1 일정을 만들고, 입국 규정은 공식 확인 링크로 분리한다.',
    flowItems: [
      { title: '여권·비자·입국요건 확인하기', schedule: 'D-7', memo: '여권 유효기간, 비자/전자허가, 항공권 영문 이름을 확인하고 공식 채널 링크를 열어 본다.', completion: '출국 서류 확인 완료' },
      { title: 'eSIM·환전·카드 준비하기', schedule: 'D-3', memo: 'eSIM 설치 가능 시점, 해외결제 카드, 소액 현금 준비 여부를 확인한다.', completion: '통신/결제 준비 완료' },
      { title: '실물 여권과 입국서류 고정하기', schedule: 'D-1', memo: '여권, 왕복권, 숙소 주소, 보험 증서를 한 곳에 넣고 캡처본을 저장한다.', completion: '출국 전 최종 체크 완료' },
    ],
    memo: '국가별 입국 규정, 외교부 해외안전여행, 항공사 수하물 링크를 메모 상단에 둔다.',
    uxNote: '여행 Flow는 체크리스트보다 기준일 타임라인이 먼저이고, 공식 확인은 고정 메모가 맞다.',
    sourceBoundary: '입국 규정과 여행경보는 블로그가 아니라 외교부, 대사관, 항공사 공식 채널을 우선한다.',
    rubric: { userNeedFit: 5, executionClarity: 5, contentFidelity: 4, portability: 5, cognitiveLoad: 4, copySpecificity: 5, sourceSafety: 5, operability: 4 },
    simulation: {
      calendar: '여권·비자·입국요건 확인',
      detail: '여권, 비자/ETA, 항공권 이름, 공식 링크 확인',
      exportMemo: '외교부/대사관/항공사 공식 링크와 원문 체크리스트',
      failureSignal: '국가별 입국 규정을 블로그 내용으로 확정하면 위험하다.',
      verdict: '실제 원문 기준으로 대표 P0 유지 가능.',
    },
  },
  {
    candidateId: 'regular-aircon-clean-home',
    decision: 'officialized_source',
    refreshedAt,
    sourceTitle: '삼성전자서비스 벽걸이 에어컨 필터 청소 표시 안내',
    sourceUrl: 'https://www.samsungsvc.co.kr/solution/40665',
    sourceType: 'brand_support',
    sourceQuality: 'clear_official',
    status: 'promote',
    userScore: 4.3,
    fitScore: 4.4,
    sourceSignal: '먼지거름필터 세척, 그늘 건조, 필터 리셋, 모델별 주의가 실행 단위로 나뉜다.',
    demandSignal: '여름 전후로 반복되는 대중적 관리 과제이고 캘린더 알림 가치가 높다.',
    conversionNote: 'AI 느낌 셀프 청소 글 대신 브랜드 공식 필터 청소 기준으로 바꾼다.',
    uxAction: '셀프 분해가 아니라 필터 분리/세척/건조/리셋만 기본 체크로 둔다.',
    flowItems: [
      { title: '먼지거름필터 분리하고 세척하기', schedule: '2주~3개월, 사용량 기준', memo: '먼지가 많으면 미지근한 물과 중성세제로 세척한다.', completion: '필터 세척 완료' },
      { title: '그늘에서 완전히 말리기', schedule: '세척 직후', memo: '강한 햇빛 건조나 무리한 물청소는 피한다.', completion: '필터 완전 건조' },
      { title: '필터 리셋 처리하기', schedule: '재장착 후', memo: '제품별 필터청소 알림 해제 방법을 확인한다.', completion: '필터 리셋 완료' },
    ],
    memo: '모델별 리셋 방법과 출장 세척 판단 기준은 메모에 둔다.',
    uxNote: '에어컨 Flow는 대표적인 보유 제품 반복 관리 후보로 좋다.',
    sourceBoundary: '열교환기 분해 세척은 전문가/제조사 기준을 우선한다.',
    rubric: { userNeedFit: 4, executionClarity: 5, contentFidelity: 5, portability: 4, cognitiveLoad: 4, copySpecificity: 5, sourceSafety: 5, operability: 4 },
    simulation: {
      calendar: '벽걸이 에어컨 필터 청소',
      detail: '필터 세척, 그늘 건조, 필터 리셋',
      exportMemo: '모델명, 공식 링크, 리셋 방법',
      failureSignal: '냉각핀 분해 청소까지 기본 체크에 넣으면 위험하고 무겁다.',
      verdict: '공식 기준으로 대표 후보군에 가까운 추가 검증 후보.',
    },
  },
];

export const koreanFlowContentSourceRefreshById = new Map(
  koreanFlowContentSourceRefreshes.map((refresh) => [refresh.candidateId, refresh]),
);

export function applyKoreanFlowContentSourceRefresh(candidate: KoreanFlowContentCandidate): KoreanFlowContentCandidate {
  const refresh = koreanFlowContentSourceRefreshById.get(candidate.id);
  if (!refresh) return candidate;

  return {
    ...candidate,
    fitScore: refresh.fitScore,
    sourceTitle: refresh.sourceTitle,
    sourceUrl: refresh.sourceUrl,
    sourceType: refresh.sourceType,
    demandSignal: refresh.demandSignal,
    sourceSignal: refresh.sourceSignal,
    flowItems: refresh.flowItems,
    memo: refresh.memo,
    uxNote: refresh.uxNote,
    sourceBoundary: refresh.sourceBoundary,
  };
}

export function applyKoreanFlowContentReviewRefresh(review: KoreanFlowContentUserReview): KoreanFlowContentUserReview {
  const refresh = koreanFlowContentSourceRefreshById.get(review.candidateId);
  if (!refresh) return review;

  return {
    ...review,
    userScore: refresh.userScore,
    status: refresh.status,
    sourceQuality: refresh.sourceQuality,
    sourceIssue: undefined,
    conversionNote: refresh.conversionNote,
    uxAction: refresh.uxAction,
  };
}
