export type FlowContentDestination = 'calendar' | 'routine' | 'checklist' | 'sheet' | 'hybrid';

export type KoreanFlowContentCandidate = {
  id: string;
  title: string;
  category: string;
  fitScore: number;
  sourceTitle: string;
  sourceUrl: string;
  sourceType: 'creator_blog' | 'creator_video' | 'official' | 'brand_support' | 'community' | 'commerce';
  demandSignal: string;
  sourceSignal: string;
  userNeed: string;
  destination: FlowContentDestination;
  structure: 'single_routine' | 'rotating_routine' | 'timeline' | 'checklist' | 'table_plan' | 'challenge';
  cta: string;
  inputs: string[];
  flowItems: Array<{
    title: string;
    schedule: string;
    memo: string;
    completion: string;
  }>;
  memo: string;
  uxNote: string;
  sourceBoundary: string;
};

export const koreanFlowContentCandidates: KoreanFlowContentCandidate[] = [
  {
    id: 'washer-tub-clean-monthly',
    title: '세탁기 통세척 월간 관리',
    category: '가전 관리',
    fitScore: 4.7,
    sourceTitle: '세탁기 통세척 방법 총정리',
    sourceUrl: 'https://raga-t.com/entry/%EC%84%B8%ED%83%81%EA%B8%B0-%ED%86%B5%EC%84%B8%EC%B2%99-%EB%B0%A9%EB%B2%95-%EC%99%84%EB%B2%BD-%EA%B0%80%EC%9D%B4%EB%93%9C',
    sourceType: 'creator_blog',
    demandSignal: '냄새, 곰팡이, 배수필터처럼 반복 검색되는 생활 문제다.',
    sourceSignal: '월 1회 통세척, 고무패킹, 세제통, 배수필터처럼 실행 단위가 분리되고 냄새가 반복되면 2주 간격으로 줄일 수 있다.',
    userNeed: '세탁 후 냄새가 나기 전에 월 1회 짧은 관리 루틴으로 세탁기를 유지한다.',
    destination: 'routine',
    structure: 'single_routine',
    cta: '월간 루틴으로 저장',
    inputs: ['첫 청소 날짜', '세탁기 종류', '반복 주기'],
    flowItems: [
      { title: '세탁조 통세척 코스 돌리기', schedule: '매월 1회', memo: '세탁조 클리너 또는 모델에 맞는 세척제를 준비하고 통세척/표준 고온 코스를 실행한다.', completion: '통세척 코스를 끝내고 문을 열어 내부 건조 상태로 둠' },
      { title: '고무패킹 물기와 찌꺼기 닦기', schedule: '통세척 직후', memo: '문 주변 고무패킹 안쪽을 마른 수건으로 닦고 이물질을 확인한다.', completion: '패킹 안쪽 물기와 찌꺼기 제거' },
      { title: '세제통과 배수필터 확인', schedule: '매월 1회', memo: '세제통은 분리 세척하고 배수필터는 물받이를 준비한 뒤 이물질을 제거한다.', completion: '세제통/필터를 제자리에 장착' },
    ],
    memo: '세탁기 모델, 세척 방법, 준비물, 원문 영상/사진 링크, 클리너 구매 링크는 입력 폼이 아니라 상세 메모에 둔다. 사진 증빙은 기본값으로 두지 않는다.',
    uxNote: '저장할 때 시작일과 반복 주기만 받는다. 상세에는 3개 체크만 보여주고 원문 링크를 메모 아래에 둔다.',
    sourceBoundary: '세제 사용량과 분해 청소는 모델 설명서 우선으로 표시한다.',
  },
  {
    id: 'lg-aircon-filter-biweekly',
    title: '에어컨 필터 2주 청소',
    category: '가전 관리',
    fitScore: 4.6,
    sourceTitle: 'LG전자 스탠드형 에어컨 필터 청소 및 교체',
    sourceUrl: 'https://www.lge.co.kr/support/solutions-20150160251795?cstFlag=Y&mktModelCd=FQ237SAU&svcqr=',
    sourceType: 'brand_support',
    demandSignal: 'LG 지원 문서가 조회수 높은 고객 문제를 직접 다룬다.',
    sourceSignal: '세척 2주 1회, 교체 6개월 또는 12개월 기준이 명확하다.',
    userNeed: '여름철 에어컨 성능과 냄새 문제를 줄이기 위해 필터 청소와 교체를 놓치지 않는다.',
    destination: 'routine',
    structure: 'single_routine',
    cta: '2주 루틴으로 저장',
    inputs: ['첫 청소 날짜', '에어컨 타입', '교체 필터 보유 여부'],
    flowItems: [
      { title: '극세 필터 물세척', schedule: '2주마다', memo: '전원 차단 후 필터를 분리해 흐르는 물로 세척하고 그늘에서 완전히 말린다.', completion: '필터가 마른 뒤 다시 장착' },
      { title: '교체 필터 상태 확인', schedule: '6개월마다', memo: '초미세/탈취 필터처럼 세척 불가 필터는 모델 기준 교체 주기를 확인한다.', completion: '교체 필요 여부 결정' },
      { title: '송풍 운전으로 내부 말리기', schedule: '청소 후', memo: '필터 장착 후 짧게 송풍 운전해 습기를 줄인다.', completion: '송풍 완료' },
    ],
    memo: '모델별 필터 이름과 교체 필터 구매 링크를 메모에 저장하면 좋다.',
    uxNote: '가전 QR에서 들어오면 모델명이 자동으로 채워지는 UX가 가장 자연스럽다.',
    sourceBoundary: '브랜드 문서 기준이며 타사 제품은 해당 제조사 설명서 확인이 필요하다.',
  },
  {
    id: 'air-purifier-filter-seasonal',
    title: '공기청정기 필터 계절 관리',
    category: '가전 관리',
    fitScore: 4.5,
    sourceTitle: '공기청정기 필터 교체 주기',
    sourceUrl: 'https://tech-goreum.tistory.com/41',
    sourceType: 'creator_blog',
    demandSignal: '필터 교체 비용과 브랜드별 주기는 구매 후 계속 반복되는 관심사다.',
    sourceSignal: '브랜드별 필터 교체 주기, 프리필터 청소, 비용 비교가 있다.',
    userNeed: '미세먼지 계절 전후로 프리필터 청소와 본필터 교체 시점을 관리한다.',
    destination: 'routine',
    structure: 'single_routine',
    cta: '계절 루틴으로 저장',
    inputs: ['제품명', '필터 마지막 교체일', '반복 주기'],
    flowItems: [
      { title: '프리필터 먼지 제거', schedule: '매월 또는 미세먼지 많은 달', memo: '분리 가능한 프리필터의 먼지를 제거하고 완전히 말린다.', completion: '프리필터 장착 완료' },
      { title: '본필터 교체 필요 확인', schedule: '6~12개월마다', memo: '사용 시간, 냄새, 표시등, 제조사 권장 주기를 함께 확인한다.', completion: '교체/유지 결정' },
      { title: '필터 구매 링크 업데이트', schedule: '교체 결정 시', memo: '호환 필터명과 구매 링크를 메모에 보관한다.', completion: '다음 교체일 저장' },
    ],
    memo: '필터명, 마지막 교체일, 구매 링크가 핵심 메모다.',
    uxNote: '첫 저장 화면은 제품명과 마지막 교체일만 받는 것이 좋다.',
    sourceBoundary: '교체 주기는 제품과 사용 환경에 따라 다르므로 제조사 표시등을 우선한다.',
  },
  {
    id: 'robot-vacuum-monthly-care',
    title: '로봇청소기 브러시·센서 월간 관리',
    category: '가전 관리',
    fitScore: 4.2,
    sourceTitle: '로봇청소기 관리 총정리',
    sourceUrl: 'https://solidtips.tistory.com/entry/robot-vacuum-maintenance-brush-sensor-dustbin-watertank',
    sourceType: 'creator_blog',
    demandSignal: '사용자가 구매 후 흡입력 저하와 오수통 냄새를 반복적으로 겪는다.',
    sourceSignal: '주간/월간 관리 루틴과 브러시, 센서, 먼지통, 오수통 관리가 분리되어 있다.',
    userNeed: '청소기가 알아서 도는 만큼 사용자가 놓치기 쉬운 소모품 관리를 캘린더에 남긴다.',
    destination: 'routine',
    structure: 'single_routine',
    cta: '월간 관리 루틴 저장',
    inputs: ['제품명', '첫 관리일', '물걸레/오수통 사용 여부'],
    flowItems: [
      { title: '메인 브러시 머리카락 제거', schedule: '매주', memo: '브러시를 분리해 머리카락과 먼지를 제거한다.', completion: '브러시가 막히지 않음' },
      { title: '센서와 충전 접점 닦기', schedule: '매월', memo: '마른 천으로 센서와 충전 접점을 닦는다.', completion: '센서/접점 닦기 완료' },
      { title: '먼지통·오수통 세척', schedule: '매월 또는 냄새 날 때', memo: '물세척 가능 여부를 확인하고 완전 건조 후 장착한다.', completion: '냄새/물기 없이 장착' },
    ],
    memo: '소모품 구매 링크와 모델별 분해 영상 링크가 유용하다.',
    uxNote: '제품 관리 Flow는 “보유 제품” 목록과 연결되면 반복 사용 가치가 높다.',
    sourceBoundary: '물세척 가능 여부는 제품 설명서 우선이다.',
  },
  {
    id: 'humidifier-daily-weekly-clean',
    title: '가습기 매일 비우고 주간 세척',
    category: '가전 관리',
    fitScore: 4.1,
    sourceTitle: '가습기 청소 주기 및 부위별 세척 방법',
    sourceUrl: 'https://particleseoul.tistory.com/1548',
    sourceType: 'creator_blog',
    demandSignal: '겨울철 반복 사용 제품이고 위생 관리 실패 비용이 크다.',
    sourceSignal: '물통/물받이 매일, 노즐/분무기 주 1회처럼 주기가 나뉜다.',
    userNeed: '매일 물을 비우고 주 1회 세척을 반복해 가습기 냄새와 물때를 줄인다.',
    destination: 'routine',
    structure: 'single_routine',
    cta: '겨울 루틴으로 저장',
    inputs: ['사용 시작일', '가습기 방식', '사용 계절'],
    flowItems: [
      { title: '물통 비우고 새 물 넣기', schedule: '사용일 매일', memo: '남은 물은 버리고 물통을 헹군 뒤 새 물을 채운다.', completion: '묵은 물 없음' },
      { title: '물받이와 노즐 세척', schedule: '매주 1회', memo: '제품 설명서에 맞는 세척 방식으로 물때를 제거한다.', completion: '세척 후 완전 건조' },
      { title: '필터 상태 확인', schedule: '매월', memo: '필터형 제품은 변색, 냄새, 권장 교체 주기를 확인한다.', completion: '유지/교체 결정' },
    ],
    memo: '식초/구연산 사용 여부는 제품 설명서 우선으로 메모에 둔다.',
    uxNote: '가습기 Flow는 매일 체크와 주간 체크가 한 카드에 같이 보이는 UI가 필요하다.',
    sourceBoundary: '건강 효과를 보장하지 않고 위생 관리 루틴으로만 제시한다.',
  },
  {
    id: 'water-purifier-filter-cycle',
    title: '정수기 필터 교체 주기 관리',
    category: '가전 관리',
    fitScore: 4.4,
    sourceTitle: '정수기 필터 교체 방법과 교체 주기',
    sourceUrl: 'https://pihamadam.tistory.com/267',
    sourceType: 'creator_blog',
    demandSignal: 'DIY 교체, 렌탈 관리, 필터 구매가 연결되는 반복 생활 과제다.',
    sourceSignal: '침전, 프리카본, 나노/RO, 후카본처럼 필터별 교체 주기가 나뉘고 후카본은 9~12개월 주기로 따로 본다.',
    userNeed: '필터별 마지막 교체일을 저장하고 다음 교체일을 놓치지 않는다.',
    destination: 'sheet',
    structure: 'table_plan',
    cta: '필터표로 저장',
    inputs: ['정수기 모델', '필터 구성', '마지막 교체일'],
    flowItems: [
      { title: '세디먼트 필터 교체 확인', schedule: '3~6개월', memo: '모래, 녹물 등 큰 입자를 거르는 첫 단계 필터로 모델 기준 주기를 확인한다.', completion: '교체일 또는 유지 결정 기록' },
      { title: '프리카본 필터 확인', schedule: '6~12개월', memo: '염소, 화학물질, 냄새 제거 필터의 마지막 교체일과 다음 확인일을 적는다.', completion: '다음 확인일 저장' },
      { title: 'RO/나노 필터 확인', schedule: '12~24개월', memo: '핵심 필터는 제조사 안내와 렌탈사 기준을 우선한다.', completion: '교체 예약 또는 구매 링크 저장' },
      { title: '후카본 필터 확인', schedule: '9~12개월', memo: '정수 마지막 단계의 물맛·냄새 개선 필터를 프리카본과 분리해 기록한다.', completion: '후카본 다음 확인일 저장' },
    ],
    memo: '필터 구매 링크, 렌탈사 연락처, 모델명을 메모에 둔다.',
    uxNote: '캘린더보다 표가 먼저이고, 각 필터 행에서 다음 알림을 만든다.',
    sourceBoundary: '정수 성능 판단은 제조사/렌탈사 점검 기준을 우선한다.',
  },
  {
    id: 'monstera-care-routine',
    title: '몬스테라 물주기·분갈이 루틴',
    category: '식물 관리',
    fitScore: 4.6,
    sourceTitle: '스투키/몬스테라 식물 관리 가이드 검색 결과 기반',
    sourceUrl: 'https://jhbd2.tistory.com/178',
    sourceType: 'creator_blog',
    demandSignal: '초보 식집사가 자주 검색하는 대표 반려식물 관리 주제다.',
    sourceSignal: '물주기, 햇빛, 과습 신호, 분갈이 조건이 실행 체크로 분리된다.',
    userNeed: '식물 이름을 저장하고 물주기와 잎/흙 관찰을 반복한다.',
    destination: 'routine',
    structure: 'rotating_routine',
    cta: '식물 루틴으로 저장',
    inputs: ['식물명', '화분 위치', '마지막 물준 날'],
    flowItems: [
      { title: '겉흙 마름 확인 후 물주기', schedule: '7~10일마다 확인', memo: '흙 2~3cm 안쪽 상태와 화분 무게를 확인한 뒤 물을 준다.', completion: '물주기 또는 보류 결정' },
      { title: '잎 색과 새잎 상태 보기', schedule: '2주마다', memo: '잎끝 마름, 갈색 반점, 새잎 성장을 확인한다.', completion: '이상 없음/위치 조정 메모' },
      { title: '분갈이 필요 확인', schedule: '6개월마다', memo: '뿌리 과밀, 배수, 화분 크기를 확인한다.', completion: '분갈이 필요 여부 결정' },
    ],
    memo: '사진 기록은 선택 사항이다. 기본은 물주기/보류 체크만 둔다.',
    uxNote: '식물명 선택에 따라 주기와 체크 항목이 바뀌는 템플릿 UX가 필요하다.',
    sourceBoundary: '실내 환경에 따라 주기는 달라지므로 “확인 알림”으로 표현한다.',
  },
  {
    id: 'stuckyi-overwater-prevention',
    title: '스투키 과습 방지 관리',
    category: '식물 관리',
    fitScore: 4.5,
    sourceTitle: '스투키 물주기 걱정 뚝',
    sourceUrl: 'https://botanical.house/stuckyi/',
    sourceType: 'creator_blog',
    demandSignal: '스투키는 초보 식물로 많이 구매하지만 과습 실패가 흔하다.',
    sourceSignal: '물주기 보류, 적응 기간, 과습 신호가 명확한 판단 지점이다.',
    userNeed: '물을 자주 주는 실수를 줄이고, 물주기 전 확인을 습관화한다.',
    destination: 'routine',
    structure: 'single_routine',
    cta: '과습 방지 루틴 저장',
    inputs: ['마지막 물준 날', '빛 환경', '분갈이 여부'],
    flowItems: [
      { title: '흙 완전 건조 확인', schedule: '2~3주마다 확인', memo: '마르지 않았으면 오늘 물주기를 보류한다.', completion: '물주기/보류 선택' },
      { title: '밑동 무름 확인', schedule: '월 1회', memo: '밑동 노랗게 변함, 물러짐이 있으면 물주기를 멈추고 통풍을 확보한다.', completion: '이상 없음/관리 메모' },
      { title: '분갈이 후 적응 관리', schedule: '분갈이 후 2주', memo: '분갈이 직후 과습을 피하고 빛 적응 기간을 둔다.', completion: '적응 기간 종료' },
    ],
    memo: '스투키는 “물주기 알림”보다 “물주기 확인 알림”이 더 맞다.',
    uxNote: '완료 버튼 옆에 “오늘은 보류” 상태가 있어야 자연스럽다.',
    sourceBoundary: '식물 상태가 나쁘면 원문 참고 후 전문가/판매처 상담을 권한다.',
  },
  {
    id: 'cat-litter-box-clean',
    title: '고양이 화장실 청소 루틴',
    category: '반려동물',
    fitScore: 4.1,
    sourceTitle: '고양이 화장실 청소, 하루 몇 번?',
    sourceUrl: 'https://i.dooboomama.com/%EA%B3%A0%EC%96%91%EC%9D%B4-%ED%99%94%EC%9E%A5%EC%8B%A4-%EC%B2%AD%EC%86%8C-%ED%95%98%EB%A3%A8-%EB%AA%87-%EB%B2%88-%EB%AA%A8%EB%9E%98-%EA%B0%88%EC%95%84%EC%A3%BC%EB%8A%94-%EC%B5%9C%EC%A0%81-%ED%83%80/',
    sourceType: 'creator_blog',
    demandSignal: '반려묘 가정에서 매일 반복되는 실제 집안일이다.',
    sourceSignal: '일일 배변 제거와 모래 전체 교체 시점이 분리된다.',
    userNeed: '화장실 청소를 매일 체크하고 전체 모래 교체를 놓치지 않는다.',
    destination: 'routine',
    structure: 'single_routine',
    cta: '반려묘 루틴 저장',
    inputs: ['고양이 수', '화장실 수', '모래 종류'],
    flowItems: [
      { title: '배변 덩어리 제거', schedule: '매일', memo: '모래삽으로 배변 덩어리와 오염된 모래를 제거한다.', completion: '배변 제거 완료' },
      { title: '모래량 보충', schedule: '주 1회 확인', memo: '모래 높이와 냄새를 확인하고 부족하면 보충한다.', completion: '보충/유지 결정' },
      { title: '화장실 세척과 전체 교체', schedule: '모래 종류별 주기', memo: '전체 모래를 버리고 화장실을 세척 후 건조한다.', completion: '전체 교체 완료' },
    ],
    memo: '모래 브랜드, 교체 주기, 구매 링크를 메모에 둔다.',
    uxNote: '반려동물 Flow는 가족 공유 체크가 있으면 가치가 높다.',
    sourceBoundary: '배변 이상은 건강 문제일 수 있으므로 진단처럼 표현하지 않는다.',
  },
  {
    id: 'puppy-vaccination-schedule',
    title: '강아지 예방접종 일정표',
    category: '반려동물',
    fitScore: 4.2,
    sourceTitle: '2026 강아지 예방접종 총정리',
    sourceUrl: 'https://hipaw.co.kr/puppy-vaccination-time-type-cycle/',
    sourceType: 'creator_blog',
    demandSignal: '입양 직후 보호자가 가장 많이 놓치는 일정형 과제다.',
    sourceSignal: '주령별 접종, 연 1회 접종, 병원 확인이라는 일정 구조가 있다.',
    userNeed: '입양일/생일 기준으로 접종 예정일을 캘린더에 저장한다.',
    destination: 'hybrid',
    structure: 'timeline',
    cta: '접종 일정으로 저장',
    inputs: ['강아지 생일 또는 입양일', '이전 접종 기록', '동물병원'],
    flowItems: [
      { title: '이전 접종 기록 확인', schedule: '입양 직후', memo: '분양/입양 서류와 접종 수첩을 확인해 병원에 보여준다.', completion: '기록 확인 또는 없음 표시' },
      { title: '다음 접종 예약', schedule: '병원 안내 기준', memo: '컨디션에 따라 수의사와 일정을 조정한다.', completion: '예약일 저장' },
      { title: '광견병/연간 접종 확인', schedule: '매년', memo: '지자체 지원 기간이 있으면 지역 공지를 확인한다.', completion: '연간 접종 여부 확인' },
    ],
    memo: '건강 판단은 수의사에게 맡기고 Flow는 일정/준비물만 관리한다.',
    uxNote: '민감 영역이므로 날짜표와 준비물은 보이되 의학 조언처럼 보이는 문구를 줄인다.',
    sourceBoundary: '접종 종류와 간격은 수의사 판단 우선이다.',
  },
  {
    id: 'wedding-12-month-timeline',
    title: '결혼 준비 D-300 타임라인',
    category: '생활 이벤트',
    fitScore: 5,
    sourceTitle: '결혼 준비 타임라인 완벽 가이드',
    sourceUrl: 'https://wedding-expo.kr/posts/post-007',
    sourceType: 'creator_blog',
    demandSignal: '결혼 준비는 검색량과 실행 기간이 길고 체크할 항목이 많다.',
    sourceSignal: '원문은 D-300~D-180, D-180~D-90, D-90~D-30, D-30~D-Day로 웨딩홀, 계약, 하객, 청첩장, 식권, BGM, 역할 분담 체크를 나눈다.',
    userNeed: '예식일을 넣으면 월별 준비 항목이 캘린더와 체크리스트로 들어온다.',
    destination: 'hybrid',
    structure: 'timeline',
    cta: '예식일 기준으로 저장',
    inputs: ['예식일', '준비 시작일', '웨딩홀 계약 여부'],
    flowItems: [
      {
        title: '예산과 웨딩홀 후보 3곳 정리',
        schedule: 'D-300~D-180',
        memo: '예산, 지역, 보증인원, 주차 조건을 같은 표에서 비교한다.',
        completion: '후보 3곳의 예산/보증인원/주차 조건 입력',
      },
      {
        title: '웨딩홀 계약금·위약금 확인',
        schedule: 'D-10~9개월',
        memo: '계약금, 환불 가능 시점, 위약금, 보증인원 변경 가능 기한을 계약 메모에 남긴다.',
        completion: '계약금/위약금/보증인원 변경 기한 기록',
      },
      {
        title: '스드메와 본식 촬영 범위 확정',
        schedule: 'D-8~6개월',
        memo: '드레스, 메이크업, 스냅, 영상, 원판 포함 여부와 추가 비용을 비교한다.',
        completion: '업체별 포함 항목과 추가 비용 체크',
      },
      {
        title: '하객 명단 1차 정리',
        schedule: 'D-5~4개월',
        memo: '양가 하객 명단, 예상 참석 인원, 연락처 누락 여부를 확인한다.',
        completion: '양가 하객 명단과 예상 인원 입력',
      },
      {
        title: '청첩장 발송과 참석 회신 확인',
        schedule: 'D-3~2개월',
        memo: '모바일/종이 청첩장 발송 상태와 참석 회신을 나눠 체크한다.',
        completion: '미발송/미회신 하객만 남김',
      },
      {
        title: '식권·좌석·BGM 준비',
        schedule: 'D-1개월',
        memo: '식권 수량, 좌석 배치, 입장/퇴장 BGM, 축가 파일 전달 상태를 확인한다.',
        completion: '식권 수량과 BGM 전달 상태 확인',
      },
      {
        title: '본식 역할 분담 공유',
        schedule: 'D-2주',
        memo: '사회자, 축가, 축의금, 차량, 혼주 동선, 업체 담당자 연락처를 공유한다.',
        completion: '역할별 담당자와 연락처 공유',
      },
      {
        title: '당일 비상 준비물 챙기기',
        schedule: 'D-1주',
        memo: '충전기, 간단한 약, 수선 키트, 예비 식권, 계약서 사본을 한 가방에 묶는다.',
        completion: '당일 가방과 계약서 사본 준비',
      },
    ],
    memo: '업체 비교표와 계약 메모는 별도 시트로 뽑히면 좋다.',
    uxNote: 'D-day 타임라인의 대표 seed 후보. My Flow 캘린더 검증에 가장 좋다.',
    sourceBoundary: '업체 추천/가격 보장은 하지 않고 사용자가 직접 비교하도록 둔다.',
  },
  {
    id: 'moving-d30-checklist',
    title: '이사 D-30 체크리스트',
    category: '생활 이벤트',
    fitScore: 4.6,
    sourceTitle: '이사 준비 체크리스트',
    sourceUrl: 'https://greechii.com/tips/home/moving-checklist/',
    sourceType: 'creator_blog',
    demandSignal: '이사 날짜 기준으로 누구나 일정과 제출/예약을 관리해야 한다.',
    sourceSignal: '전세 정리, 이삿짐센터, 입주청소, 전입신고가 단계별로 분리된다.',
    userNeed: '이사일 하나만 넣고 놓치기 쉬운 예약/신고를 캘린더에 받는다.',
    destination: 'hybrid',
    structure: 'timeline',
    cta: '이사일 기준으로 저장',
    inputs: ['이사일', '자가/전월세', '입주청소 여부'],
    flowItems: [
      { title: '이사업체 견적 비교', schedule: 'D-30~D-21', memo: '업체 3곳 견적, 포함 서비스, 추가비를 비교한다.', completion: '업체 확정' },
      { title: '인터넷·가스·관리비 이전 예약', schedule: 'D-14', memo: '이전 설치일과 해지일을 확인한다.', completion: '예약 완료' },
      { title: '입주청소와 가전 배송일 확인', schedule: 'D-7', memo: '청소, 배송, 입주 가능 시간이 겹치지 않게 조정한다.', completion: '일정 충돌 없음' },
      { title: '전입신고/확정일자 확인', schedule: 'D+1~D+14', memo: '정부24/주민센터 처리와 계약서 준비를 확인한다.', completion: '신고 완료 또는 일정 저장' },
    ],
    memo: '증빙 사진은 기본이 아니라 하자 확인이 필요한 경우에만 선택 필드로 둔다.',
    uxNote: '캘린더 안에는 D-30 대신 짧은 행동 제목만 보여야 한다.',
    sourceBoundary: '법적 효력 설명은 공식 링크 확인 메모로 분리한다.',
  },
  {
    id: 'after-move-address-report',
    title: '이사 후 전입신고·확정일자',
    category: '생활 이벤트',
    fitScore: 4.4,
    sourceTitle: '토스피드 이사 후 체크리스트',
    sourceUrl: 'https://toss.im/tossfeed/article/after-move-checklist',
    sourceType: 'creator_blog',
    demandSignal: '이사 후 보증금 보호와 우편물 문제로 일반 사용자가 바로 필요로 한다.',
    sourceSignal: '전입신고, 확정일자, 소득공제처럼 제출/확인 항목이 명확하다.',
    userNeed: '이사 직후 반드시 처리할 행정 항목을 하루 체크리스트로 받는다.',
    destination: 'checklist',
    structure: 'checklist',
    cta: '이사 후 체크로 저장',
    inputs: ['이사일', '전월세 여부', '온라인 처리 가능 여부'],
    flowItems: [
      { title: '전입신고 처리', schedule: '이사 후 14일 이내', memo: '정부24 또는 주민센터에서 처리한다.', completion: '신고 완료' },
      { title: '확정일자 확인', schedule: '전입신고 직후', memo: '임대차계약서와 신분증 준비 여부를 확인한다.', completion: '확정일자 완료' },
      { title: '주소 변경 신청', schedule: '이사 주간', memo: '카드, 은행, 쇼핑몰, 보험 주소를 확인한다.', completion: '주요 주소 변경 완료' },
    ],
    memo: '공식 처리 링크와 준비 서류를 메모에 둔다.',
    uxNote: '문자/카톡 안내를 받았을 때 바로 Flow로 저장하는 진입점이 좋다.',
    sourceBoundary: '법률 조언이 아니라 처리 항목 체크로 제한한다.',
  },
  {
    id: 'travel-d7-checklist',
    title: '출국 7일 전 여행 준비',
    category: '여행',
    fitScore: 4.3,
    sourceTitle: '출국 7일 전 체크리스트',
    sourceUrl: 'https://westctravel.com/articles/departure-checklist-d7',
    sourceType: 'creator_blog',
    demandSignal: '여행 전 짐싸기와 결제/로밍/여권 확인은 반복 수요가 높다.',
    sourceSignal: '여권, 항공권, 결제수단, 로밍 등 날짜 기반 체크가 가능하다.',
    userNeed: '출국일 기준으로 D-7, D-3, D-1 준비를 나눠 확인한다.',
    destination: 'hybrid',
    structure: 'timeline',
    cta: '출국일 기준으로 저장',
    inputs: ['출국일', '여행 국가', '체류 기간'],
    flowItems: [
      { title: '여권/항공권/숙소 재확인', schedule: 'D-7', memo: '이름 철자, 유효기간, 예약 번호를 확인한다.', completion: '주요 예약 확인 완료' },
      { title: '로밍/eSIM/결제수단 준비', schedule: 'D-5', memo: '현지 통신과 카드 사용 가능 여부를 확인한다.', completion: '통신/결제 준비 완료' },
      { title: '수하물과 공항 공지 확인', schedule: 'D-1', memo: '항공사 수하물, 보조배터리, 액체류 규정을 확인한다.', completion: '짐싸기 완료' },
    ],
    memo: '국가별 입국/안전 정보 공식 링크를 메모에 붙인다.',
    uxNote: '여행 Flow는 국가 선택 후 공식 링크 카드가 자동으로 붙으면 좋다.',
    sourceBoundary: '입국 규정은 변동 가능하므로 출발 직전 공식 링크 확인을 강조한다.',
  },
  {
    id: 'japan-trip-packing',
    title: '일본 여행 준비물 체크',
    category: '여행',
    fitScore: 4.1,
    sourceTitle: 'KKday 일본 여행 준비물 체크리스트',
    sourceUrl: 'https://www.kkday.com/ko/blog/22262/aisa-japan-entry%3Fsrsltid%3DAfmBOop6efVGJPh9BVjNZrGcUc6VMcjp_EchiOklI6Xyec_foIkmNI49',
    sourceType: 'creator_blog',
    demandSignal: '일본 여행은 한국 사용자의 반복 여행 목적지이고 준비물 검색 수요가 높다.',
    sourceSignal: 'eSIM/유심, 교통카드, 환전, 앱처럼 준비 항목이 구체적이다.',
    userNeed: '여행지별 준비물을 체크리스트로 받아 빠뜨리지 않는다.',
    destination: 'checklist',
    structure: 'checklist',
    cta: '여행 준비물로 저장',
    inputs: ['출국일', '도시', '유심/eSIM 선호'],
    flowItems: [
      { title: '통신 수단 결정', schedule: 'D-7', memo: 'eSIM, 유심, 포켓와이파이 중 하나를 선택하고 구매한다.', completion: '통신 준비 완료' },
      { title: '교통/결제 수단 준비', schedule: 'D-5', memo: '교통카드, 트래블카드, 현금 필요 여부를 확인한다.', completion: '결제 준비 완료' },
      { title: '현지 앱과 예약 확인', schedule: 'D-3', memo: '지도, 번역, 예약 앱을 설치하고 로그인한다.', completion: '앱 준비 완료' },
    ],
    memo: '도시별 추천은 메모 링크로 두고 Flow는 준비 체크에 집중한다.',
    uxNote: '국가 템플릿형 Flow로 확장 가능하다.',
    sourceBoundary: '여행 상품 추천과 공식 규정 확인은 분리한다.',
  },
  {
    id: 'japan-esim-setup-before-departure',
    title: '일본 eSIM 출국 전 설정 체크',
    category: '여행/디지털 준비',
    fitScore: 4.6,
    sourceTitle: '일본 eSIM 사용 후기와 설치 순서 참고',
    sourceUrl: 'https://blog.naver.com/PostView.naver?blogId=travelnote_jp&logNo=223529001204',
    sourceType: 'creator_blog',
    demandSignal: '여행 직전 공항에서 통신 설정을 헤매는 문제가 반복되고, 사용자가 출국일 기준 알림으로 옮기기 쉽다.',
    sourceSignal: '구매 전 기기 지원 확인, QR/설치 메일 보관, 출국 전 프로필 설치, 도착 후 회선 활성화라는 순서가 실행 단위로 분리된다.',
    userNeed: '출국 전에 eSIM 설치 준비를 끝내고, 도착 후 데이터 연결만 확인한다.',
    destination: 'hybrid',
    structure: 'timeline',
    cta: '출국 전 체크로 저장',
    inputs: ['출국일', '사용 기기', '알림 시간'],
    flowItems: [
      { title: 'eSIM 지원 기기와 상품 조건 확인', schedule: 'D-3', memo: '사용 기기가 eSIM을 지원하는지, 일본 상품/사용 기간/데이터 용량이 맞는지 확인한다.', completion: '구매할 상품과 기기 지원 여부 확인' },
      { title: 'QR 코드와 설치 메일 저장', schedule: 'D-2', memo: 'QR 코드, 주문번호, 고객센터 링크를 캡처하거나 메모에 붙인다.', completion: '오프라인에서도 열 수 있게 저장' },
      { title: '출국 전 eSIM 프로필 설치', schedule: 'D-1', memo: '설정에서 eSIM을 추가하고 회선 이름을 일본 여행처럼 바꾼다. 현지 데이터 활성화는 도착 후로 둔다.', completion: '프로필 설치 후 현지 데이터는 꺼둠' },
      { title: '도착 후 현지 데이터 연결 확인', schedule: 'D-Day', memo: '현지 회선을 켜고 셀룰러 데이터를 eSIM으로 바꾼 뒤 지도와 메신저 연결을 확인한다.', completion: '지도와 메신저가 현지 데이터로 연결됨' },
    ],
    memo: 'APN, 데이터 로밍, 기기별 화면 차이, 고객센터 링크는 상세 메모로 둔다. Flow 입력은 출국일/기기/알림 시간만 받는다.',
    uxNote: '여행 준비물 전체가 아니라 디지털 설정 1개를 Flow화하는 샘플이다. 캘린더 일정과 상세 메모가 핵심이다.',
    sourceBoundary: '통신 상품 조건과 활성화 시점은 판매처/통신사 안내를 우선한다.',
  },
  {
    id: 'alt-phone-sk7-self-activation',
    title: '알뜰폰 SK7 셀프개통 체크',
    category: '통신/디지털 준비',
    fitScore: 4.6,
    sourceTitle: '알뜰폰 SK7모바일 셀프개통 후기',
    sourceUrl: 'https://blog.naver.com/PostView.nhn?blogId=saljjak-&logNo=223661947600',
    sourceType: 'creator_blog',
    demandSignal: '알뜰폰 번호이동은 유심, 본인인증, 사전동의, 유심 교체 순서에서 막히기 쉬워 실행 체크리스트 수요가 있다.',
    sourceSignal: '원문에 가입유형/요금제 선택, 유심 일련번호 입력, 번호이동 사전동의, 셀프개통 완료 후 유심 교체와 재부팅 순서가 드러난다.',
    userNeed: '유심을 받은 사용자가 셀프개통 중 끊기거나 빠뜨리지 않도록 준비와 개통 절차를 체크한다.',
    destination: 'checklist',
    structure: 'checklist',
    cta: '개통 체크리스트로 저장',
    inputs: ['개통 예정일', '유심 보유 여부', '번호이동 여부'],
    flowItems: [
      { title: '셀프개통 가능 시간과 준비물 확인', schedule: '개통 전', memo: '유심, 유심 일련번호, 본인인증 수단, Wi-Fi 환경, 기존 통신사 정보를 준비한다.', completion: '개통 전 필요한 정보와 연결 환경 확인' },
      { title: '가입유형과 요금제 선택', schedule: '개통 전', memo: '신규가입/번호이동 여부와 사용할 요금제를 정하고 신청서 입력을 시작한다.', completion: '신청 전 선택 항목 확정' },
      { title: '번호이동 사전동의 처리', schedule: '개통 중', memo: '기존 통신사 문자나 ARS 안내에서 위약금, 잔여 할부금, 소멸 혜택을 확인하고 동의한다.', completion: '번호이동 사전동의 완료' },
      { title: '유심 교체 후 통화·데이터 확인', schedule: '개통 직후', memo: '개통 완료 후 유심을 장착하고 재부팅한 뒤 통화, 문자, 데이터 연결을 확인한다.', completion: '통화와 데이터 연결 확인' },
    ],
    memo: '요금제 추천, 주민등록번호, 인증값 같은 민감 정보는 저장하지 않는다. 개통 시간, 공식 안내 링크, 오류 시 고객센터 링크만 상세 메모로 둔다.',
    uxNote: '디지털 절차 Flow는 날짜보다 순서와 완료 기준이 중요하다. 페이지 안 체크리스트가 우선이고, 개통 예정일 알림은 보조로 둔다.',
    sourceBoundary: '개인 후기 기반 순서이므로 최신 요금제, 개통 가능 시간, 본인인증 조건은 통신사 공식 안내를 우선한다.',
  },
  {
    id: 'infant-health-checkup-prep',
    title: '영유아 건강검진 예약 준비',
    category: '육아/행정',
    fitScore: 4.5,
    sourceTitle: '국민건강보험 건강iN 영유아 건강검진 웹 서비스 안내',
    sourceUrl: 'https://www.nhis.or.kr/magazin/mobile/201604/c09.html',
    sourceType: 'official',
    demandSignal: '검진 기간, 기관 예약, 문진표/발달선별 작성, 등록번호 전달처럼 부모가 방문 전에 놓치기 쉬운 준비 행동이 있다.',
    sourceSignal: '원문은 검진 시기 확인, 웹 문진표/발달선별검사지 작성, 등록번호 저장, 검진기관 예약과 방문 절차를 순서대로 안내한다.',
    userNeed: '검진 가능 기간 안에 예약하고, 문진표와 등록번호를 미리 준비해 방문 시간을 줄인다.',
    destination: 'hybrid',
    structure: 'timeline',
    cta: '검진 준비 일정으로 저장',
    inputs: ['검진 예정일', '아이 월령', '검진기관'],
    flowItems: [
      { title: '검진 가능 기간과 기관 확인', schedule: 'D-14', memo: '검진표나 건강iN에서 월령별 검진 기간과 방문 가능한 검진기관을 확인한다.', completion: '검진 기간과 기관 후보 확인' },
      { title: '검진기관 예약하기', schedule: 'D-10', memo: '대기 시간을 줄이기 위해 기관에 연락해 예약 가능 시간, 주소, 준비 안내를 메모한다.', completion: '예약 일시와 기관 정보 저장' },
      { title: '문진표와 발달선별 작성 확인', schedule: 'D-3', memo: '건강iN에서 문진표 또는 발달선별검사지를 작성하고 등록번호 4자리를 메모한다.', completion: '문진표 작성 또는 현장 작성 준비 완료' },
      { title: '방문 준비물과 아이 상태 메모', schedule: 'D-1', memo: '등록번호, 보호자 확인 수단, 아이 컨디션이나 질문할 내용을 한 줄로 정리한다.', completion: '방문 전 확인 완료' },
      { title: '예약 시간에 검진기관 방문', schedule: 'D-Day', memo: '접수 시 온라인 문진표 등록번호를 알려주고 기관 안내에 따라 검진을 받는다.', completion: '검진 방문 완료' },
    ],
    memo: '검진 결과 해석이나 성장 평가 기록은 기본 기능에 넣지 않는다. Flow는 예약, 문진표, 등록번호, 방문 준비만 돕는다.',
    uxNote: '육아 건강 Flow는 의료 기록 앱이 아니라 방문 준비 타임라인이어야 한다. 공식 정보와 부모 메모를 시각적으로 분리한다.',
    sourceBoundary: '공식 안내를 기준으로 하되 의료 판단, 결과 해석, 이상 소견 상담은 검진기관과 전문가에게 맡긴다.',
  },
  {
    id: 'chiangmai-solo-trip-packing',
    title: '치앙마이 혼자 여행 준비물 체크',
    category: '여행/장기체류',
    fitScore: 4.4,
    sourceTitle: '치앙마이 혼자 여행 준비물 체크리스트',
    sourceUrl: 'https://blog.naver.com/PostView.nhn?blogId=mat_zip_diary&logNo=223137520451',
    sourceType: 'creator_blog',
    demandSignal: '혼자 장기 여행자는 통신, 결제, 보험, 샤워기 필터, 비상 준비처럼 개인 체크리스트로 옮길 항목이 많다.',
    sourceSignal: '원문은 유심/eSIM, 환전과 GLN, 여행자보험, 압축팩, 비상약, 필터 샤워기, 일회용품, 기타 꿀템과 PDF 체크리스트를 제공한다.',
    userNeed: '출국 전에 혼자 여행 준비물을 빠뜨리지 않고, 상품 링크와 개인 판단은 메모에 남긴다.',
    destination: 'checklist',
    structure: 'checklist',
    cta: '여행 준비 체크로 저장',
    inputs: ['출국일', '체류 기간', '여행 도시'],
    flowItems: [
      { title: '통신 수단 두 가지 확인', schedule: 'D-7', memo: '메인폰 유심/eSIM과 비상용 통신 수단이 필요한지 정한다. 구매 링크는 상세 메모에 붙인다.', completion: '통신 수단과 원본 링크 저장' },
      { title: '현금·GLN·카드 결제 준비', schedule: 'D-5', memo: '현금은 최소 금액만 정하고 GLN/카드 사용 가능 여부를 확인한다.', completion: '결제 수단 2개 이상 준비' },
      { title: '보험·비상약·비상 연락 메모', schedule: 'D-3', memo: '여행자보험 가입 여부, 지사제/밴드/상비약, 대사관·숙소 연락처를 메모한다.', completion: '비상 메모 1개 완성' },
      { title: '숙소 생활용품과 짐 압축 확인', schedule: 'D-1', memo: '필터 샤워기, 여분 필터, 물티슈, 지퍼백, 압축팩처럼 원문에서 실제 쓴 준비물을 골라 챙긴다.', completion: '짐 체크리스트 완료' },
    ],
    memo: '개 퇴치기, 특정 상품 링크, 보험/결제 서비스 추천은 원문 경험 메모로만 둔다. Flow는 준비물 체크와 원문 링크 보관에 집중한다.',
    uxNote: '여행 준비물 Flow는 국가 일반론보다 “혼자/장기체류” 같은 상황 태그가 있어야 사용자가 자기 필요를 판단하기 쉽다.',
    sourceBoundary: '여행 안전, 보험 보장, 결제 가능 여부는 공식/서비스 최신 안내를 따르고, 원문은 개인 경험으로 표시한다.',
  },
  {
    id: 'computer-skills-written-3day-summary',
    title: '컴활 2급 필기 3일 요약 플랜',
    category: '공부/자격증',
    fitScore: 4.3,
    sourceTitle: '컴활 2급 필기 요약 정리 공유 (+ PDF 파일)',
    sourceUrl: 'https://blog.naver.com/PostView.naver?blogId=bunnudy&logNo=222440821485',
    sourceType: 'creator_blog',
    demandSignal: '시험 직전 사용자는 긴 공부 앱보다 3일 캘린더와 PDF/기출 링크가 붙은 짧은 진행표를 원한다.',
    sourceSignal: '원문에는 CBT 기출 출력, 유튜브 강의 참고, 1일차 1과목, 2일차 2과목, 3일차 월단위 재풀이와 요약 PDF 활용이 명확하다.',
    userNeed: '시험일을 기준으로 3일 동안 과목별 기출과 요약 PDF를 확인한다.',
    destination: 'hybrid',
    structure: 'timeline',
    cta: '3일 공부 플랜으로 저장',
    inputs: ['시험일', '하루 공부 시간', '자료 저장 위치'],
    flowItems: [
      { title: 'CBT 기출과 요약 PDF 저장', schedule: 'D-3 시작 전', memo: 'CBT 기출 링크, 원문 요약 PDF, 참고 유튜브 링크를 메모에 붙인다.', completion: '자료 링크 3개 저장' },
      { title: '1과목 기출 풀기', schedule: 'D-3', memo: '원문처럼 컴퓨터 일반 2020~2018년 회차를 최신순으로 푼다.', completion: '1과목 기출 범위 완료' },
      { title: '2과목 기출 풀기', schedule: 'D-2', memo: '스프레드시트 일반 회차를 풀고 헷갈린 문제 번호만 남긴다.', completion: '2과목 기출 범위 완료' },
      { title: '월단위 재풀이와 PDF 훑기', schedule: 'D-1', memo: '과목 구분 없이 월단위로 다시 풀고, 잠들기 전 요약 PDF를 한 번 훑는다.', completion: '오답 후보와 PDF 확인 완료' },
    ],
    memo: '합격 보장이나 점수 예측은 하지 않는다. 기존 30일 컴활 대표 Flow와 겹치므로, 이 후보는 시험 직전 단기 variant로 본다.',
    uxNote: '공부 Flow는 “기출 회차 진행표 + 시험일 캘린더 + 자료 링크 메모” 정도가 충분하다. 별도 학습 기록 앱으로 키우지 않는다.',
    sourceBoundary: '개인 합격 후기와 자료 공유 기반이다. 시험 일정과 출제 범위는 공식 시험 안내를 별도로 확인해야 한다.',
  },
  {
    id: 'lease-contract-report-deadline',
    title: '주택 임대차계약 신고 준비',
    category: '주거/행정',
    fitScore: 4.2,
    sourceTitle: '주택임대차계약신고필증 발급방법 알아보기',
    sourceUrl: 'https://blog.naver.com/PostView.naver?blogId=havelaw&logNo=222863332365',
    sourceType: 'creator_blog',
    demandSignal: '계약 후 30일 신고 마감과 계약서/신분증/전자서명 준비는 캘린더와 체크리스트로 옮기기 좋다.',
    sourceSignal: '원문은 계약 체결일로부터 30일 이내 신고, 방문/인터넷 신고 준비물, 부동산 거래관리 시스템 접속, 계약 정보 입력, 전자서명, 접수/승인/필증 발급 순서를 설명한다.',
    userNeed: '임대차 계약 후 신고 마감 전에 필요한 서류와 온라인 신고 단계를 확인한다.',
    destination: 'hybrid',
    structure: 'timeline',
    cta: '신고 마감 일정으로 저장',
    inputs: ['계약일', '신고 방식', '주택 소재지'],
    flowItems: [
      { title: '신고 대상과 30일 마감 확인', schedule: '계약 직후', memo: '보증금/월차임 기준과 계약일 또는 가계약금 입금일 기준 마감을 확인한다.', completion: '신고 대상 여부와 마감일 확인' },
      { title: '계약서와 인증수단 준비', schedule: 'D+7 전', memo: '방문이면 신분증과 계약서, 인터넷이면 공동인증서와 계약서 스캔본을 준비한다.', completion: '신고 준비물 확보' },
      { title: '부동산 거래관리 시스템 신고서 작성', schedule: 'D+20 전', memo: '시도/시군구 선택, 신청인, 임대인, 임대목적물, 계약 내용을 계약서 기준으로 입력한다.', completion: '신고서 임시저장 또는 작성 완료' },
      { title: '전자서명·접수·필증 확인', schedule: 'D+30 전', memo: '전자서명 후 접수 완료 상태를 확인하고 승인 알림 후 신고필증을 저장한다.', completion: '접수 또는 신고필증 저장' },
    ],
    memo: '계약서의 개인정보와 주민등록번호는 Flow에 저장하지 않는다. 법적 효력과 최신 제도는 정부/지자체 공식 안내를 우선한다.',
    uxNote: '행정 Flow는 긴 법률 설명보다 “마감일 + 준비물 + 공식 시스템 링크 + 처리 상태”가 중심이어야 한다.',
    sourceBoundary: '개인 블로그 절차 설명이므로 최신 법령, 과태료, 신고 대상 여부는 국토교통부/부동산거래관리시스템/지자체 안내를 확인해야 한다.',
  },
  {
    id: 'baby-food-four-week-menu',
    title: '초기 토핑 이유식 4주 식단표',
    category: '육아/식단',
    fitScore: 4.2,
    sourceTitle: '2025 토핑이유식 식단표, 초기 1~2단계',
    sourceUrl: 'https://family-yes.tistory.com/229',
    sourceType: 'creator_blog',
    demandSignal: '부모가 바로 캘린더/냉장고 메모로 옮기고 싶어하는 표형 콘텐츠다.',
    sourceSignal: '1~4주차 식단표와 재료 추가 순서가 있다.',
    userNeed: '시작일 기준으로 4주 식단표를 캘린더/시트로 받는다.',
    destination: 'sheet',
    structure: 'table_plan',
    cta: '4주 식단표로 저장',
    inputs: ['이유식 시작일', '단계', '알레르기 주의 식품'],
    flowItems: [
      { title: '1주차 쌀죽/기본 재료 시작', schedule: '1주차', memo: '새 재료는 한 번에 하나씩 추가한다.', completion: '1주차 식단 완료' },
      { title: '2주차 채소 토핑 추가', schedule: '2주차', memo: '재료 반응을 확인하며 다음 재료로 넘어간다.', completion: '2주차 식단 완료' },
      { title: '3~4주차 소고기/단백질 확인', schedule: '3~4주차', memo: '원문 식단표와 소아과 안내를 함께 확인한다.', completion: '4주 식단표 종료' },
    ],
    memo: '반응 기록은 무겁게 만들지 않고, 오늘 먹은 메뉴와 특이사항 한 줄만 둔다.',
    uxNote: '이유식은 기록 앱이 아니라 식단표 export로 접근해야 한다.',
    sourceBoundary: '의학 판단은 하지 않고 알레르기/이상 반응은 전문가 상담 문구로 분리한다.',
  },
  {
    id: 'child-weekend-play-rotation',
    title: '아이 주말 놀이 로테이션',
    category: '육아/놀이',
    fitScore: 4.2,
    sourceTitle: 'i-누리 종이컵 놀이 자료',
    sourceUrl: 'https://i-nuri.go.kr/board/boardFile/download/27/630/1319.do',
    sourceType: 'official',
    demandSignal: '부모가 주말마다 “오늘 뭐 하고 놀지”를 반복적으로 찾는다.',
    sourceSignal: '종이컵 준비, 분류/쌓기/개수 세기처럼 놀이 방법이 실행 가능하다.',
    userNeed: '주말 놀이 루틴에 놀이 방법 카드를 하나씩 매핑한다.',
    destination: 'routine',
    structure: 'rotating_routine',
    cta: '주말 놀이로 저장',
    inputs: ['놀이 요일', '아이 연령', '준비물 보유 여부'],
    flowItems: [
      { title: '종이컵 쌓기 놀이', schedule: '이번 주말', memo: '종이컵을 준비하고 아이가 쌓거나 무너뜨리며 탐색하게 둔다.', completion: '놀이 1회 진행' },
      { title: '색/개수 분류 놀이', schedule: '다음 주말 후보', memo: '컵 색이나 개수를 활용해 분류하거나 세어본다.', completion: '분류 놀이 진행' },
      { title: '다음 놀이 카드 고르기', schedule: '놀이 후', memo: '아이 반응이 좋았던 준비물/놀이를 다음 카드로 남긴다.', completion: '다음 후보 선택' },
    ],
    memo: '완료 기준은 기록 강제가 아니라 “놀이함”으로 충분하다.',
    uxNote: '아이 독서/놀이 루틴에 콘텐츠 카드를 매핑하는 신규 UX가 필요하다.',
    sourceBoundary: '교육 효과를 보장하지 않고 놀이 아이디어로만 제공한다.',
  },
  {
    id: 'kids-dino-footprint-art',
    title: '아이 공룡 발자국 미술 놀이',
    category: '육아/놀이',
    fitScore: 4.3,
    sourceTitle: '유아 공룡 발자국 놀이 자료 검색 기반',
    sourceUrl: 'https://info.childcare.go.kr/info/pnis/search/PnisFileDownload.jsp?STCODE_POP=41480000016&filetype=YUPLOADU&flag=DNGB&schoolyear=2026&wkyear=202604',
    sourceType: 'official',
    demandSignal: '부모가 주말에 바로 따라 할 수 있는 놀이 아이디어를 찾고, 준비물과 진행 순서가 짧으면 저장 가치가 높다.',
    sourceSignal: '공룡 사전, 피규어, 화석 놀이, 클레이, 공룡 발자국 일러스트처럼 놀이 준비물과 활동 소재가 명확하다.',
    userNeed: '주말 놀이 일정에 준비물과 활동 순서를 붙여 아이와 바로 진행한다.',
    destination: 'routine',
    structure: 'single_routine',
    cta: '주말 놀이로 저장',
    inputs: ['놀이 날짜', '아이 연령', '알림 시간'],
    flowItems: [
      { title: '공룡 놀이 준비물 꺼내기', schedule: '놀이 전날', memo: '공룡 그림/피규어, 물감 또는 클레이, 종이, 물티슈를 한곳에 모은다.', completion: '준비물이 놀이 장소에 모임' },
      { title: '공룡 발자국 찍기', schedule: '놀이 시간', memo: '피규어 발이나 손가락/도구로 발자국을 찍고 아이가 색을 고르게 둔다.', completion: '발자국 작품 1개 만들기' },
      { title: '발자국 따라 이야기 만들기', schedule: '놀이 중', memo: '어떤 공룡이 지나갔는지, 어디로 갔는지 아이가 말하게 한다.', completion: '아이 말 한 줄 메모' },
      { title: '작품 말리고 다음 놀이 고르기', schedule: '놀이 후', memo: '작품을 말리고 다음 주에 하고 싶은 공룡/동물 놀이 후보를 하나 고른다.', completion: '정리 완료와 다음 후보 선택' },
    ],
    memo: '교육 효과 기록이나 발달 평가는 넣지 않는다. 준비물, 원문 링크, 아이가 한 말 한 줄만 메모로 둔다.',
    uxNote: '아이 놀이 Flow는 긴 학습 기록이 아니라 주말 일정 + 준비물 + 놀이 체크 정도가 맞는지 검증한다.',
    sourceBoundary: '교육 효과 보장이 아니라 보호자가 참고하는 놀이 아이디어로만 제시한다.',
  },
  {
    id: 'picture-book-reading-routine',
    title: '그림책 읽기 루틴 + 질문 카드',
    category: '육아/독서',
    fitScore: 4.1,
    sourceTitle: '토토북 그림책 독서 지도안',
    sourceUrl: 'https://image.aladdin.co.kr/img/files/150922_workbook/%EC%9C%A0%EC%95%84/16%20%ED%86%A0%ED%86%A0%EB%B6%81_%EB%8F%85%EC%88%98%EB%A6%AC%EC%99%80%20%EA%B5%B4%EB%9A%9D%EC%83%88.pdf',
    sourceType: 'official',
    demandSignal: '책 자체를 산 뒤 함께 읽을 질문/활동이 필요하다.',
    sourceSignal: '읽기 전, 읽기 중, 읽기 후 활동으로 나뉜다.',
    userNeed: '독서 루틴에 책별 질문 카드와 활동 체크를 붙인다.',
    destination: 'routine',
    structure: 'rotating_routine',
    cta: '독서 루틴으로 저장',
    inputs: ['읽을 요일', '책 제목', '반복 여부'],
    flowItems: [
      { title: '표지 보고 이야기 나누기', schedule: '읽기 전', memo: '표지와 제목을 보고 어떤 이야기일지 물어본다.', completion: '읽기 전 대화 완료' },
      { title: '그림책 함께 읽기', schedule: '독서 시간', memo: '중간에 아이가 고른 장면을 짚어본다.', completion: '책 1권 읽음' },
      { title: '좋아한 장면 말하기', schedule: '읽은 뒤', memo: '아이에게 기억나는 장면이나 단어를 물어본다.', completion: '후속 질문 1개 완료' },
    ],
    memo: '책 링크, 지도안 PDF, 다음에 읽을 책을 메모에 둔다.',
    uxNote: '책별 Flow가 아니라 “독서 루틴”에 책 콘텐츠가 꽂히는 구조가 맞다.',
    sourceBoundary: '지도안 원문과 Flow 항목이 다를 수 있으므로 출처 링크를 항상 붙인다.',
  },
  {
    id: 'homelearn-reading-challenge',
    title: '예비초 독서 챌린지 책 목록',
    category: '육아/독서',
    fitScore: 4.0,
    sourceTitle: '홈런 독서챌린지 권장도서 리스트',
    sourceUrl: 'https://www.home-learn.co.kr/front/doc/%ED%99%88%EB%9F%B0%EB%8F%85%EC%84%9C%EC%B1%8C%EB%A6%B0%EC%A7%80_%EA%B6%8C%EC%9E%A5%EB%8F%84%EC%84%9C_%EB%A6%AC%EC%8A%A4%ED%8A%B8.pdf',
    sourceType: 'official',
    demandSignal: '권장도서 목록은 구매/대여/읽기 체크로 바로 옮길 수 있다.',
    sourceSignal: '학년/연령별 권장도서 목록이 행 단위로 존재한다.',
    userNeed: '책 목록을 독서 체크리스트로 받고 매주 1권씩 읽는다.',
    destination: 'sheet',
    structure: 'table_plan',
    cta: '도서 체크리스트로 저장',
    inputs: ['연령/학년', '읽기 요일', '주당 권수'],
    flowItems: [
      { title: '이번 주 책 1권 고르기', schedule: '매주 시작일', memo: '권장도서 목록에서 대여/구매 가능한 책을 고른다.', completion: '이번 주 책 선택' },
      { title: '책 읽기', schedule: '매주 1회', memo: '독서 루틴에서 책 제목과 원문 목록 링크를 함께 보여준다.', completion: '책 1권 읽음' },
      { title: '다음 책으로 넘기기', schedule: '읽은 뒤', memo: '읽은 책은 완료로 바꾸고 다음 후보를 고른다.', completion: '다음 책 선택' },
    ],
    memo: '도서 구매/도서관 링크는 메모에 붙인다.',
    uxNote: '목록형 콘텐츠는 캘린더보다 “진도표 + 주간 루틴”이 적합하다.',
    sourceBoundary: '권장도서 목록은 참고용이며 아이 반응에 맞춰 변경 가능해야 한다.',
  },
  {
    id: 'plank-30-day-challenge',
    title: '30일 플랭크 챌린지',
    category: '운동/챌린지',
    fitScore: 4.2,
    sourceTitle: '플랭크 30일 챌린지 계획표',
    sourceUrl: 'https://khj2510.tistory.com/entry/%ED%94%8C%EB%9E%AD%ED%81%AC-30%EC%9D%BC-%EC%B1%8C%EB%A6%B0%EC%A7%80-%EA%B3%84%ED%9A%8D%ED%91%9C-%EA%B3%B5%EC%9C%A0',
    sourceType: 'creator_blog',
    demandSignal: '30일 챌린지는 캘린더 저장 욕구가 분명하다.',
    sourceSignal: '일자별 초 단위 목표와 휴식일이 있다.',
    userNeed: '시작일을 넣으면 30일 플랭크 목표가 매일 캘린더에 들어온다.',
    destination: 'calendar',
    structure: 'challenge',
    cta: '30일 챌린지로 저장',
    inputs: ['시작일', '난이도', '운동 시간대'],
    flowItems: [
      { title: '플랭크 20초', schedule: 'Day 1', memo: '정확한 자세는 원문을 확인하고 무리하지 않는다.', completion: '오늘 목표 초수 완료' },
      { title: '플랭크 60초', schedule: 'Day 10 전후', memo: '통증이 있으면 중단하고 목표를 낮춘다.', completion: '오늘 목표 초수 또는 조정 완료' },
      { title: '휴식·스트레칭', schedule: '휴식일', memo: '휴식일은 실패가 아니라 계획의 일부로 표시한다.', completion: '휴식 체크' },
      { title: '챌린지 완주', schedule: 'Day 30', memo: '마지막 목표를 수행하고 다음 반복 여부를 정한다.', completion: '완주 또는 재도전 결정' },
    ],
    memo: '운동 기록은 필수로 만들지 말고 완료/보류만 둔다.',
    uxNote: '운동 Flow는 내부 체크리스트보다 캘린더 이벤트와 원문 링크가 중요하다.',
    sourceBoundary: '운동 효과를 보장하지 않고 통증/어지러움 시 중단 문구를 둔다.',
  },
  {
    id: 'thankyou-bubu-no-jump-home-workout',
    title: 'ThankyouBUBU 점프 없는 홈트 영상',
    category: '운동/홈트',
    fitScore: 4.3,
    sourceTitle: '전신 다이어트 최고의 운동 [점프 없음, 눕는동작 없음, 반복 없음, 토크 없음]',
    sourceUrl: 'https://www.youtube.com/watch?v=pcyrlkHXAdE',
    sourceType: 'creator_video',
    demandSignal: '유튜브 follow-along 운동은 “나중에 해야지”에서 끝나기 쉬워 반복 캘린더 저장 욕구가 분명하다.',
    sourceSignal: '원본 제목 자체에 점프 없음, 눕는 동작 없음, 반복 없음, 토크 없음이라는 실행 조건이 드러난다.',
    userNeed: '초보 홈트 사용자가 원본 영상을 정한 요일에 열고 1회 따라 한 뒤 몸 상태만 가볍게 남긴다.',
    destination: 'routine',
    structure: 'single_routine',
    cta: '홈트 루틴으로 저장',
    inputs: ['운동 시작일', '운동 요일', '운동 시간대'],
    flowItems: [
      { title: '원본 영상 반복 일정 만들기', schedule: '저장할 때', memo: '운동 시작일, 요일, 시간대만 정하고 각 일정에 원본 영상 링크를 붙인다.', completion: '원본 영상 링크가 있는 반복 일정 생성' },
      { title: '점프 없음·눕는 동작 없음 조건 확인', schedule: '운동일', memo: '원본 제목의 점프 없음, 눕는 동작 없음, 반복 없음, 토크 없음 조건을 보고 오늘 가능한 강도로 시작한다.', completion: '조건 확인 후 원본 영상 열기' },
      { title: '원본 영상 1회 실행', schedule: '운동일', memo: 'Flow가 동작 순서를 새로 만들지 않고 원본 영상의 자세와 박자를 그대로 확인한다.', completion: '원본 영상을 열고 가능한 강도로 1회 실행' },
      { title: '몸 상태 메모 남기기', schedule: '운동 직후', memo: '완료 여부, 체감 난이도, 통증/어지러움/호흡 곤란 여부, 다음 회차 조정만 남긴다.', completion: '완료, 강도 낮춤, 휴식 중 하나로 기록' },
    ],
    memo: '영상 동작 설명은 원본 링크로 보내고, Flow에는 반복 일정과 실행 후 기록만 둔다.',
    uxNote: '단일 영상은 운동표를 새로 만들지 않는다. 캘린더 일정 안에 원본 영상 링크와 중단 조건이 같이 있어야 한다.',
    sourceBoundary: '운동 처방이 아니며 통증, 어지러움, 호흡 곤란, 기존 질환 악화가 있으면 중단한다.',
  },
  {
    id: 'banana-peanut-recipe-video',
    title: '바나나 땅콩버터 빵 영상 따라하기',
    category: '요리/레시피',
    fitScore: 4.4,
    sourceTitle: '노밀가루 바나나 땅콩버터 빵 20분 완성',
    sourceUrl: 'https://www.recipio.kr/recipes/WwyL63J3',
    sourceType: 'creator_video',
    demandSignal: '짧은 레시피 영상은 저장해두고 주말/간식 시간에 따라 하려는 수요가 분명하다.',
    sourceSignal: '바나나, 계란, 땅콩버터를 내열 용기에 넣고 에어프라이어로 굽는 짧은 조리 순서가 있다.',
    userNeed: '레시피 영상을 다시 찾지 않고 장보기, 조리, 굽기 시간을 체크한다.',
    destination: 'checklist',
    structure: 'checklist',
    cta: '요리 체크리스트로 저장',
    inputs: ['요리 날짜', '분량', '알림 시간'],
    flowItems: [
      { title: '재료 확인', schedule: '요리 전', memo: '바나나, 계란, 땅콩버터, 에어프라이어용 내열 용기를 준비한다.', completion: '재료와 용기 준비 완료' },
      { title: '용기에 재료 넣고 섞기', schedule: '조리 시작', memo: '바나나를 으깨고 계란과 땅콩버터를 넣어 섞는다.', completion: '반죽 준비 완료' },
      { title: '에어프라이어에 굽기', schedule: '조리 중', memo: '원문 영상의 온도/시간을 확인해 굽고, 중간 상태를 본다.', completion: '굽기 완료' },
      { title: '식힘 후 맛/변형 메모', schedule: '조리 후', memo: '다음에 바꿀 분량, 굽기 시간, 토핑 후보만 한 줄로 남긴다.', completion: '다음 조리 메모 1줄 작성' },
    ],
    memo: '영양 기록, 식단 관리, 칼로리 계산은 기본으로 넣지 않는다. 원본 영상 링크와 조리 온도/시간 메모만 둔다.',
    uxNote: '요리 Flow는 캘린더보다 당일 체크리스트와 원본 영상 링크가 먼저다.',
    sourceBoundary: '알레르기나 식단 효과 판단을 하지 않고 레시피 실행 메모로만 다룬다.',
  },
  {
    id: 'computer-license-2nd-written',
    title: '컴활 2급 필기 단기 공부',
    category: '공부/자격증',
    fitScore: 4.1,
    sourceTitle: '컴활 2급 필기 합격후기',
    sourceUrl: 'https://tea-books.tistory.com/5',
    sourceType: 'creator_blog',
    demandSignal: '시험일 기준으로 단기 공부 계획을 세우려는 수요가 뚜렷하다.',
    sourceSignal: '공부 시간, 기출 세트, CBT 링크, 과목별 비중이 있다.',
    userNeed: '시험일을 넣고 기출 풀이와 오답 확인을 일정으로 받는다.',
    destination: 'hybrid',
    structure: 'timeline',
    cta: '시험일 기준으로 저장',
    inputs: ['시험일', '하루 공부 가능 시간', '필기/실기 구분'],
    flowItems: [
      { title: '핵심 개념 훑기', schedule: 'D-7~D-5', memo: '컴퓨터 일반과 스프레드시트 기본 개념을 훑는다.', completion: '핵심 요약 1회독' },
      { title: '기출 2세트 풀기', schedule: 'D-4~D-2', memo: 'CBT 기출을 풀고 틀린 유형을 표시한다.', completion: '기출 세트 완료' },
      { title: '오답만 다시 보기', schedule: 'D-1', memo: '자주 틀린 과목/유형만 다시 본다.', completion: '시험 전 점검 완료' },
    ],
    memo: '기출 링크와 오답 메모만 남기고 공부 일지는 만들지 않는다.',
    uxNote: '공부 Flow는 “진도표 + 시험일 캘린더”가 핵심이다.',
    sourceBoundary: '합격 보장이 아니라 개인 후기 기반 계획임을 표시한다.',
  },
  {
    id: 'korean-history-3-week',
    title: '한능검 3주 공부 플랜',
    category: '공부/자격증',
    fitScore: 4.0,
    sourceTitle: '한국사능력검정 준비기간 3주 플랜',
    sourceUrl: 'https://hidell.tistory.com/2085',
    sourceType: 'creator_blog',
    demandSignal: '시험 일정에 맞춘 단기 플랜 수요가 크다.',
    sourceSignal: '3주 플랜, 시대별 핵심, 기출 회독 구조가 있다.',
    userNeed: '시험일까지 3주 남았을 때 주차별 공부와 기출 풀이를 캘린더에 넣는다.',
    destination: 'hybrid',
    structure: 'timeline',
    cta: '3주 플랜으로 저장',
    inputs: ['시험일', '목표 급수', '하루 공부 시간'],
    flowItems: [
      { title: '시대별 핵심 정리', schedule: '1주차', memo: '선사~조선 핵심 흐름을 정리한다.', completion: '1주차 범위 완료' },
      { title: '근현대와 빈출 세트 암기', schedule: '2주차', memo: '독립운동, 근현대, 문화재 빈출을 묶어서 본다.', completion: '2주차 범위 완료' },
      { title: '기출 회독과 오답 제거', schedule: '3주차', memo: '기출을 풀고 틀린 시대만 다시 본다.', completion: '모의/기출 점검 완료' },
    ],
    memo: '강의/교재 링크는 메모에 두고 Flow는 일정과 진도만 다룬다.',
    uxNote: '시험일을 바꾸면 주차 일정이 자동 이동해야 한다.',
    sourceBoundary: '합격 가능성 예측은 하지 않는다.',
  },
  {
    id: 'used-car-buying-check',
    title: '중고차 후보 점검 체크',
    category: '차량/구매',
    fitScore: 4.7,
    sourceTitle: '중고차 구매 체크리스트 2026',
    sourceUrl: 'https://trendmetriclab.com/guides/used-car-buying-checklist/',
    sourceType: 'creator_blog',
    demandSignal: '구매 전 실수 비용이 크고 체크리스트 전환 가치가 높다.',
    sourceSignal: '예산/후보 정리, 방문 전 준비, 현장 확인, 계약 전 확인, 구매/보류/거절 결정이 섹션별 체크리스트로 나뉜다.',
    userNeed: '후보 차량을 볼 때 바로 확인할 체크리스트와 구매/보류 결정을 남긴다.',
    destination: 'checklist',
    structure: 'checklist',
    cta: '차량 점검표로 저장',
    inputs: ['차량명', '방문일', '매매상사/딜러'],
    flowItems: [
      {
        title: '예산과 후보 차량 기준 정리',
        schedule: '방문 전',
        memo: '총예산을 차량가, 이전비, 보험료, 정비비로 나누고 연식·주행거리별 시세를 같이 본다.',
        completion: '예산 범위와 후보 차량 기준 입력',
      },
      {
        title: '성능점검기록부와 보험이력 조회',
        schedule: '방문 전/현장',
        memo: '사고, 교환, 누유, 수리 금액, 침수/도난 이력을 실차 설명과 대조한다.',
        completion: '기록부와 보험이력의 불일치 여부 표시',
      },
      {
        title: '자동차등록원부 압류·저당 확인',
        schedule: '방문 전',
        memo: '자동차등록원부에서 압류, 저당, 소유자 정보를 확인하고 계약 전 미해소 항목을 남긴다.',
        completion: '압류·저당 없음 또는 보류 사유 기록',
      },
      {
        title: '낮 시간 방문 준비',
        schedule: '방문 전날',
        memo: '낮 시간 방문을 잡고 매물 사진, 차량 정보, 손전등, 휴대폰 충전, 체크 메모를 준비한다.',
        completion: '방문 시간과 준비물 체크',
      },
      {
        title: '외관·타이어·침수 흔적 확인',
        schedule: '현장',
        memo: '외판 단차, 도장 흔적, 시트 레일 녹, 안전벨트 진흙, 트렁크 바닥, 타이어 마모와 제조 연월을 본다.',
        completion: '침수/외관/타이어 이상 여부 체크',
      },
      {
        title: '엔진·변속·제동 상태 확인',
        schedule: '시승/현장',
        memo: '엔진룸 누유, 냉각수, 벨트, 시동, 변속 충격, 제동감, 핸들 떨림을 체크한다.',
        completion: '주행 이상 여부와 추가 점검 필요 표시',
      },
      {
        title: '정비소 검수와 예상 수리비 확인',
        schedule: '계약 전',
        memo: '전문가 점검 결과와 예상 수리비를 가격 판단에 반영하고, 불확실하면 보류로 둔다.',
        completion: '정비소 검수 결과 또는 보류 사유 기록',
      },
      {
        title: '계약 조건 확인 후 구매/보류/거절 결정',
        schedule: '계약 전/방문 후',
        memo: '명의이전 비용, 보험 가입 시점, 계약서의 결함·보증·반품 조건을 확인한 뒤 결정한다.',
        completion: '구매/보류/거절 중 하나 선택',
      },
    ],
    memo: '사용자 사진 증빙을 강제하지 않고 원문 체크 항목과 주의만 메모에 둔다.',
    uxNote: '완료보다 구매/보류/거절이 핵심 상태다.',
    sourceBoundary: '법적/기술적 판단은 전문 점검과 계약서 확인을 우선한다.',
  },
  {
    id: 'car-cabin-filter-replace',
    title: '자동차 에어컨 필터 셀프 교체',
    category: '차량/관리',
    fitScore: 4.3,
    sourceTitle: '자동차 에어컨 필터 교체 주기와 방법',
    sourceUrl: 'https://www.autodirection.kr/blog/?bmode=view&idx=166941342',
    sourceType: 'creator_blog',
    demandSignal: '필터 구매와 셀프 교체가 반복되는 실용 과제다.',
    sourceSignal: '교체 주기, 증상, 셀프 교체 방법, 비용 정보가 있다.',
    userNeed: '차량별 필터 교체일을 저장하고 계절마다 교체한다.',
    destination: 'routine',
    structure: 'single_routine',
    cta: '차량 관리 루틴 저장',
    inputs: ['차량명', '마지막 교체일', '필터 모델'],
    flowItems: [
      { title: '호환 필터 확인', schedule: '교체 전', memo: '차량 연식과 필터 모델을 확인한다.', completion: '필터 구매 완료' },
      { title: '에어컨 필터 교체', schedule: '6개월 또는 1년마다', memo: '글로브박스 뒤 필터 방향을 확인해 교체한다.', completion: '필터 교체 완료' },
      { title: '강풍 운전으로 먼지 배출', schedule: '교체 후', memo: '교체 후 송풍/강풍을 짧게 켜 내부 먼지를 배출한다.', completion: '교체 후 점검 완료' },
    ],
    memo: '차량별 영상 링크와 필터 구매 링크가 중요하다.',
    uxNote: '차량 관리 Flow는 차량 프로필에 여러 소모품 루틴이 붙는 구조가 좋다.',
    sourceBoundary: '차량별 구조가 다르므로 무리한 분해는 정비소 확인을 권한다.',
  },
  {
    id: 'car-maintenance-schedule',
    title: '자동차 소모품 교체 스케줄',
    category: '차량/관리',
    fitScore: 4.4,
    sourceTitle: '자동차 소모품 교체 주기 종합표',
    sourceUrl: 'https://car.mustarddata.com/guide/maintenance-schedule/',
    sourceType: 'creator_blog',
    demandSignal: '소모품은 주행거리와 기간이 섞여 있어 앱화 가치가 높다.',
    sourceSignal: '엔진오일, 타이어, 브레이크, 배터리 등 주기표가 있다.',
    userNeed: '내 차의 주행거리/마지막 교체일 기준으로 다음 점검 알림을 만든다.',
    destination: 'sheet',
    structure: 'table_plan',
    cta: '소모품 표로 저장',
    inputs: ['차량명', '현재 주행거리', '마지막 교체일'],
    flowItems: [
      { title: '엔진오일 교체 예정 확인', schedule: '거리/개월 기준', memo: '마지막 교체일과 주행거리를 같이 본다.', completion: '교체/유지 결정' },
      { title: '와이퍼·에어컨 필터 확인', schedule: '계절 전', memo: '줄무늬, 냄새, 풍량 저하를 확인한다.', completion: '교체 필요 여부 기록' },
      { title: '타이어와 브레이크 점검', schedule: '장거리 전 또는 정비 주기', memo: '마모, 공기압, 소음을 확인한다.', completion: '점검 완료' },
    ],
    memo: '정비소 예약 링크, 소모품 구매 링크, 정비 이력을 메모에 둔다.',
    uxNote: '기간 알림과 주행거리 입력이 함께 필요하다.',
    sourceBoundary: '정비 판단은 차량 설명서와 정비소 기준을 우선한다.',
  },
  {
    id: 'vehicle-inspection-prep',
    title: '자동차 정기검사 준비 체크',
    category: '차량/행정',
    fitScore: 4.0,
    sourceTitle: '차량 정기검사 준비 방법 총정리',
    sourceUrl: 'https://carsize.co.kr/car-regular-inspection-preparation-guide/',
    sourceType: 'creator_blog',
    demandSignal: '검사 기간을 놓치면 과태료가 생기고 사전 점검 항목이 명확하다.',
    sourceSignal: '검사 전 준비, 불합격 항목, 재검사 대응이 체크리스트화 가능하다.',
    userNeed: '검사 만료일 전 사전 점검과 예약을 캘린더에 넣는다.',
    destination: 'hybrid',
    structure: 'timeline',
    cta: '검사 준비로 저장',
    inputs: ['검사 만료일', '차량번호', '검사소 후보'],
    flowItems: [
      { title: '검사 가능 기간 확인', schedule: '만료 30일 전', memo: '자동차 검사 안내문 또는 교통안전공단에서 기간을 확인한다.', completion: '검사 기간 확인' },
      { title: '전구·와이퍼·타이어 사전 점검', schedule: '검사 7일 전', memo: '간단한 불합격 요인을 미리 확인한다.', completion: '사전 점검 완료' },
      { title: '검사 예약/방문', schedule: '검사 주간', memo: '예약 시간, 준비물, 위치를 확인한다.', completion: '검사 완료' },
    ],
    memo: '공식 검사 기간 확인 링크를 메모에 둔다.',
    uxNote: '문자 안내를 Flow로 등록하는 사용 시나리오가 잘 맞는다.',
    sourceBoundary: '검사 기준은 공식 검사 기관 안내를 우선한다.',
  },
  {
    id: 'monthly-budget-close',
    title: '월말 가계부 결산 루틴',
    category: '돈 관리',
    fitScore: 3.9,
    sourceTitle: '월간 가계부 템플릿 가이드',
    sourceUrl: 'https://smart-life.kr/monthly-budget-template-checklist-guide/',
    sourceType: 'creator_blog',
    demandSignal: '월급/지출/저축 목표를 매월 반복 점검하려는 일반 수요가 있다.',
    sourceSignal: '월말 10분 결산, 지출 분류, 저축 목표 체크리스트가 있다.',
    userNeed: '투자 조언이 아니라 매월 지출 분류와 저축 목표 확인만 한다.',
    destination: 'sheet',
    structure: 'table_plan',
    cta: '월말 결산으로 저장',
    inputs: ['월급일', '결산일', '저축 목표 금액'],
    flowItems: [
      { title: '이번 달 고정비 확인', schedule: '월말', memo: '월세/통신/보험/구독을 분류한다.', completion: '고정비 확인' },
      { title: '변동비 합계 보기', schedule: '월말', memo: '식비, 교통, 쇼핑, 여가를 합산한다.', completion: '변동비 합계 기록' },
      { title: '다음 달 저축 자동이체 확인', schedule: '월급일 전후', memo: '금융상품 추천 없이 금액과 자동이체 여부만 확인한다.', completion: '자동이체 확인' },
    ],
    memo: '금융 조언이 아니라 개인 정리표로 제한한다.',
    uxNote: '돈 관리 Flow는 민감하므로 권유/추천보다 체크와 표 export만 제공한다.',
    sourceBoundary: '투자/재무 조언을 하지 않는다.',
  },
  {
    id: 'emergency-fund-account',
    title: '비상금 통장 만들기 체크',
    category: '돈 관리',
    fitScore: 3.8,
    sourceTitle: '비상금 통장 제대로 만드는 법',
    sourceUrl: 'https://world-pkrystal82.com/120?category=1175028',
    sourceType: 'creator_blog',
    demandSignal: '사회초년생/월급 관리 시작점으로 반복 검색되는 주제다.',
    sourceSignal: '월급 받는 즉시 자동이체, 비상금 상황 체크리스트가 있다.',
    userNeed: '월급일에 비상금 이체를 확인하고 목표 달성률만 본다.',
    destination: 'routine',
    structure: 'single_routine',
    cta: '월급날 루틴으로 저장',
    inputs: ['월급일', '목표 비상금', '월 이체액'],
    flowItems: [
      { title: '비상금 자동이체 확인', schedule: '월급일', memo: '월급 입금 후 정해둔 금액이 이체됐는지 확인한다.', completion: '이체 확인' },
      { title: '이번 달 사용 여부 확인', schedule: '월말', memo: '비상금 사용이 있었다면 금액만 메모한다.', completion: '사용/미사용 체크' },
      { title: '목표 달성률 확인', schedule: '매월 말', memo: '목표 금액 대비 현재 금액을 업데이트한다.', completion: '달성률 업데이트' },
    ],
    memo: '상품 추천 없이 목표, 금액, 자동이체만 다룬다.',
    uxNote: '금융 카테고리는 높은 점수라도 P0 대표 후보로는 신중히 둔다.',
    sourceBoundary: '금융상품 추천이나 수익 보장을 하지 않는다.',
  },
  {
    id: 'passport-issue-prep',
    title: '여권 발급 준비물 체크',
    category: '여행/행정',
    fitScore: 4.0,
    sourceTitle: '여권 발급 준비물 총정리',
    sourceUrl: 'https://benefitinfo.policynote.kr/51',
    sourceType: 'creator_blog',
    demandSignal: '발급 전 서류 누락으로 재방문하는 문제가 실제적이다.',
    sourceSignal: '성인/미성년자 구비서류, 사진 규정, 수수료가 체크리스트화된다.',
    userNeed: '여권 신청 방문 전 준비물을 체크하고 공식 안내 링크를 확인한다.',
    destination: 'checklist',
    structure: 'checklist',
    cta: '여권 준비물로 저장',
    inputs: ['신청자 유형', '방문 예정일', '미성년자 여부'],
    flowItems: [
      { title: '사진 규정 확인', schedule: '방문 전', memo: '최근 사진과 규격을 공식 안내 기준으로 확인한다.', completion: '사진 준비 완료' },
      { title: '신분증/서류 준비', schedule: '방문 전', memo: '성인/미성년자 구분에 따라 구비서류를 확인한다.', completion: '서류 준비 완료' },
      { title: '방문 기관과 수수료 확인', schedule: '방문 전날', memo: '운영시간, 수수료, 수령 방법을 확인한다.', completion: '방문 준비 완료' },
    ],
    memo: '공식 외교부 여권 안내 링크를 메모 상단에 둔다.',
    uxNote: '행정 Flow는 체크리스트 + 공식 링크가 핵심이다.',
    sourceBoundary: '최신 규정은 공식 여권 안내 페이지 확인이 필요하다.',
  },
  {
    id: 'dog-adoption-first-week',
    title: '강아지 입양 첫 주 체크',
    category: '반려동물',
    fitScore: 4.0,
    sourceTitle: '강아지 입양 전 완전 가이드',
    sourceUrl: 'https://www.gomin77.co.kr/blog/dog-puppy-pet-adoption',
    sourceType: 'creator_blog',
    demandSignal: '입양 전후 초기비용, 동물등록, 병원 방문이 실제 일정으로 이어진다.',
    sourceSignal: '입양 방법 비교, 동물등록, 예방접종, 초기 비용 체크가 있다.',
    userNeed: '입양일 기준 첫 주 해야 할 일을 정리한다.',
    destination: 'hybrid',
    structure: 'timeline',
    cta: '입양 첫 주로 저장',
    inputs: ['입양일', '동물등록 여부', '첫 병원 예약일'],
    flowItems: [
      { title: '첫 건강검진 예약', schedule: '입양 후 3일 이내', memo: '접종 기록과 현재 상태를 동물병원에 확인한다.', completion: '병원 예약/방문 완료' },
      { title: '동물등록 확인', schedule: '입양 첫 주', memo: '등록 여부와 마이크로칩 정보를 확인한다.', completion: '등록 완료 또는 일정 저장' },
      { title: '초기 준비물 점검', schedule: '입양 전후', memo: '사료, 물그릇, 배변패드, 켄넬, 리드줄을 확인한다.', completion: '준비물 체크 완료' },
    ],
    memo: '건강 판단보다 일정/준비물/공식 등록 링크 중심으로 둔다.',
    uxNote: '입양 Flow는 생활 이벤트와 반려동물 루틴의 연결을 보여준다.',
    sourceBoundary: '건강 문제는 수의사 상담으로 분리한다.',
  },
  {
    id: 'college-dorm-move-in-checklist',
    title: '기숙사 입사 D-Day 준비 체크',
    category: '학생/생활전환',
    fitScore: 4.7,
    sourceTitle: '대구가톨릭대학교 기숙사 입사안내',
    sourceUrl: 'https://dormitory.cu.ac.kr/page_SgCx18',
    sourceType: 'official',
    demandSignal: '기숙사 입사를 앞둔 학생은 입사일, 제출서류, 침구와 생활용품, 반입금지 물품, 입사 당일 절차를 짧은 기간에 한 번에 챙겨야 한다.',
    sourceSignal: '학교 기숙사 안내와 학기별 PDF 공지는 입사일, 결핵검사 등 제출서류, 침구/개인 물품, 반입금지 전열기구, 택배/주소, 시설점검을 학교별로 다르게 안내한다.',
    userNeed: '입사일 전에 최신 기숙사 공지 기준으로 필수 서류, 반입금지 물품, 첫날 물품, 당일 절차를 빠뜨리지 않고 준비한다.',
    destination: 'hybrid',
    structure: 'timeline',
    cta: '입사 준비로 저장',
    inputs: ['기숙사 입사일', '학교/기숙사명', '최근 공지 링크'],
    flowItems: [
      { title: '최신 기숙사 공지 다시 확인', schedule: 'D-14', memo: '학교 기숙사 공지에서 입사일, 제출서류, 반입금지 물품, 택배 주소, 입사 시간 변경 여부를 먼저 확인한다.', completion: '최신 공지와 내 입사 조건이 맞는지 확인' },
      { title: '제출서류 준비 시작', schedule: 'D-10', memo: '학교가 요구한 결핵검사, 건강확인서, 서약서, 신분 확인 서류가 있는지 확인하고 준비 방법과 제출기한을 적는다.', completion: '입사 당일 제출할 서류 목록 정리' },
      { title: '침구와 첫날 생활용품 챙기기', schedule: 'D-7', memo: '매트리스 크기, 침구, 세면도구, 수건, 슬리퍼, 개인 학습도구처럼 첫날 바로 쓰는 물건을 먼저 넣는다.', completion: '첫날 필요한 물품 가방에 넣음' },
      { title: '반입금지 물품 빼기', schedule: 'D-5', memo: '전열기구, 취사도구, 화재위험 물품, 주류처럼 학교별 금지 품목을 짐에서 제외한다.', completion: '금지 품목을 짐에서 제외' },
      { title: '입사 당일 절차와 시설점검 처리', schedule: 'D-Day', memo: '호실 확인, 서류 제출, 카드키 수령, 시설점검표 작성, 금지물품 반입 여부 확인을 입사 현장에서 처리한다.', completion: '입사 당일 접수와 시설점검 완료' },
    ],
    memo: '학교별 최신 공지가 우선이다. FlowMe에는 건강서류 이미지, 납부 계좌, 호실 비밀번호, 학생증/주민번호 같은 민감정보를 저장하지 않는다.',
    uxNote: '이 후보는 결혼/이사와 다른 학생 생활 전환 Flow다. 화면은 D-14 공지 재확인과 D-Day 입사 절차가 바로 보이고, 상세에는 학교별 공지 우선 문구가 붙어야 한다.',
    sourceBoundary: '공식 기숙사 안내와 학기별 PDF를 실행 체크로 정리한 후보다. 학교별 입사 규정, 제출서류, 반입금지 목록은 최신 학교 공지를 우선해야 한다.',
  },
  {
    id: 'elementary-school-entry-d30',
    title: '초등학교 입학 D-30 준비 체크',
    category: '학부모/입학준비',
    fitScore: 4.5,
    sourceTitle: '2026학년도 초등학교 취학통지 및 예비소집 실시',
    sourceUrl: 'https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=294&boardSeq=104634&lev=0&m=020402&opType=N&page=1&s=moe&searchType=null&statusYN=W',
    sourceType: 'official',
    demandSignal: '예비 학부모는 취학통지, 예비소집, 학교 안내문, 기본 물품, 이름 표시, 등교 연습을 입학식 전 순서로 나누고 싶어 한다.',
    sourceSignal: '교육부 공식 안내는 정부24 온라인 취학통지서, 우편·인편 통지, 2025년 12월~2026년 1월 학교별 예비소집을 제시한다. 보조 학부모 체크리스트에는 D-30 준비, 네임스티커, 등교 동선, 입학식 전날 점검 단서가 보인다.',
    userNeed: '입학식 전 한 달 동안 학교 안내를 먼저 확인하고, 먼저 살 것과 학교 안내 전 보류할 것을 분리해 준비한다.',
    destination: 'hybrid',
    structure: 'timeline',
    cta: '입학 준비로 저장',
    inputs: ['입학식 날짜', '학교명', '학교 안내문 확인 여부'],
    flowItems: [
      { title: '취학통지·예비소집 안내 확인', schedule: 'D-30', memo: '정부24 또는 지자체 취학통지, 학교 예비소집 일정, 학교 홈페이지 공지를 확인한다. 주민등록번호나 통지서 이미지는 FlowMe에 저장하지 않는다.', completion: '취학통지와 예비소집 일정 확인' },
      { title: '먼저 살 물건만 정하기', schedule: 'D-21', memo: '책가방, 실내화, 실내화 주머니, 연필, 지우개처럼 학교가 달라도 먼저 준비해도 되는 물건만 고른다.', completion: '먼저 살 물건 목록 확정' },
      { title: '학교 안내 전 보류할 물건 표시', schedule: 'D-14', memo: '공책, 종합장, 미술도구, 색연필/사인펜 종류, 추가 서류처럼 학교·담임 안내에 따라 달라질 수 있는 항목은 구매하지 않고 보류로 둔다.', completion: '보류할 준비물 분리' },
      { title: '네임스티커와 이름 표시하기', schedule: 'D-7', memo: '연필, 지우개, 물통, 실내화, 가방에 이름을 붙이고 학교 안내문에서 개인 물품 표기 방식이 있는지 확인한다.', completion: '주요 물건 이름 표시 완료' },
      { title: '등교 동선과 입학식 가방 점검', schedule: 'D-3~D-1', memo: '집에서 학교까지 가는 길, 횡단보도, 통학 시간, 가방 무게를 아이와 확인하고 입학식 전날 학교에서 요구한 물건만 넣는다.', completion: '등교 동선 연습과 입학식 가방 점검' },
    ],
    memo: '취학 절차와 학교별 준비물은 교육부, 지자체, 학교 안내가 우선이다. FlowMe에는 아동 주민번호, 통지서 이미지, 건강 정보, 지원금 세부 금액, 교실·담임 화면 캡처를 저장하지 않는다.',
    uxNote: '학부모 Flow는 구매 리스트보다 “공식 안내 확인 -> 먼저 살 것만 결정 -> 보류 항목 분리 -> 이름 붙이기 -> 아이와 연습” 순서가 보여야 실제 사용감이 생긴다.',
    sourceBoundary: '공식 취학통지/예비소집 안내를 기준으로 삼고, 블로그 체크리스트는 이름 표시와 등교 동선 같은 보조 실행 단서로만 사용한다. 학교별 준비물, 입학식 시간, 지원금, 예방접종 확인은 최신 학교/교육청/정부 안내를 우선한다.',
  },
  {
    id: 'kids-printable-squishy-craft',
    title: '아이 도안 스퀴시 만들기 준비',
    category: '육아/도안놀이',
    fitScore: 4.3,
    sourceTitle: '겨울 간식꾸러미 스퀴시 도안 만들기',
    sourceUrl: 'https://blog.naver.com/PostView.naver?blogId=makeitdiy&logNo=223260911491',
    sourceType: 'creator_blog',
    demandSignal: '도안 배포형 콘텐츠는 사용자가 저장만 하고 잊기 쉬워 인쇄일, 재료, 놀이 시간을 잡아주는 Flow 가치가 있다.',
    sourceSignal: '제작자 도안/만들기 콘텐츠는 원문 링크, 도안 저장, 인쇄, 재료 준비, 아이와 만들기 순서로 바로 실행 단위가 나뉜다.',
    userNeed: '아이와 만들기 전에 도안을 저장하고 재료를 준비해 주말 놀이 시간에 바로 실행한다.',
    destination: 'checklist',
    structure: 'checklist',
    cta: '주말 놀이로 저장',
    inputs: ['놀이 날짜', '도안 출력 여부', '아이 연령'],
    flowItems: [
      { title: '원문 도안 링크 저장', schedule: '놀이 전', memo: '도안 다운로드/비밀번호/사용 안내를 원문에서 확인하고 링크를 메모에 붙인다.', completion: '도안 링크와 사용 조건 저장' },
      { title: '도안 출력과 코팅/테이프 준비', schedule: '놀이 전날', memo: '프린터, 종이, 투명테이프 또는 손코팅지, 가위처럼 기본 재료를 준비한다.', completion: '출력물과 재료 준비 완료' },
      { title: '자르기 어려운 부분 미리 손질', schedule: '놀이 전날', memo: '아이 연령에 맞춰 위험한 가위질이나 세밀한 자르기는 보호자가 미리 해둔다.', completion: '아이에게 줄 안전한 작업 범위 정리' },
      { title: '아이와 만들고 정리하기', schedule: '놀이 당일', memo: '원문 사진/영상을 보며 만들고, 완성품 사진은 선택 메모로만 남긴다.', completion: '만들기 완료 또는 다음에 이어서 하기 표시' },
    ],
    memo: '교육 효과나 발달 평가는 넣지 않는다. 핵심은 도안 링크, 재료, 놀이 날짜, 안전한 작업 범위다.',
    uxNote: '도안형 콘텐츠는 캘린더보다 체크리스트와 원문 링크 버튼이 중요하다. Flow는 도안 자체를 복제하지 않고 실행 준비만 돕는다.',
    sourceBoundary: '제작자 도안의 사용 조건과 저작권은 원문 안내를 따른다. 칼/가위/작은 부품 사용은 보호자가 아이 연령에 맞게 조정한다.',
  },
  {
    id: 'anydesk-remote-setup-check',
    title: 'AnyDesk 원격 접속 준비 체크',
    category: '디지털/원격지원',
    fitScore: 4.2,
    sourceTitle: 'AnyDesk 사용법 | 다운로드, 설치, 원격 방법',
    sourceUrl: 'https://blog.naver.com/PostView.naver?blogId=haruitelectronics&logNo=223780890597',
    sourceType: 'creator_blog',
    demandSignal: '가족/업무 원격 지원은 상대 확인, 설치, ID 전달, 수동 승인, 보안 종료까지 절차가 짧고 명확하다.',
    sourceSignal: '원문에는 공식 사이트 다운로드, Windows 설치, AnyDesk 주소 확인, 원격 ID 입력, 연결 요청 수락, 파일 전송, 보안 설정, 종료 주의가 보인다. 원격 접속은 설치 전에 내가 요청한 trusted support인지 확인해야 한다.',
    userNeed: '원격 지원 전에 상대와 목적을 확인하고, 양쪽 기기 준비와 보안 종료를 놓치지 않는다.',
    destination: 'checklist',
    structure: 'checklist',
    cta: '원격 지원 체크로 저장',
    inputs: ['지원 예정일', '상대 기기 OS', '지원 방식'],
    flowItems: [
      { title: '누가 먼저 요청한 지원인지 확인', schedule: '지원 전', memo: '내가 먼저 요청한 가족, 업체, 사내 지원인지 확인한다. 모르는 사람이 전화나 메신저로 원격 접속을 요구하면 진행하지 않는다.', completion: '지원 요청자와 목적 확인' },
      { title: '공식 사이트에서 설치 파일 받기', schedule: '지원 전', memo: 'AnyDesk 공식 사이트에서 OS에 맞는 버전을 받고, 로컬/원격 기기 모두 실행 가능한지 확인한다.', completion: '양쪽 기기에 AnyDesk 실행 준비' },
      { title: 'AnyDesk 주소 확인 후 수동 승인으로 진행', schedule: '지원 시작 전', memo: '상대 기기의 9~10자리 ID 또는 별칭을 확인하되, AnyDesk 주소, 비밀번호, 인증값 같은 민감 정보는 Flow에 저장하지 않는다. 일회성 지원은 무인 접속 비밀번호를 만들지 않고 상대 사용자가 연결 요청을 직접 수락한 뒤 필요한 작업만 한다.', completion: '주소 확인, 민감 정보 미저장, 수동 승인 진행' },
      { title: '세션 종료와 보안 설정 확인', schedule: '지원 직후', memo: '세션을 종료하고 자동 접속/비밀번호 설정을 사용했다면 필요한 경우 끄거나 변경한다.', completion: '세션 종료와 보안 확인 완료' },
    ],
    memo: 'AnyDesk 주소, 비밀번호, 인증값 같은 민감 정보를 Flow 입력 필드로 저장하지 않는다. 일회성 지원은 무인 접속 대신 수동 승인을 기본으로 두고, 공식 연결 문서와 원문 사용법 링크만 메모에 둔다.',
    uxNote: '디지털 설정 Flow는 날짜보다 순서형 체크가 핵심이다. 첫 action은 지원 요청자 확인이고, 완료 후 보안 종료 item이 반드시 보여야 한다.',
    sourceBoundary: '개인 블로그 사용법과 AnyDesk 공식 문서를 분리한다. 무단 접속, 자동 접속 비밀번호 저장, 타인 기기 제어는 사용자 동의가 있어야 한다.',
  },
  {
    id: 'remote-help-session-precheck',
    title: '원격 도움 세션 권한 사전 체크',
    category: '디지털/원격지원',
    fitScore: 4.3,
    sourceTitle: 'AnyDesk, TeamViewer, Chrome Remote Desktop, Zoom, Quick Assist official remote-help docs',
    sourceUrl: 'https://support.anydesk.com/docs/connect-to-a-remote-client',
    sourceType: 'official',
    demandSignal: '원격 도움을 받기 전 사용자는 화면만 보여줄지, 일회성 제어를 허용할지, 반복 관리를 맡길지 먼저 결정해야 한다.',
    sourceSignal: 'Official docs from AnyDesk, TeamViewer, Chrome Remote Desktop, Zoom, and Quick Assist separate screen share, one-time remote control, repeated management, manual approval, generated code, and session closeout.',
    userNeed: '원격 도움을 받기 전에 요청자와 목적을 확인하고, 필요한 최소 권한 방식만 고른 뒤 세션 종료와 접근 정리를 놓치지 않는다.',
    destination: 'checklist',
    structure: 'checklist',
    cta: '원격 도움 사전 체크로 저장',
    inputs: ['지원 시간', '도움 요청자와 범위', '지원 방식'],
    flowItems: [
      { title: 'Confirm requested support, trust, and scope', schedule: 'Before support', memo: '내가 먼저 요청한 가족, 업체, 사내/학교 지원인지 확인한다. 모르는 사람이 먼저 연락해 remote help를 요구하면 진행하지 않고 별도 경로로 확인한다.', completion: '요청자, 목적, 작업 범위 확인' },
      { title: 'Choose screen share, one-time remote control, or repeated management', schedule: 'Before opening tool', memo: '보여주기만 필요하면 screen share only를 고른다. 한 번 조작이 필요하면 one-time remote control과 수동 승인을 고른다. 반복 관리는 담당자, 목적, 접근 기간, 해지일을 별도 정책 메모로 남긴다.', completion: '최소 권한 지원 방식 선택' },
      { title: 'Prepare tool without storing access values', schedule: 'Session start', memo: 'AnyDesk 주소, TeamViewer 세션값, Chrome Remote Desktop 확인값, Zoom remote control approval, Quick Assist 확인값은 도구 안에서만 사용하고 FlowMe 입력/메모/내보내기에 저장하지 않는다.', completion: '접속값 미저장 상태로 승인 준비' },
      { title: 'Close session and review access', schedule: 'After support', memo: '공유 또는 원격 제어를 종료하고, clipboard/file transfer/auto accept/unattended access 같은 임시 권한이 남아 있지 않은지 확인한다. 반복 관리는 다음 review access 날짜를 잡는다.', completion: '세션 종료와 접근 정리 완료' },
    ],
    memo: 'FlowMe는 원격 도움 방법 선택, 체크 상태, close/review access 메모만 저장한다. 접속 주소, 비밀번호, 인증값, 세션 URL, 화면 캡처, 상담 대화, 기기 목록은 저장하지 않는다.',
    uxNote: '설치 안내보다 trust/scope 확인과 permission ladder를 먼저 보여준다. AnyDesk 같은 특정 도구는 예시 source일 뿐 destination이 아니다.',
    sourceBoundary: 'Official product facts and practical caution stay separate. This is not 위험 판정, 보안 보장, remote tool integration, device management, password vault, or support ticketing.',
  },
  {
    id: 'naver-search-advisor-site-readiness',
    title: 'Naver Search Advisor 사이트 준비 체크',
    category: '디지털/검색설정',
    fitScore: 4.2,
    sourceTitle: 'Naver Search Advisor official setup, diagnosis, ownership, and report docs',
    sourceUrl: 'https://searchadvisor.naver.com/guide/seo-basic-intro',
    sourceType: 'official',
    demandSignal: 'Korean custom-site owners often launch a small site, shop, or creator page and then need Naver Search Advisor setup without confusing verification, crawl, indexing, and ranking.',
    sourceSignal: 'Naver Search Advisor official docs cover host-unit registration, HTML file and HTML tag ownership verification, robots.txt access, noindex checks, sitemap and RSS submission, diagnosis reports, and waiting for status to update.',
    userNeed: 'Naver Search Advisor를 시작하기 전에 사이트 단위, 접근권한, 소유확인 방법, 수집 준비 상태, 다시 볼 날짜를 정해 검증값을 Flow에 남기지 않는다.',
    destination: 'hybrid',
    structure: 'checklist',
    cta: 'Naver 준비 체크로 저장',
    inputs: ['설정 날짜', '사이트 단위', '접근권한 상태'],
    flowItems: [
      { title: 'Choose site unit and access method', schedule: 'Before setup', memo: 'Naver Search Advisor는 host-unit registration을 기준으로 본다. custom domain, host/CMS, URL unit을 먼저 고르고 DNS, root upload, homepage head edit 중 무엇이 가능한지 확인한다. 어렵다면 ask developer/host admin을 정상 상태로 남긴다.', completion: '사이트 단위와 접근권한 상태 선택' },
      { title: 'Choose ownership method outside Flow', schedule: 'Before verification', memo: 'HTML file 또는 HTML tag ownership verification 중 가능한 방법을 도구 안에서 선택한다. FlowMe에는 method name과 status만 남기고 verification value는 저장하지 않는다.', completion: '소유확인 방법과 진행 상태 기록' },
      { title: 'Check robots.txt and noindex readiness', schedule: 'Before request', memo: 'robots.txt, Yeti 접근, noindex, redirect, frame, live page accessibility를 공식 guide 기준으로 확인한다. 이 단계는 crawl readiness 체크이며 ranking improvement가 아니다.', completion: '수집 준비 차단 요소 확인' },
      { title: 'Record sitemap, RSS, or request status only', schedule: 'After ownership setup', memo: 'sitemap, RSS, URL collection request는 submitted, unavailable, skipped, ask developer/host admin 같은 status로만 남긴다. 생성 파일이나 platform value는 Flow에 저장하지 않는다.', completion: 'sitemap/RSS/request 상태 기록' },
      { title: 'Set revisit date for status review', schedule: 'Revisit date', memo: 'ownership verification, crawl collection, indexing/search reflection, diagnosis report를 나중에 다시 볼 날짜를 정한다. revisit는 status review이지 색인이나 랭킹을 보장한다는 뜻이 아니다.', completion: '다시 볼 날짜와 확인할 report 정리' },
    ],
    memo: 'FlowMe stores only Naver Search Advisor platform, method name, status, source links, and revisit memo. Verification values, DNS values, HTML tag contents, account authorization, platform keys, login secrets, generated sitemap assets, SEO scoring features, ranking trackers, and analytics dashboards stay outside FlowMe.',
    uxNote: '첫 화면은 sitemap 제출이 아니라 사이트 단위와 접근권한 선택이어야 한다. 사용자가 직접 수정할 수 없으면 ask developer/host admin을 정상 경로로 보여준다.',
    sourceBoundary: 'Official Naver setup facts, user technical access, and no-guarantee cautions stay separate. This is not Naver integration, DNS automation, sitemap generation, IndexNow/API automation, SEO scoring, ranking tracking, or analytics reporting.',
  },
  {
    id: 'fridge-cleanout-weekly-plan',
    title: '냉장고 파먹기 7일 재고 소진',
    category: '집밥/식재료',
    fitScore: 4.1,
    sourceTitle: '냉장고 파먹기 챌린지 재고 파악·루틴 체크리스트',
    sourceUrl: 'https://aruma16.tistory.com/126',
    sourceType: 'creator_blog',
    demandSignal: '생활비 절약과 식재료 소진은 사용자가 자주 시도하지만, 실제 실행은 재고 파악과 이번 주 메뉴 결정에서 막힌다.',
    sourceSignal: '원문에는 재고 파악, 식재료 표준화, 주간 메뉴 플래닝, 남은 재료 활용, 성공률 체크리스트가 보인다.',
    userNeed: '이번 주 냉장고 재료를 먼저 쓰도록 7일 식사 후보와 장보기 보류 목록을 만든다.',
    destination: 'sheet',
    structure: 'table_plan',
    cta: '7일 냉파표로 저장',
    inputs: ['시작일', '소진할 재료 3개', '장보기 보류 여부'],
    flowItems: [
      { title: '냉장고 재고 10분 정리', schedule: 'D-Day', memo: '채소, 단백질, 냉동, 소스/양념으로 나눠 빨리 써야 할 재료 3개를 고른다.', completion: '우선 소진 재료 3개 선택' },
      { title: '7일 메뉴 후보 적기', schedule: 'D-Day', memo: '복잡한 식단표가 아니라 재고 재료를 쓰는 점심/저녁 후보만 적는다.', completion: '7일 메뉴 후보 작성' },
      { title: '장보기 보류 목록 만들기', schedule: 'D+1~D+6', memo: '없는 재료를 새로 사기 전, 대체 가능한 재료와 보류 가능한 구매를 메모한다.', completion: '오늘 장보기/보류 결정' },
      { title: '남은 재료 처리일 정하기', schedule: 'D+7', memo: '남은 재료는 냉동, 소분, 다음 주 첫 메뉴 후보 중 하나로 정리한다.', completion: '남은 재료 처리 방향 결정' },
    ],
    memo: '절약 금액 보장이나 식단/영양 관리는 넣지 않는다. 냉장고 재고, 메뉴 후보, 장보기 보류만 다룬다.',
    uxNote: '집밥 Flow는 캘린더보다 작은 시트가 자연스럽다. 사용자가 직접 메뉴명을 바꿀 수 있어야 한다.',
    sourceBoundary: '개인 챌린지/생활비 경험 기반이다. 건강 식단, 영양 처방, 절약 금액 보장은 하지 않는다.',
  },
  {
    id: 'balcony-fall-vegetable-calendar',
    title: '베란다 가을 채소 파종·수확 캘린더',
    category: '베란다텃밭/채소',
    fitScore: 4.3,
    sourceTitle: '베란다 텃밭 가을 채소 10종｜파종·수확 캘린더',
    sourceUrl: 'https://naturegive.tistory.com/1655',
    sourceType: 'creator_blog',
    demandSignal: '상추, 루꼴라, 시금치처럼 집에서 바로 키워보고 싶은 채소가 많고 월별 파종·수확 표가 있다.',
    sourceSignal: '원문은 가을 채소 10종, 준비물, 채소별 파종/수확 시기, 9~12월 체크리스트, 빛·물·통풍 관리를 나눈다.',
    userNeed: '베란다에서 키울 채소 1~3개를 고르고 파종일, 물주기, 첫 수확 후보일을 놓치지 않는다.',
    destination: 'hybrid',
    structure: 'table_plan',
    cta: '텃밭 캘린더로 저장',
    inputs: ['시작 월', '키울 채소', '베란다 방향'],
    flowItems: [
      { title: '화분·상토·씨앗 준비', schedule: '시작 전', memo: '화분 깊이, 배수 구멍, 상토/배양토, 씨앗 또는 종구를 원문 기준으로 확인한다.', completion: '키울 채소와 준비물 확정' },
      { title: '선택한 채소 파종하기', schedule: '파종 주간', memo: '상추는 얕게 파종하고 시금치는 씨앗 불리기처럼 채소별 메모를 상세에 붙인다.', completion: '파종 완료와 물주기 시작' },
      { title: '빛·물·통풍 주간 점검', schedule: '매주', memo: '표토가 마르면 아침에 물을 주고 받침 물, 잎 마름, 과습 신호를 확인한다.', completion: '이번 주 관리 상태 체크' },
      { title: '첫 수확 후보일 확인', schedule: '수확권장 주간', memo: '상추는 잎 6~8매부터 바깥잎 수확, 루꼴라는 10cm 전후 커팅처럼 원문 수확 기준을 본다.', completion: '수확 또는 1주 미루기 결정' },
    ],
    memo: '채소별 상세 재배 팁과 원문 캘린더는 메모에 둔다. Flow 입력은 채소, 시작 월, 베란다 방향 정도로 제한한다.',
    uxNote: '채소별 행이 있는 작은 시트와 파종/수확 후보일 캘린더가 맞다. 매일 관찰 기록 앱처럼 만들면 과하다.',
    sourceBoundary: '지역, 온도, 베란다 방향에 따라 파종/수확 시기는 달라질 수 있다. 결과를 확정하거나 전문 재배 지침처럼 안내하지 않는다.',
  },
  {
    id: 'self-wall-paint-weekend',
    title: '주말 셀프 벽 페인팅 준비',
    category: '집꾸미기/셀프시공',
    fitScore: 4.2,
    sourceTitle: '셀프 페인팅 방법 - 벽 페인트칠 초보 가이드',
    sourceUrl: 'https://tali.kr/self-painting-wall-guide',
    sourceType: 'creator_blog',
    demandSignal: '주말 하루 단위로 방 분위기를 바꾸려는 수요가 있고 준비물과 작업 순서가 분명하다.',
    sourceSignal: '원문은 롤러, 트레이, 붓, 마스킹테이프 같은 준비물과 보양, 모서리 붓칠, 롤러 칠하기, 건조 순서를 설명한다.',
    userNeed: '페인트칠 당일 전에 준비물을 챙기고 작업 순서를 놓치지 않아 주말 작업을 끝낸다.',
    destination: 'checklist',
    structure: 'checklist',
    cta: '주말 작업 체크로 저장',
    inputs: ['작업 날짜', '칠할 공간', '페인트 색상'],
    flowItems: [
      { title: '페인트와 기본 도구 준비', schedule: 'D-3', memo: '페인트, 롤러, 트레이, 붓, 마스킹테이프, 커버링, 작업복을 확인한다.', completion: '준비물 구매/대여 완료' },
      { title: '가구 이동과 바닥 보양', schedule: 'D-1', memo: '칠할 벽 주변 가구를 빼고 바닥과 콘센트, 몰딩, 문틀을 커버링/마스킹한다.', completion: '페인트가 묻지 않을 영역 보호' },
      { title: '모서리와 경계 먼저 칠하기', schedule: '작업 시작', memo: '롤러가 닿지 않는 모서리, 스위치 주변, 천장 경계는 작은 붓으로 먼저 칠한다.', completion: '경계면 1차 칠 완료' },
      { title: '롤러로 넓은 면 칠하고 정리', schedule: '작업 중/후', memo: '넓은 면은 롤러로 채우고 원문 기준 건조 시간을 확인한 뒤 마스킹 제거와 환기를 한다.', completion: '칠하기, 정리, 환기 완료' },
    ],
    memo: '제품별 건조 시간, 페인트 양 계산, 색상 참고 링크는 상세 메모에 둔다. Flow는 작업 순서 체크에 집중한다.',
    uxNote: '캘린더보다는 D-3/D-1/당일 체크리스트가 적합하다. 시공 견적/비용 계산까지 확장하지 않는다.',
    sourceBoundary: '벽 상태, 제품 설명서, 환기/보호장비 기준은 사용 제품 안내를 우선한다.',
  },
  {
    id: 'freelancer-income-tax-docs',
    title: '프리랜서 종합소득세 서류 준비',
    category: '프리랜서/세금준비',
    fitScore: 4.0,
    sourceTitle: '종합소득세 신고 서류 총정리, 개인사업자·프리랜서 필수 체크리스트',
    sourceUrl: 'https://hiseah.tistory.com/283',
    sourceType: 'creator_blog',
    demandSignal: '5월 신고 시즌마다 프리랜서가 소득·경비·증빙 서류를 다시 찾는 반복 수요가 있다.',
    sourceSignal: '원문은 종합소득세 신고 전 준비 서류와 프리랜서/개인사업자별 소득·경비 증빙 확인 흐름을 체크리스트로 정리한다.',
    userNeed: '신고 판단은 세무사/홈택스에서 하되, 신고 전에 흩어진 서류와 증빙 링크를 한곳에 모은다.',
    destination: 'checklist',
    structure: 'checklist',
    cta: '신고 서류 체크로 저장',
    inputs: ['신고 마감일', '소득 유형', '자료 보관 위치'],
    flowItems: [
      { title: '소득 자료 모으기', schedule: '마감 14일 전', memo: '지급명세서, 원천징수 내역, 플랫폼 정산 내역처럼 소득 확인 자료를 모은다.', completion: '소득 자료 위치 메모' },
      { title: '경비 증빙 분류하기', schedule: '마감 10일 전', memo: '사업 관련 카드 사용, 세금계산서, 현금영수증, 구독료, 장비 구매 내역을 폴더별로 나눈다.', completion: '경비 후보 폴더 정리' },
      { title: '홈택스/세무대리인 확인 메모', schedule: '마감 7일 전', memo: '신고 방법, 문의할 항목, 빠진 서류를 홈택스 또는 세무대리인에게 확인할 메모로 남긴다.', completion: '확인 질문 목록 작성' },
      { title: '제출 전 누락 항목 체크', schedule: '마감 2일 전', memo: 'Flow는 제출 전 필요한 자료가 모였는지만 확인하고 금액 판단은 외부 확인으로 남긴다.', completion: '누락/보류 항목 결정' },
    ],
    memo: '세액 산출, 절세 조언, 비용 처리 결론은 Flow가 답하지 않는다. 원문 링크와 홈택스/세무대리인 확인 메모만 남긴다.',
    uxNote: '세무 앱이 아니라 서류 준비 체크리스트로 제한해야 한다. 입력도 마감일, 소득 유형, 자료 위치 정도면 충분하다.',
    sourceBoundary: '세무 판단, 신고 의무, 비용 처리 결론은 국세청/세무 전문가 확인 대상으로 분리한다.',
  },
  {
    id: 'regular-aircon-clean-home',
    title: '벽걸이 에어컨 셀프 청소',
    category: '가전 관리',
    fitScore: 4.0,
    sourceTitle: '에어컨 청소 총정리',
    sourceUrl: 'https://solidtips.tistory.com/entry/aircon-cleaning-filter-smell-mold-self-care-guide',
    sourceType: 'creator_blog',
    demandSignal: '여름 전 반복되는 대중적 수요이고 준비물/순서가 분명하다.',
    sourceSignal: '전원 차단, 필터 분리, 세척, 건조, 송풍 운전 순서가 있다.',
    userNeed: '여름 전후로 셀프 가능한 범위의 에어컨 청소를 캘린더에 넣는다.',
    destination: 'routine',
    structure: 'single_routine',
    cta: '여름 전 청소로 저장',
    inputs: ['청소 예정일', '에어컨 타입', '업체 청소 여부'],
    flowItems: [
      { title: '전원 차단 후 필터 분리', schedule: '청소일', memo: '플러그를 뽑고 필터를 분리한다.', completion: '필터 분리 완료' },
      { title: '필터 세척과 그늘 건조', schedule: '청소일', memo: '물세척 후 완전히 말린다.', completion: '필터 건조 완료' },
      { title: '송풍 모드 운전', schedule: '장착 후', memo: '송풍으로 내부 습기를 줄인다.', completion: '송풍 완료' },
    ],
    memo: '냉각핀/분해 청소는 셀프 가능 범위를 넘어가면 업체 상담으로 둔다.',
    uxNote: '사용자 피드백대로 “청소하라”만 있는 원문보다 주기와 순서가 있는 원문을 우선해야 한다.',
    sourceBoundary: '분해 청소와 전기 안전은 전문가/제조사 기준 우선이다.',
  },
  {
    id: 'first-kimjang-weekend-checklist',
    title: '초보 김장 주말 체크리스트',
    category: '계절음식/집안행사',
    fitScore: 4.2,
    sourceTitle: '김장 김치 담그는 순서(초보 체크리스트)',
    sourceUrl: 'https://today.tomorrowbliss.com/entry/kimjang-how-to-steps-checklist',
    sourceType: 'creator_blog',
    demandSignal: '김장은 매년 특정 계절에 검색되는 집안 행사이고, 초보자는 분량·절임·양념·숙성 순서를 놓치기 쉽다.',
    sourceSignal: '원문은 배추 포기별 분량 산정, 6~12시간 절임, 헹굼/배수, 양념 비율, 버무리기, 숙성·보관 체크리스트를 단계별로 정리한다.',
    userNeed: '김장 전날과 당일에 필요한 순서를 캘린더/체크리스트로 옮겨 가족과 같이 진행한다.',
    destination: 'hybrid',
    structure: 'checklist',
    cta: '김장 체크로 저장',
    inputs: ['김장 날짜', '배추 포기 수', '도움 인원'],
    flowItems: [
      { title: '배추 포기 수와 양념 분량 정하기', schedule: 'D-3', memo: '원문 분량표를 기준으로 배추 수, 고춧가루, 액젓, 무채, 쪽파 등 장보기 수량을 메모한다.', completion: '장보기 수량과 부족 재료 확정' },
      { title: '배추 절임과 뒤집기 알림 만들기', schedule: 'D-1', memo: '6~12시간 절임과 2~3회 뒤집기 시간을 캘린더 알림으로 나눈다.', completion: '절임 시작/뒤집기/헹굼 시간 저장' },
      { title: '헹굼·배수 후 양념 버무리기', schedule: '김장 당일', memo: '헹굼 2~3회와 배수 20~30분 후 줄기부터 양념을 바르는 순서를 상세에 둔다.', completion: '버무리기 완료와 용기 담기' },
      { title: '실온 스타터와 저온 보관 전환', schedule: '김장 후', memo: '실온 6~12시간 후 김치냉장고/저온 보관으로 옮기는 시간을 체크한다.', completion: '보관 위치와 다음 확인일 저장' },
    ],
    memo: '염도/pH 계산기처럼 만들지 않는다. 초보자가 원문 순서를 놓치지 않도록 분량표 링크, 절임 알림, 보관 전환만 가볍게 둔다.',
    uxNote: '김장은 루틴보다 짧은 프로젝트 Flow다. 전날/당일/보관 전환이 한 화면에서 보여야 하고, 상세 비율은 메모에 둔다.',
    sourceBoundary: '발효 결과나 위생 안전을 보장하지 않는다. 보관 온도, 저염 필요, 위생 주의는 원문/공식 식품안전 자료 확인으로 분리한다.',
  },
  {
    id: 'passport-renewal-online-pickup',
    title: '여권 재발급 온라인 신청·수령 준비',
    category: '여행/공식행정',
    fitScore: 4.4,
    sourceTitle: '외교부 여권안내 홈페이지 - 재발급',
    sourceUrl: 'https://www.passport.go.kr/home/kor/contents.do?menuPos=6',
    sourceType: 'official',
    demandSignal: '해외여행 전 여권 만료를 확인한 뒤 신청, 사진, 기존 여권, 방문 수령을 놓치지 않아야 한다.',
    sourceSignal: '외교부는 재발급 사유, 방문/온라인 신청 가능 조건, 18세 미만 온라인 불가, 분실·훼손·정보 변경 방문 신청, 사진·신분증·기존 여권 서류를 안내한다.',
    userNeed: '출국 전 여권 재발급 가능 여부와 수령 준비를 일정으로 저장한다.',
    destination: 'hybrid',
    structure: 'timeline',
    cta: '여권 준비 일정 저장',
    inputs: ['출국 예정일', '여권 만료일', '신청 방식'],
    flowItems: [
      { title: '온라인 신청 가능 조건 확인', schedule: '출국 30일 전', memo: '미성년자, 최초 발급, 분실·훼손, 정보 변경은 방문 신청 대상인지 공식 안내로 확인한다.', completion: '온라인/방문 신청 방식 결정' },
      { title: '6개월 이내 여권 사진 준비', schedule: '신청 전', memo: '여권용 사진 파일 또는 인화 사진을 준비하고 사진 규격은 외교부 안내 링크에서 확인한다.', completion: '사진 준비 완료' },
      { title: '정부24/KB 또는 방문 신청 진행', schedule: '신청일', memo: '온라인 신청은 국내 수령 시 정부24/KB스타뱅킹, 방문 신청은 여권사무 대행기관을 사용한다.', completion: '신청 완료와 접수 번호 메모' },
      { title: '방문 수령 준비', schedule: '수령 예정일', memo: '신분증과 유효기간이 남은 기존 여권을 챙기고, 온라인 신청의 방문 수령 방식/기관 변경 제한을 메모한다.', completion: '방문 수령 완료' },
    ],
    memo: '여권 번호, 주민등록번호, 결제 정보는 Flow에 저장하지 않는다. 공식 신청 링크와 접수 확인 위치만 메모한다.',
    uxNote: '공식행정 Flow는 “내가 대상인지 확인 → 신청 → 수령”만 다룬다. 법적 효력, 긴급 발급 판단은 공식 페이지로 보낸다.',
    sourceBoundary: '외교부/정부24 공식 안내를 우선한다. 국가별 입국 잔여 유효기간, 긴급여권 가능 여부, 수수료 변경은 공식 출처에서 확인해야 한다.',
  },
  {
    id: 'car-inspection-renewal-window',
    title: '자동차 정기·종합검사 예약 준비',
    category: '차량/공식검사',
    fitScore: 4.3,
    sourceTitle: 'TS한국교통안전공단 자동차검사 안내',
    sourceUrl: 'https://main.kotsa.or.kr/portal/contents.do?menuCode=01010104',
    sourceType: 'official',
    demandSignal: '차량 소유자는 주기적으로 검사 기간, 예약, 준비물, 부적합 재검사 기간을 관리해야 한다.',
    sourceSignal: 'TS 안내는 관능검사, ABS검사, 하체검사, 전조등검사, 배출가스검사, 검사결과 설명 흐름과 차종별 유효기간을 제공한다.',
    userNeed: '검사 유효기간 만료 전에 예약하고 검사 당일 준비와 부적합 시 재검사 기한을 놓치지 않는다.',
    destination: 'calendar',
    structure: 'timeline',
    cta: '검사 일정으로 저장',
    inputs: ['검사 만료일', '차종', '검사 지역'],
    flowItems: [
      { title: '검사 대상과 유효기간 확인', schedule: '만료 45일 전', memo: '비사업용 승용차 등 내 차량의 검사 주기와 종합검사 대상 지역 여부를 TS 안내에서 확인한다.', completion: '정기/종합검사 대상 확인' },
      { title: '검사소 예약과 준비물 확인', schedule: '만료 30일 전', memo: '검사소 예약, 자동차등록증 등 준비 항목, 결제 방식을 확인한다.', completion: '예약일과 검사소 저장' },
      { title: '검사 당일 항목 이해하기', schedule: '검사 당일', memo: '관능, ABS, 하체, 전조등, 배출가스, 결과 설명 순서를 메모로 확인한다.', completion: '검사 완료 또는 부적합 사유 확인' },
      { title: '부적합 재검사 기한 체크', schedule: '부적합 시', memo: '부적합 판정 시 재검사 기한과 정비 필요 항목을 공식 결과서 기준으로 기록한다.', completion: '재검사 예약 또는 최종 통과' },
    ],
    memo: '검사 판정이나 정비 견적은 Flow가 판단하지 않는다. 검사 예약 링크, 검사소, 결과서 위치만 저장한다.',
    uxNote: '차량검사는 구매 점검과 달리 공식 마감형 캘린더가 먼저다. 상세에는 검사 항목을 설명 카드로 둔다.',
    sourceBoundary: '검사 대상, 수수료, 재검사 기한은 TS/사이버검사소 공식 안내를 우선한다. 정비 판단은 검사소/정비업체 확인 대상으로 둔다.',
  },
  {
    id: 'beginner-camping-packing-sheet',
    title: '초보 캠핑 준비물 시트',
    category: '캠핑/여가준비',
    fitScore: 4.1,
    sourceTitle: '캠핑 초보 체크리스트 PDF｜처음 준비할 때 필수 항목',
    sourceUrl: 'https://infor-basket3.tistory.com/2029',
    sourceType: 'creator_blog',
    demandSignal: '캠핑은 매번 출발 전 준비물이 반복되지만 계절, 인원, 아이/반려동물 여부에 따라 빠지는 품목이 달라진다.',
    sourceSignal: '원문은 쉘터/취침/조리/식재료/안전·조명·전기/위생/의류/아이·반려동물 품목과 엑셀 체크리스트 열 구조를 제안한다.',
    userNeed: '이번 캠핑 인원과 형태에 맞게 준비물 표를 만들고 출발 전 체크한다.',
    destination: 'sheet',
    structure: 'table_plan',
    cta: '캠핑 준비표로 저장',
    inputs: ['출발일', '인원', '캠핑 형태'],
    flowItems: [
      { title: '기본 장비 행 만들기', schedule: '출발 7일 전', memo: '쉘터/텐트, 취침, 조리, 식재료, 위생 분류를 만들고 보유/대여/구매 상태를 적는다.', completion: '기본 준비물 표 생성' },
      { title: '안전·조명·전기 항목 확인', schedule: '출발 5일 전', memo: '랜턴, 헤드랜턴, 여분 배터리, 멀티탭, 보조배터리, 구급상자, 소화기/경보기 필요 여부를 체크한다.', completion: '안전/전기 항목 체크' },
      { title: '아이·반려동물 추가 품목 고르기', schedule: '출발 3일 전', memo: '동반자에 따라 기저귀, 장난감, 배변봉투, 하네스 등 추가 행만 켠다.', completion: '동반자별 추가 행 정리' },
      { title: '출발 전 체크와 공유', schedule: '출발 전날', memo: '체크박스가 남은 행만 가족/동행자에게 공유하고 당일 차에 실을 품목을 표시한다.', completion: '미체크 품목 0개 또는 담당자 지정' },
    ],
    memo: '캠핑장 예약, 요금, 장비 추천 순위까지 확장하지 않는다. Flow는 준비물 표와 출발 전 체크에 집중한다.',
    uxNote: '캠핑은 캘린더보다 시트가 먼저다. 사용자가 품목 행을 지우고 추가할 수 있어야 한다.',
    sourceBoundary: '화기, 전기, 난로, 일산화탄소 관련 안전은 캠핑장/제품/공식 안전 안내를 우선한다.',
  },
  {
    id: 'free-appliance-pickup-reservation',
    title: '폐가전 무상방문수거 예약 준비',
    category: '정리/방문수거',
    fitScore: 4.2,
    sourceTitle: '폐가전 방문수거 배출예약시스템',
    sourceUrl: 'https://www.15990903.or.kr/portal/reserve/insertFormReserveStep01_1.do',
    sourceType: 'official',
    demandSignal: '이사, 가전 교체, 집 정리 때 사용자가 수거 가능 품목과 예약 당일 준비를 자주 헷갈린다.',
    sourceSignal: '공식 예약 시스템은 배출품목 입력, 기본정보 입력, 본인인증, 예약 확인/완료 단계로 구성되고 지자체 안내는 대형가전 단일 수거와 소형가전 5개 이상 기준을 안내한다.',
    userNeed: '수거 가능한 품목인지 확인하고 예약일 전까지 제품을 수거 가능한 상태로 준비한다.',
    destination: 'checklist',
    structure: 'checklist',
    cta: '방문수거 체크로 저장',
    inputs: ['수거 희망일', '배출 품목', '엘리베이터/통로 여부'],
    flowItems: [
      { title: '수거 가능 품목 확인', schedule: '예약 전', memo: '냉장고, 세탁기, 에어컨 등 단일 수거 품목인지, 소형가전은 5개 이상인지 공식 사이트에서 확인한다.', completion: '수거 가능/불가 결정' },
      { title: '예약 정보 입력', schedule: '예약일', memo: '공식 예약 시스템에서 배출품목, 주소, 희망일, 이사 여부를 입력한다. 개인정보는 Flow에 저장하지 않는다.', completion: '예약 번호 또는 확인 위치 메모' },
      { title: '철거·통로·잉크/토너 준비', schedule: '수거 전날', memo: '벽걸이 TV/에어컨 등 고정 제품은 철거 필요 여부를 확인하고, 프린터는 잉크/토너 유출 방지 상태를 확인한다.', completion: '수거 가능한 상태로 준비' },
      { title: '수거 당일 문전 배출 확인', schedule: '수거 당일', memo: '방문/문전 수거 위치, 엘리베이터/통로 확보, 연락 가능 상태를 확인한다.', completion: '수거 완료 또는 재예약 필요 표시' },
    ],
    memo: '폐가구, 원형 훼손 제품, 설치 미철거 제품 등 수거 불가 여부는 공식 사이트와 지자체 안내를 확인한다.',
    uxNote: '방문수거 Flow는 일정 하나와 전날 체크가 핵심이다. 수거 품목별 조건은 접힌 메모로 둔다.',
    sourceBoundary: '수거 가능 품목, 지역별 수거일, 예약 변경은 공식 1599-0903/E-순환거버넌스 또는 지자체 안내를 우선한다.',
  },
  {
    id: 'piano-carol-sheet-7day-practice',
    title: '아이 피아노 캐롤 악보 7일 연습',
    category: '음악/악보연습',
    fitScore: 4.1,
    sourceTitle: '[무료 악보] Jingle Bells 바이엘 난이도',
    sourceUrl: 'https://blog.naver.com/PostView.nhn?blogId=yeyepiano&logNo=222566652121',
    sourceType: 'creator_blog',
    demandSignal: '무료 악보/PDF 나눔형 콘텐츠는 저장 후 연습 일정으로 이어지기 쉽고 댓글·이웃추가 같은 제작자 상호작용도 보인다.',
    sourceSignal: '원문 검색 결과에는 초반/중반 난이도 PDF 첨부, 아이들이 치기 쉬운 캐롤 악보, 이웃 추가와 댓글 요청 흐름이 보인다.',
    userNeed: '아이 난이도에 맞는 악보를 저장하고 발표 전 1주일 동안 짧게 연습한다.',
    destination: 'hybrid',
    structure: 'timeline',
    cta: '7일 연습으로 저장',
    inputs: ['연주 목표일', '난이도', '연습 시간대'],
    flowItems: [
      { title: '원문 악보 PDF 저장', schedule: 'D-7', memo: '원문에서 초반/중반 난이도 PDF와 사용 조건을 확인하고 악보 링크를 메모에 둔다.', completion: '악보 링크와 난이도 선택 완료' },
      { title: '첫 4마디 천천히 연습', schedule: 'D-6~D-5', memo: '오른손/왼손을 나눠 첫 4마디만 천천히 연습한다.', completion: '첫 4마디를 멈추지 않고 연주' },
      { title: '전체 악보 이어치기', schedule: 'D-3', memo: '틀리는 마디를 표시하고 원문 악보를 보며 전체 흐름을 이어친다.', completion: '전체 1회 이어치기 완료' },
      { title: '연주 전날 녹음 체크', schedule: 'D-1', memo: '휴대폰으로 1회 녹음하고 아이가 어려워하는 마디만 메모한다.', completion: '녹음 1회와 어려운 마디 표시' },
    ],
    memo: '악보 파일 자체를 복제하지 않고 원문 링크, 난이도, 연습 날짜만 둔다. 저작권/배포 조건은 원문을 따른다.',
    uxNote: '악보 콘텐츠는 달력+체크 조합이 맞다. 악보 뷰어를 만들기보다 원문 링크와 하루 연습 항목이 먼저 보여야 한다.',
    sourceBoundary: '제작자 악보의 배포/사용 조건을 따른다. 연주 수준 평가나 교육 효과 보장은 하지 않는다.',
  },
  {
    id: 'cat-adoption-first-week-setup',
    title: '초보 집사 고양이 입양 첫 주 준비',
    category: '반려묘/입양준비',
    fitScore: 4.2,
    sourceTitle: '초보 집사를 위한 고양이 입양 준비 체크리스트',
    sourceUrl: 'https://catinthehat.tistory.com/4',
    sourceType: 'creator_blog',
    demandSignal: '입양 전 준비물과 첫 주 적응은 검색 수요가 꾸준하고, 사용자가 날짜 기준으로 실제 행동을 나눌 수 있다.',
    sourceSignal: '검색 결과상 원문은 초보 집사가 정보가 흩어져 어려웠던 경험과 입양 준비 체크리스트를 제공한다.',
    userNeed: '입양일 전후로 화장실, 사료, 숨숨집, 병원 확인을 빠뜨리지 않는다.',
    destination: 'hybrid',
    structure: 'timeline',
    cta: '입양 첫 주로 저장',
    inputs: ['입양일', '고양이 나이', '첫 병원 후보'],
    flowItems: [
      { title: '화장실·모래·사료 위치 만들기', schedule: 'D-3', memo: '화장실, 모래, 사료/물그릇, 숨을 공간을 먼저 배치한다.', completion: '첫날 생활 공간 준비' },
      { title: '이동장과 첫날 동선 확인', schedule: 'D-1', memo: '이동장, 담요, 안전한 방 하나, 문/창문 잠금 상태를 확인한다.', completion: '첫날 이동과 안전 체크 완료' },
      { title: '첫 병원/건강 기록 메모', schedule: '입양 후 3일 이내', memo: '접종 기록, 중성화 여부, 구충 여부를 병원에 확인할 질문으로 남긴다.', completion: '병원 예약 또는 질문 메모 완료' },
      { title: '첫 주 적응 관찰', schedule: '입양 후 7일', memo: '먹는 양, 화장실 사용, 숨는 시간, 놀이 반응을 짧게 메모한다.', completion: '첫 주 적응 메모 완료' },
    ],
    memo: '건강 판단을 앱에서 하지 않는다. 준비물, 병원 질문, 첫 주 관찰 메모만 둔다.',
    uxNote: '반려동물 Flow는 “입양일 기준 타임라인 + 첫 주 관찰 메모”가 적합하다. 사진/상세 기록은 선택으로 둔다.',
    sourceBoundary: '건강, 접종, 질병 판단은 수의사 확인으로 분리한다. 원문은 개인/블로그 준비 체크리스트다.',
  },
  {
    id: 'jeonse-contract-precheck-docs',
    title: '전세계약 전 서류 10단계 확인',
    category: '주거/계약전점검',
    fitScore: 4.3,
    sourceTitle: '전세 계약할 때 이것 꼭 확인하세요',
    sourceUrl: 'https://contents.kakaopay.com/contents/2056',
    sourceType: 'commerce',
    demandSignal: '전세계약 전 서류 확인은 사용자가 실제 계약일 전에 체크리스트로 들고 가고 싶은 고빈도 생활 이벤트다.',
    sourceSignal: '원문 검색 결과에는 계약 전 시세·등기부등본·보증보험, 계약 시 중개사/표준계약서/정보 일치, 계약 후 확정일자·임대차신고·보증보험 흐름이 보인다.',
    userNeed: '계약일 전날과 당일에 확인해야 할 서류와 공식 링크를 한 장 체크리스트로 정리한다.',
    destination: 'checklist',
    structure: 'checklist',
    cta: '계약 전 체크로 저장',
    inputs: ['계약 예정일', '주소 후보', '보증보험 확인 여부'],
    flowItems: [
      { title: '시세·등기부등본·권리관계 확인', schedule: '계약 3일 전', memo: '주변 시세, 등기부등본의 소유자/근저당/압류, 보증보험 가능 여부를 확인할 공식 링크를 둔다.', completion: '계약 전 확인 항목 표시' },
      { title: '계약 당일 정보 일치 확인', schedule: '계약 당일', memo: '중개사 등록번호, 표준계약서, 주소·면적·보증금·소유자 정보가 맞는지 체크한다.', completion: '계약서 정보 일치 확인' },
      { title: '입주 후 확정일자·임대차신고 저장', schedule: '입주 직후', memo: '확정일자, 전입신고, 임대차신고, 보증보험 가입 여부를 후속 체크로 둔다.', completion: '입주 후 보호 절차 일정 저장' },
      { title: '보류 사유 메모', schedule: '위험 신호 발견 시', memo: '이상 항목이 있으면 계약 진행 판단을 하지 않고 보류 사유와 문의 대상을 메모한다.', completion: '보류 또는 전문가 확인 메모' },
    ],
    memo: 'Flow는 법률 판단을 하지 않고 확인해야 할 문서와 질문만 남긴다. 주민등록번호, 계좌번호, 계약금 영수증 원본은 저장하지 않는다.',
    uxNote: '주거 계약 Flow는 체크리스트가 먼저이고, “보류”가 정상 결과로 보여야 한다. 법률 조언처럼 보이는 점수화는 피한다.',
    sourceBoundary: '카카오페이 콘텐츠와 국토교통부/법무부/등기소 등 공식 자료를 분리해 표시한다. 계약 판단은 공인중개사/전문가 확인 대상이다.',
  },
  {
    id: 'goodnotes-template-study-setup',
    title: '굿노트 무료 속지 공부 세팅',
    category: '디지털필기/템플릿',
    fitScore: 3.9,
    sourceTitle: '[굿노트 속지] 세로 2분할 라인노트 무료공유',
    sourceUrl: 'https://blog.naver.com/PostView.naver?blogId=soil582&logNo=222695091788',
    sourceType: 'creator_blog',
    demandSignal: '굿노트/노타빌리티 무료 속지는 저장만 하고 끝나기 쉬워 실제 필기 세팅과 첫 사용 체크로 이어질 수 있다.',
    sourceSignal: '원문 검색 결과에는 심플/종이질감 PDF, 9종 색상, 굿노트·노트쉘프·노타빌리티 사용, 파일 문제 댓글 요청, 저작권 조건이 보인다.',
    userNeed: '무료 속지를 내려받고 내 필기 앱에 넣어 이번 주 공부 노트로 바로 쓴다.',
    destination: 'checklist',
    structure: 'checklist',
    cta: '필기 세팅으로 저장',
    inputs: ['사용 앱', '속지 색상', '첫 사용일'],
    flowItems: [
      { title: '원문 속지 링크와 사용 조건 확인', schedule: '세팅 전', memo: '심플/종이질감 PDF 중 선택하고 저작권·사용 조건을 원문에서 확인한다.', completion: '속지 링크와 조건 저장' },
      { title: '필기 앱에 PDF 가져오기', schedule: '세팅일', memo: '굿노트, 노트쉘프, 노타빌리티 중 사용하는 앱에 PDF를 가져온다.', completion: '앱에 속지 추가 완료' },
      { title: '과목/프로젝트 표지와 첫 페이지 만들기', schedule: '세팅일', memo: '이번 주 사용할 과목명, 날짜, 목표를 첫 페이지에 적는다.', completion: '첫 페이지 작성 완료' },
      { title: '일주일 뒤 유지/교체 결정', schedule: '첫 사용 7일 후', memo: '필기 폭, 색상, 페이지 복사 편의가 맞는지 보고 계속 쓸지 교체할지 정한다.', completion: '유지/교체 결정' },
    ],
    memo: '속지 파일을 Flow에 복제하지 않는다. 원문 링크, 사용 앱, 첫 사용일만 저장한다.',
    uxNote: '템플릿 콘텐츠는 캘린더보다 체크리스트+메모가 맞다. 실행 UI는 “다운로드 → 가져오기 → 첫 사용 → 유지 결정”이면 충분하다.',
    sourceBoundary: '제작자 파일의 저작권 조건과 재배포 금지를 원문 기준으로 따른다. 앱 사용법은 각 앱 안내를 우선한다.',
  },
  {
    id: 'macaron-template-baking-day',
    title: '마카롱 도안 베이킹 데이 준비',
    category: '베이킹/도안자료',
    fitScore: 4.0,
    sourceTitle: '#마카롱 꼬끄 도안 34 - 오버액션 토끼 마카롱',
    sourceUrl: 'https://blog.naver.com/PostView.naver?blogId=laetus76&logNo=222290368217',
    sourceType: 'creator_blog',
    demandSignal: '도안 PDF 기반 베이킹은 원문 자료 저장, 재료 준비, 도안 출력, 굽는 날 체크가 명확하다.',
    sourceSignal: '원문 검색 결과에는 마카롱 꼬끄 도안 PDF 첨부, 다운로드 시 댓글/좋아요 요청, 저작자 명시·비영리·변경 금지 조건이 보인다.',
    userNeed: '도안 PDF와 재료를 준비해 베이킹 당일에 바로 작업한다.',
    destination: 'hybrid',
    structure: 'timeline',
    cta: '베이킹 데이로 저장',
    inputs: ['베이킹 날짜', '도안 출력 여부', '재료 준비 여부'],
    flowItems: [
      { title: '도안 PDF와 사용 조건 확인', schedule: 'D-5', memo: '원문에서 도안 PDF, 댓글/좋아요 요청, 저작권 조건을 확인하고 링크만 저장한다.', completion: '도안 링크와 사용 조건 확인' },
      { title: '재료와 도구 준비', schedule: 'D-3', memo: '아몬드가루, 슈가파우더, 흰자, 짤주머니, 테프론시트, 오븐 예열 조건을 체크한다.', completion: '재료/도구 준비 완료' },
      { title: '도안 출력과 팬 세팅', schedule: 'D-1', memo: '도안을 출력해 팬 아래에 깔고 꼬끄 크기와 간격을 확인한다.', completion: '도안 출력과 팬 세팅 완료' },
      { title: '굽기 후 결과 메모', schedule: '베이킹 당일', memo: '굽는 시간, 오븐 온도, 퍼짐/삐에 상태를 한 줄 메모한다.', completion: '굽기 완료와 다음 조정 메모' },
    ],
    memo: '레시피 성공 보장이나 정밀 온도 계산은 하지 않는다. 원문 도안 링크와 내 오븐 메모만 남긴다.',
    uxNote: '도안 베이킹은 “자료형 콘텐츠 + 짧은 프로젝트”다. 도안 자체보다 출력/재료/당일 실행 체크가 중요하다.',
    sourceBoundary: '제작자 도안의 저작권 조건을 따른다. 식품 위생, 알레르기, 오븐 안전은 사용자/공식 안전 기준을 따른다.',
  },
];

export const koreanFlowContentCategories = Array.from(
  new Set(koreanFlowContentCandidates.map((candidate) => candidate.category)),
);
