import type { FlowBundle } from './types';
import type { NaturalArtifactSimulation } from './source-fit';

export type NaturalArtifactAuditDecision =
  | 'promote_to_manual_source_fit'
  | 'reshape_content_or_ux'
  | 'keep_catalog_review'
  | 'replace_or_hide_source';

export type RealSourceNaturalArtifactAudit = {
  slug: string;
  checkedAt: string;
  sourceTitle: string;
  sourceUrl: string;
  sourceEvidence: string[];
  userScenario: string;
  naturalArtifacts: NaturalArtifactSimulation[];
  currentContentGap: string;
  currentUxGap: string;
  nextContentAction: string;
  nextUxAction: string;
  decision: NaturalArtifactAuditDecision;
};

type DecisionCounts = Record<NaturalArtifactAuditDecision, number>;

export type NaturalArtifactAuditCoverageSummary = {
  realSourceCount: number;
  auditedRealSourceCount: number;
  remainingRealSourceCount: number;
  auditedCategoryCounts: Record<string, number>;
  decisionCounts: DecisionCounts;
};

const emptyDecisionCounts: DecisionCounts = {
  promote_to_manual_source_fit: 0,
  reshape_content_or_ux: 0,
  keep_catalog_review: 0,
  replace_or_hide_source: 0,
};

export const realSourceNaturalArtifactAudits: RealSourceNaturalArtifactAudit[] = [
  {
    slug: 'real-samsung-aircon-seasonal-care',
    checkedAt: '2026-05-22',
    sourceTitle: '삼성전자서비스 에어컨 세척 서비스 안내',
    sourceUrl: 'https://www.samsungsvc.co.kr/info/maintenance',
    sourceEvidence: [
      '공식 페이지가 에어컨 세척/유지보수의 필요, 서비스 범위, 세척 과정, 전문 세척 신청 연락처를 제공한다.',
      '세척은 예약과 방문 준비가 필요한 서비스라 사용자가 일정표와 예약 메모를 따로 만들 가능성이 높다.',
    ],
    userScenario: '사용자는 여름 전 에어컨 냄새와 냉방 약화를 보고 공식 세척 서비스를 예약할지 판단한다.',
    naturalArtifacts: [
      {
        kind: 'monthly_calendar',
        artifactTitle: '여름 전 에어컨 세척 예약 달력',
        simulatedInputs: ['사용시작일=2026-06-15', '실내기=거실 1대/안방 1대', '희망방문=2026-06-01~2026-06-08'],
        expectedOutput: [
          '2026-05-25 모델명/설치 위치 확인',
          '2026-05-27 필터 오염과 냄새 사진 기록',
          '2026-05-28 세척 범위와 비용 문의',
          '2026-06-03 방문 예약',
          '2026-06-03 세척 후 냉방/누수 확인',
        ],
        currentFlowMatch: '현재 Flow 항목은 모델, 오염, 비용, 예약, 사후 확인을 모두 포함한다.',
        currentUxSupport: 'timeline 입력과 월별 달력은 맞지만 예약 후보 날짜 여러 개를 비교하는 UI는 약하다.',
        gap: '서비스 예약 후보와 현장 연락처 메모가 export preview에 더 명확히 보여야 한다.',
      },
      {
        kind: 'memo',
        artifactTitle: '세척 상담 메모',
        simulatedInputs: ['모델=AF18...', '증상=냄새/약한 냉방', '예산상한=20만원', '문의번호=1588-4190'],
        expectedOutput: ['모델명, 설치 위치, 증상 사진, 문의한 서비스 범위, 비용, 방문 가능 시간, 상담 결과'],
        currentFlowMatch: '항목별 메모로 대부분 기록할 수 있다.',
        currentUxSupport: '일반 메모는 가능하지만 상담 메모 전용 필드로 보이지 않는다.',
        gap: '서비스형 Flow에는 상담/예약 메모 템플릿이 필요하다.',
      },
    ],
    currentContentGap: '콘텐츠 구조는 좋지만 서비스 예약 메모와 비용 문의 결과가 별도 산출물로 분리되어 있지 않다.',
    currentUxGap: '달력은 보이지만 예약 후보 비교와 상담 메모 preview가 약하다.',
    nextContentAction: '에어컨 세척 Flow를 manual source-fit 후보로 승격하고 상담 메모 기준을 추가한다.',
    nextUxAction: '서비스 예약형 Flow에 예약 후보/상담 메모 export preview를 붙인다.',
    decision: 'promote_to_manual_source_fit',
  },
  {
    slug: 'real-samsung-washer-filter-care',
    checkedAt: '2026-05-22',
    sourceTitle: '삼성전자서비스 세탁기 배수필터 청소 안내',
    sourceUrl: 'https://www.samsungsvc.co.kr/solution/1978102',
    sourceEvidence: [
      '공식 페이지가 배수필터 주 1회 이상 청소, 잔수 제거, 재조립/잠김 확인, 누수 주의를 안내한다.',
      '반복 관리 루틴과 안전 체크가 핵심이라 캘린더 반복과 짧은 체크리스트가 자연스럽다.',
    ],
    userScenario: '사용자는 세탁기 5C 점검 문자를 본 뒤 매주 배수필터 청소를 반복 루틴으로 만들고 싶다.',
    naturalArtifacts: [
      {
        kind: 'routine_calendar',
        artifactTitle: '주 1회 배수필터 청소 달력',
        simulatedInputs: ['시작일=2026-06-06', '반복=매주 토요일 오전', '제품=비스포크 AI 콤보', '주의=잔수 제거'],
        expectedOutput: ['매주 토요일 배수필터 청소', '잔수 제거', '필터/내부 청소', '재조립과 잠김 확인', '누수 확인'],
        currentFlowMatch: '루틴 항목은 공식 절차와 잘 맞는다.',
        currentUxSupport: '반복 루틴 preview는 가능하지만 주 1회 권장 근거가 첫 화면에서 더 보여야 한다.',
        gap: '반복 주기와 안전 주의가 달력 카드에 함께 표시되어야 한다.',
      },
      {
        kind: 'checklist',
        artifactTitle: '청소 당일 안전 체크리스트',
        simulatedInputs: ['청소일=2026-06-06', '준비물=낮은 용기/수건/장갑', '상태=5C 표시'],
        expectedOutput: ['전원 끄기', '잔수 제거 용기 준비', '필터 분리', '솔로 청소', '오른쪽으로 재조립', '잠김/누수 확인'],
        currentFlowMatch: '청소 전 준비와 청소 후 확인이 포함되어 있다.',
        currentUxSupport: '체크리스트 UI는 맞지만 사진/증상 메모가 보조로만 존재한다.',
        gap: '고장 코드, 누수 여부, 다음 청소일이 export에 들어가야 한다.',
      },
    ],
    currentContentGap: '주 1회 반복 근거와 잠김/누수 확인이 대표 메타로 더 강조되어야 한다.',
    currentUxGap: '반복 달력과 안전 체크가 분리되어 보여야 사용자가 루틴을 이해하기 쉽다.',
    nextContentAction: '공식 주기와 안전 주의를 item meta로 승격한다.',
    nextUxAction: 'routine Flow의 반복 주기/주의 배지를 월간 달력 preview에 포함한다.',
    decision: 'promote_to_manual_source_fit',
  },
  {
    slug: 'real-qnet-application-examday-check',
    checkedAt: '2026-05-22',
    sourceTitle: 'Q-Net 원서접수시 유의사항',
    sourceUrl: 'https://www.q-net.or.kr/rcv002.do?gSite=L&id=rcv002_identi',
    sourceEvidence: [
      '공식 페이지가 인정 신분증 요건, 원본/사진/주민등록번호/성명/발급자 기준, 인정되지 않는 예시를 안내한다.',
      '시험 접수와 시험 당일 준비는 마감과 준비물 누락 리스크가 있어 일정+체크리스트 산출물이 자연스럽다.',
    ],
    userScenario: '사용자는 자격증 원서접수 후 시험 전날 신분증과 준비물을 빠뜨리지 않으려 한다.',
    naturalArtifacts: [
      {
        kind: 'monthly_calendar',
        artifactTitle: 'Q-Net 접수부터 시험당일 일정표',
        simulatedInputs: ['시험일=2026-07-12', '접수마감=2026-06-10 18:00', '종목=정보처리기사', '시험장=서울동부'],
        expectedOutput: ['6/9 접수 마감 전 확인', '6/10 결제/접수 상태 저장', '7/11 신분증/수험표 준비', '7/12 입실 시간 맞춰 출발'],
        currentFlowMatch: '접수 전, 접수 완료, 시험 당일 흐름은 맞다.',
        currentUxSupport: '시험일 anchor는 맞지만 접수 마감 같은 별도 deadline 입력은 부족하다.',
        gap: '시험일 외 접수 마감/수험표 출력일 같은 보조 날짜를 입력할 수 있어야 한다.',
      },
      {
        kind: 'spreadsheet',
        artifactTitle: '시험 준비물 확인표',
        simulatedInputs: ['신분증=운전면허증 원본', '수험표=PDF 저장', '계산기=허용기종 확인', '입실=09:00'],
        expectedOutput: ['항목, 공식 기준, 내 준비물, 확인일, 보관 위치, 미해결 여부 열'],
        currentFlowMatch: '준비물 항목은 있으나 공식 기준과 내 준비물을 나란히 보는 표는 없다.',
        currentUxSupport: '일반 체크리스트로는 가능하지만 신분증 인정 기준 같은 긴 공식 기준을 보존하기 어렵다.',
        gap: '공식 기준/내 준비물 비교형 export가 필요하다.',
      },
    ],
    currentContentGap: '접수 마감, 수험표, 신분증 기준처럼 시험 전 단계별 deadline이 더 구조화되어야 한다.',
    currentUxGap: '시험일 하나만으로는 접수/출력/준비물 날짜가 충분히 표현되지 않는다.',
    nextContentAction: 'Q-Net Flow를 시험일+접수마감 다중 deadline Flow로 보강한다.',
    nextUxAction: 'timeline Flow에 보조 deadline 입력과 공식 기준 대비표 export를 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-gov24-moving-report-check',
    checkedAt: '2026-05-22',
    sourceTitle: '정부24 전입신고 민원안내',
    sourceUrl: 'https://www.gov.kr/mw/AA020InfoCappView.do?CappBizCD=13100000016&tp_seq=01',
    sourceEvidence: [
      '점검 시점에는 정부24 URL이 서비스 일시중단 안내로 리다이렉트되어 실제 민원 안내 본문을 확인하지 못했다.',
      '전입신고는 이사 후 신고 준비, 온라인 가능 여부, 처리 결과 보관이 핵심이라는 기존 Flow 구조는 유지 가치가 있다.',
    ],
    userScenario: '사용자는 이사 후 전입신고를 정부24에서 처리하고 완료 캡처와 후속 확인을 남기려 한다.',
    naturalArtifacts: [
      {
        kind: 'checklist',
        artifactTitle: '전입신고 실행 체크리스트',
        simulatedInputs: ['이사일=2026-06-27', '신고자=세대주 본인', '인증수단=공동인증서', '주택유형=전세'],
        expectedOutput: ['신고 기한 확인', '온라인 신청 가능 여부 확인', '주소/세대 정보 입력', '처리 완료 캡처', '확정일자/주소 변경 후속 확인'],
        currentFlowMatch: '신고 전 확인과 신고 후 확인 구조는 맞다.',
        currentUxSupport: '날짜 없는 체크리스트로 되어 있어 이사일 기준 신고 기한을 시각화하기 어렵다.',
        gap: 'anchor_type none보다 선택적 이사일 입력과 마감 표시가 적합하다.',
      },
      {
        kind: 'memo',
        artifactTitle: '신고 완료 증빙 메모',
        simulatedInputs: ['처리일=2026-06-28', '접수번호=예시-1234', '결과=처리완료', '후속=주소 변경'],
        expectedOutput: ['접수번호, 처리상태, 캡처 위치, 후속 처리 목록, 문제 발생 시 문의처'],
        currentFlowMatch: '메모로 기록할 수는 있지만 증빙 메모가 별도 산출물로 드러나지 않는다.',
        currentUxSupport: '체크와 메모는 가능하지만 완료 증빙 중심 UX는 약하다.',
        gap: '행정 Flow에는 접수번호/처리상태/증빙 캡처 위치 필드가 필요하다.',
      },
    ],
    currentContentGap: '현재 source 확인이 일시적으로 불완전하므로 실제 정부24 본문 재확인이 필요하다.',
    currentUxGap: '행정 신고형 Flow에는 선택 날짜와 증빙 메모가 필요하다.',
    nextContentAction: '정부24 페이지 정상 접근 시 민원 조건과 처리 기한을 재확인한다.',
    nextUxAction: 'checklist Flow에 선택적 deadline과 증빙 메모 패턴을 추가한다.',
    decision: 'keep_catalog_review',
  },
  {
    slug: 'real-childcare-vaccination-visit-prep',
    checkedAt: '2026-05-22',
    sourceTitle: '아이사랑 월령별 성장 및 돌보기',
    sourceUrl: 'https://www.childcare.go.kr/?menuno=439',
    sourceEvidence: [
      '아이사랑 페이지는 4~6개월 건강검진, 생후 4개월 예방접종, 증상/외출 준비 등 월령별 돌봄 정보를 제공한다.',
      '검진/접종은 의료진 판단이 우선인 민감 영역이므로 방문 준비 메모와 공식 주의 분리가 핵심이다.',
    ],
    userScenario: '보호자는 4개월 접종/검진 예약 전 최근 증상과 준비물을 정리해 병원에서 빠뜨리지 않으려 한다.',
    naturalArtifacts: [
      {
        kind: 'monthly_calendar',
        artifactTitle: '4개월 접종/검진 방문 준비 달력',
        simulatedInputs: ['방문일=2026-06-12', '아기월령=4개월', '방문유형=예방접종+검진', '보호자=엄마'],
        expectedOutput: ['6/9 문진표/예약 확인', '6/11 체온/수유/수면 기록 준비', '6/12 아기수첩 지참', '6/13 접종 후 반응 관찰'],
        currentFlowMatch: '방문 전후 흐름은 맞지만 방문 후 관찰이 더 중요하게 보여야 한다.',
        currentUxSupport: 'timeline은 맞지만 의료 주의와 기록 입력이 일반 메모에 묻힌다.',
        gap: '방문 후 반응 기록과 의료진 상담 우선 문구가 별도 산출물이어야 한다.',
      },
      {
        kind: 'memo',
        artifactTitle: '의료진에게 보여줄 증상 메모',
        simulatedInputs: ['최근증상=기침 없음/수유량 감소', '체온=36.8', '수면=밤중 2회 깸', '질문=이유식 시작 시점'],
        expectedOutput: ['체온, 수유, 수면, 최근 증상, 보호자 질문, 의료진 답변, 다음 방문일'],
        currentFlowMatch: '증상 기록 항목은 있으나 질문/답변 구조는 약하다.',
        currentUxSupport: '메모 입력은 가능하지만 병원 방문 기록장처럼 보이지 않는다.',
        gap: '민감 의료 방문형 Flow에는 질문/답변/다음 방문일 메모가 필요하다.',
      },
    ],
    currentContentGap: '방문 후 관찰과 의료진 답변 기록이 현재 항목에서 덜 강조된다.',
    currentUxGap: '의료 민감 기록은 일반 메모보다 구조화된 방문 기록으로 보여야 한다.',
    nextContentAction: '검진/접종 Flow에 방문 후 관찰과 의료진 답변 항목을 보강한다.',
    nextUxAction: '의료/육아 Flow에 방문 기록 메모 템플릿과 주의 배너를 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-pet-registration-check',
    checkedAt: '2026-05-22',
    sourceTitle: '국가동물보호정보시스템 동물등록제도 안내',
    sourceUrl: 'https://www.animal.go.kr/front/community/show.do?boardId=contents&menuNo=2000000016&seq=+66',
    sourceEvidence: [
      '공식 페이지는 등록대상동물 기준, 내장형/외장형 등록방법, 동반 방문, 대행기관/지자체 확인, 대리 신청 서류를 안내한다.',
      '사용자는 등록 대상 확인과 방문 준비물, 등록번호 보관 메모를 만들 가능성이 높다.',
    ],
    userScenario: '사용자는 3개월 강아지를 입양한 뒤 동물등록 대상 여부와 방문 준비를 확인한다.',
    naturalArtifacts: [
      {
        kind: 'checklist',
        artifactTitle: '반려동물 등록 방문 준비표',
        simulatedInputs: ['동물=강아지', '월령=3개월', '거주=아파트', '등록방식=내장형 희망'],
        expectedOutput: ['등록 대상 여부 확인', '대행기관 찾기', '반려동물 동반 방문', '소유자 신분/연락처 준비', '등록번호 보관'],
        currentFlowMatch: '등록 대상, 방식, 기관, 소유자 정보, 등록번호 보관이 모두 포함되어 있다.',
        currentUxSupport: '날짜 없는 체크리스트로는 적합하지만 기관 후보와 문의 결과 기록이 약하다.',
        gap: '대행기관 후보/전화 문의 결과를 저장하는 비교 또는 메모가 필요하다.',
      },
      {
        kind: 'memo',
        artifactTitle: '등록번호 보관 메모',
        simulatedInputs: ['등록번호=410000000000000', '기관=OO동물병원', '변경신고=주소/연락처 변경 시', '보관위치=사진앨범/메모앱'],
        expectedOutput: ['등록번호, 기관명, 등록방식, 소유자 연락처, 변경신고 조건, 보관 위치'],
        currentFlowMatch: '등록번호 보관 항목은 맞다.',
        currentUxSupport: '메모는 가능하지만 장기 보관 정보로 강조되지 않는다.',
        gap: '등록 완료 후 반복 조회할 핵심 정보 카드가 필요하다.',
      },
    ],
    currentContentGap: '대행기관 선택과 등록 후 장기 보관 정보가 더 구조화되어야 한다.',
    currentUxGap: '체크리스트는 맞지만 기관 후보/등록번호 보관 카드가 약하다.',
    nextContentAction: '등록기관 후보와 등록번호 보관 기준을 item detail에 추가한다.',
    nextUxAction: '행정/등록형 checklist에 장기 보관 메모 preview를 추가한다.',
    decision: 'promote_to_manual_source_fit',
  },
  {
    slug: 'real-ohouse-moving-d30-prep',
    checkedAt: '2026-05-22',
    sourceTitle: '오늘의집 원룸 이사 준비 순서 가이드',
    sourceUrl: 'https://ohou.se/advices/12199',
    sourceEvidence: [
      '원문은 원룸 이사를 이사 2주 전, 전날, 당일, 이사 후 7일 이내로 나누고 업체 예약, 이전 신청, 하자 사진, 공과금, 전입신고를 안내한다.',
      '금전/보증금 리스크가 있어 일정, 증빙 메모, 업체/비용 비교표가 함께 필요하다.',
    ],
    userScenario: '1인 가구 사용자가 6월 말 원룸 이사를 앞두고 업체 예약, 공과금, 전입신고, 하자 사진을 놓치지 않으려 한다.',
    naturalArtifacts: [
      {
        kind: 'monthly_calendar',
        artifactTitle: '원룸 이사 2주 준비 달력',
        simulatedInputs: ['이사일=2026-06-27', '집유형=원룸 전세', '이사방식=용달+기사 도움', '보증금=1,000만원'],
        expectedOutput: ['6/13 업체 예약/이전 신청', '6/26 냉장고/귀중품/서류 분리', '6/27 하자 사진/공과금/잔금', '7/4 전입신고/주소변경 확인'],
        currentFlowMatch: 'Flow 항목은 원문 단계와 잘 맞는다.',
        currentUxSupport: 'timeline 달력은 맞지만 보증금/정산 증빙 산출물이 부족하다.',
        gap: '금전 리스크가 있는 이사 Flow는 증빙 사진/정산 메모가 중심에 와야 한다.',
      },
      {
        kind: 'comparison_table',
        artifactTitle: '이사 업체 후보 비교표',
        simulatedInputs: ['후보A=용달 18만원', '후보B=반포장 32만원', '조건=엘리베이터/사다리차 없음', '우선순위=가격/시간'],
        expectedOutput: ['업체, 견적, 포함 서비스, 예약 가능 시간, 추가비, 연락처, 결정 상태 열'],
        currentFlowMatch: '업체 예약 항목은 있으나 후보 비교표는 없다.',
        currentUxSupport: '현재 UX는 후보 비교보다 체크리스트 중심이다.',
        gap: '이사/구매/서비스 예약 Flow에는 간단한 후보 비교표가 필요하다.',
      },
    ],
    currentContentGap: '정산/하자/보증금 증빙과 업체 비교가 항목 수준에서 더 분리되어야 한다.',
    currentUxGap: 'financial_sensitive Flow인데 비교표와 증빙 메모 preview가 약하다.',
    nextContentAction: '오늘의집 이사 Flow를 후보 비교+증빙 메모 중심으로 보강한다.',
    nextUxAction: '금전 리스크가 있는 timeline Flow에 비교표와 증빙 메모 export를 연결한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-kdca-travel-health-check',
    checkedAt: '2026-05-22',
    sourceTitle: '질병관리청 해외여행 전 건강정보',
    sourceUrl: 'https://www.kdca.go.kr/menu.es?mid=a20102060200',
    sourceEvidence: [
      '질병관리청 페이지는 국가별 위험요인 확인, 예방접종/예방약/구급약 준비, 필요 시 의사 상담을 안내한다.',
      '예방접종은 여행 직전이 아니라 여유 있게 준비해야 하므로 출국일 기준 건강 준비 달력이 자연스럽다.',
    ],
    userScenario: '사용자는 7월 해외여행 전 국가별 감염병 위험과 예방접종 상담 여부를 확인하려 한다.',
    naturalArtifacts: [
      {
        kind: 'monthly_calendar',
        artifactTitle: '해외여행 건강 준비 달력',
        simulatedInputs: ['출국일=2026-07-20', '국가=베트남', '기저질환=없음', '상담희망=여행의학 클리닉'],
        expectedOutput: ['5/25 국가별 위험 확인', '6/1 예방접종/예방약 상담', '7/13 복용약/구급약 준비', '7/20 출국 전 위생수칙 확인'],
        currentFlowMatch: '감염병 확인, 상담, 약 준비, 위생수칙 항목은 맞다.',
        currentUxSupport: 'timeline은 맞지만 국가 입력과 공식 확인일 기록이 별도 필드가 아니다.',
        gap: '여행 건강 Flow에는 국가/확인일/공식 링크 메모가 필요하다.',
      },
      {
        kind: 'memo',
        artifactTitle: '국가별 감염병 확인 메모',
        simulatedInputs: ['국가=베트남', '확인일=2026-06-01', '확인항목=예방접종/말라리아/모기 회피', '상담=필요'],
        expectedOutput: ['국가, 확인일, 감염병 위험, 예방접종/예방약 상담 필요, 의료진 답변, 재확인일'],
        currentFlowMatch: '주의와 확인 항목은 있으나 국가별 기록 표면은 약하다.',
        currentUxSupport: '의료 민감 정보가 일반 메모로만 남는다.',
        gap: '공식 확인 메모와 의료진 상담 결과를 구조화해야 한다.',
      },
    ],
    currentContentGap: '국가별 확인 결과와 상담 결과 기록이 더 중심이 되어야 한다.',
    currentUxGap: '민감 여행건강 Flow인데 공식 확인일/상담 결과/재확인일 UX가 부족하다.',
    nextContentAction: '국가별 공식 확인과 상담 결과 기록 항목을 보강한다.',
    nextUxAction: 'medical_sensitive timeline에 공식 확인 메모와 재확인일 필드를 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-thankyou-bubu-video-full-body-no-jump',
    checkedAt: '2026-05-22',
    sourceTitle: 'ThankyouBUBU 전신 다이어트 최고의 운동',
    sourceUrl: 'https://www.youtube.com/watch?v=pcyrlkHXAdE',
    sourceEvidence: [
      '영상 제목이 점프, 눕는 동작, 반복, 토크가 없는 전신 다이어트 운동임을 직접 드러내며 저충격 단회 운동 루틴에 가깝다.',
      '사용자는 영상을 본 뒤 운동 동작 자체를 다시 열람하기보다 정해진 요일에 1회 실행하고 완료 여부와 몸 상태를 기록할 가능성이 높다.',
    ],
    userScenario: '사용자는 퇴근 후 층간소음 없이 할 20분 전신 운동을 찾고, 월수금 저녁 반복 일정과 운동 후 피로도를 기록하려 한다.',
    naturalArtifacts: [
      {
        kind: 'routine_calendar',
        artifactTitle: '월수금 전신 운동 반복 캘린더',
        simulatedInputs: ['시작일=2026-06-01', '반복=월/수/금 20:30', '기간=4주', '장소=거실', '강도=중간'],
        expectedOutput: [
          '6/1, 6/3, 6/5, 6/8... 각 날짜에 전신 다이어트 1회 등록',
          '각 회차에 준비운동, 본운동, 마무리 스트레칭 체크',
          '완료 후 피로도 1~5와 무릎/허리 불편 여부 기록',
        ],
        currentFlowMatch: '현재 Flow는 routine/start_date 구조와 운동 항목 체크는 맞지만 요일 반복과 4주 달력 반영이 약하다.',
        currentUxSupport: '루틴 preview는 있으나 사용자가 월수금 같은 반복 요일을 지정해 월간 캘린더로 보는 화면이 부족하다.',
        gap: '운동 영상형 Flow는 반복 요일, 기간, 회차별 기록이 한 화면에서 캘린더로 보여야 한다.',
      },
      {
        kind: 'memo',
        artifactTitle: '운동 후 몸 상태 기록',
        simulatedInputs: ['회차=1회차', '운동시간=18분', '피로도=4', '통증=없음', '메모=점프 없이 가능'],
        expectedOutput: ['회차, 실제 소요시간, 피로도, 통증 여부, 다음 회차 조정 메모'],
        currentFlowMatch: '일반 메모는 가능하지만 운동 기록 전용 필드는 없다.',
        currentUxSupport: '체크 완료 후 기록을 남기는 affordance가 약해 사용자가 완료만 누르고 떠날 가능성이 있다.',
        gap: '운동 루틴에는 완료 체크 뒤 짧은 기록 입력이 자연스럽게 이어져야 한다.',
      },
    ],
    currentContentGap: '동작명보다 반복 일정과 실행 후 몸 상태 기록이 핵심인데 현재 콘텐츠는 todo 목록 중심이다.',
    currentUxGap: '반복 요일을 캘린더에 박아 보여주는 월간 루틴 화면이 부족하다.',
    nextContentAction: '전신 운동 Flow를 회차 단위 루틴+기록형으로 재구성한다.',
    nextUxAction: 'routine Flow에 요일 선택, 월간 반복 캘린더, 회차별 상태 기록 preview를 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-thankyou-bubu-video-daily-stretch-9min',
    checkedAt: '2026-05-22',
    sourceTitle: 'ThankyouBUBU 하루 9분 전신 스트레칭 BEST',
    sourceUrl: 'https://www.youtube.com/watch?v=aob4Lh1Vebk',
    sourceEvidence: [
      '영상 제목이 하루 9분 전신 스트레칭과 운동 전후 활용 맥락을 제시하므로 짧은 반복 루틴으로 전환하기 쉽다.',
      '스트레칭은 한 번 보고 끝나는 정보보다 아침, 운동 전, 운동 후 같은 반복 트리거와 더 잘 맞는다.',
    ],
    userScenario: '사용자는 아침마다 9분 스트레칭을 해보고 싶지만 매일 하는 것은 부담스러워 평일 아침 반복과 주말 휴식을 설정하려 한다.',
    naturalArtifacts: [
      {
        kind: 'routine_calendar',
        artifactTitle: '평일 아침 9분 스트레칭 루틴 캘린더',
        simulatedInputs: ['시작일=2026-06-02', '반복=평일 07:40', '휴식=토/일', '소요시간=9분'],
        expectedOutput: [
          '월~금 오전 7:40에 스트레칭 일정 생성',
          '각 회차에 목/어깨, 허리, 하체 이완 체크',
          '주말은 자동 휴식일로 표시',
        ],
        currentFlowMatch: 'routine 구조는 맞지만 짧은 루틴의 반복 요일과 휴식일이 콘텐츠에 드러나지 않는다.',
        currentUxSupport: '현재 UX는 루틴 시작일 위주라 평일만 반복 같은 자연 입력을 충분히 지원하지 않는다.',
        gap: '짧은 루틴 Flow에는 반복 빈도와 제외 요일이 필수 입력이어야 한다.',
      },
      {
        kind: 'todo_list',
        artifactTitle: '운동 전후 스트레칭 체크리스트',
        simulatedInputs: ['사용맥락=러닝 전후', '러닝요일=화/목/토', '목표=부상 예방'],
        expectedOutput: ['러닝 전 9분 스트레칭', '러닝 후 하체 이완', '통증 부위 메모', '다음 운동 강도 조정'],
        currentFlowMatch: '동작 체크리스트로는 변환 가능하지만 운동 전후라는 트리거가 약하다.',
        currentUxSupport: '루틴과 다른 Flow 일정의 연결이 없어 러닝일에 붙여 쓰기 어렵다.',
        gap: '루틴 Flow는 단독 반복뿐 아니라 다른 일정 전후에 붙는 트리거형 반복도 고려해야 한다.',
      },
    ],
    currentContentGap: '현재 항목은 스트레칭 실행 자체에 머물고 반복 트리거, 휴식일, 운동 전후 용도를 분리하지 않는다.',
    currentUxGap: '짧은 반복 루틴을 한눈에 월간으로 확인하는 화면이 없다.',
    nextContentAction: '스트레칭 Flow를 매일형/운동전후형 두 사용 시나리오로 분리한다.',
    nextUxAction: 'routine 설정에 반복 요일, 제외 요일, 연결 트리거를 넣는다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-thankyou-bubu-video-belly-side-all-in-one',
    checkedAt: '2026-05-22',
    sourceTitle: 'ThankyouBUBU NO관절부담 뱃살 옆구리살 빼는 운동',
    sourceUrl: 'https://www.youtube.com/watch?v=toAUho9bEw0',
    sourceEvidence: [
      '자동화 환경에서 YouTube 원문 fetch는 throttled 되었지만, seed metadata와 검색 결과가 ThankyouBUBU exact video 제목을 뱃살/옆구리살, 관절부담 낮은 운동으로 확인한다.',
      '이 영상형 원본은 긴 체크리스트보다 반복할 요일, 강도, 허리/복부 체감 기록을 남기는 루틴 캘린더가 자연 산출물이다.',
    ],
    userScenario: '사용자는 관절 부담이 낮은 복부/옆구리 운동 영상을 4주 동안 주 3회 반복하고 허리둘레와 운동 후 컨디션을 기록하려 한다.',
    naturalArtifacts: [
      {
        kind: 'routine_calendar',
        artifactTitle: '뱃살/옆구리 주 3회 반복 캘린더',
        simulatedInputs: ['시작일=2026-06-01', '반복=월/수/금 20:30', '기간=4주', '강도=초보'],
        expectedOutput: [
          '매주 월/수/금 운동 일정',
          '각 일정에 영상 링크와 준비 메모',
          '운동 후 복부/허리 부담 체크',
          '4주 종료일에 유지/변경 판단',
        ],
        currentFlowMatch: 'exact-video Flow는 영상 실행 action을 잘 좁히지만 목표 부위별 반복 계획과 종료 리뷰가 약하다.',
        currentUxSupport: '월간 반복 미리보기는 가능하지만 부위별 몸상태 로그가 export preview에 분리되지 않는다.',
        gap: '부위 집중 홈트 영상은 캘린더와 몸상태 메모가 함께 보여야 한다.',
      },
      {
        kind: 'memo',
        artifactTitle: '복부/옆구리 운동 후 컨디션 메모',
        simulatedInputs: ['허리둘레=78cm', '운동후=허리 통증 없음', '복부자극=중간', '다음강도=유지'],
        expectedOutput: ['운동일, 허리둘레, 통증 여부, 복부/옆구리 자극, 난이도, 다음 회차 조절 메모'],
        currentFlowMatch: '일반 item 메모는 가능하지만 운동 후 기록 템플릿으로 보이지 않는다.',
        currentUxSupport: '메모가 캘린더 회차와 연결되지 않는다.',
        gap: '운동 회차별 컨디션 메모가 캘린더 occurrence에 붙어야 한다.',
      },
    ],
    currentContentGap: '현재 콘텐츠는 영상 실행 1개 action에 가깝고 4주 반복/측정 기준은 부족하다.',
    currentUxGap: '반복 일정은 보이나 목표 부위 기록과 회차별 컨디션 저장이 약하다.',
    nextContentAction: '복부/옆구리 exact-video Flow에 반복 기간, 측정 기준, 통증 중단 기준을 추가한다.',
    nextUxAction: 'routine calendar occurrence마다 컨디션 메모와 측정값을 붙이는 로그 UX를 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-thankyou-bubu-video-no-knee-cardio-strength',
    checkedAt: '2026-05-22',
    sourceTitle: 'ThankyouBUBU NO무릎부담 전신유산소 근력 다이어트',
    sourceUrl: 'https://www.youtube.com/watch?v=hesjApxDlj0',
    sourceEvidence: [
      '검색 결과가 영상 제목을 NO무릎부담 전신유산소 근력 다이어트, 칼소폭 올인원으로 확인하며, 관련 태그는 홈트/유산소/전신유산소/무릎유산소/노점프 운동 맥락을 보여준다.',
      '무릎부담 낮춤이 핵심인 영상은 단순 완료 체크보다 무릎 상태, 강도 조절, 노점프 유지 여부를 기록하는 안전 메모가 필요하다.',
    ],
    userScenario: '사용자는 무릎 부담이 적은 전신 유산소+근력 운동을 주 4회 반복하되, 무릎 통증이 생기면 강도를 낮추려 한다.',
    naturalArtifacts: [
      {
        kind: 'routine_calendar',
        artifactTitle: '무릎부담 낮춘 전신운동 주 4회 캘린더',
        simulatedInputs: ['시작일=2026-06-02', '반복=화/목/토/일 19:30', '무릎상태=계단 내려갈 때 불편', '강도=절반부터'],
        expectedOutput: [
          '화/목/토/일 운동 일정',
          '첫 주는 절반 강도 표시',
          '무릎 통증 있으면 중단/대체 메모',
          '2주차부터 유지 또는 횟수 조정',
        ],
        currentFlowMatch: '영상 실행 action은 맞지만 무릎 상태 기반 강도 조절이 콘텐츠에 충분히 반영되지 않는다.',
        currentUxSupport: '반복 캘린더는 가능하나 통증 기준에 따른 skip/대체 운동 표시가 없다.',
        gap: '무릎부담 낮춘 운동 Flow는 안전 체크와 반복 일정이 결합되어야 한다.',
      },
      {
        kind: 'memo',
        artifactTitle: '무릎 상태와 강도 조절 메모',
        simulatedInputs: ['운동후통증=2/10', '숨참=보통', '땀=많음', '다음회차=동일강도'],
        expectedOutput: ['회차, 운동 전 무릎상태, 운동 후 통증 점수, 숨참 정도, 다음 회차 강도, 중단 여부'],
        currentFlowMatch: '현재 메모는 가능하지만 안전 중심 필드가 없다.',
        currentUxSupport: '통증 점수나 강도 변경이 다음 반복 일정에 반영되지 않는다.',
        gap: '건강 민감 루틴에는 회차별 안전 피드백이 다음 일정을 조정해야 한다.',
      },
    ],
    currentContentGap: '무릎 부담이라는 핵심 조건이 실행 세부 기준과 완료 기준에 충분히 구조화되어 있지 않다.',
    currentUxGap: '반복 일정과 안전 피드백이 분리되어 있어 사용자가 다음 회차 강도를 조절하기 어렵다.',
    nextContentAction: '무릎부담 Flow에 운동 전 상태 확인, 절반 강도 시작, 통증 중단 기준을 추가한다.',
    nextUxAction: 'routine Flow에 회차별 안전 점수와 다음 회차 강도 조절 필드를 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-thankyou-bubu-video-arm-back-shoulder',
    checkedAt: '2026-05-22',
    sourceTitle: 'ThankyouBUBU 팔뚝살 등살 가슴 어깨 운동',
    sourceUrl: 'https://www.youtube.com/watch?v=73IrtWDDby0',
    sourceEvidence: [
      'seed metadata가 이 exact video를 팔뚝살, 등살, 가슴, 어깨를 겨냥한 ThankyouBUBU 다이어트 운동으로 분류한다.',
      '상체 부위 집중 운동은 사용자가 운동 요일뿐 아니라 팔둘레, 어깨/등 자극, 자세 불편을 기록하는 측정표를 만들 가능성이 높다.',
    ],
    userScenario: '사용자는 팔뚝과 등/어깨 라인을 관리하기 위해 주 3회 상체 홈트를 반복하고 팔둘레와 어깨 통증 여부를 주간으로 기록하려 한다.',
    naturalArtifacts: [
      {
        kind: 'routine_calendar',
        artifactTitle: '상체 라인 홈트 반복 캘린더',
        simulatedInputs: ['시작일=2026-06-03', '반복=월/수/토 21:00', '부위=팔뚝/등/어깨', '장비=맨몸'],
        expectedOutput: [
          '월/수/토 상체 운동 일정',
          '각 회차에 영상 링크',
          '운동 전 어깨 불편 여부 확인',
          '주 1회 팔둘레 측정 일정',
        ],
        currentFlowMatch: '현재 exact-video 구조는 영상 실행에 집중되어 있어 부위별 측정과 자세 체크가 부족하다.',
        currentUxSupport: '반복 일정은 가능하지만 측정일과 운동일을 함께 보여주는 로그 구조가 약하다.',
        gap: '상체 집중 Flow는 운동 반복과 주간 측정표가 결합되어야 한다.',
      },
      {
        kind: 'spreadsheet',
        artifactTitle: '팔둘레/어깨 컨디션 주간 기록표',
        simulatedInputs: ['팔둘레=29cm', '측정=매주 월요일 아침', '어깨통증=없음', '자극부위=삼두/등'],
        expectedOutput: ['주차, 팔둘레, 어깨 통증, 등/팔 자극, 운동 횟수, 다음 주 조절 메모'],
        currentFlowMatch: '체크 완료만으로는 팔둘레나 자극 부위 변화를 볼 수 없다.',
        currentUxSupport: 'spreadsheet export는 있지만 exact-video 루틴 로그와 연결되지 않는다.',
        gap: '목표 부위 운동은 체크보다 주간 변화 기록이 중요하다.',
      },
    ],
    currentContentGap: '상체 부위별 관리 기준과 측정 주기가 콘텐츠에 없다.',
    currentUxGap: '운동 캘린더와 주간 측정 로그가 하나의 산출물로 연결되지 않는다.',
    nextContentAction: '팔뚝/등/어깨 Flow에 주간 측정과 어깨 통증 중단 기준을 추가한다.',
    nextUxAction: 'routine calendar에 주간 측정 occurrence와 spreadsheet 로그를 연결한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-thankyou-bubu-video-waist-8cm',
    checkedAt: '2026-05-22',
    sourceTitle: 'ThankyouBUBU 허리둘레 줄어드는 운동',
    sourceUrl: 'https://www.youtube.com/watch?v=k3MznPQvUEk',
    sourceEvidence: [
      'seed metadata가 이 exact video를 허리둘레와 뱃살/옆구리살에 초점을 둔 ThankyouBUBU 운동으로 분류한다.',
      '수치 목표가 제목에 있는 영상은 사용자가 무리하게 결과를 기대할 수 있으므로 반복 일정과 측정 로그, 건강상태 중단 기준을 분리해야 한다.',
    ],
    userScenario: '사용자는 허리둘레를 줄이고 싶지만 과장된 결과를 그대로 기대하지 않고, 6주 동안 운동 횟수와 허리둘레 변화를 기록하려 한다.',
    naturalArtifacts: [
      {
        kind: 'routine_calendar',
        artifactTitle: '허리둘레 관리 6주 운동 캘린더',
        simulatedInputs: ['시작일=2026-06-01', '반복=월/수/금/일 20:00', '기간=6주', '목표=꾸준히 20회 실행'],
        expectedOutput: [
          '6주간 주 4회 운동 일정',
          '매주 월요일 허리둘레 측정 일정',
          '허리 통증 또는 어지러움 시 중단 메모',
          '6주 후 실행 횟수와 측정값 리뷰',
        ],
        currentFlowMatch: '영상 실행은 가능하지만 수치 목표를 안전하게 재해석한 장기 실행 계획이 없다.',
        currentUxSupport: '월간 반복은 보이나 6주 측정 로그와 결과 기대치 안내가 부족하다.',
        gap: '수치형 다이어트 영상은 안전한 기대치 문구와 측정 로그가 필수다.',
      },
      {
        kind: 'spreadsheet',
        artifactTitle: '허리둘레 주간 측정표',
        simulatedInputs: ['초기허리=78cm', '측정주기=매주 월요일', '운동횟수목표=주4회', '식사메모=야식 줄이기'],
        expectedOutput: ['주차, 허리둘레, 운동 실행 횟수, 컨디션, 식사 메모, 다음 주 조절'],
        currentFlowMatch: '현재 Flow는 체크 중심이라 허리둘레 변화와 운동 횟수를 함께 보지 못한다.',
        currentUxSupport: '엑셀 export는 가능하지만 측정 로그 시트가 자동 생성되지 않는다.',
        gap: '허리둘레 Flow는 체크리스트보다 주간 측정표가 핵심 산출물이다.',
      },
    ],
    currentContentGap: '허리둘레 수치 목표를 사용자의 안전한 실행 목표와 측정 기준으로 바꾸는 콘텐츠가 부족하다.',
    currentUxGap: '반복 캘린더와 spreadsheet형 측정 로그가 연결되지 않는다.',
    nextContentAction: '허리둘레 Flow에 6주 실행 계획, 측정 주기, 결과 기대치 주의 문구를 추가한다.',
    nextUxAction: 'routine Flow export에 반복 캘린더와 주간 측정표를 함께 생성한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-thankyou-bubu-video-8min-cardio',
    checkedAt: '2026-05-22',
    sourceTitle: 'ThankyouBUBU 8분 전신유산소 다이어트',
    sourceUrl: 'https://www.youtube.com/watch?v=O87gkL1cKSc',
    sourceEvidence: [
      '검색 결과가 ThankyouBUBU 채널의 8분 완벽한 전신유산소 다이어트 영상 제목과 약 8분 길이의 칼소폭 맥락을 확인한다.',
      '짧은 전신 유산소 영상은 사용자가 빈 시간에 반복할 요일과 운동 후 숨참/피로도를 기록하는 간단 루틴으로 전환하기 좋다.',
    ],
    userScenario: '사용자는 긴 운동은 부담스러워 8분 전신 유산소를 평일 저녁에 반복하고 피로도에 따라 다음 주 횟수를 조절하려 한다.',
    naturalArtifacts: [
      {
        kind: 'routine_calendar',
        artifactTitle: '8분 전신유산소 평일 루틴 캘린더',
        simulatedInputs: ['시작일=2026-06-02', '반복=월/화/목/금 21:30', '소요시간=8분', '강도=중간'],
        expectedOutput: [
          '평일 4회 8분 운동 일정',
          '운동 전 물/매트 준비 메모',
          '운동 후 숨참과 피로도 기록',
          '다음 주 횟수 유지/감소 결정',
        ],
        currentFlowMatch: 'exact-video Flow는 한 번 실행을 잘 안내하지만 반복 빈도와 강도 조절 기준이 약하다.',
        currentUxSupport: '캘린더 반복은 보이나 피로도 로그가 다음 주 일정에 반영되지 않는다.',
        gap: '짧은 유산소 Flow는 실행률과 피로도 로그가 함께 필요하다.',
      },
      {
        kind: 'memo',
        artifactTitle: '유산소 피로도 기록 메모',
        simulatedInputs: ['숨참=7/10', '피로도=6/10', '무릎통증=없음', '다음주=주4회 유지'],
        expectedOutput: ['회차, 숨참, 피로도, 통증 여부, 완료 여부, 다음 주 반복 횟수 조절'],
        currentFlowMatch: '메모는 가능하지만 유산소 intensity log로 구조화되어 있지 않다.',
        currentUxSupport: '회차별 메모가 월별 캘린더에서 바로 보이지 않는다.',
        gap: '운동 강도 조절을 위한 짧은 회차 로그가 필요하다.',
      },
    ],
    currentContentGap: '영상 제목의 8분/전신유산소 특성이 반복 빈도와 강도 조절 기준으로 변환되지 않았다.',
    currentUxGap: '캘린더 반복과 피로도 로그가 연결되지 않는다.',
    nextContentAction: '8분 전신유산소 Flow에 추천 반복 빈도, 피로도 기준, 횟수 조절 기준을 추가한다.',
    nextUxAction: 'routine calendar에 회차별 intensity memo와 다음 주 반복 조정 액션을 붙인다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-thankyou-bubu-video-3min-arm',
    checkedAt: '2026-05-22',
    sourceTitle: 'ThankyouBUBU 3분 최고의 팔뚝살빼는운동',
    sourceUrl: 'https://www.youtube.com/watch?v=Kl9Dmx86Z0Q',
    sourceEvidence: [
      '검색 결과가 3분 최고의 팔뚝살빼는운동 제목과 팔뚝/상체/등살/어깨라인을 포함하는 부담 낮은 루틴 설명을 확인한다.',
      '3분 영상은 별도 긴 운동계획보다 출근 전, 점심, 자기 전 같은 생활 트리거에 붙이는 micro-routine 산출물과 잘 맞는다.',
    ],
    userScenario: '사용자는 팔뚝 운동을 매일 길게 하기보다 점심 후 3분씩 반복하고 주말에는 쉬는 간단한 micro-routine으로 만들려 한다.',
    naturalArtifacts: [
      {
        kind: 'routine_calendar',
        artifactTitle: '3분 팔뚝 micro-routine 캘린더',
        simulatedInputs: ['시작일=2026-06-01', '반복=월~금 12:50', '트리거=점심 후', '휴식=토/일'],
        expectedOutput: [
          '평일 점심 후 3분 팔뚝 운동 일정',
          '주말 자동 휴식 표시',
          '팔/어깨 불편 시 skip 메모',
          '2주 후 지속 여부 리뷰',
        ],
        currentFlowMatch: '현재 Flow는 영상 실행 action 중심이라 생활 트리거 기반 micro-routine으로 보이지 않는다.',
        currentUxSupport: '캘린더 반복은 가능하지만 트리거와 휴식일을 명확히 관리하지 못한다.',
        gap: '짧은 영상 Flow에는 시간보다 생활 트리거 입력이 중요하다.',
      },
      {
        kind: 'memo',
        artifactTitle: '팔/어깨 부담 체크 메모',
        simulatedInputs: ['어깨통증=없음', '팔자극=중간', '횟수=5회 완료', '다음주=유지'],
        expectedOutput: ['주간 완료 횟수, 어깨 통증, 팔 자극, 루틴 유지 여부, 시간대 조정'],
        currentFlowMatch: '완료 체크는 가능하지만 주간 완료 횟수와 통증 메모가 분리되어 있지 않다.',
        currentUxSupport: '주간 summary가 없어서 작은 루틴의 지속 여부를 판단하기 어렵다.',
        gap: 'micro-routine은 주간 완료 횟수 요약이 필요하다.',
      },
    ],
    currentContentGap: '3분이라는 장점이 생활 트리거형 루틴으로 변환되지 않았다.',
    currentUxGap: '캘린더와 주간 로그가 있어야 짧은 루틴의 반복 가치가 보인다.',
    nextContentAction: '3분 팔뚝 Flow를 점심 후/자기 전 같은 트리거 기반 반복 옵션으로 재구성한다.',
    nextUxAction: 'routine Flow에 micro-routine 트리거와 주간 완료 요약을 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-thankyou-bubu-video-3min-abs',
    checkedAt: '2026-05-22',
    sourceTitle: 'ThankyouBUBU 3분 최고의 복근운동',
    sourceUrl: 'https://www.youtube.com/watch?v=6IUL8-nGetA',
    sourceEvidence: [
      '검색 결과가 ThankyouBUBU 채널의 3분 최고의 복근운동 exact video 제목을 확인한다.',
      '복근 micro-routine은 매일 반복 욕구가 크지만 허리 부담과 회복일을 확인해야 하므로 주기와 상태 메모가 중요하다.',
    ],
    userScenario: '사용자는 3분 복근 운동을 격일로 반복하면서 허리 부담이 있으면 쉬고, 주간 완료 횟수를 보고 다음 주 계획을 조절하려 한다.',
    naturalArtifacts: [
      {
        kind: 'routine_calendar',
        artifactTitle: '3분 복근 격일 루틴 캘린더',
        simulatedInputs: ['시작일=2026-06-01', '반복=월/수/금/일', '회복=화/목/토', '허리주의=있음'],
        expectedOutput: [
          '월/수/금/일 3분 복근 운동 일정',
          '화/목/토 회복일 표시',
          '허리 통증 시 중단 체크',
          '주간 완료 횟수 요약',
        ],
        currentFlowMatch: '현재 exact-video action은 간단하지만 격일 반복과 회복일 개념이 부족하다.',
        currentUxSupport: '캘린더는 일정만 보여주고 회복일이나 허리주의 상태를 따로 표시하지 않는다.',
        gap: '복근 루틴은 운동일과 회복일이 함께 보여야 한다.',
      },
      {
        kind: 'memo',
        artifactTitle: '복근/허리 컨디션 메모',
        simulatedInputs: ['복부자극=강함', '허리부담=1/10', '완료횟수=4회', '다음주=동일'],
        expectedOutput: ['주차, 완료 횟수, 복부 자극, 허리 부담, 회복일 준수 여부, 다음 주 조절'],
        currentFlowMatch: '일반 메모는 가능하지만 허리 부담과 회복일 준수를 묶어 보여주지 않는다.',
        currentUxSupport: '로그가 다음 주 캘린더 조정으로 이어지지 않는다.',
        gap: '복근 micro-routine은 안전 메모와 다음 주 반복 계획이 연결되어야 한다.',
      },
    ],
    currentContentGap: '복근운동의 반복 주기와 허리부담 중단 기준이 콘텐츠에 없다.',
    currentUxGap: '캘린더가 운동일만 보여주고 회복일/로그를 함께 처리하지 못한다.',
    nextContentAction: '3분 복근 Flow에 격일/회복일 기본값과 허리 부담 중단 기준을 추가한다.',
    nextUxAction: 'routine calendar에 회복일 표시와 주간 완료/컨디션 summary를 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-thankyou-bubu-video-lower-belly-8min',
    checkedAt: '2026-05-22',
    sourceTitle: 'ThankyouBUBU 8분 아랫뱃살 똥배 운동',
    sourceUrl: 'https://www.youtube.com/watch?v=9xxCFu21CLM',
    sourceEvidence: [
      '검색 결과가 8분 아랫뱃살/똥배 운동 exact video 제목과 약 9분대 길이를 확인한다.',
      '아랫배 집중 영상은 사용자가 운동일, 허리/복부 부담, 허리둘레 또는 복부 사진 메모를 주간으로 관리할 가능성이 높다.',
    ],
    userScenario: '사용자는 아랫뱃살 운동을 5주 동안 주 3회 반복하고, 매주 아침 허리둘레와 복부 컨디션을 기록하려 한다.',
    naturalArtifacts: [
      {
        kind: 'routine_calendar',
        artifactTitle: '아랫뱃살 5주 루틴 캘린더',
        simulatedInputs: ['시작일=2026-06-03', '반복=수/금/일 20:30', '기간=5주', '측정=매주 수요일 아침'],
        expectedOutput: [
          '5주간 주 3회 운동 일정',
          '매주 수요일 허리둘레/복부 상태 측정 일정',
          '허리 부담 시 중단 메모',
          '5주 후 실행 횟수와 측정값 리뷰',
        ],
        currentFlowMatch: '현재 Flow는 영상 실행은 가능하지만 5주 단위 측정 루틴이 없다.',
        currentUxSupport: '반복 캘린더와 측정 로그가 한 export로 묶이지 않는다.',
        gap: '부위 집중 다이어트 Flow는 반복 일정과 주간 측정이 결합되어야 한다.',
      },
      {
        kind: 'spreadsheet',
        artifactTitle: '아랫배 운동 주간 측정표',
        simulatedInputs: ['초기허리=80cm', '복부사진=선택', '운동횟수목표=주3회', '식사메모=저녁간식 줄이기'],
        expectedOutput: ['주차, 허리둘레, 운동 완료 횟수, 복부 컨디션, 식사 메모, 다음 주 조절'],
        currentFlowMatch: '체크 완료만으로는 주간 변화와 실행 횟수를 비교하기 어렵다.',
        currentUxSupport: '엑셀 export에 목표 부위 측정표가 없다.',
        gap: '아랫배 Flow는 수치/사진 여부를 사용자가 선택하는 측정 로그가 필요하다.',
      },
    ],
    currentContentGap: '부위 집중 영상의 반복 기간, 측정 주기, 안전 기준이 콘텐츠로 드러나지 않는다.',
    currentUxGap: '캘린더와 측정 로그가 분리되어 있어 사용자가 관리 산출물을 따로 만들어야 한다.',
    nextContentAction: '아랫뱃살 Flow에 5주 반복 계획과 선택형 측정 로그를 추가한다.',
    nextUxAction: 'routine Flow export에 목표 부위별 측정 시트를 생성한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-fitvely-video-body-fat-6kg-method',
    checkedAt: '2026-05-22',
    sourceTitle: 'FITVELY 체지방 6kg 감량 비법',
    sourceUrl: 'https://www.youtube.com/watch?v=EQcoKqDO8Ds',
    sourceEvidence: [
      '체지방 감량 방법 콘텐츠는 단일 체크리스트보다 식단, 운동, 체중/체지방 기록이 반복되는 추적형 산출물과 잘 맞는다.',
      '사용자는 영상의 원칙을 자기 식사와 운동 루틴에 적용하며 매일 기록하고 주간으로 조정할 가능성이 높다.',
    ],
    userScenario: '사용자는 4주간 체지방을 줄이기 위해 식단 원칙과 운동 여부를 기록하고, 매주 체중과 허리둘레 변화를 확인하려 한다.',
    naturalArtifacts: [
      {
        kind: 'spreadsheet',
        artifactTitle: '4주 체지방 감량 기록표',
        simulatedInputs: ['시작일=2026-06-01', '목표=체지방 -2kg', '측정=월요일 아침', '운동=주4회', '식단=단백질 우선'],
        expectedOutput: [
          '날짜, 체중, 허리둘레, 운동 여부, 식단 준수, 수면, 메모 컬럼',
          '주간 평균과 지난주 대비 변화량',
          '2주 연속 정체 시 식단/운동 조정 메모',
        ],
        currentFlowMatch: '현재 routine 구조는 반복 체크는 가능하지만 체중/둘레/식단 같은 수치 기록이 약하다.',
        currentUxSupport: '체크리스트 UI는 있으나 표 형태 기록과 주간 요약 preview가 부족하다.',
        gap: '다이어트 콘텐츠는 체크보다 로그와 주간 리포트가 핵심 산출물이다.',
      },
      {
        kind: 'routine_calendar',
        artifactTitle: '운동+식단 반복 실행 캘린더',
        simulatedInputs: ['반복=월/화/목/토 운동', '식단체크=매일 저녁', '리셋=매주 일요일'],
        expectedOutput: ['운동일 일정', '매일 식단 체크 알림', '일요일 주간 측정/리뷰 일정'],
        currentFlowMatch: '운동/식단 항목이 있으나 서로 다른 반복 주기를 한 Flow 안에서 조합하는 모델이 부족하다.',
        currentUxSupport: '한 Flow 안에 여러 반복 패턴을 캘린더로 미리보기 어렵다.',
        gap: '다이어트 Flow는 여러 루틴이 같은 달력에 겹쳐 보여야 한다.',
      },
    ],
    currentContentGap: '체지방 감량 콘텐츠는 원칙 적용과 기록이 핵심인데 현재 항목은 실행 체크 중심이다.',
    currentUxGap: '식단/운동/측정처럼 서로 다른 반복 주기를 한 달력에서 조합하지 못한다.',
    nextContentAction: '다이어트 Flow를 로그형 spreadsheet와 루틴형 calendar를 함께 가진 구조로 바꾼다.',
    nextUxAction: 'routine Flow에 복수 반복 규칙과 주간 기록표 preview를 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-fitvely-video-carb-reason',
    checkedAt: '2026-05-22',
    sourceTitle: 'FITVELY 다이어트할 때 탄수화물을 먹어야 하는 이유',
    sourceUrl: 'https://www.youtube.com/watch?v=_h3u30M9ECc',
    sourceEvidence: [
      '검색 결과와 요약 글이 FITVELY 탄수화물 섭취 필요성 영상을 다이어트 중 탄수화물을 지나치게 줄이지 않는 영양 가이드 맥락으로 설명한다.',
      '탄수화물 가이드형 영상은 할 일 체크보다 매끼 탄수화물 선택과 운동일 섭취 타이밍을 기록하는 식단표가 자연 산출물이다.',
    ],
    userScenario: '사용자는 다이어트 중 탄수화물을 무조건 끊지 않고, 운동일과 비운동일에 어떤 탄수화물을 얼마나 먹었는지 기록하려 한다.',
    naturalArtifacts: [
      {
        kind: 'spreadsheet',
        artifactTitle: '탄수화물 섭취 선택/기록표',
        simulatedInputs: ['목표=감량 유지', '운동일=월/수/금', '탄수화물원=현미밥/고구마/과일', '기록기간=2주'],
        expectedOutput: [
          '날짜, 운동 여부, 아침/점심/저녁 탄수화물원',
          '운동 전후 섭취 여부',
          '허기/컨디션 메모',
          '탄수화물 과소/과다 조절 메모',
        ],
        currentFlowMatch: '현재 exact-video Flow는 적용 행동 1개로 좁히지만 식단 기록표로 이어지지 않는다.',
        currentUxSupport: '메모/복사는 가능하지만 매끼 식단 spreadsheet preview가 없다.',
        gap: '영양 가이드 Flow는 체크리스트보다 식단 기록표와 조절 메모가 핵심이다.',
      },
      {
        kind: 'memo',
        artifactTitle: '이번 주 탄수화물 기준 메모',
        simulatedInputs: ['평일기준=점심 현미밥 반공기', '운동전=바나나 1개', '운동후=고구마/단백질', '주의=무탄수 금지'],
        expectedOutput: ['평일 기준, 운동 전 기준, 운동 후 기준, 피해야 할 극단 기준, 다음 주 조정'],
        currentFlowMatch: '항목 메모로 기록은 가능하지만 사용자가 다시 붙여 쓸 기준 카드로 보이지 않는다.',
        currentUxSupport: '메모가 export에서 영양 기준 카드로 분리되지 않는다.',
        gap: '반복 적용할 식단 기준은 한 장짜리 memo card로 복사되어야 한다.',
      },
    ],
    currentContentGap: '탄수화물 섭취 원칙이 사용자의 매끼 기준과 운동일 타이밍으로 재구성되지 않는다.',
    currentUxGap: '식단 로그와 기준 메모가 부족해 사용자가 별도 앱/시트에 다시 정리해야 한다.',
    nextContentAction: '탄수화물 Flow를 식단 기준 카드와 2주 기록표로 재구성한다.',
    nextUxAction: 'diet routine에 meal spreadsheet preview와 weekly adjustment memo를 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-fitvely-video-three-week-check',
    checkedAt: '2026-05-22',
    sourceTitle: 'FITVELY 3주 감량 점검',
    sourceUrl: 'https://www.youtube.com/watch?v=nfdIpPXfIc8',
    sourceEvidence: [
      '검색 결과가 3주 만에 큰 폭의 감량 사례와 FITVELY 다이어트 맥락을 연결해 보여준다.',
      '큰 수치의 감량 제목은 그대로 약속하면 위험하므로 사용자의 실제 산출물은 3주 실행/측정/컨디션 점검표여야 한다.',
    ],
    userScenario: '사용자는 3주 동안 무리한 감량을 따라 하기보다 체중, 허리둘레, 운동, 식단, 컨디션을 매주 점검하려 한다.',
    naturalArtifacts: [
      {
        kind: 'spreadsheet',
        artifactTitle: '3주 감량 실행 점검표',
        simulatedInputs: ['시작체중=68kg', '목표=3주 습관 점검', '측정=매주 월요일', '운동=주4회', '식단=야식 줄이기'],
        expectedOutput: [
          '주차, 체중, 허리둘레, 운동 횟수, 식단 준수일',
          '수면/컨디션 메모',
          '무리한 제한 여부',
          '다음 주 유지/완화 결정',
        ],
        currentFlowMatch: '현재 Flow는 영상 적용 action만 있어 3주 점검표로 충분히 변환되지 않는다.',
        currentUxSupport: '일반 반복 캘린더는 가능하지만 주차별 측정표와 안전 점검이 없다.',
        gap: '감량 사례 영상은 결과 약속이 아니라 3주 점검표로 바뀌어야 한다.',
      },
      {
        kind: 'memo',
        artifactTitle: '무리한 감량 방지 체크 메모',
        simulatedInputs: ['어지러움=없음', '폭식유발=가끔', '수면=6시간', '조정=운동 유지/식사 제한 완화'],
        expectedOutput: ['어지러움, 폭식 유발, 수면, 생리/컨디션 변화, 다음 주 제한 완화 여부'],
        currentFlowMatch: '건강 민감 warning은 있지만 구체적인 자기점검 메모가 없다.',
        currentUxSupport: '메모가 주차별 점검표와 연결되지 않는다.',
        gap: '민감한 감량 Flow는 안전 self-check가 실행 로그와 함께 있어야 한다.',
      },
    ],
    currentContentGap: '극적인 감량 사례를 안전한 3주 자기점검 계획으로 재구성하는 장치가 부족하다.',
    currentUxGap: '주차별 측정/컨디션 로그와 캘린더가 분리되어 있다.',
    nextContentAction: '3주 감량 Flow를 결과 약속이 아닌 안전 점검표와 주차별 리뷰로 재작성한다.',
    nextUxAction: 'diet Flow에 3주 측정표와 health-sensitive self-check memo를 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-fitvely-video-post-workout-nutrition',
    checkedAt: '2026-05-22',
    sourceTitle: 'FITVELY 운동 직후 섭취 가이드',
    sourceUrl: 'https://www.youtube.com/watch?v=J8YmqzhPS2Q',
    sourceEvidence: [
      'seed metadata가 이 exact video를 운동 직후 섭취가 중요하다는 FITVELY 영양 콘텐츠로 분류한다.',
      '운동 직후 섭취형 콘텐츠는 운동일에만 반복되는 식사 타이밍 메모와 준비물 체크가 자연 산출물이다.',
    ],
    userScenario: '사용자는 저녁 운동 후 무엇을 언제 먹을지 정해두고, 운동일마다 섭취 여부와 속 불편 여부를 기록하려 한다.',
    naturalArtifacts: [
      {
        kind: 'routine_calendar',
        artifactTitle: '운동일 직후 섭취 리마인더',
        simulatedInputs: ['운동일=월/수/금 20:00', '섭취시점=운동 후 30분', '준비=바나나/요거트', '기간=4주'],
        expectedOutput: [
          '월/수/금 운동 후 30분 섭취 리마인더',
          '운동 전 준비물 체크',
          '섭취 완료 여부',
          '속 불편/허기 메모',
        ],
        currentFlowMatch: 'routine 구조는 맞지만 운동일 후속 섭취 같은 종속 리마인더 모델이 약하다.',
        currentUxSupport: '반복 캘린더에 운동 후 상대시간 이벤트를 붙이기 어렵다.',
        gap: '영양 루틴은 운동 이벤트에 연결된 후속 이벤트로 보여야 한다.',
      },
      {
        kind: 'memo',
        artifactTitle: '운동 직후 섭취 기준 카드',
        simulatedInputs: ['운동종류=웨이트 60분', '운동후식사=바나나+요거트', '저녁시간=21:00', '불편=없음'],
        expectedOutput: ['운동 종류, 운동 후 먹을 것, 섭취 시간, 불편 여부, 다음 운동일 준비물'],
        currentFlowMatch: '항목 메모로 기록은 가능하지만 기준 카드로 재사용하기 어렵다.',
        currentUxSupport: '메모 export에서 운동 후 섭취 기준이 독립적으로 보이지 않는다.',
        gap: '운동 후 영양 Flow는 반복 카드와 캘린더 후속 이벤트가 함께 필요하다.',
      },
    ],
    currentContentGap: '운동 후 섭취 기준이 사용자의 운동요일, 준비물, 속 불편 기록으로 변환되지 않았다.',
    currentUxGap: '캘린더가 상대시간 후속 리마인더와 섭취 메모를 지원하지 않는다.',
    nextContentAction: '운동직후 섭취 Flow를 운동일 후속 리마인더와 섭취 기준 카드로 재구성한다.',
    nextUxAction: 'routine Flow에 parent event 이후 N분 후속 리마인더를 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-fitvely-video-carb-amount-shorts',
    checkedAt: '2026-05-22',
    sourceTitle: 'FITVELY 탄수화물 얼마나 섭취해야 할까',
    sourceUrl: 'https://www.youtube.com/watch?v=t630vnDGIWw',
    sourceEvidence: [
      'seed metadata가 이 exact video를 오늘 탄수화물 양을 기록하고 조정하는 shorts 기반 식단 콘텐츠로 분류한다.',
      '짧은 영양 영상은 긴 학습 플랜보다 오늘 먹은 탄수화물 양과 다음 끼 조정 메모를 빠르게 남기는 로그와 맞다.',
    ],
    userScenario: '사용자는 오늘 먹은 탄수화물 양을 대략 기록하고, 저녁이나 다음날 식사에서 줄일지 유지할지 결정하려 한다.',
    naturalArtifacts: [
      {
        kind: 'spreadsheet',
        artifactTitle: '오늘 탄수화물 간단 기록표',
        simulatedInputs: ['날짜=2026-06-05', '아침=식빵 1장', '점심=밥 반공기', '저녁계획=고구마 1개', '운동=없음'],
        expectedOutput: [
          '끼니별 탄수화물 음식',
          '대략 양',
          '운동 여부',
          '저녁/다음날 조정',
          '과도한 제한 여부 메모',
        ],
        currentFlowMatch: '현재 Flow는 오늘 적용 행동은 만들 수 있으나 끼니별 기록표는 없다.',
        currentUxSupport: '메모에 적을 수 있지만 빠른 식단 로그 UI가 없다.',
        gap: 'shorts형 식단 콘텐츠는 one-tap daily log로 전환되어야 한다.',
      },
      {
        kind: 'memo',
        artifactTitle: '다음 끼 조정 메모',
        simulatedInputs: ['현재상태=허기 있음', '저녁조정=밥 줄이지 않음', '내일=운동 전 바나나', '주의=무탄수 금지'],
        expectedOutput: ['허기, 운동 예정, 다음 끼 탄수화물 유지/감소, 무리한 제한 방지 메모'],
        currentFlowMatch: '일반 메모는 가능하지만 다음 끼 조정으로 드러나지 않는다.',
        currentUxSupport: '일별 로그와 다음 끼 메모가 연결되지 않는다.',
        gap: '일일 식단 Flow는 기록 후 바로 다음 행동을 제안해야 한다.',
      },
    ],
    currentContentGap: 'shorts 콘텐츠의 핵심인 오늘 기록과 다음 끼 조정이 Flow item으로 구조화되어 있지 않다.',
    currentUxGap: '빠른 식단 로그와 다음 끼 조정 메모 UI가 없다.',
    nextContentAction: '탄수화물 shorts Flow를 일일 기록표와 다음 끼 조정 카드로 전환한다.',
    nextUxAction: 'diet Flow에 daily quick-log와 next-meal memo를 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-fitvely-video-after-work-nutrition',
    checkedAt: '2026-05-22',
    sourceTitle: 'FITVELY 퇴근 후 운동 영양 섭취',
    sourceUrl: 'https://www.youtube.com/watch?v=zipquv7TErU',
    sourceEvidence: [
      'seed metadata가 이 exact video를 퇴근 후 운동하는 사람을 위한 영양 섭취 방법과 잘못된 경우 Top3로 분류한다.',
      '퇴근 후 운동 콘텐츠는 퇴근 시간, 운동 시간, 운동 전후 식사 타이밍을 캘린더와 기준 메모로 바꾸는 것이 자연스럽다.',
    ],
    userScenario: '사용자는 퇴근 시간이 늦어 운동 전 저녁을 먹을지 운동 후에 먹을지 헷갈려서, 운동일별 식사 타이밍 기준을 정하려 한다.',
    naturalArtifacts: [
      {
        kind: 'routine_calendar',
        artifactTitle: '퇴근 후 운동 전후 식사 캘린더',
        simulatedInputs: ['퇴근=19:00', '운동=20:30', '운동일=화/목/토', '식사전략=운동 전 간식/운동 후 저녁'],
        expectedOutput: [
          '화/목/토 퇴근 후 운동 일정',
          '운동 60분 전 간식 리마인더',
          '운동 후 저녁 식사 메모',
          '속 불편/허기 여부 기록',
        ],
        currentFlowMatch: '현재 Flow는 오늘 적용 기준을 정할 수 있지만 퇴근-운동-식사의 시간 관계를 구조화하지 않는다.',
        currentUxSupport: '캘린더는 단일 반복에 강하지만 운동 전후 상대시간 이벤트가 약하다.',
        gap: '퇴근 후 운동 Flow는 시간대별 후속 리마인더와 식사 기준이 필요하다.',
      },
      {
        kind: 'memo',
        artifactTitle: '퇴근 후 운동 식사 기준 카드',
        simulatedInputs: ['간식=바나나+우유', '운동후=밥 반공기+단백질', '피해야함=공복 고강도', '다음조정=속불편시 양 줄이기'],
        expectedOutput: ['운동 전 간식 기준, 운동 후 식사 기준, 피해야 할 경우, 속 불편 시 조정, 다음 운동일 준비'],
        currentFlowMatch: '메모는 가능하지만 반복해서 참고할 기준 카드로 분리되지 않는다.',
        currentUxSupport: '식사 기준 카드가 복사/엑셀 export에 독립 섹션으로 나오지 않는다.',
        gap: '영양 타이밍 콘텐츠는 루틴 캘린더와 기준 memo card를 함께 가져야 한다.',
      },
    ],
    currentContentGap: '퇴근 후 운동의 시간 제약과 식사 타이밍이 Flow item에 반영되어 있지 않다.',
    currentUxGap: '캘린더 상대시간 이벤트와 식사 기준 로그가 부족하다.',
    nextContentAction: '퇴근 후 운동 영양 Flow를 시간대 입력, 운동 전 간식, 운동 후 식사 기준으로 재구성한다.',
    nextUxAction: 'routine Flow에 event-relative reminders와 nutrition memo export를 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-fitvely-video-weight-class-method',
    checkedAt: '2026-05-22',
    sourceTitle: 'FITVELY 체중별 다이어트 방법 정리',
    sourceUrl: 'https://www.youtube.com/watch?v=qADmhOJemTs',
    sourceEvidence: [
      'seed metadata가 이 exact video를 현재 체중 구간에 맞는 실행 기준을 고르는 다이어트 콘텐츠로 분류한다.',
      '체중별 방법 콘텐츠는 사용자가 자신의 체중/목표/활동량을 넣고 어느 기준을 적용할지 고르는 comparison artifact가 자연스럽다.',
    ],
    userScenario: '사용자는 현재 체중과 목표 감량폭을 기준으로 식단, 운동, 측정 주기를 어느 정도로 잡을지 선택하려 한다.',
    naturalArtifacts: [
      {
        kind: 'comparison_table',
        artifactTitle: '체중 구간별 다이어트 기준 선택표',
        simulatedInputs: ['현재체중=82kg', '목표=12주 -5kg', '활동량=사무직', '운동가능=주3회'],
        expectedOutput: [
          '체중 구간',
          '권장 운동 빈도',
          '식단 조절 강도',
          '측정 주기',
          '무리한 제한 여부',
          '선택 기준',
        ],
        currentFlowMatch: '현재 routine Flow는 하나의 행동을 적용하는 형태라 체중 구간별 선택을 충분히 지원하지 않는다.',
        currentUxSupport: '조건 입력 후 항목이 바뀌는 분기형 UX가 없다.',
        gap: '체중별 콘텐츠는 먼저 사용자 구간을 선택하고 그에 맞는 계획을 생성해야 한다.',
      },
      {
        kind: 'spreadsheet',
        artifactTitle: '12주 체중구간 적용 기록표',
        simulatedInputs: ['측정=매주 월요일', '운동=주3회', '식단=야식 줄이기', '검토=4주마다'],
        expectedOutput: ['주차, 체중, 운동 횟수, 식단 준수, 컨디션, 기준 유지/변경'],
        currentFlowMatch: '체중별 기준을 적용한 뒤 장기 기록표로 이어지지 않는다.',
        currentUxSupport: '반복 체크는 가능하지만 기준 유지/변경 판단이 없다.',
        gap: '체중 구간 Flow는 선택표와 장기 기록표가 연결되어야 한다.',
      },
    ],
    currentContentGap: '사용자 체중 구간을 입력받고 그에 따라 실행 기준을 좁히는 콘텐츠 구조가 없다.',
    currentUxGap: '조건 분기와 장기 기록 로그가 부족하다.',
    nextContentAction: '체중별 다이어트 Flow를 체중/목표/활동량 입력 기반 선택표로 재구성한다.',
    nextUxAction: 'diet Flow에 condition-based comparison and generated tracking table을 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-fitvely-video-bulk-up-method',
    checkedAt: '2026-05-22',
    sourceTitle: 'FITVELY 벌크업 운동 방법',
    sourceUrl: 'https://www.youtube.com/watch?v=JurCSqpjl5I',
    sourceEvidence: [
      'seed metadata가 이 exact video를 벌크업 운동 기준을 주간 루틴으로 바꾸는 workout-plan 콘텐츠로 분류한다.',
      '벌크업 방법 콘텐츠는 운동 루틴뿐 아니라 체중, 중량, 식사량, 회복을 주간으로 기록하는 sheet artifact가 자연스럽다.',
    ],
    userScenario: '사용자는 벌크업을 위해 주 4회 운동표와 체중/중량/식사량 기록표를 만들어 8주 동안 유지하려 한다.',
    naturalArtifacts: [
      {
        kind: 'routine_calendar',
        artifactTitle: '벌크업 주 4회 운동 캘린더',
        simulatedInputs: ['시작일=2026-06-02', '반복=월/화/목/금', '분할=상체/하체', '기간=8주'],
        expectedOutput: [
          '월/목 상체, 화/금 하체 일정',
          '운동 후 식사/수면 체크',
          '매주 체중 측정 일정',
          '4주차 중간 리뷰',
        ],
        currentFlowMatch: '현재 Flow는 운동 기준 1개 적용에 가깝고 8주 벌크업 루틴과 리뷰 구조가 없다.',
        currentUxSupport: '반복 캘린더는 가능하지만 운동 분할과 측정/식사 로그가 결합되어 있지 않다.',
        gap: '벌크업 Flow는 운동 캘린더와 체중/중량/식사 로그가 함께 필요하다.',
      },
      {
        kind: 'spreadsheet',
        artifactTitle: '벌크업 체중/중량/식사 기록표',
        simulatedInputs: ['시작체중=72kg', '목표=8주 +2kg', '운동기록=스쿼트/벤치/로우', '식사=하루4끼'],
        expectedOutput: ['주차, 체중, 주요 운동 중량, 식사 횟수, 수면, 컨디션, 다음 주 증량 여부'],
        currentFlowMatch: '현재 checklist로는 중량 증가와 체중 변화를 볼 수 없다.',
        currentUxSupport: 'spreadsheet export가 exact workout-plan 로그를 자동 생성하지 않는다.',
        gap: '벌크업은 완료 체크보다 진행 로그가 핵심 산출물이다.',
      },
    ],
    currentContentGap: '벌크업 기준이 장기 운동표와 체중/중량/식사 로그로 재구성되지 않았다.',
    currentUxGap: '캘린더와 spreadsheet 로그가 결합되어 있지 않다.',
    nextContentAction: '벌크업 Flow를 8주 운동 캘린더와 주간 기록표로 재구성한다.',
    nextUxAction: 'workout-plan Flow에 운동 분할, 주간 측정, 중량 로그 export를 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-fitvely-video-workout-order',
    checkedAt: '2026-05-22',
    sourceTitle: 'FITVELY 운동 순서 결정',
    sourceUrl: 'https://www.youtube.com/watch?v=oPBA8E_WtXY',
    sourceEvidence: [
      '검색 결과와 요약 페이지가 FITVELY 운동 순서 영상을 다이어트 목적의 무산소/유산소 순서와 목표별 예외를 설명하는 콘텐츠로 확인한다.',
      '운동 순서 콘텐츠는 사용자가 목표를 고르고 무산소/유산소/워밍업/쿨다운 순서를 자기 운동표에 반영하는 decision artifact와 잘 맞는다.',
    ],
    userScenario: '사용자는 다이어트, 근육량 증가, 심폐지구력 중 자기 목표에 맞는 운동 순서를 고른 뒤 이번 주 운동표에 적용하려 한다.',
    naturalArtifacts: [
      {
        kind: 'comparison_table',
        artifactTitle: '운동 목표별 순서 선택표',
        simulatedInputs: ['목표A=체지방감량', '목표B=근육량증가', '목표C=심폐지구력', '선택=체지방감량'],
        expectedOutput: [
          '목표',
          '추천 순서',
          '워밍업',
          '근력운동 시간',
          '유산소 시간',
          '예외 상황',
          '선택 여부',
        ],
        currentFlowMatch: '현재 Flow는 오늘 순서를 반영하는 action은 있지만 목표별 비교표가 없다.',
        currentUxSupport: 'decision comparison UI가 운동 exact Flow에는 연결되지 않았다.',
        gap: '운동 순서 Flow는 목표별 선택표를 먼저 보여줘야 한다.',
      },
      {
        kind: 'routine_calendar',
        artifactTitle: '선택한 운동 순서 주간 적용 캘린더',
        simulatedInputs: ['운동일=월/수/금', '순서=워밍업 10분→근력 45분→유산소 20분', '기간=4주'],
        expectedOutput: ['월/수/금 운동 일정', '각 회차의 순서 블록', '운동 후 피로도', '2주차 순서 유지/변경 리뷰'],
        currentFlowMatch: '순서를 텍스트로 적을 수 있지만 캘린더 회차 안의 블록 구조로 보이지 않는다.',
        currentUxSupport: '루틴 occurrence에 세부 순서 블록을 표시하는 UX가 없다.',
        gap: '운동 순서 콘텐츠는 선택 후 회차별 실행 순서가 보여야 한다.',
      },
    ],
    currentContentGap: '운동 목표별 예외와 선택 기준이 단일 action으로 축소되어 있다.',
    currentUxGap: '비교표와 루틴 캘린더가 연결되지 않아 사용자가 순서를 별도 메모해야 한다.',
    nextContentAction: '운동 순서 Flow를 목표 선택표와 주간 적용 캘린더로 재구성한다.',
    nextUxAction: 'workout-plan Flow에 comparison-to-calendar 전환과 회차 순서 블록을 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-fitvely-video-workout-split-science',
    checkedAt: '2026-05-22',
    sourceTitle: 'FITVELY 과학적으로 운동루틴 짜는법',
    sourceUrl: 'https://www.youtube.com/watch?v=-GJMwcES45A',
    sourceEvidence: [
      '영상 제목은 분할법, 세트수, 무게, 휴식, 운동 종류처럼 사용자가 자기 주간 운동표로 재구성해야 하는 요소를 담고 있다.',
      '단순 todo보다 요일별 부위, 세트수, 휴식일, 중량 기록을 포함한 루틴 설계표가 자연 산출물이다.',
    ],
    userScenario: '사용자는 헬스장 주 4회 루틴을 짜기 위해 가슴/등/하체/어깨 요일과 세트수, 휴식일을 월간 캘린더에 배치하려 한다.',
    naturalArtifacts: [
      {
        kind: 'routine_calendar',
        artifactTitle: '주 4회 분할 운동 월간 캘린더',
        simulatedInputs: ['시작일=2026-06-01', '분할=상체/하체/휴식/상체/하체', '운동일=월/화/목/금', '휴식=수/토/일'],
        expectedOutput: [
          '월요일 상체A, 화요일 하체A, 목요일 상체B, 금요일 하체B 반복',
          '휴식일은 회색으로 표시',
          '각 회차에 세트수, 중량, RPE 기록칸 제공',
        ],
        currentFlowMatch: '현재 Flow는 운동 순서를 체크할 수 있지만 분할법을 월간 루틴으로 설계하는 정보가 부족하다.',
        currentUxSupport: '복수 운동 항목을 요일별로 반복 배치하는 UI가 없다.',
        gap: '운동루틴 설계 콘텐츠에는 루틴 빌더와 월간 반영 preview가 필요하다.',
      },
      {
        kind: 'comparison_table',
        artifactTitle: '분할법 선택 비교표',
        simulatedInputs: ['후보A=무분할 주3회', '후보B=상하체 주4회', '후보C=3분할 주5회', '제약=평일 4일 가능'],
        expectedOutput: ['후보, 주당 횟수, 회복 부담, 장비 필요, 예상 소요시간, 선택 여부'],
        currentFlowMatch: '현재 항목은 하나의 루틴을 따라가는 구조라 사용자가 분할법 후보를 비교하기 어렵다.',
        currentUxSupport: 'decision/comparison 화면은 중고차 Flow에는 있으나 운동 루틴형에는 연결되어 있지 않다.',
        gap: '루틴 설계형 콘텐츠는 반복 캘린더 전에 비교/선택 단계가 필요하다.',
      },
    ],
    currentContentGap: '운동루틴 설계 원본은 선택과 설계가 핵심인데 현재 Flow는 이미 정해진 루틴 실행에 가깝다.',
    currentUxGap: '루틴 후보 비교 후 선택한 패턴을 캘린더에 반영하는 UX가 없다.',
    nextContentAction: '운동루틴 설계 Flow를 후보 비교 -> 주간 패턴 확정 -> 월간 반복으로 재구성한다.',
    nextUxAction: 'routine Flow에 comparison_table에서 선택한 반복 규칙을 캘린더로 전환하는 흐름을 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-sinagong-computer-d30-study',
    checkedAt: '2026-05-25',
    sourceTitle: '2026 한 권으로 끝내는 시나공 컴활 1급 필기+실기',
    sourceUrl: 'https://www.gilbut.co.kr/m/book/view?bookcode=BN004603',
    sourceEvidence: [
      'The Gilbut book page is the exact product source already used by the representative `computer-skills-d30-study` route.',
      'This replaces the broad Sinagong site source with one exact book/source boundary for manual study-progress conversion.',
    ],
    userScenario: '사용자는 컴활 1급 필기 시험을 30일 앞두고 기출, 요약, CBT, 오답 복습을 주차별로 나누어 공부표를 만들려 한다.',
    naturalArtifacts: [
      {
        kind: 'monthly_calendar',
        artifactTitle: '컴활 D-30 주차별 학습 달력',
        simulatedInputs: ['시험일=2026-07-05', '과목=컴활1급필기', '평일공부=90분', '주말공부=3시간'],
        expectedOutput: [
          'D-30~D-21 개념+핵심요약',
          'D-20~D-10 기출 5회',
          'D-9~D-3 오답 반복',
          'D-2~D-1 CBT 실전과 시험장 준비',
        ],
        currentFlowMatch: '현재 timeline/end_date 구조는 맞지만 자료실에서 받은 파일과 기출 회차를 붙이는 공간이 부족하다.',
        currentUxSupport: '날짜별 todo는 가능하나 과목/회차/점수 기록을 달력과 함께 보기는 어렵다.',
        gap: '시험 공부 Flow는 일정표와 점수/오답 로그가 함께 필요하다.',
      },
      {
        kind: 'spreadsheet',
        artifactTitle: '기출 회차 점수/오답 기록표',
        simulatedInputs: ['기출회차=2026년 2차/2025년 1차', '합격기준=과목별 40점 이상 평균 60점', '오답복습=2회'],
        expectedOutput: ['회차, 풀이일, 과목별 점수, 평균, 오답 수, 재풀이일, 약점 키워드'],
        currentFlowMatch: '오답 정리 항목은 있으나 실제 점수표 산출물이 없다.',
        currentUxSupport: '체크리스트는 점수 변화를 보여주지 못한다.',
        gap: '자격증 학습 Flow는 캘린더뿐 아니라 spreadsheet형 성과 로그가 필요하다.',
      },
    ],
    currentContentGap: 'exact 교재 페이지는 붙었지만 실제 진도표 row는 여전히 제작자가 source-derived chapter/exam-scope rows로 더 구체화해야 한다.',
    currentUxGap: 'D-30 일정은 가능하지만 자료 링크, 회차 점수, 오답 로그가 한 화면에 없다.',
    nextContentAction: '시나공 Flow를 exact book source 기반 source-derived progress rows, 기출/모의 회차, 오답 재풀이 row 중심으로 보강한다.',
    nextUxAction: 'study timeline에 점수/오답 spreadsheet preview를 결합한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-mofa-overseas-travel-prep',
    checkedAt: '2026-05-25',
    sourceTitle: '외교부 해외안전여행 베트남 국가/지역별 정보',
    sourceUrl: 'https://www.0404.go.kr/ntnSafetyInfo/86/detail',
    sourceEvidence: [
      '외교부 베트남 국가/지역별 정보 page는 베트남의 여행경보, 안전공지, 여행경보 조정 내역, 현지 대사관/총영사관 연락처, 현지 신고 번호를 한 페이지에서 제공한다.',
      '현재 audit scenario가 베트남 여행을 기준으로 하므로 broad portal보다 이 exact country page가 안전 확인 달력과 비상 연락처 memo를 더 직접 지원한다.',
    ],
    userScenario: '사용자는 베트남 여행 전 여행경보, 여권/비자, 영사콜센터, 가족 공유 정보를 정리하고 출국 전날까지 확인하려 한다.',
    naturalArtifacts: [
      {
        kind: 'monthly_calendar',
        artifactTitle: '출국 D-14 해외안전 준비 달력',
        simulatedInputs: ['출국일=2026-07-20', '방문국=베트남', '동행=부모님', '공유대상=가족 단톡방'],
        expectedOutput: [
          'D-14 여행경보와 안전공지 확인',
          'D-10 여권/비자/입국 조건 확인',
          'D-7 영사콜센터와 현지 공관 연락처 저장',
          'D-1 가족에게 일정과 숙소 공유',
        ],
        currentFlowMatch: '여행 안전 준비 항목은 대체로 있으나 공식 확인 결과를 저장하는 구조가 약하다.',
        currentUxSupport: 'timeline UI는 맞지만 국가명과 확인일을 입력해 재확인하는 인터랙션이 없다.',
        gap: '여행 안전 Flow는 국가별 확인 결과와 재확인일이 핵심 필드여야 한다.',
      },
      {
        kind: 'memo',
        artifactTitle: '비상 연락처 오프라인 메모',
        simulatedInputs: ['영사콜센터=+82-2-3210-0404', '현지공관=주베트남대사관', '보험=OO손보', '가족=배우자'],
        expectedOutput: ['영사콜센터, 현지 공관, 보험사, 숙소, 가족 연락처, 여권 사본 위치'],
        currentFlowMatch: '긴급 연락처 저장 항목은 있으나 실제 오프라인 메모 출력 형태가 약하다.',
        currentUxSupport: '메모는 item에 묶여 있어 한 장짜리 비상 카드로 복사하기 어렵다.',
        gap: '여행 Flow는 체크리스트 외에 비상 카드 export가 필요하다.',
      },
    ],
    currentContentGap: '공식 사이트의 여행경보/동행/영사콜센터 기능이 Flow 안에서 별도 산출물로 분리되지 않는다.',
    currentUxGap: '국가별 공식 확인 결과와 비상 연락처 카드를 만들기 어렵다.',
    nextContentAction: '해외안전 Flow를 국가별 확인표와 비상 연락처 카드 중심으로 보강한다.',
    nextUxAction: 'travel timeline에 국가 입력, 확인일, 비상 카드 복사 preview를 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-ts-vehicle-inspection-prep',
    checkedAt: '2026-05-22',
    sourceTitle: 'TS한국교통안전공단 자동차검사 절차 안내',
    sourceUrl: 'https://main.kotsa.or.kr/portal/contents.do?menuCode=01010104',
    sourceEvidence: [
      'TS 안내는 자동차검사가 관능검사, ABS검사, 하체검사, 전조등 검사, 배출가스 검사, 검사결과 설명으로 시행된다고 설명한다.',
      '관능검사에는 차대번호, 원동기 형식, 등록번호판, 봉인상태, 불법구조변경, 전자센서, 오일량, 타이어, 브레이크 패드 등이 포함된다.',
    ],
    userScenario: '사용자는 자동차 정기검사 예약일을 앞두고 서류, 타이어/등화, 검사소 방문, 결과 후 정비 메모를 준비하려 한다.',
    naturalArtifacts: [
      {
        kind: 'monthly_calendar',
        artifactTitle: '자동차검사 예약 전후 준비 달력',
        simulatedInputs: ['검사일=2026-06-18', '차량=아반떼 2021', '검사소=성산검사소', '예약=2026-06-18 10:30'],
        expectedOutput: [
          'D-7 검사 기간과 예약 확인',
          'D-3 등록증/보험/등화/타이어 점검',
          'D-Day 검사소 방문과 결제',
          'D+1 결과표 보관과 정비 필요 항목 등록',
        ],
        currentFlowMatch: 'timeline 구조와 차량 점검 항목은 맞다.',
        currentUxSupport: '예약 시간, 검사소, 결과표 보관 같은 정보가 일반 메모에만 들어간다.',
        gap: '자동차검사 Flow는 예약 정보와 검사 결과 후속 정비가 별도 산출물로 보여야 한다.',
      },
      {
        kind: 'checklist',
        artifactTitle: '검사 전 자가점검 체크리스트',
        simulatedInputs: ['확인=등화/타이어/와이퍼/경고등', '서류=자동차등록증', '결제=카드'],
        expectedOutput: ['등록번호판/봉인 확인', '전조등/방향지시등 확인', '타이어 마모 확인', '경고등 확인', '검사 결과표 저장'],
        currentFlowMatch: '기본 자가점검 항목은 포함되어 있다.',
        currentUxSupport: '검사 절차별로 접힘 구분이 약해 사용자가 무엇을 검사소에서 보는지 알기 어렵다.',
        gap: '공식 검사 절차와 사용자 사전점검 항목을 분리해서 보여야 한다.',
      },
    ],
    currentContentGap: '공식 절차와 사용자가 검사 전 할 자가점검이 섞여 있다.',
    currentUxGap: '예약 정보, 검사소 정보, 결과 후 정비 메모가 카드로 분리되지 않는다.',
    nextContentAction: '자동차검사 Flow를 검사 전 준비, 검사소 방문, 결과 후 정비로 재구성한다.',
    nextUxAction: 'vehicle timeline에 예약 카드와 검사 결과 follow-up 메모를 추가한다.',
    decision: 'promote_to_manual_source_fit',
  },
  {
    slug: 'real-safe-driving-license-renewal',
    checkedAt: '2026-05-22',
    sourceTitle: '한국도로교통공단 운전면허증 발급 가이드',
    sourceUrl: 'https://www.safedriving.or.kr/guide/larGuide10.do?menuCode=MN-PO-12111o',
    sourceEvidence: [
      '안전운전 통합민원은 적성검사와 갱신, 재발급, 국제운전면허증 등 유형별 수수료와 준비물, 인터넷/대리접수 가능 여부를 구분해 안내한다.',
      '적성검사는 운전면허증, 6개월 이내 여권용 사진 2매, 건강검진결과 활용 가능성, 신체검사장 유무 같은 조건이 필요하다.',
    ],
    userScenario: '사용자는 2종 보통 면허 갱신 대상인지 적성검사 대상인지 헷갈려서 준비물, 수수료, 온라인 가능 여부를 표로 정리하려 한다.',
    naturalArtifacts: [
      {
        kind: 'monthly_calendar',
        artifactTitle: '면허 갱신 마감 준비 달력',
        simulatedInputs: ['만료일=2026-08-31', '면허=2종보통', '나이=45', '사진촬영=필요', '수령=시험장 방문'],
        expectedOutput: [
          'D-30 대상 유형 확인',
          'D-21 사진 촬영',
          'D-14 온라인 신청 또는 방문 예약',
          'D-7 수령 장소/수수료 확인',
          'D-Day 면허증 수령',
        ],
        currentFlowMatch: '현재 checklist/none이라 기한을 입력하지 않으면 마감 준비가 보이지 않는다.',
        currentUxSupport: '날짜 없는 체크리스트로는 갱신기간 경과 리스크를 충분히 보여주기 어렵다.',
        gap: '면허 갱신은 checklist가 아니라 선택적 마감일 입력이 있는 deadline Flow가 더 적합하다.',
      },
      {
        kind: 'comparison_table',
        artifactTitle: '적성검사/갱신/재발급 조건 비교표',
        simulatedInputs: ['후보A=2종 갱신', '후보B=1종 적성검사', '후보C=분실 재발급', '선택=2종 갱신'],
        expectedOutput: ['유형, 준비물, 사진 매수, 수수료, 인터넷 가능 여부, 대리 가능 여부, 수령 조건'],
        currentFlowMatch: '준비물 체크는 있으나 본인 유형을 고르는 비교 단계가 없다.',
        currentUxSupport: '사용자가 자신에게 맞는 경로를 선택한 뒤 checklist가 줄어드는 UX가 없다.',
        gap: '행정 발급 Flow는 먼저 유형을 선택하고 그에 맞는 체크리스트로 필터링되어야 한다.',
      },
    ],
    currentContentGap: '면허 발급 가이드는 유형별 조건표가 핵심인데 현재 Flow는 단일 체크리스트로 단순화되어 있다.',
    currentUxGap: '사용자 유형 선택과 마감일 입력이 없어서 실제 준비 일정으로 전환하기 어렵다.',
    nextContentAction: '면허 갱신 Flow를 유형 선택형 행정 checklist+deadline Flow로 재구성한다.',
    nextUxAction: 'checklist Flow에 optional deadline과 조건 분기 필터를 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-gov24-resident-register-copy',
    checkedAt: '2026-05-22',
    sourceTitle: '정부24 주민등록표 등본 발급 민원안내',
    sourceUrl: 'https://www.gov.kr/mw/AA020InfoCappView.do?CappBizCD=13100000015&HighCtgCD=A1004',
    sourceEvidence: [
      '정부24 민원 안내 원문은 직접 본문 접근이 제한되어 검색 인덱스와 공공 민원 안내를 보조 확인했으며, 인터넷/방문/FAX/우편/무인발급기 신청과 즉시 처리, 인터넷 무료 발급이 핵심 정보다.',
      '주민등록등본은 발급 자체보다 제출처 요구, 주민번호 공개 범위, PDF/출력 방식, 제출 증빙 보관이 사용자의 실제 관리 산출물이다.',
    ],
    userScenario: '사용자는 은행 대출 서류로 주민등록등본을 제출해야 해서 공개 범위와 PDF 저장본, 제출 완료 여부를 체크리스트로 관리하려 한다.',
    naturalArtifacts: [
      {
        kind: 'checklist',
        artifactTitle: '주민등록등본 제출 전 발급 체크리스트',
        simulatedInputs: ['제출처=은행 대출', '서류=주민등록등본', '공개범위=주민번호 뒷자리 비공개', '제출방식=PDF 업로드'],
        expectedOutput: [
          '제출처가 요구한 서류명과 발급일 기준 확인',
          '본인 인증 수단 준비',
          '주민번호/세대원 표시 범위 선택',
          'PDF 저장 또는 출력 방식 선택',
          '제출 전 발급일, 표시항목, 파일명을 재확인',
        ],
        currentFlowMatch: '현재 checklist 구조는 발급 준비 항목을 담을 수 있지만 제출처 요구와 공개 범위 선택이 구조화되어 있지 않다.',
        currentUxSupport: '체크와 메모는 가능하나 제출처, 공개범위, 파일 위치 같은 행정 증빙 필드가 없다.',
        gap: '행정서류 Flow는 발급 전 조건 선택과 제출 후 증빙 보관이 한 체크리스트 안에 보여야 한다.',
      },
      {
        kind: 'memo',
        artifactTitle: '발급본 검수/제출 증빙 메모',
        simulatedInputs: ['발급일=2026-06-03', '파일명=등본_은행제출.pdf', '제출기한=2026-06-10', '제출상태=업로드 완료'],
        expectedOutput: ['발급일, 파일 위치, 공개 범위, 제출처, 제출 기한, 제출 상태, 재발급 필요 여부'],
        currentFlowMatch: '일반 메모로 일부 기록할 수 있지만 발급 문서 검수 카드로 보이지 않는다.',
        currentUxSupport: '메모가 item 단위라 최종 제출 증빙을 한 장으로 복사하기 어렵다.',
        gap: '민원 발급 Flow에는 제출 증빙 memo export가 필요하다.',
      },
    ],
    currentContentGap: '현재 Flow는 발급하기 행동 중심이고 제출처 요구와 표시항목 검수 기준이 약하다.',
    currentUxGap: '체크리스트는 있으나 행정서류용 조건 필터와 제출 증빙 카드가 없다.',
    nextContentAction: '주민등록등본 Flow를 제출처 요구 확인, 표시항목 선택, 발급, 제출 증빙 보관 순서로 재구성한다.',
    nextUxAction: 'checklist Flow에 제출처/공개범위/파일위치 같은 행정 증빙 필드를 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-childcare-support-application-check',
    checkedAt: '2026-05-22',
    sourceTitle: '아이사랑 시간제 보육 이용안내',
    sourceUrl: 'https://www.childcare.go.kr/?menuno=202',
    sourceEvidence: [
      '아이사랑 시간제보육 안내는 독립반 6개월~36개월 미만, 통합반 6개월 이상 0~2세 영아, 월 60시간 지원, 평일 운영시간, 시간 단위 예약을 안내한다.',
      '제공기관 첫 방문 시 이용신청서/운영규정서약서, 가족관계증명서와 신분증, 기저귀/침구/간식 같은 개별 준비물이 필요하다.',
    ],
    userScenario: '사용자는 24개월 아이를 반나절 맡기기 위해 이용 조건을 확인하고 근처 기관의 가능 시간대를 비교한 뒤 첫 방문 서류와 준비물을 챙기려 한다.',
    naturalArtifacts: [
      {
        kind: 'checklist',
        artifactTitle: '시간제보육 예약 실행 체크리스트',
        simulatedInputs: ['아이월령=24개월', '희망일=2026-06-18', '이용시간=13:00-16:00', '지역=마포구'],
        expectedOutput: [
          '지원 대상과 월 이용 가능 시간 확인',
          '아이사랑 회원가입과 아동 등록',
          '희망 지역 제공기관과 가능 시간 조회',
          '예약과 결제 방식 확인',
          '첫 방문 서류와 기저귀/침구/간식 준비',
        ],
        currentFlowMatch: '현재 checklist 구조는 신청 단계를 담기 좋지만 아이 월령, 지역, 희망 시간 같은 입력값이 없다.',
        currentUxSupport: '일반 체크는 가능하나 예약 후보를 비교하고 선택하는 화면이 없다.',
        gap: '보육 신청 Flow는 기관/시간 후보를 고른 뒤 선택한 후보 기준으로 준비물이 좁혀져야 한다.',
      },
      {
        kind: 'comparison_table',
        artifactTitle: '시간제보육 기관/시간 후보표',
        simulatedInputs: ['후보A=센터A 13:00-16:00', '후보B=센터B 10:00-13:00', '우선순위=거리/시간', '첫방문=서류 제출 필요'],
        expectedOutput: ['기관명, 거리, 가능 시간, 지원/본인부담 금액, 예약 가능 여부, 첫 방문 서류, 선택 여부'],
        currentFlowMatch: '현재 Flow는 기관 비교 전제를 갖고 있지 않다.',
        currentUxSupport: '중고차용 비교표 UX는 있지만 보육 checklist에는 연결되지 않았다.',
        gap: '신청형 육아 Flow에도 candidate comparison이 필요하다.',
      },
    ],
    currentContentGap: '공식 안내의 이용 대상, 시간, 서류, 준비물이 Flow item에 직접 매핑되어 있지 않다.',
    currentUxGap: '지역/시간 입력과 기관 후보 비교가 없어 실제 예약 의사결정까지 이어지지 않는다.',
    nextContentAction: '시간제보육 Flow를 조건 확인, 기관 후보 비교, 예약, 첫 방문 준비로 재구성한다.',
    nextUxAction: 'checklist Flow에 조건 입력과 후보 비교표를 선택적으로 붙일 수 있게 한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-pet-health-visit-routine',
    checkedAt: '2026-05-25',
    sourceTitle: '서울시 우리동네 동물병원',
    sourceUrl: 'https://news.seoul.go.kr/env/archives/567583/',
    sourceEvidence: [
      '서울시 공식 페이지는 2026 우리동네 동물병원 사업의 대상, 신청 기간, 지정 동물병원 방문 신청, 준비물, 문의처를 안내한다.',
      '지원내용은 기초건강검진, 필수예방접종, 심장사상충 예방약 같은 필수진료와 검진 중 발견된 질병 치료 또는 중성화 수술 같은 선택진료로 나뉜다.',
      '기존 Animal.go.kr FAQ보다 병원 방문과 준비물에 가까운 exact official source지만, 서울시/취약계층/등록동물 조건이 있어 일반 pet health route로 promotion하면 안 된다.',
    ],
    userScenario: '사용자는 동물병원 방문 전에 최근 증상, 식욕, 배변, 접종/등록 정보를 정리하고 방문 후 재진과 접종 리마인더를 남기려 한다.',
    naturalArtifacts: [
      {
        kind: 'checklist',
        artifactTitle: '동물병원 방문 전 질문/증상 체크리스트',
        simulatedInputs: ['방문일=2026-06-12', '증상=구토 2회', '식욕=감소', '기록=동물등록번호/접종수첩'],
        expectedOutput: [
          '증상 발생 시간과 횟수',
          '식욕/음수/배변/활동 변화',
          '동물등록번호와 이전 진료 기록',
          '수의사에게 물어볼 질문',
          '검사/처방 동의 전 확인사항',
        ],
        currentFlowMatch: 'Flow 주제는 건강 방문 준비와 맞지만 현재 원본은 이 건강 방문 체크리스트를 직접 뒷받침하지 못한다.',
        currentUxSupport: '메모와 체크는 가능하나 증상 타임라인과 질문 목록을 별도 산출물로 보여주지 않는다.',
        gap: '반려동물 건강 방문 Flow는 더 정확한 수의학/병원 방문 원본으로 교체하거나 보강해야 한다.',
      },
      {
        kind: 'routine_calendar',
        artifactTitle: '다음 접종/재진 캘린더',
        simulatedInputs: ['시작일=2026-06-12', '재진=2주 후', '복약=7일', '예방접종=매년 6월'],
        expectedOutput: ['복약 종료일', '2주 후 재진 일정', '다음 예방접종 월간 리마인더', '이상 증상 관찰 메모'],
        currentFlowMatch: 'routine 구조는 맞지만 source가 건강 루틴을 충분히 설명하지 않는다.',
        currentUxSupport: '단일 반복은 가능하나 복약 종료, 재진, 연간 접종처럼 다른 주기를 함께 표시하기 어렵다.',
        gap: '건강 Flow는 복수 리마인더와 방문 메모가 함께 필요하다.',
      },
    ],
    currentContentGap: '현재 원본은 동물등록 FAQ라 건강 방문 루틴의 근거로는 broad/reference 수준이다.',
    currentUxGap: '증상 기록, 질문 목록, 복약/재진/접종의 서로 다른 리마인더를 한 화면에서 만들기 어렵다.',
    nextContentAction: '반려동물 건강 방문 Flow는 더 직접적인 병원 방문/예방접종 안내 원본을 찾은 뒤 재감사한다.',
    nextUxAction: 'routine Flow에 복수 리마인더와 방문 전 질문 메모 export를 추가한다.',
    decision: 'keep_catalog_review',
  },
  {
    slug: 'real-ohouse-movein-cleaning-check',
    checkedAt: '2026-05-22',
    sourceTitle: '오늘의집 원룸 입주청소 가격표',
    sourceUrl: 'https://ohou.se/advices/12375',
    sourceEvidence: [
      '오늘의집 글은 10평 기준 20만~30만 원, 청소 범위/인원/날짜에 따른 비용 차이, 주말/성수기 20~30% 상승 가능성, 추가 비용 발생 포인트를 설명한다.',
      '업체 선택 기준으로 최소 2~3곳 비교, 후기 확인, 추가 비용 여부, 서비스 범위 확인을 제시하고 원룸 입주청소 체크리스트를 제공한다.',
    ],
    userScenario: '사용자는 원룸 입주 전 셀프 청소와 업체 청소 비용을 비교하고 2~3개 업체 견적의 포함/제외 범위와 재청소 기준을 정리하려 한다.',
    naturalArtifacts: [
      {
        kind: 'comparison_table',
        artifactTitle: '입주청소 견적 비교표',
        simulatedInputs: ['평수=9평', '입주일=2026-07-01', '후보A=18만원 기본청소', '후보B=24만원 창틀 포함', '추가=곰팡이/베란다 확인'],
        expectedOutput: [
          '업체명과 견적 금액',
          '기본/고급 청소 범위',
          '창틀, 베란다, 곰팡이 제거 포함 여부',
          '주말/성수기 추가비',
          '재청소 기준과 예약 가능일',
          '선택 여부',
        ],
        currentFlowMatch: '현재 checklist는 청소 범위 확인에는 맞지만 견적 후보 비교가 핵심 산출물로 보이지 않는다.',
        currentUxSupport: 'decision Flow 비교표 UX가 있지만 이 입주청소 checklist에는 아직 연결되어 있지 않다.',
        gap: '비용이 걸린 주거 Flow는 업체 후보 비교표를 먼저 보여줘야 한다.',
      },
      {
        kind: 'checklist',
        artifactTitle: '청소 후 검수/재청소 요청 체크리스트',
        simulatedInputs: ['청소일=2026-06-29', '확인공간=화장실/주방/창틀', '미흡=창틀 먼지', '증빙=사진 6장'],
        expectedOutput: ['공간별 사진 체크', '계약 범위 대비 미흡 목록', '재청소 요청 메시지', '재확인일', '입주 전 최종 확인'],
        currentFlowMatch: '입주청소 준비 항목은 있지만 청소 후 검수와 재청소 요청 단계가 약하다.',
        currentUxSupport: '메모는 가능하나 사진/증빙 중심 검수 카드가 없다.',
        gap: '청소 Flow는 계약 전 비교와 작업 후 검수라는 두 산출물이 분리되어야 한다.',
      },
    ],
    currentContentGap: '원본은 가격 구조와 업체 선택 기준이 핵심인데 현재 Flow는 단순 준비 체크리스트로 축소되어 있다.',
    currentUxGap: '견적 비교, 추가비 확인, 재청소 증빙 메모가 연결되지 않는다.',
    nextContentAction: '입주청소 Flow를 비용 비교, 계약 전 포함범위 확인, 청소 후 검수로 재구성한다.',
    nextUxAction: 'financial-sensitive checklist에 comparison_table과 proof memo를 결합한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-thankyou-bubu-home-workout-starter',
    checkedAt: '2026-05-25',
    sourceTitle: '전신 다이어트 최고의 운동 [점프 없음, 눕는동작 없음, 반복 없음, 토크 없음] - ThankyouBUBU',
    sourceUrl: 'https://www.youtube.com/watch?v=pcyrlkHXAdE',
    sourceEvidence: [
      'YouTube oEmbed confirms video id pcyrlkHXAdE is titled "전신 다이어트 최고의 운동 [점프❌ 눕는동작❌ 반복❌ 토크❌]" by Thankyou BUBU.',
      'This replaces the former channel-level source with one exact starter-friendly workout video source.',
    ],
    userScenario: '사용자는 홈트를 처음 시작하려고 채널을 둘러본 뒤 무릎 부담, 운동 가능 요일, 하루 운동 시간을 기준으로 시작 루틴을 고르려 한다.',
    naturalArtifacts: [
      {
        kind: 'comparison_table',
        artifactTitle: '초보 홈트 영상 선택표',
        simulatedInputs: ['운동경험=초보', '무릎상태=불편함', '가능시간=20분', '목표=가볍게 시작'],
        expectedOutput: ['후보 영상/루틴, 소요 시간, 충격도, 준비물, 쉬운 대체 동작, 선택 여부'],
        currentFlowMatch: '현재 Flow는 exact 영상 1개를 가리키므로 사용자가 어떤 영상을 열지 추측하지 않아도 된다.',
        currentUxSupport: 'decision comparison UI 없이도 원본 영상 링크와 준비/기록 항목이 연결된다.',
        gap: '대표 후보가 되려면 broad 후보 선택표보다 exact 영상 실행 요약과 몸 상태 기록 밀도를 더 다듬어야 한다.',
      },
      {
        kind: 'routine_calendar',
        artifactTitle: '4주 홈트 시작 캘린더',
        simulatedInputs: ['시작일=2026-06-01', '반복=월/수/금', '기간=4주', '강도=초보'],
        expectedOutput: ['월/수/금 홈트 일정', '1주차 적응 루틴', '2주차 반복 유지', '운동 후 컨디션 메모', '4주차 지속 여부 리뷰'],
        currentFlowMatch: 'routine calendar가 exact 영상 링크와 연결되어 반복 실행으로 옮길 수 있다.',
        currentUxSupport: '반복 캘린더는 가능하지만 초보 적응 단계와 컨디션 기록은 아직 exact-video route만큼 압축되어 있지 않다.',
        gap: 'starter Flow는 영상 실행 요약, 몸 상태 기록, 중단 조건을 한 화면에서 더 가볍게 보여줘야 한다.',
      },
    ],
    currentContentGap: 'exact 영상은 붙었지만 기존 5-step starter Flow는 exact workout video의 단일 실행 요약보다 여전히 무겁다.',
    currentUxGap: '반복 캘린더와 컨디션 기록은 가능하지만 exact-video execution panel처럼 요약, 원본 영상, 기록, 중단 조건이 압축되어 있지 않다.',
    nextContentAction: 'starter Flow를 exact-video 실행 요약 중심으로 더 줄이고, 원본 영상에서 확인할 항목과 사용자 기록 필드만 남긴다.',
    nextUxAction: 'routine calendar와 condition memo를 유지하되 첫 화면에서는 원본 영상 실행과 몸 상태 기록을 먼저 보이게 한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-thankyou-bubu-20min-routine',
    checkedAt: '2026-05-25',
    sourceTitle: '전신 다이어트 최고의 운동 [칼소폭 찐 핵핵핵 매운맛] - ThankyouBUBU',
    sourceUrl: 'https://www.youtube.com/watch?v=gSz5n4sLENI',
    sourceEvidence: [
      'YouTube oEmbed confirms video id gSz5n4sLENI is titled "전신 다이어트 최고의 운동 [칼소폭 찐 핵핵핵 매운맛]" by Thankyou BUBU.',
      'This replaces the former channel-level source with one exact workout video source for the recurring routine.',
    ],
    userScenario: '사용자는 매일은 부담스럽지만 주 4회 20분 홈트를 반복하려고 운동일과 휴식일을 정하고 월간 캘린더에 박아두려 한다.',
    naturalArtifacts: [
      {
        kind: 'routine_calendar',
        artifactTitle: '20분 홈트 월간 반복 캘린더',
        simulatedInputs: ['시작일=2026-06-02', '반복=화/목/토/일', '회차시간=20분', '휴식=월/수/금'],
        expectedOutput: ['화/목/토/일 20분 운동 일정', '월/수/금 휴식 표시', '주간 완료 횟수', '피로도/무릎 부담 메모'],
        currentFlowMatch: '반복 루틴이 exact 영상 링크와 연결되어 사용자가 어떤 영상을 반복할지 알 수 있다.',
        currentUxSupport: 'routine recurrence는 보이지만 쉬는 날과 주간 완료 요약이 충분히 강조되지 않는다.',
        gap: 'near-20-minute routine은 월간 캘린더에 운동일/휴식일/회차수를 한눈에 보여줘야 한다.',
      },
      {
        kind: 'memo',
        artifactTitle: '20분 루틴 조정 메모',
        simulatedInputs: ['대체=무릎 불편하면 점프 제외', '컨디션=피로 높으면 스트레칭만', '리뷰=매주 일요일'],
        expectedOutput: ['대체 동작, 중단 기준, 피로도 조정, 다음 주 반복 유지/변경'],
        currentFlowMatch: '현재 Flow는 반복만 만들 수 있고 컨디션에 따른 조정 기준은 약하다.',
        currentUxSupport: 'item memo는 있지만 반복 루틴의 공통 기준 카드로 export되지 않는다.',
        gap: '루틴 Flow는 회차별 체크와 별개로 공통 조정 메모가 필요하다.',
      },
    ],
    currentContentGap: 'exact 영상은 붙었지만 강도가 높은 전신 운동이므로 반복 기준과 중단 조건이 더 선명해야 한다.',
    currentUxGap: '월간 반복 캘린더, 휴식일, 주간 완료 요약, 공통 조정 메모가 한 화면에서 연결되지 않는다.',
    nextContentAction: 'near-20-minute exact 영상 반복 루틴에 휴식일, 강도 조정, 중단 조건을 더 명확히 둔다.',
    nextUxAction: 'routine Flow에 rest-day display, weekly completion summary, shared adjustment memo를 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-fitvely-diet-record-routine',
    checkedAt: '2026-05-25',
    sourceTitle: '【영양학】 다이어트 식단, 이 영상으로 g단위 완벽정리 해드림 - FITVELY',
    sourceUrl: 'https://www.youtube.com/watch?v=qcTxaFMWzKs',
    sourceEvidence: [
      'YouTube oEmbed confirms video id qcTxaFMWzKs is titled "【영양학】 다이어트 식단, 이 영상으로 g단위 완벽정리 해드림 (단백질/탄수화물/식이섬유/지방)" by 핏블리 FITVELY.',
      'This replaces the former official-site source with one exact nutrition video source for diet-record conversion.',
    ],
    userScenario: '사용자는 다이어트 중 매일 식사, 운동, 체중, 컨디션을 기록하고 주 1회 무엇을 조정할지 보기 위해 엑셀형 기록표를 만들려 한다.',
    naturalArtifacts: [
      {
        kind: 'spreadsheet',
        artifactTitle: '4주 식단/운동 기록표',
        simulatedInputs: ['기간=2026-06-01~2026-06-28', '기록=아침/점심/저녁/간식', '운동=주3회', '체중측정=월/목'],
        expectedOutput: ['날짜, 식사 요약, 단백질/탄수화물 기준, 운동 여부, 체중, 컨디션, 다음날 조정'],
        currentFlowMatch: '현재 Flow는 식단 기록 루틴이라는 틀은 있으나 daily sheet의 열 구조와 주간 리뷰가 약하다.',
        currentUxSupport: '엑셀 export는 가능하지만 식단 기록 전용 sheet가 자동 생성되는 수준은 아니다.',
        gap: 'diet-record Flow는 체크리스트보다 spreadsheet가 1차 산출물이어야 한다.',
      },
      {
        kind: 'routine_calendar',
        artifactTitle: '식단 기록 리마인더 캘린더',
        simulatedInputs: ['기록시간=매일 22:00', '측정=월/목 아침', '리뷰=일요일 저녁'],
        expectedOutput: ['매일 밤 기록 리마인더', '월/목 체중 측정', '일요일 주간 리뷰', '기록 누락 확인'],
        currentFlowMatch: '기록 루틴과 측정 루틴이 함께 보여야 하지만 현재는 단일 루틴에 가깝다.',
        currentUxSupport: '서로 다른 반복 주기를 한 Flow에서 시각화하는 기능이 부족하다.',
        gap: '식단 기록은 daily log와 weekly/monthly review recurrence를 함께 가져야 한다.',
      },
    ],
    currentContentGap: 'exact 영상은 붙었지만 FLOW가 영상의 식단 기준을 사용자 기록 열과 주간 조정 메모로 충분히 압축하지 못한다.',
    currentUxGap: '식단 기록 전용 spreadsheet, 다중 반복 리마인더, 주간 리뷰가 연결되지 않는다.',
    nextContentAction: 'FITVELY diet record Flow를 exact source 기반 식단 기록 열, 선택 기준, 중단/상담 조건 중심으로 더 줄인다.',
    nextUxAction: 'diet Flow에 spreadsheet-first preview와 multiple reminder rules를 추가한다.',
    decision: 'reshape_content_or_ux',
  },
  {
    slug: 'real-fitvely-weekly-body-check',
    checkedAt: '2026-05-22',
    sourceTitle: 'FITVELY 공식 사이트',
    sourceUrl: 'https://www.fitvely.com/',
    sourceEvidence: [
      'seed metadata uses the broad FITVELY official site as the source for weekly body-check behavior.',
      'search results support FITVELY as a fitness/diet creator brand, but not a specific weekly check-in guide for measurements, photos, or review decisions.',
    ],
    userScenario: '사용자는 매주 같은 조건으로 체중, 사진, 둘레, 운동 수행률을 기록하고 다음 주 식단/운동을 조정하려 한다.',
    naturalArtifacts: [
      {
        kind: 'spreadsheet',
        artifactTitle: '주간 바디 체크 기록표',
        simulatedInputs: ['체크일=매주 월요일 아침', '측정=체중/허리/사진', '리뷰=운동횟수/식단준수', '목표=8주'],
        expectedOutput: ['주차, 체중, 허리둘레, 사진 위치, 운동 횟수, 식단 준수, 컨디션, 다음 주 조정'],
        currentFlowMatch: '현재 Flow는 주간 체크라는 방향은 맞지만 측정값과 사진 증거를 구조화하지 않는다.',
        currentUxSupport: 'item memo는 가능하지만 주차별 수치 변화와 사진 위치를 보는 sheet preview가 없다.',
        gap: 'body-check Flow는 반복 체크보다 주차별 기록표가 핵심이다.',
      },
      {
        kind: 'memo',
        artifactTitle: '다음 주 조정 메모',
        simulatedInputs: ['변화=체중 -0.2kg', '운동=3/4회', '식단=주말 과식', '조정=주말 간식 제한'],
        expectedOutput: ['이번 주 해석, 유지할 것, 바꿀 것, 다음 체크 전 확인할 것'],
        currentFlowMatch: '현재 Flow는 완료 체크 위주라 측정 결과를 해석해 다음 행동으로 바꾸는 메모가 약하다.',
        currentUxSupport: '주간 리뷰 memo card가 export에 독립적으로 나오지 않는다.',
        gap: '주간 바디 체크는 수치 기록과 해석 메모가 같이 필요하다.',
      },
    ],
    currentContentGap: 'broad official site source라 주간 측정 항목과 조정 기준을 직접 검증할 수 없다.',
    currentUxGap: '측정 spreadsheet와 다음 주 조정 memo가 Flow의 주 산출물로 보이지 않는다.',
    nextContentAction: 'weekly body-check Flow는 exact body-check source로 교체하고 측정/사진/조정 기준을 확정한다.',
    nextUxAction: 'diet tracking Flow에 weekly measurement sheet and review memo export를 추가한다.',
    decision: 'keep_catalog_review',
  },
];

export function getNaturalArtifactAudit(slug: string): RealSourceNaturalArtifactAudit | undefined {
  return realSourceNaturalArtifactAudits.find((audit) => audit.slug === slug);
}

export function summarizeNaturalArtifactAuditCoverage(
  bundles: FlowBundle[],
): NaturalArtifactAuditCoverageSummary {
  const realSourceBundles = bundles.filter((bundle) => bundle.flow.source_status === 'real');
  const auditedSlugs = new Set(realSourceNaturalArtifactAudits.map((audit) => audit.slug));
  const auditedCategoryCounts: Record<string, number> = {};
  const decisionCounts: DecisionCounts = { ...emptyDecisionCounts };

  for (const audit of realSourceNaturalArtifactAudits) {
    const bundle = realSourceBundles.find((entry) => entry.flow.slug === audit.slug);
    if (bundle) {
      auditedCategoryCounts[bundle.flow.category] = (auditedCategoryCounts[bundle.flow.category] ?? 0) + 1;
    }
    decisionCounts[audit.decision] += 1;
  }

  return {
    realSourceCount: realSourceBundles.length,
    auditedRealSourceCount: realSourceBundles.filter((bundle) => auditedSlugs.has(bundle.flow.slug)).length,
    remainingRealSourceCount: realSourceBundles.filter((bundle) => !auditedSlugs.has(bundle.flow.slug)).length,
    auditedCategoryCounts,
    decisionCounts,
  };
}
