import { parseTextFlow } from './parser';import { FlowBundle } from './types';
const now=new Date().toISOString();
const make=(flow:any,text:string)=>{const p=parseTextFlow(text,flow.id);return {...p,flow:{...flow,created_at:now,updated_at:now,content_type:flow.content_type??'default'}} as FlowBundle};
export const seedBundles:FlowBundle[]=[
make({id:'flow-moving',slug:'moving-d30-basic',title:'이사 D-30 준비 Flow',category:'이사',structure_type:'timeline',anchor_type:'end_date',status:'published',risk_level:'low',source_title:'이사 체크리스트 참고',source_url:'https://www.ajd.co.kr/contents/basic-tip/detail/이사_준비_체크리스트_완벽정리!_엑셀_Xls_PDF_노션_notion_첨부-23363'},`## D-30 큰 준비\n- 이사 방식 정하기 D-30\n- 이사할 집 하자 점검하기 D-30\n- 필요 없는 물건 정리하기 D-30\n- 이사/청소 업체 견적 받고 예약하기 D-30\n## D-10 생활 이전 준비\n- 우편물/카드/은행 주소 변경하기 D-10\n- 정기 배달 서비스 중지 요청하기 D-10\n- 엘리베이터 또는 사다리차 사용 예약하기 D-10\n- 인터넷/정수기 이전 설치 예약하기 D-10\n## D-3 필수 예약 확인\n- 도시가스 철거/설치 예약하기 D-3\n- 자동이체 해지 또는 변경 확인하기 D-3\n- 이사 당일 사용할 물건 따로 포장하기 D-3\n## D-1 최종 점검\n- 이사 업체와 일정 최종 확인하기 D-1\n- 이체 한도 증액 확인하기 D-1\n- 귀중품과 중요 서류 별도 보관하기 D-1\n## D-Day 이사 당일\n- 전기/가스/수도/관리비 정산하기 D-Day\n- 이삿짐 분실/파손 확인하기 D-Day\n- 전입신고와 확정일자 확인하기 D-Day`),
make({id:'flow-routine',slug:'home-workout-20min',title:'하루 20분 전신 홈트 Flow',category:'운동/홈트',structure_type:'routine',anchor_type:'start_date',status:'published',risk_level:'medium',source_title:'홈트 루틴 참고',source_url:'https://hyeondams.tistory.com/185',warning:'통증이 있거나 질환이 있는 경우 무리하지 말고 전문가와 상담하세요.'},`@주 3회\n## 준비 운동 5분\n- 제자리 걷기 1분\n- 팔 돌리기 앞/뒤 각 30초\n- 무릎 들어 걷기 1분\n- 가벼운 점핑잭 1분\n## 본 운동 20분\n@2~3세트\n- 스쿼트 15회\n- 런지 양쪽 10회씩\n- 점핑잭 30초\n- 푸시업 10~15회\n- 플랭크 숄더탭 30초\n- 크런치 15회\n- 러시안 트위스트 20회\n- 플랭크 30초\n## 마무리 스트레칭 5분\n- 햄스트링 늘리기\n- 고양이-소 자세\n- 어깨/팔/목 스트레칭\n- 복식 호흡으로 마무리`),
make({id:'flow-check',slug:'job-change-risk-check',title:'이직 전 리스크 점검 Flow',category:'커리어/이직',structure_type:'checklist',anchor_type:'none',status:'published',risk_level:'financial_sensitive',source_title:'이직 준비 체크리스트 참고',source_url:'https://luckysuni-diary.tistory.com/102'},`## 1. 퇴사 가능 상태 확인\n- 근로계약서에서 퇴사 통보 기한 확인하기\n- 현재 업무 인수인계 범위 정리하기\n- 남은 연차, 급여, 퇴직금 예상 금액 확인하기\n- 퇴사 시점이 프로젝트 일정과 충돌하는지 확인하기\n## 2. 이직할 회사 조건 비교\n- 연봉과 복리후생 비교하기\n- 근무 지역과 출퇴근 시간 확인하기\n- 업무 강도와 성장 가능성 비교하기\n- 회사 리뷰와 내부 분위기 조사하기\n## 3. 지원 서류 업데이트\n- 최신 경력과 성과를 이력서에 반영하기\n- 지원 회사에 맞게 자기소개서 수정하기\n- 포트폴리오가 필요한 직무라면 최신 작업물 정리하기\n## 4. 면접 준비\n- 지원 직무 예상 질문 정리하기\n- 이전 회사에서의 성과와 기여도 사례 준비하기\n- 비대면 면접 환경 점검하기\n## 5. 재정 안전장치 확인\n- 공백 기간을 가정해 최소 3개월치 생활비 계산하기\n- 퇴직금과 실업급여 가능 여부 확인하기\n- 새 회사 급여 지급일과 기존 자금 흐름 비교하기`),
{flow:{id:'flow-meal',slug:'baby-food-menu-recipe',title:'초기 이유식 메뉴·레시피 Flow',category:'육아/이유식',structure_type:'phase',content_type:'meal_plan',anchor_type:'start_date',status:'published',risk_level:'medical_sensitive',source_title:'초기 이유식 식단표 참고',source_url:'https://kimstar1021.tistory.com/63',created_at:now,updated_at:now,warning:'이 Flow는 제작자 경험 기반의 식단표와 레시피를 시작일 기준으로 정리한 것입니다. 아이의 건강 상태, 알레르기, 시작 시기, 재료 선택은 전문가 또는 공식 정보를 확인하세요.'},sections:[{id:'m1',flow_id:'flow-meal',title:'초기 1단계',order:0},{id:'m2',flow_id:'flow-meal',title:'초기 2단계',order:1}],items:[],mealSlots:[{id:'ms1',flow_id:'flow-meal',section_id:'m1',recipe_id:'r1',day_offset:0,duration_days:3,menu_title:'쌀미음',new_ingredients:['쌀'],order:0},{id:'ms2',flow_id:'flow-meal',section_id:'m1',recipe_id:'r2',day_offset:3,duration_days:3,menu_title:'찹쌀미음',new_ingredients:['찹쌀'],order:1},{id:'ms3',flow_id:'flow-meal',section_id:'m1',recipe_id:'r3',day_offset:6,duration_days:3,menu_title:'애호박미음',new_ingredients:['애호박'],order:2},{id:'ms4',flow_id:'flow-meal',section_id:'m1',recipe_id:'r4',day_offset:9,duration_days:3,menu_title:'청경채미음',new_ingredients:['청경채'],order:3},{id:'ms5',flow_id:'flow-meal',section_id:'m2',recipe_id:'r5',day_offset:30,duration_days:3,menu_title:'소고기미음',new_ingredients:['소고기'],order:4},{id:'ms6',flow_id:'flow-meal',section_id:'m2',recipe_id:'r6',day_offset:33,duration_days:3,menu_title:'단호박미음',new_ingredients:['단호박'],order:5}],recipes:[1,2,3,4,5,6].map(n=>({id:`r${n}`,flow_id:'flow-meal',title:['쌀미음','찹쌀미음','애호박미음','청경채미음','소고기미음','단호박미음'][n-1],ingredients:[{name:'재료 메모'}],steps:[{order:1,text:'충분히 익힌 후 아이에게 맞게 조절합니다.'}],source_type:'creator_experience',risk_level:'medical_sensitive' as const,storage_note:'위생적으로 보관',caution_note:n===5?'단백질 재료는 아이 상태에 따라 전문가 또는 공식 정보를 확인합니다.':undefined}))}
];
