import assert from 'node:assert/strict';
import test from 'node:test';
import {createTextAuthoringDocument} from '../../../lib/flow/integrated-poc/native-creator-vendor/text-authoring/parser';
import {applyAuthoringOperation} from '../../../lib/flow/integrated-poc/native-creator-vendor/text-authoring/operations';
import {createNativeCreatorDocumentOwner,applyNativeCreatorDocumentOperation,readNativeCreatorDocument} from '../../../lib/flow/integrated-poc/native-creator-document';
import {nativeInspectorPatch,nativeInspectorUnsafeReason,nativeSplitBoundaries,nativeInspectorLabels,nativeCalendarAlignment,nativeIssueViews} from './creator-native-context-model';
const now='2026-09-13T01:00:00.000Z';
const raw='# 출처 보존\n- [ ] 원래 작업\n  - 설명: 실제 설명\n  - 완료 기준: 증빙 남김\n  - 날짜: 2026-09-20\n  - 시간: 10:00\n  - 시간대: Asia/Seoul\n  - 장소: 회의실\n  - 소요 시간: 30분\n  - 반복: 매주 일\n  - 반복 종료: 3회\n  - 실행 조건: 가능할 때\n  - 자료: https://example.com/tool\n  - 출처: https://example.com/source\n  - 안내: 순서 유지\n  - 주의: 무리하면 중단\n- [ ] 다른 문서 항목\n  - 설명: 건드리지 않을 설명';
function document(text=raw){return createTextAuthoringDocument(text,{documentId:'native-helper',ownership:'creator',now});}
function owner(text:string){const d=document(text),r=createNativeCreatorDocumentOwner({id:'helper-owner',source:{storageKey:'flow:text-authoring:drafts:v1',draftId:'source-draft',versionId:'source-save',revisionId:d.revision.revisionId,documentJson:JSON.stringify(d)}},now);assert(r.ok);return r.owner;}
test('NCM01 all original 16 inspector keys preserve native values and omit embedded property prose from detail',()=>{const d=document(),patch=nativeInspectorPatch(d,d.parseResult.canonical.items[0]);assert.equal(Object.keys(patch).length,16);assert.deepEqual(Object.keys(patch),Object.keys(nativeInspectorLabels));assert.equal(patch.detail,'실제 설명');assert.equal(patch.source,'https://example.com/source');assert.equal(patch.guide,'순서 유지');assert.equal(patch.caution,'무리하면 중단');assert.equal(patch.time,'10:00');});
test('NCM02 full original sync operation changes source/canonical once, leaves unrelated bytes and one undo restores',()=>{const d=document(),i=d.parseResult.canonical.items[0],p={...nativeInspectorPatch(d,i),detail:'수정한 설명',time:'11:00',source:'https://example.com/new-source',guide:'바뀐 안내',caution:'바뀐 주의'};assert.equal(nativeInspectorUnsafeReason(d,i,p),undefined);const next=applyAuthoringOperation(d,{type:'sync_item_to_working_text',itemId:i.itemId,patch:p},{actorLane:'creator',now});assert.notEqual(next,d);assert(next.rawText.includes('시간: 11:00'));assert(next.rawText.endsWith('- [ ] 다른 문서 항목\n  - 설명: 건드리지 않을 설명'));assert.equal(next.parseResult.canonical.items[0].itemId,i.itemId);const undone=applyAuthoringOperation(next,{type:'undo'},{actorLane:'creator',now});assert.equal(undone.rawText,d.rawText);assert.deepEqual(undone.parseResult.canonical,d.parseResult.canonical);assert.deepEqual(undone.parseResult.mappings,d.parseResult.mappings);});
test('NCM03 duplicated property, invalid date and multiple links remain explicit 0-change',()=>{const duplicate=document(raw.replace('  - 설명: 실제 설명','  - 설명: 실제 설명\n  - 설명: 두 번째 설명')),item=duplicate.parseResult.canonical.items[0];assert(nativeInspectorUnsafeReason(duplicate,item,{...nativeInspectorPatch(duplicate,item),detail:'바꿀 설명'}));const d=document(),i=d.parseResult.canonical.items[0],p=nativeInspectorPatch(d,i);assert(nativeInspectorUnsafeReason(d,i,{...p,date:'2026-02-30'}));assert(nativeInspectorUnsafeReason(d,i,{...p,source:'https://example.com/a https://example.com/b'}));assert.equal(nativeInspectorUnsafeReason(d,i,p),undefined);});
test('NCM04 split candidates only use nonempty whitespace boundaries without UTF16 interior guessing',()=>{assert.deepEqual(nativeSplitBoundaries('🧭 준비  끝내기'),[{at:3,left:'🧭',right:'준비  끝내기'},{at:7,left:'🧭 준비',right:'끝내기'}]);assert.deepEqual(nativeSplitBoundaries('한단어'),[]);});
test('NCM05 native Calendar rank includes relative recurrence and time, aligns whole blocks per Step then undo restores raw',()=>{const o=owner('# 기준\n기준일: 2026-09-20\n## 첫 단계\n- [ ] 늦은 일\n  - 날짜: 2026-09-23\n- [ ] 상대 반복\n  - 상대 날짜: D+1\n  - 시간: 09:00\n  - 반복: 매일\n  - 반복 종료: 3회\n- [ ] 미정\n## 둘째 단계\n- [ ] 별도 단계\n  - 날짜: 2026-09-19'),plan=nativeCalendarAlignment(o);assert(plan.differs);assert.deepEqual(plan.afterTitles,['상대 반복','늦은 일','미정','별도 단계']);const read=readNativeCreatorDocument(o);assert(read.ok);assert.equal(read.projection.artifacts.calendar.rows[0].title,'별도 단계');const applied=applyNativeCreatorDocumentOperation(o,{expectedOwner:o,requestId:'align',operation:{type:'align_source_order',orderedItemIds:plan.orderedItemIds}},now);assert(applied.ok&&applied.changed);assert(applied.owner.document.rawText.indexOf('상대 반복')<applied.owner.document.rawText.indexOf('늦은 일'));assert.equal(nativeCalendarAlignment(applied.owner).differs,false);const undo=applyAuthoringOperation(applied.owner.document,{type:'undo'},{actorLane:'creator',now});assert.equal(undo.rawText,o.document.rawText);assert.deepEqual(undo.parseResult.canonical,o.document.parseResult.canonical);});
test('NCM06 ambiguous source after split cannot be forced through Calendar alignment',()=>{const o=owner('# 일\n- [ ] 늦은 두 작업\n  - 날짜: 2026-09-23\n- [ ] 이른 작업\n  - 날짜: 2026-09-20');const split=applyNativeCreatorDocumentOperation(o,{expectedOwner:o,requestId:'split',operation:{type:'split',itemId:o.document.parseResult.canonical.items[0].itemId,at:3}},now);assert(split.ok&&split.changed);const plan=nativeCalendarAlignment(split.owner);assert(plan.differs);const attempt=applyNativeCreatorDocumentOperation(split.owner,{expectedOwner:split.owner,requestId:'align-ambiguous',operation:{type:'align_source_order',orderedItemIds:plan.orderedItemIds}},now);assert(attempt.ok&&!attempt.changed);assert.equal(attempt.owner,split.owner);});
test('NCM07 classification reads original eligibility and native Undo restores decisions/lineage for every supported outcome',()=>{for(const outcome of ['hold','keep_source_only','convert_to_item'] as const){const o=owner('제주 여행은 여름에 사람이 많습니다.'),view=nativeIssueViews(o.document)[0];assert(view.outcomes.includes(outcome));const applied=applyNativeCreatorDocumentOperation(o,{expectedOwner:o,requestId:`classify-${outcome}`,operation:{type:'classify_issue',issueId:view.issue.issueId,outcome}},now);assert(applied.ok&&applied.changed);const loaded=JSON.parse(JSON.stringify(applied.owner));const undo=applyNativeCreatorDocumentOperation(loaded,{expectedOwner:loaded,requestId:`undo-${outcome}`,operation:{type:'undo'}},now);assert(undo.ok&&undo.changed);assert.deepEqual(undo.owner.document.parseResult.issues,o.document.parseResult.issues);assert.deepEqual(undo.owner.document.parseResult.canonical,o.document.parseResult.canonical);assert.deepEqual(undo.owner.document.parseResult.mappings,o.document.parseResult.mappings);assert.equal(undo.owner.document.rawText,o.document.rawText);assert.equal(undo.owner.source.documentJson,o.source.documentJson);}});
test('NCM08 no fake conversion for URL-only, unknown issue or wrong outcome; same held choice adds no receipt',()=>{const o=owner('https://example.com/source'),view=nativeIssueViews(o.document)[0];assert.deepEqual(view.outcomes,['hold']);for(const operation of [{type:'classify_issue' as const,issueId:view.issue.issueId,outcome:'convert_to_item' as const},{type:'classify_issue' as const,issueId:'missing-issue',outcome:'hold' as const}]){const result=applyNativeCreatorDocumentOperation(o,{expectedOwner:o,requestId:'forbidden',operation},now);assert(result.ok&&!result.changed);assert.equal(result.owner,o);}const held=applyNativeCreatorDocumentOperation(o,{expectedOwner:o,requestId:'hold',operation:{type:'classify_issue',issueId:view.issue.issueId,outcome:'hold'}},now);assert(held.ok);assert.deepEqual(nativeIssueViews(held.owner.document)[0].outcomes,[]);const again=applyNativeCreatorDocumentOperation(held.owner,{expectedOwner:held.owner,requestId:'hold-again',operation:{type:'classify_issue',issueId:view.issue.issueId,outcome:'hold'}},now);assert(again.ok&&!again.changed);assert.equal(again.owner.actions.length,1);});
