import test from 'node:test';import assert from 'node:assert/strict';import React from 'react';import {readFileSync,existsSync} from 'node:fs';import {createRequire} from 'node:module';import {resolve,dirname} from 'node:path';import {fileURLToPath} from 'node:url';import vm from 'node:vm';import ts from 'typescript';
import {materializePersonalWorkspacePocAuthoring} from '../../../lib/flow/personal-workspace-poc-authoring';
import {toPersonalWorkspacePocMapGroupRef} from '../../../lib/flow/personal-workspace-poc-contract';
import {createPersonalWorkspacePocState} from '../../../lib/flow/personal-workspace-poc-state';
import {prepareProgramInitialData} from '../../../lib/flow/integrated-poc/legacy-entry';
import type {ProgramEditorFlush} from '../../../lib/flow/integrated-poc/document-action';
import {programSame} from '../../../lib/flow/integrated-poc/controller';
const now='2026-09-13T00:00:00.000Z';
function harness(map=false){
 const source=materializePersonalWorkspacePocAuthoring({handoffId:'series-ui',documentId:'series-ui-doc',revisionId:'v1',committedAt:now,rawText:'# 계획\n- 기준일: 2026-09-18\n- [ ] 일반\n  - 상대 날짜: D+1\n- [ ] 상대 반복\n  - 상대 날짜: D+2\n  - 반복: 매일\n- [ ] 고정 반복\n  - 날짜: 2026-09-23\n  - 반복: 매주 수'});assert.ok(source.ok);
 const flowRef=source.flow.ref;
 const second=materializePersonalWorkspacePocAuthoring({handoffId:'series-ui-2',documentId:'series-ui-doc-2',revisionId:'v1',committedAt:now,rawText:source.rawText});assert.ok(second.ok);
 const flows=map?[source.flow,second.flow].map((flow,n)=>({...flow,presentation:{...flow.presentation,mapGroup:{groupRef:toPersonalWorkspacePocMapGroupRef('ui-synthetic'),ownerId:'ui-synthetic',title:'명시 합성 묶음',childOrder:n,childCount:2,executionState:'executable' as const,reviewReasons:[]}}})):[source.flow];
 let data=prepareProgramInitialData({baseModel:{version:1,flows},legacyState:createPersonalWorkspacePocState(now)}).data;
 let cursor=0,writes=0,calls=0,fail=false,port:ProgramEditorFlush|null=null;const slots:any[]=[];
 const hooks={...React,useState:(v:any)=>{const i=cursor++;if(!(i in slots))slots[i]=typeof v==='function'?v():v;return[slots[i],(n:any)=>{slots[i]=typeof n==='function'?n(slots[i]):n;}];},useRef:(v:any)=>{const i=cursor++;if(!(i in slots))slots[i]={current:v};return slots[i];},useEffect:(fn:()=>void)=>{const i=cursor++;if(!(i in slots)){slots[i]=true;fn();}}};
 const root=resolve(dirname(fileURLToPath(import.meta.url)),'../../..'),cache=new Map<string,any>();
 function load(path:string):any{if(cache.has(path))return cache.get(path);const req=createRequire(path),module={exports:{}};cache.set(path,module.exports);const output=ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;
  vm.runInThisContext(`(function(module,exports,require){${output}\n})`)(module,module.exports,(id:string)=>{if(id==='react')return hooks;if(id.endsWith('.css'))return{__esModule:true,default:{}};const resolved=id.startsWith('@/')?resolve(root,id.slice(2)):id.startsWith('.')?resolve(dirname(path),id):null;if(resolved&&existsSync(resolved+'.tsx'))return load(resolved+'.tsx');return req(resolved??id);});return module.exports;}
 const Component=load(resolve(root,'components/flow/integrated-poc/ProgramLegacyPlan.tsx'));
 const words=(n:any):string=>typeof n==='string'||typeof n==='number'?String(n):Array.isArray(n)?n.map(words).join(''):n?.props?words(n.props.children):'';
 function render(){cursor=0;const nodes:any[]=[];const tree=Component.ProgramLegacyPlan({data,flowRef,onRegisterEditors:(p:ProgramEditorFlush)=>{port=p;},mutate:async(_l:any,build:any)=>{calls++;if(fail)return{ok:false,reason:'quota'};const r=build(data);if(!r.ok)return{ok:false,reason:r.reason};if(r.changed)writes++;data=r.data;return{ok:true,result:r.result};}});function visit(n:any){if(Array.isArray(n))n.forEach(visit);else if(n?.props){if(typeof n.type==='function'){visit(n.type(n.props));return;}nodes.push(n);visit(n.props.children);}}visit(tree);return{nodes,button:(s:string)=>nodes.find(n=>n.type==='button'&&words(n)===s),buttons:()=>nodes.filter(n=>n.type==='button'),date:(index=0)=>nodes.filter(n=>n.type==='input'&&n.props.type==='date')[index],text:()=>words(tree)};}
 return{render,get data(){return data;},setData:(v:typeof data)=>{data=v;},get calls(){return calls;},get writes(){return writes;},get port(){return port!;},setFail:(v:boolean)=>{fail=v;}};
}
function open(h:ReturnType<typeof harness>){let v=h.render();v.button('기준일·항목 선택 검토').props.onClick();v=h.render();v.date().props.onChange({target:{value:'2026-09-25'}});return h.render();}
function choose(h:ReturnType<typeof harness>,index=0){let v=h.render();const row=v.buttons().filter(n=>Array.isArray(n.props.children)&&n.props.children.includes('원래 계획'))[index];assert.ok(row);row.props.onClick();v=h.render();assert.equal(v.nodes.filter(n=>n.type==='input'&&n.props.type==='radio').some(n=>n.props.checked),false);assert.equal(v.button('이 회차 선택 확인').props.disabled,true);v.nodes.find(n=>n.type==='input'&&n.props.type==='radio').props.onChange();v=h.render();v.nodes.find(n=>n.type==='label'&&Array.isArray(n.props.children)&&n.props.children[0]==='선택한 회차의 새 날짜').props.children[1].props.onChange({target:{value:'2026-09-27'}});v=h.render();v.button('이 회차 선택 확인').props.onClick();return h.render();}
test('mixed ordinary + fixed + relative series uses explicit empty selection, bounded dates and one parent apply; quota keeps choice',async()=>{
 const h=harness(),before=h.data;let v=open(h);assert.ok(v.button('이 날짜부터 회차 찾기'));assert.equal(h.writes,0);v.button('변경 비교').props.onClick();v=h.render();assert.equal(v.button('이 선택 적용'),undefined);
 v=choose(h);assert.equal(h.calls,0);v.button('변경 비교').props.onClick();v=h.render();assert.ok(v.button('이 선택 적용'));
 h.setFail(true);v.button('이 선택 적용').props.onClick();await new Promise(r=>setImmediate(r));v=h.render();assert.equal(h.writes,0);assert.ok(h.port.hasPendingInput?.());assert.ok(v.button('반복 선택 지우기'));
 h.setFail(false);v.button('이 선택 적용').props.onClick();await new Promise(r=>setImmediate(r));assert.equal(h.writes,1);assert.equal(Object.keys(h.data.spaces[h.data.activeActorId].recurrencePlans!.owners).length,1);assert.ok(!programSame(before,h.data));
});
test('unconfirmed child capture blocks parent compare, Escape/cancel and immediate lock are no write',()=>{
 const h=harness();let v=open(h);v.buttons().find(n=>Array.isArray(n.props.children)&&n.props.children.includes('원래 계획')).props.onClick();v=h.render();assert.ok(JSON.stringify(h.port.captureDrafts?.()).includes('seriesInputs'));v.button('변경 비교').props.onClick();v=h.render();assert.equal(v.button('이 선택 적용'),undefined);
 const release=h.port.lockInput();v.nodes.find(n=>n.type==='input'&&n.props.type==='radio').props.onChange();v=h.render();assert.ok(v.nodes.filter(n=>n.type==='input'&&n.props.type==='radio').every(n=>!n.props.checked));release();v=h.render();v.nodes.find(n=>n.props['aria-label']==='상대 반복 회차 변경 선택').props.onKeyDown({key:'Escape',preventDefault(){},stopPropagation(){}});v=h.render();assert.equal(v.button('이 회차 선택 확인'),undefined);v.button('취소').props.onClick();assert.equal(h.writes,0);assert.equal(h.calls,0);assert.equal(h.port.hasPendingInput?.(),false);
});
test('anchor or inclusion edits invalidate receipts, and a foreign snapshot prevents apply',async()=>{
 const h=harness();open(h);let v=choose(h);v.button('변경 비교').props.onClick();v=h.render();assert.ok(v.button('이 선택 적용'));v.date().props.onChange({target:{value:'2026-09-26'}});v=h.render();assert.equal(v.button('이 선택 적용'),undefined);assert.equal(v.button('반복 선택 지우기'),undefined);
 v=choose(h);v.button('변경 비교').props.onClick();v=h.render();const foreign=structuredClone(h.data);foreign.spaces[foreign.activeActorId].text.flows[0].title+=' 외부 수정';h.setData(foreign);v=h.render();assert.equal(v.button('이 선택 적용').props.disabled,true);v.button('이 선택 적용').props.onClick();await new Promise(r=>setImmediate(r));assert.equal(h.writes,0);
});
test('later date lookup is read only; IME cannot confirm; inclusion change invalidates confirmed preview',()=>{
 const h=harness(),before=JSON.stringify(h.data);let v=open(h);v.date(1).props.onChange({target:{value:'2027-03-01'}});v=h.render();v.button('이 날짜부터 회차 찾기').props.onClick();v=h.render();assert.ok(v.buttons().some(n=>Array.isArray(n.props.children)&&String(n.props.children[0]).startsWith('2027-03')));assert.equal(JSON.stringify(h.data),before);
 v.buttons().find(n=>Array.isArray(n.props.children)&&n.props.children.includes('원래 계획')).props.onClick();v=h.render();v.nodes.find(n=>n.type==='input'&&n.props.type==='radio').props.onChange();v=h.render();v.date(2).props.onChange({target:{value:'2027-03-08'}});v=h.render();const child=v.nodes.find(n=>n.type==='fieldset'&&n.props.onCompositionStart);child.props.onCompositionStart();v.button('이 회차 선택 확인').props.onClick();v=h.render();assert.equal(v.button('반복 선택 지우기'),undefined);child.props.onCompositionEnd();v.button('이 회차 선택 확인').props.onClick();v=h.render();v.button('변경 비교').props.onClick();v=h.render();assert.ok(v.button('이 선택 적용'));v.nodes.find(n=>n.type==='input'&&n.props.type==='checkbox').props.onChange({target:{checked:false}});v=h.render();assert.equal(v.button('이 선택 적용'),undefined);assert.equal(h.calls,0);assert.equal(JSON.stringify(h.data),before);
});
test('synthetic Map grouping of two genuine authored children confirms both series before one parent transaction',async()=>{
 const h=harness(true);let v=h.render();v.button('Map 기준일·항목 검토').props.onClick();v=h.render();v.date().props.onChange({target:{value:'2026-09-25'}});v=h.render();
 const rowCount=v.buttons().filter(n=>Array.isArray(n.props.children)&&n.props.children.includes('원래 계획')).length;assert.ok(rowCount>1);
 v=choose(h);v.button('변경 비교').props.onClick();v=h.render();assert.equal(v.button('Map 선택 적용'),undefined);
 v=choose(h,rowCount/2);v.button('변경 비교').props.onClick();v=h.render();assert.ok(v.button('Map 선택 적용'));assert.equal(h.calls,0);v.button('Map 선택 적용').props.onClick();await new Promise(r=>setImmediate(r));assert.equal(h.writes,1);assert.equal(Object.keys(h.data.spaces[h.data.activeActorId].recurrencePlans!.owners).length,2);
});
