'use client';
import React,{useEffect,useRef,useState} from 'react';
import type { ProgramData } from '@/lib/flow/integrated-poc/contract';
import type { ProgramEditorFlush } from '@/lib/flow/integrated-poc/document-action';
import { programSame } from '@/lib/flow/integrated-poc/controller';
import { programErrorMessage,type ProgramMutate } from '@/lib/flow/integrated-poc/ui-contract';
import { readProgramLegacyMapPlan,previewProgramLegacyMapPlan,applyProgramLegacyMapPlan,type ProgramLegacyMapPlanDraft } from '@/lib/flow/integrated-poc/program-legacy-map-plan';
import styles from './ProgramLegacyPlan.module.css';
import { ProgramLegacyPlanSeries, ProgramLegacySeriesComparison } from './ProgramLegacyPlanSeries';
type Props={data:ProgramData;flowRef:string;mutate:ProgramMutate;disabled?:boolean;onRegisterEditors?:(port:ProgramEditorFlush|null)=>void;onPendingChange?:(pending:boolean)=>void;canStart?:()=>boolean};
function issue(reason:string){return ({'source-review-required':'원본이 바뀌었습니다. 현재 하위 Flow와 항목 선택을 다시 확인해 주세요.','invalid-map-child-selection':'실제로 저장된 하위 Flow만 선택할 수 있습니다. 취소하고 다시 열어 주세요.','shared-anchor-required':'공통 기준일을 입력한 뒤 공통 날짜 따르기를 선택해 주세요.','empty-plan-policy-not-decided':'각 하위 Flow에서 한 항목 이상 선택해 주세요. 전체 제외의 저장 방식은 아직 정하지 않았습니다.','new-items-need-explicit-choice':'새 항목을 포함할지 제외할지 각각 선택해 주세요.','relative-series-anchor-owner-required':'바뀌는 상대 반복마다 회차·범위·새 날짜를 선택해 주세요.','excluded-series-reinclude-review-required':'제외한 반복은 기준일을 유지한 채 먼저 다시 포함해 주세요. 저장 후 기준일을 바꿀 수 있습니다.','duplicate-series-owner':'같은 반복 계획이 두 번 선택됐습니다. 반복 선택을 지우고 각 항목의 현재 회차를 다시 골라 주세요.','unexpected-series-choice':'기준일이나 포함 범위가 바뀌었습니다. 반복 선택을 지우고 다시 확인해 주세요.','excluded-series-choice':'제외한 항목의 반복 변경 선택을 지워 주세요. 원문과 기록은 남습니다.','series-owner-conflict':'검토 중 반복 계획이 바뀌었습니다. 선택을 보관하고 취소한 뒤 다시 열어 주세요.','typed-source-schedule-required':'원문 일정의 상대 날짜를 확인하지 못했습니다. 기준일을 유지하고 포함 항목만 검토해 주세요.','invalid-anchor':'실제 날짜를 입력해 주세요.'} as Record<string,string>)[reason]??'계획을 안전하게 비교하지 못했습니다. 입력을 보관한 뒤 취소하고 다시 확인해 주세요.';}
export function ProgramLegacyMapPlan({data,flowRef,mutate,disabled,onRegisterEditors,onPendingChange,canStart}:Props){
 const actorId=data.activeActorId,live=useRef(data);live.current=data;const [draft,setDraft]=useState<ProgramLegacyMapPlanDraft|null>(null),pending=useRef(draft);pending.current=draft;const [preview,setPreview]=useState<ReturnType<typeof previewProgramLegacyMapPlan>|null>(null),[error,setError]=useState('');const expected=useRef(data.spaces[actorId]),busyRef=useRef(false),locks=useRef(0),ime=useRef(false);const [busy,setBusy]=useState(false),[locked,setLocked]=useState(false);
 const seriesInputs=useRef<Record<string,string>>({});
 const read=readProgramLegacyMapPlan(data,actorId,flowRef,new Date().toISOString());
 const hasPending=!!draft||busy;
 useEffect(()=>{onPendingChange?.(hasPending);return()=>onPendingChange?.(false);},[hasPending,onPendingChange]);
 useEffect(()=>{const port:ProgramEditorFlush={hasPendingInput:()=>!!pending.current||busyRef.current||ime.current,flushAll:async()=>!pending.current&&!busyRef.current&&!ime.current,lockInput:()=>{locks.current++;setLocked(true);return()=>{locks.current=Math.max(0,locks.current-1);setLocked(locks.current>0);};},pendingDocumentIds:()=>{const r=readProgramLegacyMapPlan(live.current,actorId,flowRef,new Date().toISOString());return r.ok?live.current.spaces[actorId].savedBindings.filter(b=>r.childFlowRefs.includes(b.flowRef)).map(b=>b.documentId):[];},captureDrafts:()=>pending.current?[{title:'Map 개인 기준일·포함 선택',raw:JSON.stringify({draft:pending.current,seriesInputs:seriesInputs.current},null,2)}]:[],blocksExternalSnapshot:()=>!!pending.current||busyRef.current||ime.current};onRegisterEditors?.(port);return()=>onRegisterEditors?.(null);},[actorId,flowRef,onRegisterEditors]);
 if(!read.ok)return <p role="status">{read.reason==='retained-map-child'?'이 Flow는 Map 실행에서 제외하고 기록을 보존 중입니다. 위의 구성 변경에서 다시 연결할 수 있습니다.':'Map 계획을 읽지 못했습니다. 원문과 개인 기록은 그대로 보관합니다.'}</p>;
 const blocked=busy||locked,stale=!!draft&&!programSame(expected.current,data.spaces[actorId]);
 const change=(next:ProgramLegacyMapPlanDraft)=>{if(busyRef.current||locks.current)return;if(pending.current){for(const [ref,child] of Object.entries(next.children)){const prior=pending.current.children[ref];if(next.personalAnchor!==pending.current.personalAnchor||!programSame(child.mode,prior?.mode)||!programSame(child.selection.includedItemRefs,prior?.selection.includedItemRefs)){next={...next,children:{...next.children,[ref]:{...child,selection:{...child.selection,seriesChoices:undefined}}}}};}}pending.current=next;setDraft(next);setPreview(null);setError('');};
 const cancel=()=>{if(busyRef.current||locks.current||ime.current)return;seriesInputs.current={};pending.current=null;setDraft(null);setPreview(null);setError('');};
 return <section className={styles.panel} aria-label="Map 개인 기준일과 포함 선택" onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();cancel();}}} onCompositionStart={()=>{ime.current=true;}} onCompositionEnd={()=>{ime.current=false;}}>
 <h3>Map 개인 계획</h3><p>공통 기준일은 공통 날짜를 따르는 하위 Flow에 적용합니다. 개별 기준일과 항목 포함 선택은 따로 유지합니다.</p><p>내 공통 기준일 {read.personalAnchor??'아직 지정하지 않음'}</p>
 {read.stale&&<p role="alert">Map 원본이 바뀌었습니다. 기존 기준일·포함 선택과 기록은 보관 중입니다. 현재 원본을 다시 검토해 주세요.</p>}
 {!draft?<button disabled={disabled||locked} onClick={()=>{if(disabled||locks.current||canStart?.()===false)return;expected.current=data.spaces[actorId];change({...(read.personalAnchor?{personalAnchor:read.personalAnchor}:{}),...(read.stale?{reviewSourceToken:read.token}:{}),children:Object.fromEntries(read.children.map(c=>{const added=!!read.saved&&!read.saved.childFlowRefs.includes(c.flow.ref);return[c.flow.ref,{mode:read.saved?.childModes[c.flow.ref]??(c.saved?.personalAnchor?{mode:'fixed-child',anchor:c.saved.personalAnchor}:{mode:'follow-group'}),selection:{includedItemRefs:added?[]:c.rows.filter(r=>r.included).map(r=>r.itemRef),...(c.stale?{reviewSourceToken:c.token}:{}),newItemChoices:{}}}];}))});}}>Map 기준일·항목 검토</button>:<>
 <label>새 공통 기준일 (비우면 현재 유지)<input type="date" value={draft.personalAnchor??''} disabled={blocked} onChange={e=>change({...draft,personalAnchor:e.target.value||undefined})}/></label>
 {read.children.map(child=>{const c=draft.children[child.flow.ref],added=!!read.saved&&!read.saved.childFlowRefs.includes(child.flow.ref);const setChild=(next:typeof c)=>change({...draft,children:{...draft.children,[child.flow.ref]:next}});return <fieldset key={child.flow.ref} disabled={blocked}><legend>{child.flow.title}</legend><label>이 Flow의 기준일<select value={c.mode.mode} onChange={e=>setChild({...c,mode:e.target.value==='follow-group'?{mode:'follow-group'}:{mode:'fixed-child',anchor:child.personalAnchor??''}})}><option value="follow-group">공통 날짜 따르기</option><option value="fixed-child">개별 기준일 고정</option></select></label>{c.mode.mode==='fixed-child'&&<label>개별 기준일<input type="date" value={c.mode.anchor} onChange={e=>setChild({...c,mode:{mode:'fixed-child',anchor:e.target.value}})}/></label>}<p>포함할 항목 · 제외해도 원문과 지난 기록은 남습니다.</p>{child.rows.map(row=>row.pending||added?<fieldset key={row.itemRef}><legend>{row.title} · 새 항목</legend>{[true,false].map(include=><label key={String(include)}><input type="radio" name={`map-new-${row.itemRef}`} checked={c.selection.newItemChoices?.[row.itemRef]===include} onChange={()=>setChild({...c,selection:{...c.selection,newItemChoices:{...c.selection.newItemChoices,[row.itemRef]:include},includedItemRefs:include?[...c.selection.includedItemRefs.filter(r=>r!==row.itemRef),row.itemRef]:c.selection.includedItemRefs.filter(r=>r!==row.itemRef)}})}/>{include?'포함':'제외'}</label>)}</fieldset>:<label key={row.itemRef}><input type="checkbox" checked={c.selection.includedItemRefs.includes(row.itemRef)} onChange={e=>setChild({...c,selection:{...c.selection,includedItemRefs:e.target.checked?[...c.selection.includedItemRefs,row.itemRef]:c.selection.includedItemRefs.filter(r=>r!==row.itemRef)}})}/>{row.title}</label>)}<ProgramLegacyPlanSeries data={data} read={child} anchor={c.mode.mode==='fixed-child'?c.mode.anchor:draft.personalAnchor??read.personalAnchor??undefined} included={c.selection.includedItemRefs} choices={c.selection.seriesChoices} disabled={blocked||stale} canEdit={()=>!busyRef.current&&!locks.current} onCapture={(id,raw)=>{if(raw)seriesInputs.current[id]=raw;else delete seriesInputs.current[id];setPreview(null);}} onChange={seriesChoices=>setChild({...c,selection:{...c.selection,seriesChoices}})}/></fieldset>;})}
 {stale&&<p role="alert">검토 중 개인 내용이 바뀌었습니다. 취소한 뒤 다시 비교해 주세요.</p>}<button disabled={blocked||stale} onClick={()=>{if(ime.current||Object.keys(seriesInputs.current).length){setError('열어 둔 회차 선택을 확인하거나 취소해 주세요.');return;}setPreview(previewProgramLegacyMapPlan(data,{actorId,flowRef,now:new Date().toISOString(),draft}));}}>변경 비교</button><button disabled={blocked} onClick={cancel}>취소</button>
 {preview&&(!preview.ok?<p role="alert">{issue(preview.reason)}</p>:<><p role="status">반복 계획 변경 {preview.previews.reduce((count,p)=>count+p.seriesPreviews.filter(row=>row.status==='changed').length,0)}개</p><p>일반 항목 계획 날짜 변경 {preview.counts.planDateChanges}개 · 일반 항목 실행 날짜 변경 {preview.counts.executionDateChanges}개 · 제외 {preview.counts.excluded}개 · 다시 포함 {preview.counts.restored}개</p>{preview.previews.map(p=><details key={p.read.flow.ref}><summary>{p.read.flow.title} · 계획 {p.counts.planDateChanges}개 / 실행 {p.counts.executionDateChanges}개 변경</summary><ProgramLegacySeriesComparison receipts={p.seriesPreviews} titles={Object.fromEntries(p.read.rows.map(r=>[r.itemRef,r.title]))}/><div role="region" aria-label={`${p.read.flow.title} 날짜와 포함 변화`} tabIndex={0} className={styles.comparison}><table><thead><tr><th>항목</th><th>계획 날짜</th><th>실행 날짜</th><th>포함</th></tr></thead><tbody>{p.rows.map(r=><tr key={r.itemRef}><td>{r.title}</td><td>{r.planDate??'미정'} → {r.afterDate??'미정'}</td><td>{r.executionDate??'미정'} → {r.afterExecutionDate??'미정'}</td><td>{r.afterIncluded?'포함':'제외·기록 보관'}</td></tr>)}</tbody></table></div></details>)}<p>원본 일정·품질 보류와 개인 고정·미정 날짜·진행 기록은 유지합니다.</p><button disabled={blocked||stale} onClick={()=>{if(busyRef.current||locks.current||ime.current||Object.keys(seriesInputs.current).length)return;busyRef.current=true;setBusy(true);void(async()=>{try{const result=await mutate('Map 개인 기준일·포함 선택',current=>applyProgramLegacyMapPlan(current,{actorId,flowRef,now:new Date().toISOString(),draft,expectedSpace:expected.current}));if(result.ok){seriesInputs.current={};pending.current=null;setDraft(null);setPreview(null);setError('');}else setError(programErrorMessage(result.reason));}catch{setError('저장하지 못했습니다. 입력은 유지했습니다.');}finally{busyRef.current=false;setBusy(false);}})();}}>Map 선택 적용</button></>)}{error&&<p role="alert">{error}</p>}
 </>}
 </section>;
}
