import assert from 'node:assert/strict';import test from 'node:test';
import './test-css-modules';
import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';
import {createRequire} from 'node:module';import {readFileSync} from 'node:fs';import {dirname,resolve} from 'node:path';import {fileURLToPath} from 'node:url';import vm from 'node:vm';import ts from 'typescript';
import {createProgramData} from '../../../lib/flow/integrated-poc/program-data';
import {setProgramCreatorWorking,applyProgramCreatorAction} from '../../../lib/flow/integrated-poc/creator-workspace';
import {fingerprintPersonalWorkspacePocAuthoringSource as fp} from '../../../lib/flow/personal-workspace-poc-authoring';
import type {ProgramCreatorWorkspaceProps,ProgramCreatorHistoryComparison} from './ProgramCreatorWorkspace';
import {previewProgramCreatorSavedRestore} from '../../../lib/flow/integrated-poc/creator-history';
const NOW='2026-09-12T01:00:00.000Z',DRAFT='creator-history-ui',A='# 예전\n- [ ] 먼저',B='# 최신\n- [ ] 나중';
function fixture(){let data=createProgramData();const actorId=data.activeActorId;
  for(const [i,rawText] of [A,B].entries()){const own=data.spaces[actorId].creatorWorkspace,w=own?.working??null;const working={draftId:DRAFT,title:'제작 제목',rawText,baseRecordRevision:own?.library.records[DRAFT]?.recordRevision??null};const set=setProgramCreatorWorking(data,{actorId,expectedWorking:w,working},NOW);assert(set.ok);data=set.data;
    const o=data.spaces[actorId].creatorWorkspace!;const save=applyProgramCreatorAction(data,{actorId,requestId:`save-ui-${i}`,action:{type:'save',draftId:DRAFT,title:working.title,rawText,sourceFingerprint:fp(rawText),expectedLibraryRevision:o.library.revision,...(working.baseRecordRevision?{expectedRecordRevision:working.baseRecordRevision}:{}),now:NOW}},NOW);assert(save.ok);data=save.data;}
  return data;}
const label=(v:any):string=>Array.isArray(v)?v.map(label).join(''):typeof v==='string'||typeof v==='number'?String(v):v?.props?label(v.props.children):'';
function harness(){let data=fixture(),at=0,writes=0,fail=false;const slots:any[]=[];let editorNode:any,snapshot:any={documentId:DRAFT,rawText:B,composing:false};
  const hooks={...React,useState:(initial:any)=>{const i=at++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return[slots[i],(value:any)=>slots[i]=typeof value==='function'?value(slots[i]):value];},useRef:(initial:any)=>{const i=at++;return slots[i]??=( {current:initial});},useMemo:(fn:any)=>{at++;return fn();},useEffect:()=>{at++;}};
  const url=new URL('./ProgramCreatorWorkspace.tsx',import.meta.url),require=createRequire(url),root=resolve(dirname(fileURLToPath(url)),'../../..');const loaded={exports:{} as {ProgramCreatorWorkspace:(p:ProgramCreatorWorkspaceProps)=>React.ReactNode;ProgramCreatorHistoryComparison:typeof ProgramCreatorHistoryComparison}};
  const code=ts.transpileModule(readFileSync(url,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;
  vm.runInThisContext(`(function(module,exports,require){${code}\n})`)(loaded,loaded.exports,(id:string)=>id==='react'?hooks:id.endsWith('.css')?{__esModule:true,default:{}}:require(id.startsWith('@/')?resolve(root,id.slice(2)):id));
  function render(){at=0;const tree=loaded.exports.ProgramCreatorWorkspace({data,mutate:async(_label,build)=>{if(fail)return{ok:false,reason:'storage'};const result=build(data);if(!result.ok)return{ok:false,reason:result.reason};if(result.changed)writes++;data=result.data;return{ok:true,result:result.result};},navigate:()=>{},today:'2026-09-13'});const nodes:any[]=[];function walk(v:any){if(Array.isArray(v))v.forEach(walk);else if(v?.props){nodes.push(v);walk(v.props.children);}}walk(tree);editorNode=nodes.find(n=>n.props.label==='제작 원문'&&n.props.onNativeInput);editorNode.props.ref.current={readSnapshot:()=>snapshot};return{nodes,button:(text:string)=>nodes.find(n=>n.type==='button'&&label(n.props.children).startsWith(text))};}
  const settle=async()=>{for(let i=0;i<20;i++)await Promise.resolve();};
  return{render,settle,Comparison:loaded.exports.ProgramCreatorHistoryComparison,get data(){return data;},get writes(){return writes;},fail(v:boolean){fail=v;},compose(v:boolean){snapshot={...snapshot,composing:v};},input(raw:string){snapshot={...snapshot,rawText:raw};editorNode.props.onNativeInput(snapshot,'insertText');},foreign(){data=structuredClone(data);data.spaces[data.activeActorId].creatorWorkspace!.working!.title='다른 탭';}};
}
test('CHUI01 comparison shows actual current/previous values and no implicit execution/public restore',()=>{const data=fixture(),entry=data.spaces[data.activeActorId].creatorWorkspace!.savedHistory!.drafts[DRAFT][0],preview=previewProgramCreatorSavedRestore(data,data.activeActorId,DRAFT,entry.id,null);assert(preview.ok);
  const Component=harness().Comparison;const html=renderToStaticMarkup(<Component preview={preview.value}/>);for(const text of ['# 최신','# 예전','개인 인계 문서·실행 기록·공개 판본은 바꾸지 않습니다.'])assert(html.includes(text));});
test('CHUI02 preview/cancel make zero writes, IME prevents comparison',()=>{const h=harness();h.compose(true);h.render().button('Program 저장 1').props.onClick();assert(!h.render().button('이 저장본의 원문으로 복구'));h.compose(false);h.render().button('Program 저장 1').props.onClick();assert(h.render().button('이 저장본의 원문으로 복구'));h.render().button('저장본 비교 닫기').props.onClick();assert.equal(h.writes,0);});
test('CHUI03 failed restore preserves comparison and request, retry commits once, old source remains in history',async()=>{const h=harness();h.render().button('Program 저장 1').props.onClick();h.fail(true);await h.render().button('이 저장본의 원문으로 복구').props.onClick();await h.settle();assert(h.render().button('이 저장본의 원문으로 복구'));assert.equal(h.writes,0);h.fail(false);
  const apply=h.render().button('이 저장본의 원문으로 복구').props.onClick;await Promise.all([apply(),apply()]);await h.settle();assert.equal(h.writes,1);assert.equal(h.data.spaces[h.data.activeActorId].creatorWorkspace!.working!.rawText,A);assert(h.data.spaces[h.data.activeActorId].creatorWorkspace!.savedHistory!.drafts[DRAFT].some(r=>r.rawText===B));});
test('CHUI04 typing after preview and source external changes cannot restore stale intent',async()=>{for(const mode of ['input','foreign'] as const){const h=harness();h.render().button('Program 저장 1').props.onClick();if(mode==='input')h.input(B+'\n유지할 입력');else h.foreign();await h.render().button('이 저장본의 원문으로 복구').props.onClick();await h.settle();assert.equal(h.writes,0);}});
