import test from 'node:test';import assert from 'node:assert/strict';import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';import {fileURLToPath} from 'node:url';
import {loadProgramPlanUi} from './ProgramLegacyPlan.test-support';
import {createProgramData} from '../../../lib/flow/integrated-poc/program-data';
import {createProgramController} from '../../../lib/flow/integrated-poc/controller';
import {createTextAuthoringDocument} from '../../../lib/flow/integrated-poc/native-creator-vendor/text-authoring/parser';
import {createNativeCreatorDocumentOwner} from '../../../lib/flow/integrated-poc/native-creator-document';
import {setProgramCreatorWorking,applyProgramCreatorAction} from '../../../lib/flow/integrated-poc/creator-workspace';
import {stageProgramNativeSourceUpdate,transitionProgramNativeSourceUpdate,upgradeProgramNativeSourceAbsences,readProgramNativeSourceUpdate} from '../../../lib/flow/integrated-poc/creator-native-source-store';
import {fingerprintPersonalWorkspacePocAuthoringSource as fp} from '../../../lib/flow/personal-workspace-poc-authoring';
import type {ProgramEditorFlush} from '../../../lib/flow/integrated-poc/document-action';
import type {ProgramCreatorSourceCommand} from './ProgramCreatorSourceUpdate';
const NOW='2026-09-12T08:00:00.000Z',RAW='# 작업\n- [ ] 준비\n  - 날짜: 2026-09-20',NEXT='# 작업\n- [ ] 새 준비\n  - 날짜: 2026-09-22';
function harness(){
 let data=createProgramData();const actorId=data.activeActorId,draftId='source-child';const document=createTextAuthoringDocument(RAW,{documentId:'real-document',ownership:'creator',now:NOW});
 const native=createNativeCreatorDocumentOwner({id:draftId,source:{storageKey:'flow:text-authoring:drafts:v1',draftId:'source-draft',versionId:'source-version',revisionId:document.revision.revisionId,documentJson:JSON.stringify(document)}},NOW);assert(native.ok);
 const set=setProgramCreatorWorking(data,{actorId,expectedWorking:null,working:{draftId,title:'작업',rawText:RAW,baseRecordRevision:null,nativeDocument:native.owner}},NOW);assert(set.ok);data=set.data;
 const save=applyProgramCreatorAction(data,{actorId,requestId:'save',expectedNativeDocument:native.owner,expectedStructure:null,action:{type:'save',draftId,title:'작업',rawText:RAW,sourceFingerprint:fp(RAW),expectedLibraryRevision:0,now:NOW}},NOW);assert(save.ok);data=save.data;
 const values=new Map<string,string>([['flow:protected',' exact ']]);let fail=false,writes=0,port:ProgramEditorFlush|null=null,cursor=0,calls=0;const slots:any[]=[];const jobs:Promise<unknown>[]=[];
 const controller=createProgramController({initialData:data,storage:{getItem:k=>values.get(k)??null,setItem:(k,v)=>{if(fail)throw Error('quota');values.set(k,v);writes++;},removeItem:()=>{throw Error('remove')}},exclusive:async f=>f()});assert(controller.ok);
 const snapshot=controller.snapshot;assert.equal(typeof snapshot,'function');
 const hooks={...React,useState:(initial:any)=>{const i=cursor++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return[slots[i],(v:any)=>slots[i]=typeof v==='function'?v(slots[i]):v]},useRef:(v:any)=>{const i=cursor++;return slots[i]??=( {current:v})},useMemo:(f:()=>any)=>{cursor++;return f()},useEffect:(f:()=>any)=>{const i=cursor++;if(!(i in slots)){slots[i]=true;f()}}};
 const module=loadProgramPlanUi(fileURLToPath(new URL('./ProgramCreatorSourceUpdate.tsx',import.meta.url)),hooks);
 const command=(c:ProgramCreatorSourceCommand)=>{calls++;const job=controller.mutate('child source',d=>c.kind==='stage'?stageProgramNativeSourceUpdate(d,c.input,c.now):c.kind==='upgrade'?upgradeProgramNativeSourceAbsences(d,c.input,c.now):transitionProgramNativeSourceUpdate(d,c.input,c.now),{actorId}).then(r=>r.ok?{ok:true as const}:{ok:false as const,reason:r.reason});jobs.push(job);return job};
  function render(){cursor=0;data=snapshot().envelope.data;const tree=module.ProgramCreatorSourceUpdate({data,working:data.spaces[actorId].creatorWorkspace!.working!,disabled:false,onCommand:command,onRegisterEditors:(p:ProgramEditorFlush)=>{port=p}});const nodes:any[]=[];function visit(n:any){if(Array.isArray(n))n.forEach(visit);else if(n?.props){nodes.push(n);visit(n.props.children)}}visit(tree);return{tree,nodes,button:(text:string)=>{const n=nodes.find(n=>n.type==='button'&&n.props.children===text);assert(n,`button ${text}`);return n},changeNodes:()=>nodes.filter(n=>typeof n.type==='function'&&n.props.change)};}
 async function settle(){await Promise.all(jobs);await Promise.resolve();await Promise.resolve();return render()}
 function prepare(){let v=render();v.button('새 원문과 비교').props.onClick();v=render();v.nodes.find(n=>n.type==='input').props.onChange({target:{value:'후속 원문'}});v.nodes.find(n=>n.type==='textarea').props.onChange({target:{value:NEXT}});v=render();v.button('원문 항목 확인').props.onClick();return render()}
 async function stage(){let v=prepare();const select=v.nodes.find(n=>n.type==='select');const options=select.props.children.flat(Infinity).filter((n:any)=>n?.type==='option'&&n.props.value);select.props.onChange({target:{value:options[0].props.value}});v=render();v.button('이 연결로 비교 시작').props.onClick();v=await settle();assert(!v.nodes.some(n=>n.props.role==='alert'),v.nodes.filter(n=>n.props.role==='alert').map(n=>n.props.children).join(','));return v}
 return{render,prepare,stage,settle,get port(){return port!},get writes(){return writes},get calls(){return calls},get data(){return controller.snapshot().envelope.data},get view(){const r=readProgramNativeSourceUpdate(controller.snapshot().envelope.data,actorId,draftId);assert(r?.ok);return r.value},fail(v:boolean){fail=v},protected(){return values.get('flow:protected')},html(){return renderToStaticMarkup(render().tree)}};
}
test('CSU01 actual child SSR, raw prepare explicit mapping stage uses real controller and preserves canonical working',async()=>{const h=harness();assert(h.html().includes('새 원문과 비교'));const before=h.data.spaces[h.data.activeActorId].creatorWorkspace!.working;await h.stage();assert.equal(h.writes,1);assert.deepEqual(h.data.spaces[h.data.activeActorId].creatorWorkspace!.working,before);assert(h.view.changes.length>0);assert.equal(h.protected(),' exact ');});
test('CSU02 prepared draft Escape/cancel, composition and lock preserve input with zero commands',async()=>{const h=harness();let v=h.prepare();assert(h.port.hasPendingInput?.());assert.equal(await h.port.flushAll(),false);assert(h.port.captureDrafts?.().length);const section=v.nodes.find(n=>n.props.onCompositionStartCapture);section.props.onCompositionStartCapture();v.nodes.find(n=>n.props.onKeyDown).props.onKeyDown({key:'Escape',nativeEvent:{isComposing:true},preventDefault(){},stopPropagation(){}});v.button('이 연결로 비교 시작').props.onClick();await h.settle();assert.equal(h.calls,0);section.props.onCompositionEndCapture();const release=h.port.lockInput();v=h.render();v.button('이 연결로 비교 시작').props.onClick();await h.settle();assert.equal(h.calls,0);release();v=h.render();v.nodes.find(n=>n.props.onKeyDown).props.onKeyDown({key:'Escape',nativeEvent:{isComposing:false},preventDefault(){},stopPropagation(){}});h.render();assert.equal(h.port.hasPendingInput?.(),false);assert.equal(h.writes,0);});
test('CSU03 quota decision retains visible choice and retry commits exactly once; apply and source Undo preserve public/private',async()=>{const h=harness();let v=await h.stage();h.fail(true);const first=v.changeNodes()[0];first.props.onChange('use_incoming');v=await h.settle();assert.equal(h.writes,1);assert.equal(v.changeNodes()[0].props.value,'use_incoming');assert(h.port.hasPendingInput?.());h.fail(false);v.button('같은 선택 저장 다시 시도').props.onClick();v=await h.settle();assert.equal(h.writes,2);for(const row of h.view.changes){v=h.render();const n=v.changeNodes().find(n=>n.props.change.changeId===row.changeId);if(n.props.value!=='use_incoming'){n.props.onChange('use_incoming');await h.settle()}}const before=h.data,working=before.spaces[before.activeActorId].creatorWorkspace!.working;v=h.render();assert.equal(v.button('선택한 원본 변경 적용').props.disabled,false);v.button('선택한 원본 변경 적용').props.onClick();v=await h.settle();assert.equal(h.view.status,'undo-available');assert.deepEqual(h.data.public,before.public);assert.deepEqual(h.data.spaces[before.activeActorId].text,before.spaces[before.activeActorId].text);v.button('이번 원본 반영 되돌리기').props.onClick();await h.settle();assert.equal(h.view.status,'reverted');assert.deepEqual(h.data.spaces[before.activeActorId].creatorWorkspace!.working,working);});
test('CSU04 defer closes safely and reopens saved decisions; reject leaves working untouched',async()=>{const h=harness();let v=await h.stage();const before=h.data.spaces[h.data.activeActorId].creatorWorkspace!.working;v.button('선택 보관하고 나중에').props.onClick();v=await h.settle();assert.equal(h.view.status,'deferred');assert.equal(h.port.hasPendingInput?.(),false);v.button('원본 비교 이어 보기').props.onClick();v=h.render();v.button('이번 원본 반영하지 않기').props.onClick();await h.settle();assert.equal(h.view.status,'rejected');assert.deepEqual(h.data.spaces[h.data.activeActorId].creatorWorkspace!.working,before);});
test('CSU05 defer quota retry must perform the same close presentation as first success',async()=>{const h=harness();let v=await h.stage();h.fail(true);v.button('선택 보관하고 나중에').props.onClick();v=await h.settle();assert.equal(h.writes,1);h.fail(false);v.button('같은 선택 저장 다시 시도').props.onClick();v=await h.settle();assert.equal(h.view.status,'deferred');assert.equal(h.writes,2);assert.equal(v.button('원본 비교 이어 보기').props['aria-expanded'],false);});

test('CSU06 three-value display distinguishes absent schedule and typed recurrence end without inferring dates',()=>{
 const module=loadProgramPlanUi(fileURLToPath(new URL('./ProgramCreatorSourceUpdate.tsx',import.meta.url)),React),format=module.programSourceValueText;
 assert.equal(format(null,'schedule'),'없음');assert.equal(format({kind:'absolute',raw:'2026-09-20',date:'2026-09-20',time:'10:00',timezone:'Asia/Seoul'},'schedule'),'2026-09-20\n시간: 10:00\n시간대: Asia/Seoul');
 assert.equal(format({kind:'relative',raw:'D-3',dayOffset:-3,anchorLabel:'이사일'},'schedule'),'이사일 -3일\n원문 표기: D-3');
 const rule={raw:'매주 월·수',frequency:'weekly',interval:1,weekdays:['MO','WE'],end:{mode:'count',count:3,raw:'3회'},sourceRowIds:['actual-row']};
 assert(format(rule,'recurrence').includes('1주마다 · 월·수요일'));assert(format(rule,'recurrence').includes('종료: 3회'));assert(!format(rule,'recurrence').includes('sourceRowIds'));
 assert(format({...rule,end:{mode:'until',date:'2026-10-01',raw:'2026-10-01까지'}},'recurrence').includes('종료: 2026-10-01까지'));
 assert(format({...rule,end:undefined},'recurrence').includes('종료 지정 없음'));
 const unsupported={...rule,unexpectedFact:'preserve me'};assert.equal(format(unsupported,'recurrence'),JSON.stringify(unsupported,null,2));
 assert.equal(format({kind:'unsupported',raw:'unknown',date:'2026-09-20'},'schedule'),JSON.stringify({kind:'unsupported',raw:'unknown',date:'2026-09-20'},null,2));
});

test('CSU07 removed item compares source fields with the current creator values and discloses complete properties',async()=>{
 const h=harness();await h.stage();const view=structuredClone(h.view),item=view.stagedOwner.document.parseResult.canonical.items[0];
 item.title='내가 수정한 제목';item.sourceTitle='이전 원본 제목';item.detail='내가 덧붙인 설명';item.sourceDetail='이전 출처 설명';
 const module=loadProgramPlanUi(fileURLToPath(new URL('./ProgramCreatorSourceUpdate.tsx',import.meta.url)),React),change={kind:'removed',activeItemId:item.itemId,changeId:'removed-ui-fixture',oldSourceValue:structuredClone(item),hasOwnedState:true,state:'open'};
 const tree=module.ProgramSourceChange({change,view,value:'later',disabled:false,onChange(){throw Error('render must not decide')}}),html=renderToStaticMarkup(tree);
 const columns=[...html.matchAll(/<pre[^>]*>([\s\S]*?)<\/pre>/g)].map(match=>match[1]);
 assert(columns[0].includes('이전 원본 제목'));assert(columns[0].includes('이전 출처 설명'));assert(!columns[0].includes('내가 수정한 제목'));
 assert(columns[1].includes('내가 수정한 제목'));assert(columns[1].includes('내가 덧붙인 설명'));assert.equal(columns[2],'없음');
 assert(html.includes('항목의 전체 속성 확인'));assert(columns[3].includes('sourceRowIds'));assert.equal(h.writes,1);
});

test('CSU08 child lists show actual checks before source identities and require an explicit choice without renderer writes',async()=>{
 const h=harness();await h.stage();const view=structuredClone(h.view),item=view.stagedOwner.document.parseResult.canonical.items[0],module=loadProgramPlanUi(fileURLToPath(new URL('./ProgramCreatorSourceUpdate.tsx',import.meta.url)),React);
 const old=[{subcheckId:'old-child',title:'여권 확인',sourceChecked:false,order:0,sourceRowIds:['old-row'],owner:'source'}],incoming=[{subcheckId:'new-child',title:'여권 확인',sourceChecked:true,order:0,sourceRowIds:['new-row'],owner:'source'}];
 const change={kind:'changed',field:'subchecks',changeId:'checks-display',activeItemId:item.itemId,incomingItemId:'incoming',oldSourceValue:old,userValue:old,incomingSourceValue:incoming,userOwner:'creator',workingFingerprint:'display-fixture',state:'open'};
 const tree=module.ProgramSourceChange({change,view,value:'later',disabled:false,onChange(){throw Error('render must not decide')}}),html=renderToStaticMarkup(tree),columns=[...html.matchAll(/<pre[^>]*>([\s\S]*?)<\/pre>/g)].map(m=>m[1]);
 assert.equal(columns[0],'[ ] 여권 확인');assert.equal(columns[1],'[ ] 여권 확인');assert.equal(columns[2],'[x] 여권 확인');assert(html.includes('하위 확인 목록'));assert(html.includes('개인 실행의 체크와 기록은 여기서 바꾸지 않습니다'));assert(html.includes('같은 내용도 비교하는 이유'));assert(columns[3].includes('new-row'));assert.equal(h.writes,1);
 assert.equal(module.programSourceValueText([],'subchecks'),'없음');const unknown=[{...old[0],extra:'retain unknown evidence'}];assert.equal(module.programSourceValueText(unknown,'subchecks'),JSON.stringify(unknown,null,2));
});
