import assert from 'node:assert/strict';import test from 'node:test';import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';
import {createRequire} from 'node:module';import {readFileSync} from 'node:fs';import {dirname,resolve} from 'node:path';import {fileURLToPath} from 'node:url';import vm from 'node:vm';import ts from 'typescript';
import {createTextAuthoringDocument} from '../../../lib/flow/integrated-poc/native-creator-vendor/text-authoring/parser';
import {createNativeCreatorDocumentOwner,applyNativeCreatorDocumentOperation,restoreNativeCreatorDocument} from '../../../lib/flow/integrated-poc/native-creator-document';
import type {ProgramCreatorNativeContextProps,ProgramCreatorNativeOperationRequest,ProgramCreatorNativeComparison,ProgramCreatorNativeResult,programNativeResultExpansion} from './ProgramCreatorNativeContext';
import type {ProgramEditorFlush} from '../../../lib/flow/integrated-poc/document-action';
const NOW='2026-09-12T01:00:00.000Z';
function fixture(raw='# 보존할 구조\n- [ ] 처음 할 일\n  - 날짜: 2026-09-20\n- [ ] 둘째 할 일'){const document=createTextAuthoringDocument(raw,{documentId:'native-ui-document',ownership:'creator',reviewRequirements:[{kind:'safety',reasonKey:'original-safety-review'}],now:NOW});const result=createNativeCreatorDocumentOwner({id:'native-ui',source:{storageKey:'flow:text-authoring:drafts:v1',draftId:'native-source-draft',versionId:'saved-1',revisionId:document.revision.revisionId,documentJson:JSON.stringify(document)}},NOW);assert(result.ok);return result.owner;}
const label=(node:any):string=>Array.isArray(node)?node.map(label).join(''):typeof node==='string'?node:node?.props?label(node.props.children):'';
const inspectorTitle=(screen:{nodes:any[]})=>screen.nodes.find(n=>n.type==='label'&&Array.isArray(n.props.children)&&n.props.children[0]==='제목').props.children[1];
function harness(raw?:string,onOpenSource?:ProgramCreatorNativeContextProps['onOpenSource']){let owner=fixture(raw),at=0,writes=0,fail=false,readonly=false,pendingRawText:string|undefined,selectedItemId:string|null|undefined,port:ProgramEditorFlush|null=null;const slots:any[]=[],requests:ProgramCreatorNativeOperationRequest[]=[],selections:Array<{ownerId:string;itemId:string|null}>=[];
 const hooks={...React,useState:(initial:any)=>{const i=at++;if(!(i in slots))slots[i]=initial;return[slots[i],(v:any)=>slots[i]=typeof v==='function'?v(slots[i]):v];},useRef:(initial:any)=>{const i=at++;return slots[i]??={current:initial};},useEffect:(fn:any)=>{at++;fn();}};
 const url=new URL('./ProgramCreatorNativeContext.tsx',import.meta.url),require=createRequire(url),root=resolve(dirname(fileURLToPath(url)),'../../..'),loaded={exports:{} as {ProgramCreatorNativeContext:(p:ProgramCreatorNativeContextProps)=>React.ReactNode;ProgramCreatorNativeComparison:typeof ProgramCreatorNativeComparison;ProgramCreatorNativeResult:typeof ProgramCreatorNativeResult;programNativeResultExpansion:typeof programNativeResultExpansion}};
 const code=ts.transpileModule(readFileSync(url,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;
 vm.runInThisContext(`(function(module,exports,require){${code}\n})`)(loaded,loaded.exports,(id:string)=>id==='react'?hooks:id.endsWith('.css')?{__esModule:true,default:{}}:require(id.startsWith('@/')?resolve(root,id.slice(2)):id));
 function inspect(tree:React.ReactNode){const nodes:any[]=[];function walk(n:any){if(Array.isArray(n))n.forEach(walk);else if(n?.props){nodes.push(n);walk(n.props.children);}}walk(tree);return{tree,nodes,text:label(tree),button:(text:string)=>nodes.find(n=>n.type==='button'&&label(n).startsWith(text)),field:(text:string)=>{const l=nodes.find(n=>n.type==='label'&&label(n).startsWith(text));return l&&nodes.find(n=>['input','textarea','select'].includes(n.type)&&Array.isArray(l.props.children)&&l.props.children.includes(n));}};}
 function render(){at=0;return inspect(loaded.exports.ProgramCreatorNativeContext({owner,onOpenSource,pendingRawText,selectedItemId,onSelectionChange:(ownerId,itemId)=>selections.push({ownerId,itemId}),readOnly:readonly,onRegisterEditors:value=>{port=value;},onOperation:async request=>{requests.push(request);if(fail)return{ok:false,reason:'storage-unavailable'};const result=applyNativeCreatorDocumentOperation(owner,request,request.now);if(!result.ok)return result;if(result.changed)writes++;owner=result.owner;if(request.operation.type==='sync_working_text_from_input')pendingRawText=undefined;return{ok:true};},onRestore:async request=>{if(fail)return{ok:false,reason:'storage-unavailable'};const result=restoreNativeCreatorDocument(owner,request,request.now);if(!result.ok)return result;if(result.changed)writes++;owner=result.owner;return{ok:true};}}));}
 return{render,selections,renderResult(){at=0;return inspect(loaded.exports.ProgramCreatorNativeResult({owner}));},Comparison:loaded.exports.ProgramCreatorNativeComparison,expansion:loaded.exports.programNativeResultExpansion,get owner(){return owner;},get writes(){return writes;},get requests(){return requests;},get port(){return port!;},fail(v:boolean){fail=v;},readonly(v:boolean){readonly=v;},pending(value:string){pendingRawText=value;},requestSelection(value:string|null|undefined){selectedItemId=value;},exclude(){const result=applyNativeCreatorDocumentOperation(owner,{expectedOwner:owner,requestId:'fixture-exclude',operation:{type:'exclude',itemId:owner.document.parseResult.canonical.items[0].itemId}},NOW);assert(result.ok);owner=result.owner;},foreign(){owner=structuredClone(owner);owner.id='changed-owner';},async settle(){for(let i=0;i<20;i++)await Promise.resolve();}};
}

test('NCUI36 native selection reports exact current owner and success target without adding writes',async()=>{
 const h=harness('# 구조\n- [ ] 첫 작업\n- [ ] 둘째 작업'),before=h.owner;
 h.render().button('둘째 작업').props.onClick();h.render();assert.deepEqual(h.selections.at(-1),{ownerId:before.id,itemId:before.document.parseResult.canonical.items[1].itemId});assert.equal(h.writes,0);
 h.render().button('첫 작업').props.onClick();h.render().button('같은 단계의 다음 항목과').props.onClick();h.fail(true);h.render().button('비교한 구조 적용').props.onClick();await h.settle();h.render();assert.equal(h.writes,0);
 h.fail(false);h.render().button('비교한 구조 적용').props.onClick();await h.settle();h.render();assert.equal(h.writes,1);assert.deepEqual(h.selections.at(-1),{ownerId:before.id,itemId:before.document.parseResult.canonical.items[0].itemId});assert.equal(h.owner.source.documentJson,before.source.documentJson);
});

test('NCUI37 explicitly missing restored selection clears the inspector without focusing a substitute or losing dirty input',()=>{
 const h=harness();h.render().button('둘째 할 일').props.onClick();h.render().field('작업 항목 제목').props.onChange({target:{value:'보존할 입력'}});h.requestSelection(null);h.render();assert.equal(h.render().field('작업 항목 제목').props.value,'보존할 입력');
 h.render().button('미확정 구조 입력 버리기').props.onClick();h.render();assert(!h.render().field('작업 항목 제목'));assert.deepEqual(h.selections.at(-1),{ownerId:h.owner.id,itemId:null});assert.equal(h.writes,0);
 const initial=harness();initial.requestSelection(null);assert(!initial.render().field('작업 항목 제목'));assert.equal(initial.writes,0);
});
test('NCUI01 real saved items/roles/review context render without native writes or raw reparse',()=>{const h=harness(),screen=h.render();assert(screen.text.includes('처음 할 일'));assert(screen.text.includes('둘째 할 일'));assert(screen.text.includes('해결하지 않은 검토'));assert.equal(h.writes,0);assert.equal(h.owner.actions.length,0);assert(screen.text.includes('실행·공개 반영은 별도 확인'));});
test('NCUI02 include comparison/cancel has zero callback; explicit apply uses exact native operation once',async()=>{const h=harness();h.render().button('처음 할 일').props.onClick();h.render().button('결과에서 제외 비교').props.onClick();assert(h.render().button('비교한 구조 적용'));assert.equal(h.requests.length,0);h.render().button('비교 닫고 계속 편집').props.onClick();assert.equal(h.requests.length,0);h.render().button('결과에서 제외 비교').props.onClick();const apply=h.render().button('비교한 구조 적용').props.onClick;apply();apply();await h.settle();assert.equal(h.writes,1);assert.equal(h.requests.length,1);assert.equal(h.owner.document.parseResult.canonical.items[0].included,false);});
test('NCUI03 failed apply retains preview and exact request for retry',async()=>{const h=harness();h.render().button('처음 할 일').props.onClick();h.render().button('결과에서 제외 비교').props.onClick();h.fail(true);h.render().button('비교한 구조 적용').props.onClick();await h.settle();assert(h.render().button('비교한 구조 적용'));assert.equal(h.writes,0);h.fail(false);h.render().button('비교한 구조 적용').props.onClick();await h.settle();assert.equal(h.writes,1);assert.equal(h.requests[0].requestId,h.requests[1].requestId);assert.equal(h.requests[0].now,h.requests[1].now);});
test('NCUI04 dirty title immediately blocks navigation flush, retains capture and cannot silently switch item',async()=>{const h=harness();h.render().button('처음 할 일').props.onClick();h.render().field('작업 항목 제목').props.onChange({target:{value:'아직 저장하지 않은 제목'}});assert(h.port.hasPendingInput!());assert.equal(await h.port.flushAll(),false);assert(h.port.captureDrafts!()[0].raw.includes('아직 저장하지 않은 제목'));h.render().button('둘째 할 일').props.onClick();assert.equal(h.render().field('작업 항목 제목').props.value,'아직 저장하지 않은 제목');const unlock=h.port.lockInput();h.render().field('작업 항목 제목').props.onChange({target:{value:'잠금 중 입력'}});assert.equal(h.render().field('작업 항목 제목').props.value,'아직 저장하지 않은 제목');unlock();assert.equal(h.writes,0);});
test('NCUI05 composition and source change reject stale preview without callback or draft loss',async()=>{const h=harness();h.render().button('처음 할 일').props.onClick();const parent=h.render().nodes.find(n=>n.type==='div'&&n.props.onCompositionStart);parent.props.onCompositionStart();h.render().button('결과에서 제외 비교').props.onClick();assert(!h.render().button('비교한 구조 적용'));parent.props.onCompositionEnd();h.render().button('미확정 구조 입력 버리기').props.onClick();h.render().button('결과에서 제외 비교').props.onClick();h.foreign();h.render().button('비교한 구조 적용').props.onClick();await h.settle();assert.equal(h.requests.length,0);assert(h.render().button('비교한 구조 적용'));});
test('NCUI06 comparison renders actual before/after values and explicit private/public boundary',()=>{const h=harness(),owner=h.owner,result=applyNativeCreatorDocumentOperation(owner,{expectedOwner:owner,requestId:'compare',operation:{type:'exclude',itemId:owner.document.parseResult.canonical.items[0].itemId}},NOW);assert(result.ok);const Compare=h.Comparison,html=renderToStaticMarkup(<Compare before={owner} after={result.owner}/>);for(const text of ['결과에 포함','결과에서 제외','개인 실행 기록','공개 판본'])assert(html.includes(text));});
test('NCUI07 review evidence creates an actual decision preview; never approves on render',async()=>{const h=harness(),screen=h.render();screen.field('검토 항목').props.onChange({target:{value:h.owner.document.reviewGates![0].gateId}});h.render().field('검토 근거').props.onChange({target:{value:'원래 자료의 경고를 확인한 근거'}});assert.equal(h.owner.document.reviewGates![0].status,'required');h.render().button('근거 기록 비교').props.onClick();assert.equal(h.requests.length,0);h.render().button('비교한 구조 적용').props.onClick();await h.settle();assert.equal(h.requests[0].operation.type,'record_review_decision');assert.equal(h.owner.document.reviewGates![0].status,'evidence_recorded');const source=h.owner.source;assert('versionId' in source);assert.equal(source.versionId,'saved-1');});
test('NCUI08 readonly blocks handlers and responsive styles wrap controls with keyboard focus',()=>{const h=harness();h.readonly(true);h.render().button('처음 할 일').props.onClick();assert(!h.render().field('작업 항목 제목'));assert.equal(h.writes,0);const css=readFileSync(new URL('./ProgramCreatorNativeContext.module.css',import.meta.url),'utf8');for(const rule of ['min-height:44px','focus-visible','overflow-wrap:anywhere','grid-template-columns:minmax(0,1fr)'])assert(css.includes(rule));});
test('NCUI09 pending raw blocks unrelated operations and modified raw invalidates confirmed preview',async()=>{const h=harness();h.render().button('처음 할 일').props.onClick();h.pending(h.owner.document.rawText.replace('처음','새로운'));h.render().button('결과에서 제외 비교').props.onClick();assert.equal(h.requests.length,0);assert(!h.render().button('비교한 구조 적용'));h.render().button('원문 변경을 구조에 반영하기 전 비교').props.onClick();assert(h.render().button('비교한 구조 적용'));h.pending(h.owner.document.rawText+'\n더 쓴 입력');h.render().button('비교한 구조 적용').props.onClick();await h.settle();assert.equal(h.requests.length,0);assert.equal(h.writes,0);});
test('NCUI10 raw change uses shared review-aware helper then explicit one native callback',async()=>{const h=harness(),raw=h.owner.document.rawText.replace('처음','새로운');h.pending(raw);h.render().button('원문 변경을 구조에 반영하기 전 비교').props.onClick();assert.equal(h.requests.length,0);h.render().button('비교한 구조 적용').props.onClick();await h.settle();assert.equal(h.writes,1);assert.equal(h.owner.document.rawText,raw);assert.equal(h.owner.document.reviewGates![0].status,'required');const op=h.requests[0].operation;assert(op.type==='sync_working_text_from_input');assert.equal(op.reviewRequirements?.length,1);});
test('NCUI11 actual native result excludes canonical-only removed item while preserved raw remains inspectable',()=>{const h=harness();h.exclude();h.renderResult().button('할 일').props.onClick();const screen=h.renderResult(),rows=screen.nodes.filter(n=>n.type==='li');assert(!rows.some(row=>label(row).includes('처음 할 일')));assert(rows.some(row=>label(row).includes('둘째 할 일')));assert(screen.text.includes('처음 할 일'));assert.equal(h.writes,0);assert(screen.text.includes('개인 완료 기록이 아닙니다'));});
test('NCUI12 original open-ended result expands bounded rows without any owner or storage mutation',()=>{const h=harness('# 계속\n- [ ] 매주 할 일\n  - 날짜: 2026-09-14\n  - 반복: 매주 월'),before=JSON.stringify(h.owner);h.renderResult().button('캘린더').props.onClick();let screen=h.renderResult();assert.equal(screen.nodes.filter(n=>n.type==='li').length,4);screen.button('다음 반복 범위 더 보기').props.onClick();screen=h.renderResult();assert.equal(screen.nodes.filter(n=>n.type==='li').length,8);assert.equal(JSON.stringify(h.owner),before);assert.equal(h.writes,0);});
test('NCUI13 review cannot consume an unrelated dirty title and synchronous lock prevents native beforeinput',()=>{const h=harness();h.render().field('검토 항목').props.onChange({target:{value:h.owner.document.reviewGates![0].gateId}});h.render().button('처음 할 일').props.onClick();h.render().field('작업 항목 제목').props.onChange({target:{value:'남겨둘 제목'}});h.render().button('개인 사용만 비교').props.onClick();assert(!h.render().button('비교한 구조 적용'));assert.equal(h.requests.length,0);const release=h.port.lockInput();let prevented=false;h.render().nodes.find(n=>n.type==='div'&&n.props.onBeforeInput).props.onBeforeInput({preventDefault(){prevented=true;}});assert(prevented);release();assert(h.port.captureDrafts!()[0].raw.includes('남겨둘 제목'));});
test('NCUI14 explicit full source restoration applies the original included state without reparsing raw',async()=>{const h=harness();h.exclude();const raw=h.owner.document.rawText;h.render().button('처음 가져온 전체 저장본으로 복구 비교').props.onClick();assert.equal(h.writes,0);h.render().button('비교한 구조 적용').props.onClick();await h.settle();assert.equal(h.writes,1);assert.equal(h.owner.document.rawText,raw);assert.equal(h.owner.document.parseResult.canonical.items[0].included,true);assert.equal(h.owner.actions.length,2);});
test('NCUI15 expansion is per actual recurrence mode; capped source does not show a no-op more action',()=>{const fn=harness().expansion,open={itemId:'open',label:'매주',mode:'open_ended' as const,visibleCount:520,visibleWeeks:520,hasMore:true},finite={itemId:'finite',label:'횟수',mode:'finite_count' as const,visibleCount:10000,totalCount:10001,hasMore:true};assert.deepEqual(fn([open],30,520),{finite:false,openEnded:false,canExpand:false,limited:true});assert.deepEqual(fn([finite],10000,4),{finite:false,openEnded:false,canExpand:false,limited:true});assert.deepEqual(fn([open,{...finite,visibleCount:30,totalCount:60}],30,520),{finite:true,openEnded:false,canExpand:true,limited:true});assert.equal(fn([{...finite,hasMore:false,totalCount:30}],30,4).canExpand,false);});
test('NCUI16 external exact item selection focuses its own ID; missing ID does not fall back',()=>{const h=harness();let focused=0;const screen=h.render(),second=h.owner.document.parseResult.canonical.items[1];screen.button('둘째 할 일').props.ref({focus(){focused++;}});h.requestSelection(second.itemId);h.render();assert.equal(h.render().field('작업 항목 제목').props.value,'둘째 할 일');assert.equal(focused,1);h.requestSelection('missing-exact-id');h.render();const current=h.render();assert.equal(current.field('작업 항목 제목').props.value,'둘째 할 일');assert(current.text.includes('다른 항목으로 대신 연결하지 않았습니다'));assert.equal(h.writes,0);});
test('NCUI17 dirty/IME selection requests preserve input and choose only after explicit discard',()=>{const h=harness();h.render().button('처음 할 일').props.onClick();h.render().field('작업 항목 제목').props.onChange({target:{value:'남길 제목'}});h.requestSelection(h.owner.document.parseResult.canonical.items[1].itemId);h.render();assert.equal(h.render().field('작업 항목 제목').props.value,'남길 제목');const editor=h.render().nodes.find(n=>n.type==='div'&&n.props.onCompositionStart);editor.props.onCompositionStart();h.render().button('미확정 구조 입력 버리기').props.onClick();assert.equal(h.render().field('작업 항목 제목').props.value,'남길 제목');editor.props.onCompositionEnd();h.render().button('미확정 구조 입력 버리기').props.onClick();h.render();assert.equal(h.render().field('작업 항목 제목').props.value,'둘째 할 일');assert.equal(h.writes,0);});
test('NCUI18 original merge preview keeps both exact source lineages, cancellation0 and explicit commit1',async()=>{const h=harness('# 구조\n- [ ] 첫 작업\n- [ ] 둘째 작업'),before=h.owner,ids=before.document.parseResult.canonical.items.map(i=>i.itemId);h.render().button('첫 작업').props.onClick();h.render().button('같은 단계의 다음 항목과').props.onClick();assert.equal(h.requests.length,0);h.render().button('비교 닫고 계속 편집').props.onClick();assert.equal(h.writes,0);h.render().button('같은 단계의 다음 항목과').props.onClick();h.render().button('비교한 구조 적용').props.onClick();await h.settle();assert.equal(h.writes,1);assert.equal(h.requests[0].operation.type,'merge');assert.equal(h.owner.document.parseResult.canonical.items[0].itemId,ids[0]);assert.equal(h.owner.document.parseResult.canonical.items.length,1);assert.equal(h.owner.document.rawText,before.document.rawText);assert.deepEqual(new Set(h.owner.document.parseResult.canonical.items[0].sourceRowIds),new Set(before.document.parseResult.canonical.items.flatMap(i=>i.sourceRowIds)));assert.equal(h.owner.source.documentJson,before.source.documentJson);});
test('NCUI19 conflicting merge remains unchanged and does not call persistence',()=>{const h=harness('# 구조\n- [ ] 첫 작업\n  - 날짜: 2026-09-20\n- [ ] 둘째 작업\n  - 날짜: 2026-09-21'),before=JSON.stringify(h.owner);h.render().button('첫 작업').props.onClick();h.render().button('같은 단계의 다음 항목과').props.onClick();assert(!h.render().button('비교한 구조 적용'));assert.equal(h.requests.length,0);assert.equal(JSON.stringify(h.owner),before);});
test('NCUI20 explicit split boundary preserves details and input on failure, retry reuses request and adds only one Item',async()=>{const h=harness('# 구조\n- [ ] 준비 끝내기\n  - 설명: 두 항목 공통 설명'),before=h.owner;h.render().button('준비 끝내기').props.onClick();h.render().field('제목을 나눌 위치').props.onChange({target:{value:'3'}});assert(h.port.hasPendingInput!());assert(h.port.captureDrafts!()[0].raw.includes('나눌 위치: 3'));h.render().button('선택한 위치에서').props.onClick();h.fail(true);h.render().button('비교한 구조 적용').props.onClick();await h.settle();assert.equal(h.writes,0);assert.equal(h.render().field('제목을 나눌 위치').props.value,'3');h.fail(false);const apply=h.render().button('비교한 구조 적용').props.onClick;apply();apply();await h.settle();assert.equal(h.writes,1);assert.equal(h.requests.length,2);assert.equal(h.requests[0].requestId,h.requests[1].requestId);assert.deepEqual(h.owner.document.parseResult.canonical.items.map(i=>i.title),['준비','끝내기']);assert.equal(new Set(h.owner.document.parseResult.canonical.items.map(i=>i.itemId)).size,2);assert.equal(h.owner.document.rawText,before.document.rawText);});
test('NCUI21 full inspector changes actual working raw and native Calendar time with failure/IME/dirty protection',async()=>{const h=harness('# 구조\n- [ ] 첫 작업\n  - 설명: 원래 설명\n  - 날짜: 2026-09-20\n  - 시간: 10:00\n- [ ] 별도 작업'),before=h.owner;h.render().button('첫 작업').props.onClick();h.render().field('설명').props.onChange({target:{value:'보존할 상세 입력'}});h.render().field('시간').props.onChange({target:{value:'11:00'}});assert(h.port.captureDrafts!()[0].raw.includes('보존할 상세 입력'));h.render().button('별도 작업').props.onClick();assert.equal(h.render().field('설명').props.value,'보존할 상세 입력');const editor=h.render().nodes.find(n=>n.type==='div'&&n.props.onCompositionStart);editor.props.onCompositionStart();h.render().button('상세 내용과 원문 변경 비교').props.onClick();assert(!h.render().button('비교한 구조 적용'));editor.props.onCompositionEnd();h.render().button('상세 내용과 원문 변경 비교').props.onClick();h.fail(true);h.render().button('비교한 구조 적용').props.onClick();await h.settle();assert.equal(h.writes,0);assert.equal(h.render().field('시간').props.value,'11:00');h.fail(false);h.render().button('비교한 구조 적용').props.onClick();await h.settle();assert.equal(h.writes,1);const op=h.requests[0].operation;assert.equal(op.type,'sync_item_to_working_text');assert(op.type==='sync_item_to_working_text');assert.equal(Object.keys(op.patch).length,16);assert(h.owner.document.rawText.includes('시간: 11:00'));assert(h.owner.document.rawText.includes('설명: 보존할 상세 입력'));assert.equal(h.owner.document.parseResult.canonical.items[0].itemId,before.document.parseResult.canonical.items[0].itemId);assert.equal(h.owner.source.documentJson,before.source.documentJson);});
test('NCUI22 duplicate property and same-value inspector do not emit operation and preserve entered data',()=>{const duplicate=harness('# 구조\n- [ ] 첫 작업\n  - 설명: 첫째\n  - 설명: 둘째');duplicate.render().button('첫 작업').props.onClick();duplicate.render().field('설명').props.onChange({target:{value:'미확정 상세'}});duplicate.render().button('상세 내용과 원문 변경 비교').props.onClick();assert(!duplicate.render().button('비교한 구조 적용'));assert.equal(duplicate.render().field('설명').props.value,'미확정 상세');assert.equal(duplicate.requests.length,0);const h=harness();h.render().button('처음 할 일').props.onClick();h.render().button('상세 내용과 원문 변경 비교').props.onClick();assert.equal(h.requests.length,0);assert(!h.render().button('비교한 구조 적용'));});

test('NCUI31 absent property preview/cancel/failure/retry preserves input and commits the original operation once',async()=>{
 const h=harness('# 구조\n- [ ] 첫 작업\n- [ ] 다른 작업'),before=h.owner;
 h.render().button('첫 작업').props.onClick();h.render().field('설명').props.onChange({target:{value:'추가할 상세'}});h.render().field('장소').props.onChange({target:{value:'회의실'}});
 h.render().button('상세 내용과 원문 변경 비교').props.onClick();assert(h.render().button('비교한 구조 적용'));assert.equal(h.requests.length,0);
 h.render().button('비교 닫고 계속 편집').props.onClick();assert.equal(h.render().field('설명').props.value,'추가할 상세');assert.equal(h.writes,0);
 h.render().button('상세 내용과 원문 변경 비교').props.onClick();h.fail(true);h.render().button('비교한 구조 적용').props.onClick();await h.settle();assert.equal(h.writes,0);assert.equal(h.owner,before);assert.equal(h.render().field('장소').props.value,'회의실');
 h.fail(false);h.render().button('비교한 구조 적용').props.onClick();await h.settle();assert.equal(h.writes,1);assert.equal(h.requests[0].requestId,h.requests[1].requestId);
 assert(h.owner.document.rawText.includes('  - 설명: 추가할 상세'));assert(h.owner.document.rawText.includes('  - 장소: 회의실'));assert.equal(h.owner.source.documentJson,before.source.documentJson);
 h.render().button('상세 내용과 원문 변경 비교').props.onClick();assert.equal(h.writes,1);assert(!h.render().button('비교한 구조 적용'));
});

test('NCUI32 successful inspector commit restores focus only after success, never during quota failure',async()=>{
 const h=harness('# 구조\n- [ ] 첫 작업');let focused=0;
 h.render().button('첫 작업').props.onClick();h.render().button('상세 내용과 원문 변경 비교').props.ref.current={focus(){focused++;}};
 h.render().field('장소').props.onChange({target:{value:'회의실'}});h.render().button('상세 내용과 원문 변경 비교').props.onClick();
 h.fail(true);h.render().button('비교한 구조 적용').props.onClick();await h.settle();h.render();assert.equal(focused,0);
 h.fail(false);h.render().button('비교한 구조 적용').props.onClick();await h.settle();h.render();assert.equal(focused,1);h.render();assert.equal(focused,1);
 assert.equal(h.render().field('장소').props.value,'회의실');assert.equal(h.render().field('작업 항목 제목').props.value,'첫 작업');
});
for(const [index,kind] of ['split','merge'].entries())test(`NCUI${33+index} ${kind} restores exact result focus once after success and waits for unlocked writable controls`,async()=>{
 const h=harness('# 구조\n- [ ] 준비 끝내기\n- [ ] 별도 작업'),before=h.owner;let focused=0;
 h.render().button('준비 끝내기').props.onClick();h.render().button('준비 끝내기').props.ref({focus(){focused++;}});
 const stage=()=>{if(kind==='split'){h.render().field('제목을 나눌 위치').props.onChange({target:{value:'3'}});h.render().button('선택한 위치에서 나누기 비교').props.onClick();}else h.render().button('같은 단계의 다음 항목과 합치기 비교').props.onClick();};
 stage();h.render().button('비교 닫고 계속 편집').props.onClick();h.render();assert.equal(focused,0);assert.equal(h.writes,0);
 stage();h.fail(true);h.render().button('비교한 구조 적용').props.onClick();h.render();assert.equal(focused,0);await h.settle();h.render();assert.equal(focused,0);assert.equal(h.owner,before);
 h.fail(false);h.render().button('비교한 구조 적용').props.onClick();h.render();assert.equal(focused,0);await h.settle();
 const unlock=h.port.lockInput();h.render();assert.equal(focused,0);unlock();h.readonly(true);h.render();assert.equal(focused,0);
 h.readonly(false);h.render();assert.equal(focused,1);h.render();assert.equal(focused,1);assert.equal(h.writes,1);
 assert.equal(h.owner.document.parseResult.canonical.items[0].itemId,before.document.parseResult.canonical.items[0].itemId);
 assert.equal(h.render().field('작업 항목 제목').props.value,kind==='split'?'준비':'준비 끝내기 · 별도 작업');
 assert.equal(h.owner.document.rawText,before.document.rawText);assert.equal(h.owner.source.documentJson,before.source.documentJson);
});
test('NCUI35 pending correction focus cannot jump into a different creator owner',async()=>{
 const h=harness('# 구조\n- [ ] 준비 끝내기\n- [ ] 별도 작업');let focused=0;
 h.render().button('준비 끝내기').props.onClick();h.render().button('준비 끝내기').props.ref({focus(){focused++;}});
 h.render().button('같은 단계의 다음 항목과 합치기 비교').props.onClick();h.render().button('비교한 구조 적용').props.onClick();await h.settle();h.foreign();h.render();assert.equal(focused,0);
});
test('NCUI23 Calendar source order uses original native operation and guarded full-block preview',async()=>{const h=harness('# 구조\n- [ ] 늦은 작업\n  - 날짜: 2026-09-23\n- [ ] 이른 작업\n  - 날짜: 2026-09-20'),before=h.owner;h.render().button('Calendar 순서로 원문 변경 비교').props.onClick();assert.equal(h.requests.length,0);h.render().button('비교한 구조 적용').props.onClick();await h.settle();assert.equal(h.writes,1);assert.equal(h.requests[0].operation.type,'align_source_order');assert(h.owner.document.rawText.indexOf('이른 작업')<h.owner.document.rawText.indexOf('늦은 작업'));assert.equal(h.owner.source.documentJson,before.source.documentJson);assert(!h.render().button('Calendar 순서로 원문 변경 비교'));});
test('NCUI24 inspector source focus uses exact native target and cannot bypass dirty input, IME or locks',async()=>{const opened:any[]=[],h=harness(undefined,target=>{opened.push(target);});h.render().button('처음 할 일').props.onClick();h.render().button('이 항목의 원문 위치 열기').props.onClick();await h.settle();assert.equal(opened.length,1);const item=h.owner.document.parseResult.canonical.items[0];assert.deepEqual(opened[0].sourceRowIds,item.sourceRowIds);assert.equal(opened[0].ownerRevision,h.owner.revision);assert.equal(opened[0].rawText,h.owner.document.rawText);h.render().field('설명').props.onChange({target:{value:'원문으로 이동해도 버리면 안 되는 입력'}});h.render().button('이 항목의 원문 위치 열기').props.onClick();await h.settle();assert.equal(opened.length,1);assert(h.port.captureDrafts!()[0].raw.includes('버리면 안 되는 입력'));h.render().button('미확정 구조 입력 버리기').props.onClick();const editor=h.render().nodes.find(n=>n.type==='div'&&n.props.onCompositionStart);editor.props.onCompositionStart();h.render().button('이 항목의 원문 위치 열기').props.onClick();editor.props.onCompositionEnd();h.render().button('미확정 구조 입력 버리기').props.onClick();const unlock=h.port.lockInput();h.render().button('이 항목의 원문 위치 열기').props.onClick();unlock();await h.settle();assert.equal(opened.length,1);assert.equal(h.writes,0);});
test('NCUI25 inspector title commit refreshes old rename buffer and editing confirmed patch invalidates old payload',async()=>{const h=harness();h.render().button('처음 할 일').props.onClick();inspectorTitle(h.render()).props.onChange({target:{value:'새 상세 제목'}});h.render().button('상세 내용과 원문 변경 비교').props.onClick();inspectorTitle(h.render()).props.onChange({target:{value:'마지막 상세 제목'}});assert(!h.render().button('비교한 구조 적용'));assert.equal(h.requests.length,0);h.render().button('상세 내용과 원문 변경 비교').props.onClick();h.render().button('비교한 구조 적용').props.onClick();await h.settle();assert.equal(h.writes,1);assert.equal(h.render().field('작업 항목 제목').props.value,'마지막 상세 제목');h.render().button('제목 변경 비교').props.onClick();assert(!h.render().button('비교한 구조 적용'));assert.equal(h.writes,1);});
test('NCUI26 stale full-property preview preserves all values and does not call changed owner',async()=>{const h=harness('# 구조\n- [ ] 첫 작업\n  - 설명: 원래 설명');h.render().button('첫 작업').props.onClick();h.render().field('설명').props.onChange({target:{value:'내 상세 내용'}});h.render().button('상세 내용과 원문 변경 비교').props.onClick();h.foreign();h.render().button('비교한 구조 적용').props.onClick();await h.settle();assert.equal(h.requests.length,0);assert.equal(h.render().field('설명').props.value,'내 상세 내용');assert(h.render().button('비교한 구조 적용'));});
test('NCUI27 actual plain source offers original outcomes and keep-source comparison/cancel never creates an Item',async()=>{const raw='제주 여행은 여름에 사람이 많습니다.',h=harness(raw),before=h.owner,issue=before.document.parseResult.issues[0];h.render().button('원문에만 유지 비교').props.onClick();assert.equal(h.requests.length,0);assert(h.port.captureDrafts!()[0].raw.includes(issue.issueId));assert(h.port.captureDrafts!()[0].raw.includes(raw));const preview=h.render().nodes.find(n=>n.type===h.Comparison);const html=renderToStaticMarkup(React.createElement(h.Comparison,preview.props));assert(html.includes('현재 판단'));assert(html.includes('원문에만 유지'));h.render().button('비교 닫고 계속 편집').props.onClick();assert.equal(h.writes,0);h.render().button('원문에만 유지 비교').props.onClick();h.render().button('비교한 구조 적용').props.onClick();await h.settle();assert.equal(h.writes,1);assert.equal(h.owner.document.parseResult.canonical.items.length,0);assert.equal(h.owner.document.parseResult.issues[0].decision?.outcome,'keep_source_only');assert.equal(h.owner.document.rawText,raw);assert.equal(h.owner.source.documentJson,before.source.documentJson);assert(!h.render().button('할 일로 만들기 비교'));});
test('NCUI28 URL-only source permits hold only and does not turn held review into an execution Item',async()=>{const h=harness('https://example.com/source'),before=h.owner;assert(!h.render().button('할 일로 만들기 비교'));assert(!h.render().button('원문에만 유지 비교'));h.render().button('나중에 결정 비교').props.onClick();h.render().button('비교한 구조 적용').props.onClick();await h.settle();assert.equal(h.writes,1);const issue=h.owner.document.parseResult.issues[0];assert.equal(issue.decision?.state,'held');assert.equal(issue.blocking,true);assert.equal(h.owner.document.lifecycleStatus,'needs_review');assert.deepEqual(h.owner.document.parseResult.canonical,before.document.parseResult.canonical);assert(h.render().text.includes('보류 중'));});
test('NCUI29 explicit conversion creates exact native lineage once, selects converted Item and retains retry choice',async()=>{const raw='제주 여행은 여름에 사람이 많습니다.',h=harness(raw),before=h.owner,issue=before.document.parseResult.issues[0];h.render().button('할 일로 만들기 비교').props.onClick();h.fail(true);h.render().button('비교한 구조 적용').props.onClick();await h.settle();assert.equal(h.writes,0);assert(h.port.captureDrafts!()[0].raw.includes('선택: 할 일로 만들기'));h.fail(false);const apply=h.render().button('비교한 구조 적용').props.onClick;apply();apply();await h.settle();assert.equal(h.writes,1);assert.equal(h.requests[0].requestId,h.requests[1].requestId);const item=h.owner.document.parseResult.canonical.items[0];assert.deepEqual(item.sourceRowIds,issue.sourceRowIds);assert.equal(item.title,raw);assert.equal(item.schedule,undefined);const decision=h.owner.document.parseResult.issues[0].decision;assert(decision?.outcome==='convert_to_item');assert.equal(decision.targetDraftId,item.itemId);assert.equal(h.render().field('작업 항목 제목').props.value,raw);assert.equal(h.owner.source.documentJson,before.source.documentJson);assert.equal(h.owner.document.rawText,raw);assert(!h.render().button('할 일로 만들기 비교'));});
test('NCUI30 classify cannot consume dirty/IME input and stale source preview does not call persistence',async()=>{const h=harness('# 실제 구조\n- [ ] 첫 작업\n개인적으로 확인할 문장');h.render().button('첫 작업').props.onClick();h.render().field('작업 항목 제목').props.onChange({target:{value:'아직 보존할 제목'}});h.render().button('할 일로 만들기 비교').props.onClick();assert(!h.render().button('비교한 구조 적용'));assert(h.port.captureDrafts!()[0].raw.includes('아직 보존할 제목'));h.render().button('미확정 구조 입력 버리기').props.onClick();const editor=h.render().nodes.find(n=>n.type==='div'&&n.props.onCompositionStart);editor.props.onCompositionStart();h.render().button('원문에만 유지 비교').props.onClick();assert(!h.render().button('비교한 구조 적용'));editor.props.onCompositionEnd();h.render().button('미확정 구조 입력 버리기').props.onClick();h.render().button('원문에만 유지 비교').props.onClick();h.foreign();h.render().button('비교한 구조 적용').props.onClick();await h.settle();assert.equal(h.requests.length,0);assert(h.render().button('비교한 구조 적용'));});
