import {loadProgramPlanUi} from './ProgramLegacyPlan.test-support';
import assert from 'node:assert/strict';import test from 'node:test';import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';import {resolve,dirname} from 'node:path';import {fileURLToPath} from 'node:url';import vm from 'node:vm';import ts from 'typescript';
import {buildSourceBackedFlowMapSavedSnapshot,buildSourceBackedFlowMapPersistenceRecord,sourceBackedMyFlowBundles} from '../../../lib/flow/source-backed-my-flow';import {buildPersonalWorkspacePocReadModel} from '../../../lib/flow/personal-workspace-poc-read-model';import {createPersonalWorkspacePocState} from '../../../lib/flow/personal-workspace-poc-state';import {createProgramData} from '../../../lib/flow/integrated-poc/program-data';import {hydrateProgramLegacy} from '../../../lib/flow/integrated-poc/legacy-projection';import type {ProgramEditorFlush} from '../../../lib/flow/integrated-poc/document-action';import type * as Component from './ProgramLegacyMapPlan';
function harness(){const now='2026-09-13T00:00:00.000Z',id='moving-d30',keys:Record<string,string>={[`flow:map:saved:${id}`]:JSON.stringify(buildSourceBackedFlowMapSavedSnapshot(id,{savedAt:now,anchor:'2026-09-30'})),[`flow:map:persistence:${id}`]:JSON.stringify(buildSourceBackedFlowMapPersistenceRecord(id,{savedAt:now,anchor:'2026-09-30'}))};const read=buildPersonalWorkspacePocReadModel({length:2,key:i=>Object.keys(keys)[i]??null,getItem:k=>keys[k]??null},sourceBackedMyFlowBundles);assert.ok(read.ok);const hydrated=hydrateProgramLegacy(createProgramData(),read.model,createPersonalWorkspacePocState(now),{actorId:'local-user',preserveUnsupported:true});assert.ok(hydrated.ok);let data=hydrated.data,port:ProgramEditorFlush|null=null,writes=0,fail=false,cursor=0;const slots:any[]=[];
 const hooks={...React,useState:(initial:any)=>{const i=cursor++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return[slots[i],(v:any)=>{slots[i]=typeof v==='function'?v(slots[i]):v;}];},useRef:(initial:any)=>{const i=cursor++;if(!(i in slots))slots[i]={current:initial};return slots[i];},useEffect:(fn:()=>void)=>{const i=cursor++;if(!(i in slots)){slots[i]=true;fn();}}};
 const url=new URL('./ProgramLegacyMapPlan.tsx',import.meta.url),req=createRequire(url),root=resolve(dirname(fileURLToPath(url)),'../../..'),loaded={exports:{} as typeof Component};const output=ts.transpileModule(readFileSync(url,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;vm.runInThisContext(`(function(module,exports,require){${output}\n})`)(loaded,loaded.exports,(id:string)=>id==='react'?hooks:id==='./ProgramLegacyPlanSeries'?loadProgramPlanUi(resolve(root,'components/flow/integrated-poc/ProgramLegacyPlanSeries.tsx'),hooks):id.endsWith('.css')?{__esModule:true,default:{}}:req(id.startsWith('@/')?resolve(root,id.slice(2)):id));
 const flowRef=read.model.flows[0].ref;
 function render(canStart=()=>true){cursor=0;const tree=loaded.exports.ProgramLegacyMapPlan({data,flowRef,canStart,onRegisterEditors:p=>{port=p;},mutate:async(_l,build)=>{if(fail)return{ok:false,reason:'quota'};const r=build(data);if(!r.ok)return{ok:false,reason:r.reason};if(r.changed)writes++;data=r.data;return{ok:true,result:r.result};}});const nodes:any[]=[];function visit(n:any){if(Array.isArray(n))n.forEach(visit);else if(n?.props){nodes.push(n);visit(n.props.children);}}visit(tree);return{tree,nodes,button:(s:string)=>nodes.find(n=>n.type==='button'&&n.props.children===s),date:()=>nodes.find(n=>n.type==='input'&&n.props.type==='date')};}
 return{render,get writes(){return writes;},get port(){return port!;},fail:(v:boolean)=>{fail=v;}};
}
test('Map actual child SSR and handlers: separate shared/child/item controls, cancel/IME/lock/quota input safety',async()=>{const h=harness();let v=h.render();assert.ok(renderToStaticMarkup(v.tree).includes('Map 개인 계획'));v.button('Map 기준일·항목 검토').props.onClick();v=h.render();assert.ok(v.nodes.some(n=>n.type==='select'));assert.ok(v.nodes.some(n=>n.type==='input'&&n.props.type==='checkbox'));assert.equal(await h.port.flushAll(),false);v.date().props.onChange({target:{value:'2026-10-10'}});v=h.render();v.button('변경 비교').props.onClick();v=h.render();assert.ok(v.button('Map 선택 적용'));v.tree.props.onKeyDown({key:'Escape',preventDefault(){}});assert.equal(h.writes,0);v=h.render();v.button('Map 기준일·항목 검토').props.onClick();v=h.render();v.date().props.onChange({target:{value:'2026-10-10'}});v=h.render();v.button('변경 비교').props.onClick();v=h.render();const release=h.port.lockInput();v.button('Map 선택 적용').props.onClick();assert.equal(h.writes,0);release();v.tree.props.onCompositionStart();v.button('Map 선택 적용').props.onClick();assert.equal(h.writes,0);v.tree.props.onCompositionEnd();h.fail(true);v.button('Map 선택 적용').props.onClick();await new Promise(r=>setImmediate(r));assert.equal(h.writes,0);assert.ok(h.port.hasPendingInput?.());h.fail(false);v=h.render();v.button('Map 선택 적용').props.onClick();await new Promise(r=>setImmediate(r));h.render();assert.equal(h.writes,1);assert.equal(h.port.hasPendingInput?.(),false);});

test('membership opened after plan render prevents a second plan draft before parent rerender',()=>{
 const h=harness();let membershipPending=false;const view=h.render(()=>!membershipPending);
 membershipPending=true;view.button('Map 기준일·항목 검토').props.onClick();
 assert.equal(h.port.hasPendingInput?.(),false);assert.equal(h.writes,0);assert.equal(h.render().date(),undefined);
 membershipPending=false;h.render(()=>!membershipPending).button('Map 기준일·항목 검토').props.onClick();
 assert.equal(h.port.hasPendingInput?.(),true);assert.ok(h.render().date());
});
