import test from 'node:test';
import assert from 'node:assert/strict';
import React from 'react';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import type {LegacyCreatorRecoveryCandidate,LegacyCreatorRecoveryRead} from '../../../lib/flow/integrated-poc/legacy-creator-recovery-codec';
import type {ProgramLegacyCreatorRecoveryProps} from './ProgramLegacyCreatorRecovery';
import type {ProgramMutationResult} from '../../../lib/flow/integrated-poc/ui-contract';

type Request={id:string;raw:string;recoveryId:string};
const text=(v:any):string=>Array.isArray(v)?v.map(text).join(''):typeof v==='string'?v:typeof v==='number'?String(v):v?.props?text(v.props.children):'';
/** Port DTOs only: these are not fabricated native owners or codec validation evidence. */
function row(overrides:Partial<LegacyCreatorRecoveryCandidate>={}):LegacyCreatorRecoveryCandidate{return{
 contractVersion:1,storageKey:'flow:text-authoring:drafts:v1',draftId:'old-draft',recoveryId:'recovery-one',documentId:'native-document',revisionId:'working-r2',recoveredAt:'2026-09-20T01:00:00.000Z',
 timestampSource:'recoveredAt',title:'같은 제목',canonicalRawText:'# 해석한 원문\r\n- [ ] 첫 항목',workingRawText:'# 미반영 원문\r\n- [ ] 새 입력',documentJson:'{"readOnly":"native document evidence"}',recoveryJson:'{"original":"recovery metadata"}',
 durableRecordJson:null,lastSavedAt:null,eligibility:'first-save-before',eligible:true,activeStage:'result',selectionAvailable:true,...overrides,
};}
function harness(){
 let at=0,reads=0,prepares=0,actorId='local-user',blocked=false,prepareReason:string|null=null,hold=false,fail=false,presentation=false,openThrows=false,focus=0;
 let loaded:LegacyCreatorRecoveryRead={kind:'ready',raw:'EXACT_SOURCE_WIRE',candidates:[row(),row({draftId:'other-draft',recoveryId:'recovery-two'})],issues:[]};
 const slots:any[]=[],requests:Request[]=[],opened:string[]=[],pendingStates:boolean[]=[],continued:string[]=[],held:Array<(result:ProgramMutationResult)=>void>=[];
 const hooks={...React,useState:(initial:any)=>{const i=at++;if(!(i in slots))slots[i]=typeof initial==='function'?initial():initial;return[slots[i],(v:any)=>slots[i]=typeof v==='function'?v(slots[i]):v];},useRef:(initial:any)=>{const i=at++;return slots[i]??={current:initial};}};
 const url=new URL('./ProgramLegacyCreatorRecovery.tsx',import.meta.url),require=createRequire(url),module={exports:{} as {ProgramLegacyCreatorRecovery:(p:ProgramLegacyCreatorRecoveryProps<Request>)=>React.ReactNode}};
 const code=ts.transpileModule(readFileSync(url,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;
 vm.runInThisContext(`(function(module,exports,require){${code}\n})`)(module,module.exports,(id:string)=>id==='react'?hooks:id.endsWith('.css')?{__esModule:true,default:{}}:require(id));
 let preview={contextWarnings:['미반영 원문은 원문 단계에서 먼저 확인합니다.'],existingDraftId:null as string|null};
 const props=():ProgramLegacyCreatorRecoveryProps<Request>=>({actorId,inputBlocked:blocked,read:()=>{reads++;return loaded;},prepare:(source,candidate)=>{prepares++;return prepareReason?{ok:false,reason:prepareReason}:{ok:true,request:{id:'request-'+prepares,raw:source.raw,recoveryId:candidate.recoveryId},preview};},handoff:async request=>{requests.push(request);if(hold)return new Promise(resolve=>held.push(resolve));return fail?{ok:false,reason:'storage-unavailable'}:{ok:true,result:'new-working',...(presentation?{presentationPending:true}:{})};},onOpenCreatorDraft:id=>{if(openThrows)throw Error('presentation only');opened.push(id);},onContinueCurrent:()=>continued.push('current'),onPendingChange:v=>pendingStates.push(v)});
 function render(){at=0;const tree=module.exports.ProgramLegacyCreatorRecovery(props()),nodes:any[]=[];const visit=(v:any)=>{if(Array.isArray(v))v.forEach(visit);else if(v?.props){nodes.push(v);visit(v.props.children);}};visit(tree);for(const n of nodes)if(n.type==='button'&&n.props.ref)n.props.ref.current={focus:()=>focus++};return{nodes,text:text(tree),button:(label:string)=>nodes.find(n=>n.type==='button'&&text(n)===label),select:()=>nodes.find(n=>n.type==='select'),section:nodes[0]};}
 const click=(label:string)=>{const b=render().button(label);assert(b,'button '+label);assert.equal(b.props.disabled,false,'enabled '+label);return b.props.onClick();};
 function choose(id='recovery-one'){const select=render().select();assert(select);select.props.onChange({target:{value:id}});}
 async function settle(){for(let i=0;i<15;i++)await Promise.resolve();}
 return{render,click,choose,settle,requests,opened,pendingStates,continued,get reads(){return reads;},get prepares(){return prepares;},get focus(){return focus;},setRead:(v:LegacyCreatorRecoveryRead)=>loaded=v,setRows:(candidates:LegacyCreatorRecoveryCandidate[])=>loaded={kind:'ready',raw:'EXACT_SOURCE_WIRE',candidates,issues:[]},setFail:(v:boolean)=>fail=v,setHold:(v:boolean)=>hold=v,resolve:(value:ProgramMutationResult)=>held.shift()!(value),setBlocked:(v:boolean)=>blocked=v,setActor:(v:string)=>actorId=v,setPrepareReason:(v:string|null)=>prepareReason=v,setPresentation:(v:boolean)=>presentation=v,setOpenThrows:(v:boolean)=>openThrows=v,setPreview:(v:typeof preview)=>preview=v};
}

test('LCRUI01 mount has no source read; explicit read does not auto-select or prepare',()=>{const h=harness();h.render();assert.equal(h.reads,0);assert.equal(h.prepares,0);h.click('개발2 임시 작업 읽기');assert.equal(h.reads,1);assert.equal(h.render().select().props.value,'');assert.equal(h.prepares,0);assert.equal(h.requests.length,0);});
test('LCRUI02 same titles retain exact draft/recovery identities, canonical/pending CRLF and real first-save absence',()=>{const h=harness();h.click('개발2 임시 작업 읽기');h.choose('recovery-two');const ui=h.render();assert.equal(ui.select().props.value,'recovery-two');assert(ui.text.includes('other-draft'));assert(ui.text.includes('# 해석한 원문\r\n'));assert(ui.text.includes('# 미반영 원문\r\n'));assert(ui.text.includes('첫 명시 저장 전 자료'));assert(ui.text.includes('미반영 원문은 원문 단계'));assert.equal(h.requests.length,0);});
test('LCRUI03 empty pending remains distinct from canonical; actual saved revision is comparison-only',()=>{const h=harness();h.setRows([row({workingRawText:'',eligibility:'newer-than-saved',lastSavedAt:'2026-09-19T00:00:00.000Z',durableRecordJson:JSON.stringify({revisionId:'saved-real-r1',document:{rawText:'SAVED_BYTES'}})})]);h.click('개발2 임시 작업 읽기');h.choose();const ui=h.render();assert(ui.text.includes('(비운 입력)'));assert(ui.text.includes('saved-real-r1'));assert(ui.text.includes('SAVED_BYTES'));assert(!ui.text.includes('기존 저장 판본은 없습니다'));assert.equal(h.requests.length,0);});
test('LCRUI04 same raw does not fabricate pending input warning',()=>{const h=harness();const c=row();h.setRows([{...c,workingRawText:c.canonicalRawText}]);h.click('개발2 임시 작업 읽기');h.choose();assert(h.render().text.includes('원문과 작성 중 입력이 같습니다'));assert(!h.render().text.includes('아직 반영하지 않은 입력'));});
test('LCRUI05 failed handoff retains exact selected request object, retry and double-click commit once',async()=>{const h=harness();h.click('개발2 임시 작업 읽기');h.choose();h.setFail(true);h.click('이 임시 작업으로 제작 이어가기');await h.settle();assert.equal(h.requests.length,1);assert.equal(h.render().select().props.value,'recovery-one');assert(h.render().text.includes('저장하지 못했습니다'));assert.equal(h.opened.length,0);h.setFail(false);const submit=h.render().button('이 임시 작업으로 제작 이어가기').props.onClick;submit();submit();await h.settle();assert.equal(h.requests.length,2);assert.strictEqual(h.requests[0],h.requests[1]);assert.equal(h.prepares,1);assert.deepEqual(h.opened,['new-working']);assert.deepEqual(h.pendingStates,[true,false,true,false]);submit();await h.settle();assert.equal(h.requests.length,2);});
test('LCRUI06 pending locks close/reread/selection and suppresses Escape; success opens only afterward',async()=>{const h=harness();h.click('개발2 임시 작업 읽기');h.choose();const oldRead=h.render().button('임시 작업 목록 다시 읽기').props.onClick,oldSelect=h.render().select().props.onChange,oldClose=h.render().button('임시 작업 목록 닫기').props.onClick;h.setHold(true);h.click('이 임시 작업으로 제작 이어가기');assert.equal(h.opened.length,0);oldRead();oldSelect({target:{value:'recovery-two'}});oldClose();let prevented=0;h.render().section.props.onKeyDown({key:'Escape',preventDefault:()=>prevented++,stopPropagation:()=>{}});assert.equal(prevented,1);assert.equal(h.reads,1);assert.equal(h.render().select().props.value,'recovery-one');assert.equal(h.render().button('임시 작업 목록 닫기').props.disabled,true);h.resolve({ok:true,result:'new-working'});await h.settle();assert.deepEqual(h.opened,['new-working']);});
test('LCRUI07 close/Escape retains comparison and selection, restores trigger focus without read/write',()=>{const h=harness();h.click('개발2 임시 작업 읽기');h.choose();h.render().section.props.onKeyDown({key:'Escape',preventDefault:()=>{},stopPropagation:()=>{}});assert.equal(h.focus,1);assert(!h.render().select());h.click('읽은 임시 작업 다시 보기');assert.equal(h.render().select().props.value,'recovery-one');assert.equal(h.reads,1);assert.equal(h.prepares,1);assert.equal(h.requests.length,0);});
test('LCRUI08 dirty input blocks preparation and no autoflush, continue-current is distinct',()=>{const h=harness();h.setBlocked(true);h.click('개발2 임시 작업 읽기');h.choose();assert.equal(h.prepares,0);assert.equal(h.requests.length,0);assert.equal(h.render().button('이 임시 작업으로 제작 이어가기').props.disabled,true);h.click('현재 제작 작업으로 돌아가기');assert.deepEqual(h.continued,['current']);});
test('LCRUI09 newly dirty state and actor switch reject stale submit closures',async()=>{const h=harness();h.click('개발2 임시 작업 읽기');h.choose();const oldSubmit=h.render().button('이 임시 작업으로 제작 이어가기').props.onClick;h.setBlocked(true);h.render();oldSubmit();await h.settle();assert.equal(h.requests.length,0);h.setBlocked(false);h.setActor('creator-minji');const ui=h.render();oldSubmit();await h.settle();assert.equal(h.requests.length,0);assert(!ui.text.includes('# 해석한 원문'));assert(!ui.select());});
test('LCRUI10 changed source/dirty working preparation failure retains selected comparison but cannot submit',()=>{const h=harness();h.setPrepareReason('dirty-working');h.click('개발2 임시 작업 읽기');h.choose();assert.equal(h.render().select().props.value,'recovery-one');assert(h.render().text.includes('자동으로 저장하거나 덮어쓰지'));assert.equal(h.render().button('이 임시 작업으로 제작 이어가기').props.disabled,true);assert.equal(h.requests.length,0);});
test('LCRUI11 old recovery remains inspectable without preparation or handoff',()=>{const h=harness();h.setRows([row({eligible:false,eligibility:'not-newer-than-saved'})]);h.click('개발2 임시 작업 읽기');h.choose();assert.equal(h.prepares,0);assert.equal(h.render().button('이 임시 작업으로 제작 이어가기').props.disabled,true);assert(h.render().text.includes('원본을 삭제하지'));});
test('LCRUI12 no-storage/unsupported/corrupt/unavailable states are distinct and do not invent choices',()=>{for(const kind of ['empty','unsupported','corrupt','unavailable'] as const){const h=harness();h.setRead({kind,raw:null});h.click('개발2 임시 작업 읽기');const ui=h.render();assert(!ui.select());assert.equal(h.prepares,0);assert.equal(h.requests.length,0);assert(ui.text.includes({empty:'남아 있는 개발2 임시 작업이 없습니다',unsupported:'저장 형식',corrupt:'자료가 손상',unavailable:'저장소를 읽지 못했습니다'}[kind]));}});
test('LCRUI13 partial invalid entries are disclosed while valid candidate remains selectable',()=>{const h=harness();h.setRead({kind:'ready',raw:'wire',candidates:[row()],issues:[{draftId:'broken-source',reason:'invalid-entry'}]});h.click('개발2 임시 작업 읽기');assert(h.render().text.includes('broken-source'));assert(h.render().text.includes('이어갈 수 없는 자료'));h.choose();assert.equal(h.prepares,1);});
test('LCRUI14 presentation-pending success is not retried as another handoff',async()=>{const h=harness();h.setPresentation(true);h.click('개발2 임시 작업 읽기');h.choose();const submit=h.render().button('이 임시 작업으로 제작 이어가기').props.onClick;submit();await h.settle();assert.equal(h.requests.length,1);assert.equal(h.opened.length,0);assert(h.render().text.includes('임시 작업은 보관됐습니다'));submit();await h.settle();assert.equal(h.requests.length,1);h.click('복구한 제작 작업 열기');assert.deepEqual(h.opened,['new-working']);});
test('LCRUI15 navigation exception keeps committed latch and retries only opening',async()=>{const h=harness();h.setOpenThrows(true);h.click('개발2 임시 작업 읽기');h.choose();const submit=h.render().button('이 임시 작업으로 제작 이어가기').props.onClick;submit();await h.settle();assert(h.render().text.includes('제작 화면을 열지 못했습니다'));submit();await h.settle();assert.equal(h.requests.length,1);h.setOpenThrows(false);h.click('복구한 제작 작업 열기');assert.deepEqual(h.opened,['new-working']);assert.equal(h.requests.length,1);});
test('LCRUI16 existing exact working uses reopen wording and preserves context warnings',async()=>{const h=harness();h.setPreview({contextWarnings:['원래 선택 항목이 없어 자동 선택하지 않습니다.'],existingDraftId:'old-working'});h.click('개발2 임시 작업 읽기');h.choose();assert(h.render().text.includes('저장 없이 그 작업을 엽니다'));assert(h.render().text.includes('자동 선택하지 않습니다'));assert(h.render().button('이미 이어가는 제작 작업 열기'));});
test('LCRUI17 disappeared exact item is explained without selecting first item',()=>{const h=harness();h.setRows([row({selectedItemId:'missing-item',selectionAvailable:false})]);h.click('개발2 임시 작업 읽기');h.choose();assert(h.render().text.includes('현재 구조에 없어 자동 선택하지 않습니다: missing-item'));});
test('LCRUI18 result arriving after actor change cannot navigate to that actors private draft',async()=>{const h=harness();h.click('개발2 임시 작업 읽기');h.choose();h.setHold(true);h.click('이 임시 작업으로 제작 이어가기');h.setActor('creator-minji');h.render();h.resolve({ok:true,result:'new-working'});await h.settle();assert.equal(h.opened.length,0);assert(h.render().text.includes('보관한 개인공간으로 돌아온 뒤'));assert.equal(h.requests.length,1);});
