import test from 'node:test';import assert from 'node:assert/strict';
import {createTextAuthoringDocument} from './native-creator-vendor/text-authoring/parser';
import {applyAuthoringOperation} from './native-creator-vendor/text-authoring/operations';
import {createAuthoringSourceUpdateCandidate} from './native-creator-vendor/text-authoring/source-update';
import {validateTextAuthoringDocument} from './native-creator-vendor/text-authoring/validation';
import {replayNativeSourceDecision} from './creator-native-source-update-decision';
import {replayNativeSourceApply} from './creator-native-source-update-apply';
const NOW='2026-09-12T01:00:00.000Z';
function decided(raw:string,incoming:string){const base=createTextAuthoringDocument(raw,{documentId:'exact',ownership:'creator',now:NOW}),next=createTextAuthoringDocument(incoming,{documentId:'exact',ownership:'creator',now:NOW});const candidate=createAuthoringSourceUpdateCandidate(next,{capturedAt:NOW,externalVersion:'v2',matches:base.parseResult.canonical.items.map((i,n)=>({activeItemId:i.itemId,incomingItemId:next.parseResult.canonical.items[n].itemId,basis:'explicit' as const}))});let staged=applyAuthoringOperation(base,{type:'stage_source_update',candidate},{actorLane:'creator',now:NOW});const state=staged.sourceState;assert(state&&state.status!=='current');for(const change of state.changes){const result=replayNativeSourceDecision(staged,{decisionVersion:1,changeId:change.changeId,decision:'keep_working'},NOW);assert(result);staged=result;}return{base,staged};}
test('NSA01 original no-override keep is rejected; Program repair keeps detail with real incoming source and native Undo',()=>{const {base,staged}=decided('# A\n- [ ] One\n  detail: old','# A\n- [ ] One\n  detail: incoming');assert.throws(()=>applyAuthoringOperation(staged,{type:'apply_source_update'},{actorLane:'creator',now:NOW}),/inconsistent/);const result=replayNativeSourceApply(staged,NOW);assert(result,'apply helper returned null');assert(validateTextAuthoringDocument(result).valid,JSON.stringify(validateTextAuthoringDocument(result)));assert.equal(result.parseResult.canonical.items[0].detail,base.parseResult.canonical.items[0].detail);assert.equal(result.parseResult.canonical.items[0].sourceDetail,'incoming');const undo=applyAuthoringOperation(result,{type:'undo'},{actorLane:'creator',now:NOW});assert.deepEqual(undo.parseResult.canonical,staged.parseResult.canonical);});
test('NSA02 exact title/date/time/checked keep preserves working fields and original incoming snapshot',()=>{const raw='# A\n- [ ] Old title\n  date: 2026-09-14\n  time: 09:00',incoming='# A\n- [x] New title\n  date: 2026-09-15\n  time: 11:00';const {base,staged}=decided(raw,incoming),result=replayNativeSourceApply(staged,NOW);assert(result);assert(validateTextAuthoringDocument(result).valid,JSON.stringify(validateTextAuthoringDocument(result)));const old=base.parseResult.canonical.items[0],actual=result.parseResult.canonical.items[0];assert.equal(actual.title,old.title);assert.equal(actual.sourceTitle,'New title');assert.deepEqual(actual.schedule,old.schedule);assert.equal(actual.sourceChecked,false);assert.deepEqual(actual.properties.filter(p=>['date','time'].includes(p.key)).map(p=>[p.key,p.value]),old.properties.filter(p=>['date','time'].includes(p.key)).map(p=>[p.key,p.value]));assert.equal(result.rawText,incoming);assert.equal(result.sourceState?.active.rawText,incoming);assert.deepEqual(applyAuthoringOperation(result,{type:'undo'},{actorLane:'creator',now:NOW}).parseResult.canonical,staged.parseResult.canonical);});
test('NSA03 missing prior detail/schedule stays empty instead of silently accepting incoming fields',()=>{const {staged}=decided('# A\n- [ ] One','# A\n- [ ] One\n  detail: incoming\n  date: 2026-09-14'),result=replayNativeSourceApply(staged,NOW);assert(result);assert(validateTextAuthoringDocument(result).valid,JSON.stringify(validateTextAuthoringDocument(result)));assert.equal(result.parseResult.canonical.items[0].detail,undefined);assert.equal(result.parseResult.canonical.items[0].schedule,undefined);});
test('NSA04 forged marker values and missing diff are rejected without mutating staged source',()=>{const {staged}=decided('# A\n- [ ] One\n  detail: old','# A\n- [ ] One\n  detail: incoming');const baseline=JSON.stringify(staged);for(const mutate of [(s:any)=>s.changes[0].userValue='forged',(s:any)=>s.changes[0].oldSourceValue='forged',(s:any)=>s.changes[0].userOwner='personal',(s:any)=>s.changes.pop(),(s:any)=>s.incoming.matches[0].activeItemId='foreign']){const bad=structuredClone(staged);mutate(bad.sourceState);assert.equal(replayNativeSourceApply(bad,NOW),null);}assert.equal(JSON.stringify(staged),baseline);});
test('NSA05 changed child semantics remain original explicit rejection, not silently flattened keep',()=>{assert.throws(()=>decided('# A\n- [ ] One\n  - [ ] Old child','# A\n- [ ] One\n  - [ ] Changed child'));});
test('NSA06 genuine creator role/exclusion/nesting/order keep remains byte-equal to original apply',()=>{const raw='# A\n## Stage\n- [ ] One\n  date: 2026-09-14\n- [ ] Two';let base=createTextAuthoringDocument(raw,{documentId:'structural',ownership:'creator',now:NOW});const incoming=createTextAuthoringDocument(raw.replace('2026-09-14','2026-09-15'),{documentId:'structural',ownership:'creator',now:NOW}),id=base.parseResult.canonical.items[0].itemId;const matches=base.parseResult.canonical.items.map((i,n)=>({activeItemId:i.itemId,incomingItemId:incoming.parseResult.canonical.items[n].itemId,basis:'explicit' as const}));for(const op of [{type:'change_role',itemId:id,role:'caution'},{type:'exclude',itemId:id},{type:'indent',itemId:id},{type:'reorder',itemId:id,toIndex:1}] as const)base=applyAuthoringOperation(base,op,{actorLane:'creator',now:NOW});let staged=applyAuthoringOperation(base,{type:'stage_source_update',candidate:createAuthoringSourceUpdateCandidate(incoming,{capturedAt:NOW,externalVersion:'v2',matches})},{actorLane:'creator',now:NOW});const state=staged.sourceState;assert(state&&state.status!=='current');for(const c of state.changes){const next=replayNativeSourceDecision(staged,{decisionVersion:1,changeId:c.changeId,decision:c.kind==='changed'&&c.userValue!==undefined?'keep_working':'use_incoming'},NOW);assert(next);staged=next;}const result=replayNativeSourceApply(staged,NOW);assert(result);assert.deepEqual(result,JSON.parse(JSON.stringify(applyAuthoringOperation(staged,{type:'apply_source_update'},{actorLane:'creator',now:NOW}))));const item=result.parseResult.canonical.items.find(i=>i.itemId===id)!;assert.equal(item.role,'caution');assert.equal(item.included,false);assert.equal(item.nestingLevel,1);assert.equal(item.order,1);});
test('NSA07 keep does not approve a source review gate and source snapshot stays incoming',()=>{const raw='# A\n- [ ] One\n  detail: old';let base=createTextAuthoringDocument(raw,{documentId:'review',ownership:'creator',reviewRequirements:[{kind:'safety',reasonKey:'medical'}],now:NOW});base=applyAuthoringOperation(base,{type:'record_review_decision',gateId:base.reviewGates![0].gateId,status:'evidence_recorded',evidenceNote:'Original review evidence'},{actorLane:'creator',now:NOW});const next=createTextAuthoringDocument(raw.replace('old','incoming'),{documentId:'review',ownership:'creator',now:NOW});let staged=applyAuthoringOperation(base,{type:'stage_source_update',candidate:createAuthoringSourceUpdateCandidate(next,{capturedAt:NOW,externalVersion:'v2',matches:[{activeItemId:base.parseResult.canonical.items[0].itemId,incomingItemId:next.parseResult.canonical.items[0].itemId,basis:'explicit'}]})},{actorLane:'creator',now:NOW});const state=staged.sourceState;assert(state&&state.status!=='current');for(const c of state.changes)staged=replayNativeSourceDecision(staged,{decisionVersion:1,changeId:c.changeId,decision:'keep_working'},NOW)!;const result=replayNativeSourceApply(staged,NOW);assert(result);assert.equal(result.reviewGates?.[0].status,'required');assert.equal(result.lifecycleStatus,'needs_review');assert.equal(result.reviewGates?.[0].sourceSnapshotId,result.sourceState?.active.snapshotId);assert.equal(base.reviewGates?.[0].status,'evidence_recorded');});
