import test from 'node:test';import assert from 'node:assert/strict';
import {createNativeSourceValidationCache,NATIVE_SOURCE_VALIDATION_CACHE_MAX_ENTRIES,NATIVE_SOURCE_VALIDATION_CACHE_MAX_ENTRY_BYTES,NATIVE_SOURCE_VALIDATION_CACHE_MAX_KEY_BYTES} from './creator-native-source-update-cache';
test('NSC01 exact-content clones hit but mutable edits and invalid results never reuse positive validation',()=>{let calls=0;const cache=createNativeSourceValidationCache((v:any)=>{calls++;return v.allowed===true;});const input={allowed:true,actor:'a',text:'private'};assert(cache.validate(input));assert(cache.validate(structuredClone(input)));assert.equal(calls,1);input.allowed=false;assert(!cache.validate(input));assert(!cache.validate(input));assert.equal(calls,3);input.allowed=true;input.actor='b';assert(cache.validate(input));assert.equal(calls,4);assert.equal(cache.stats().entries,2);});
test('NSC02 strict JSON preflight always rejects accessors/undefined/sparse/symbol fields without invocation',()=>{let calls=0,gets=0;const cache=createNativeSourceValidationCache(()=>{calls++;return true;});assert(cache.validate({a:1}));for(const input of [{a:undefined},Object.defineProperty({},'a',{enumerable:true,get(){gets++;return 1;}}),[,,],{a:1,[Symbol('hidden')]:1},new Date()])assert(!cache.validate(input));assert.equal(calls,1);assert.equal(gets,0);});
test('NSC03 LRU count and key-byte bounds remain finite; evicted content is revalidated',()=>{let calls=0;const cache=createNativeSourceValidationCache(()=>{calls++;return true;});for(let id=1;id<=NATIVE_SOURCE_VALIDATION_CACHE_MAX_ENTRIES;id++)assert(cache.validate({id}));assert(cache.validate({id:1}));assert(cache.validate({id:NATIVE_SOURCE_VALIDATION_CACHE_MAX_ENTRIES+1}));assert.equal(cache.stats().entries,NATIVE_SOURCE_VALIDATION_CACHE_MAX_ENTRIES);assert(cache.validate({id:2}));assert.equal(calls,NATIVE_SOURCE_VALIDATION_CACHE_MAX_ENTRIES+2);assert(cache.stats().keyBytes<=NATIVE_SOURCE_VALIDATION_CACHE_MAX_KEY_BYTES);});
test('NSC04 oversized positive payloads are not cached; failed/throwing validation retains no content',()=>{let calls=0;const cache=createNativeSourceValidationCache(()=>{calls++;return true;}),large={raw:'x'.repeat(NATIVE_SOURCE_VALIDATION_CACHE_MAX_ENTRY_BYTES)};assert(cache.validate(large));assert(cache.validate(large));assert.equal(calls,2);assert.equal(cache.stats().entries,0);assert.equal(cache.stats().keyBytes,0);for(const validate of [()=>false,()=>{throw Error('invalid');}]){const no=createNativeSourceValidationCache(validate);assert(!no.validate({raw:'private'}));assert.equal(no.stats().entries,0);}});
test('NSC05 five retained source decisions do not replay on every unchanged workspace save',()=>{
 let calls=0;const cache=createNativeSourceValidationCache((value:any)=>{calls++;return value.valid===true;});
 // The genuine source/private fixture retains five ~60k-char source sessions.
 // Exercise that working set without embedding private source content here.
 const sessions=Array.from({length:5},(_,revision)=>({valid:true,revision,raw:'x'.repeat(60_000)}));
 for(let pass=0;pass<3;pass++)for(const session of sessions)assert(cache.validate(structuredClone(session)));
 assert.equal(calls,5);assert.equal(cache.stats().hits,10);
 const changed={...sessions[0],valid:false};assert(!cache.validate(changed));assert(!cache.validate(changed));assert.equal(calls,7);
 assert(cache.stats().keyBytes<=NATIVE_SOURCE_VALIDATION_CACHE_MAX_KEY_BYTES);
});
