import test from 'node:test';import assert from 'node:assert/strict';
import {createProgramData,validateProgramData} from './program-data';
import {programClone,PROGRAM_STATE_KEY,type ProgramData,type ProgramTransition} from './contract';
import {setProgramCreatorWorking,applyProgramCreatorAction,handoffProgramCreatorDraft} from './creator-workspace';
import {fingerprintPersonalWorkspacePocAuthoringSource as fp} from '../personal-workspace-poc-authoring';
import {createTextAuthoringDocument} from './native-creator-vendor/text-authoring/parser';
import {createNativeCreatorDocumentOwner} from './native-creator-document';
import {applyProgramNativeCreatorOperation} from './creator-native-workspace';
import {inspectProgramCreatorNativeLineage,applyProgramCreatorNativeLineage} from './creator-native-lineage';
import {inspectProgramNativeCreatorHandoff,applyProgramNativeCreatorHandoff} from './creator-native-execution-adapter';
import {textWorkspaceModel as M} from './text-workspace';
import {createProgramController} from './controller';
import {programNativeExecutionRef} from './creator-native-execution-contract';
import {readProgramExecutionOccurrences,updateProgramOccurrenceExecution} from './recurrence-state';
import type {ProgramNativeLineageMapping} from './creator-native-lineage-contract';
import {moveProgramPersonalTaskText} from './task-document-move';
import {readProgramOccurrenceRecovery} from './recurrence-recovery';
const NOW='2026-09-13T08:00:00.000Z',DRAFT='lineage-draft',RAW='# 준비\n- [ ] 같은 제목\n  - 날짜: 2026-09-20\n  - 시간: 09:30\n  - 설명: 첫 원문\n\n- [ ] 같은 제목\n  - 날짜: 2026-09-21';
function ok(r:ProgramTransition<string>){if(!r.ok)assert.fail(r.reason);assert(validateProgramData(r.data));return r;}
function save(data:ProgramData,id:string){const own=data.spaces[data.activeActorId].creatorWorkspace!,w=own.working!;return ok(applyProgramCreatorAction(data,{actorId:data.activeActorId,requestId:id,expectedStructure:w.structure??null,expectedNativeDocument:w.nativeDocument??null,expectedNativeSelection:w.nativeSelection??null,action:{type:'save',draftId:DRAFT,title:w.title,rawText:w.rawText,sourceFingerprint:fp(w.rawText),expectedLibraryRevision:own.library.revision,...(w.baseRecordRevision?{expectedRecordRevision:w.baseRecordRevision}:{}),now:NOW}},NOW)).data;}
export function nativeLineageFixture(raw=RAW){let data=createProgramData();const actorId=data.activeActorId;
 data=ok(setProgramCreatorWorking(data,{actorId,expectedWorking:null,working:{draftId:DRAFT,title:'원래 개인문서',rawText:raw,baseRecordRevision:null}},NOW)).data;data=save(data,'raw-save');
 data=ok(handoffProgramCreatorDraft(data,{actorId,requestId:'raw-handoff',draftId:DRAFT,expectedRecordRevision:data.spaces[actorId].creatorWorkspace!.library.records[DRAFT].recordRevision,today:'2026-09-13'},NOW)).data;
 const doc=createTextAuthoringDocument(raw,{documentId:'actual-lineage-native',ownership:'creator',now:NOW}),source={storageKey:'flow:text-authoring:drafts:v1' as const,draftId:'original-creator',versionId:'actual-source-version',revisionId:doc.revision.revisionId,documentJson:JSON.stringify(doc)},made=createNativeCreatorDocumentOwner({id:DRAFT,source},NOW);assert(made.ok);
 const w=data.spaces[actorId].creatorWorkspace!.working!;data=ok(setProgramCreatorWorking(data,{actorId,expectedWorking:w,working:{...w,nativeDocument:made.owner,nativeSelection:source}},NOW)).data;data=save(data,'native-save');return data;
}
function inspect(data:ProgramData){const r=inspectProgramCreatorNativeLineage(data,{actorId:data.activeActorId,draftId:DRAFT},NOW);assert(r.ok,r.ok?'':r.reason);return r.preview;}
function defaults(p:ReturnType<typeof inspect>):ProgramNativeLineageMapping{const items=Object.fromEntries(p.items.map(i=>[i.itemId,i.suggestedRowId??'skip']));return{items,remaining:Object.fromEntries(p.existing.filter(e=>!Object.values(items).includes(e.rowId)).map(e=>[e.rowId,'keep' as const]))};}
function apply(data:ProgramData,p=inspect(data),mapping=defaults(p),id='lineage'){return applyProgramCreatorNativeLineage(data,{actorId:data.activeActorId,requestId:id,preview:p,mapping},NOW);}
function edit(data:ProgramData,id:string,operation:Parameters<typeof applyProgramNativeCreatorOperation>[1]['operation']){const w=data.spaces[data.activeActorId].creatorWorkspace!.working!;return save(ok(applyProgramNativeCreatorOperation(data,{actorId:data.activeActorId,requestId:id,draftId:DRAFT,expectedWorking:w,expectedOwner:w.nativeDocument!,operation},NOW)).data,'save-'+id);}

test('NL01 identical captured source locators disambiguate equal titles and preserve moved targets, refs, dates, notes and progress byte-for-byte',()=>{
 let data=nativeLineageFixture(),space=data.spaces[data.activeActorId],old=space.creatorWorkspace!.executionSources![DRAFT],first=old.revisions[0].rows[0];
 space.text=M.updateTask(space.text,first.documentLineId,{date:'2026-10-02',note:'PRIVATE LINEAGE NOTE'});space.text=M.recordProgress(space.text,first.documentLineId,'2026-09-13',65);space.text=M.addDocument(space.text,{title:'옮긴 원래 항목'});const moved=moveProgramPersonalTaskText(space.text,first.documentLineId,space.text.documents.at(-1)!.id);assert(moved);space.text=moved;space.text=M.addDocument(space.text,{title:'연결 문서'});space.text=M.linkTask(space.text,space.text.documents.at(-1)!.id,0,first.documentLineId);
 const before=JSON.stringify(data),text=programClone(space.text),oldRevisions=programClone(old.revisions),p=inspect(data);assert.equal(new Set(p.items.map(i=>i.suggestedRowId)).size,2);assert(p.items.every(i=>i.suggestedRowId));
 const result=ok(apply(data,p));assert.equal(result.result,old.documentId);assert.deepEqual(result.data.spaces[data.activeActorId].text,text);assert.equal(JSON.stringify(data),before);assert.deepEqual(result.data.public,data.public);
 const own=result.data.spaces[data.activeActorId].creatorWorkspace!;assert.deepEqual(own.executionSources![DRAFT].revisions,oldRevisions);assert.equal(own.nativeExecutionSources![DRAFT].selections[p.items[0].itemId].execution!.lineId,first.documentLineId);assert.equal(Object.values(own.executionSources![DRAFT].adoption!.selections).filter(s=>s.disposition==='active').length,0);assert(validateProgramData(JSON.parse(JSON.stringify(result.data))));
});
test('NL02 explicit split mapping accepts one existing ID and one new target; duplicate target choices and cancellation are atomic',()=>{
 let data=nativeLineageFixture('# Split\n- [ ] One Two');const item=data.spaces[data.activeActorId].creatorWorkspace!.working!.nativeDocument!.document.parseResult.canonical.items[0];data=edit(data,'split',{type:'split',itemId:item.itemId,at:3});const p=inspect(data);assert.equal(p.items.length,2);assert(p.items.every(i=>i.suggestedRowId===null));
 const row=p.existing[0].rowId,bad={items:Object.fromEntries(p.items.map(i=>[i.itemId,row])),remaining:{}};assert(!apply(data,p,bad).ok);const cancel=ok(apply(data,p,{items:Object.fromEntries(p.items.map(i=>[i.itemId,'skip'])),remaining:{[row]:'keep'}}));assert(!cancel.changed);assert.equal(cancel.data,data);
 const result=ok(apply(data,p,{items:{[p.items[0].itemId]:row,[p.items[1].itemId]:'new'},remaining:{}}));assert.equal(M.tasks(result.data.spaces[data.activeActorId].text).filter(t=>t.docId===result.result).length,2);assert(M.tasks(result.data.spaces[data.activeActorId].text).some(t=>t.id===p.existing[0].lineId));
});
test('NL03 explicit merge maps one old ID and retains other exact block; no title inference or fabricated source version',()=>{
 let data=nativeLineageFixture('# Merge\n- [ ] One\n- [ ] Two'),items=data.spaces[data.activeActorId].creatorWorkspace!.working!.nativeDocument!.document.parseResult.canonical.items;data=edit(data,'merge',{type:'merge',itemIds:items.map(i=>i.itemId)});const p=inspect(data),included=p.items.filter(i=>i.included);assert.equal(included.length,1);assert.equal(included[0].suggestedRowId,null);assert.equal(included[0].exactRowIds.length,2);
 const [one,two]=p.existing,result=ok(apply(data,p,{items:Object.fromEntries(p.items.map(i=>[i.itemId,i.included?one.rowId:'skip'])),remaining:{[two.rowId]:'retain'}})),space=result.data.spaces[data.activeActorId],retained=M.tasks(space.text).find(t=>t.id===two.lineId)!;
 assert(space.archivedDocumentIds.includes(retained.docId));const selection=space.creatorWorkspace!.nativeExecutionSources![DRAFT].revisions[0].nativeSelection;assert('versionId' in selection);assert.equal(selection.versionId,'actual-source-version');assert.equal(M.tasks(space.text).find(t=>t.id===one.lineId)!.title,'One');
});
test('NL04 preview mutation, stale private edit, unknown mapping, foreign actor and replay after target loss never commit',()=>{
 const data=nativeLineageFixture(),p=inspect(data),mapping=defaults(p),original=p.items[0].incoming;p.items[0].incoming='forged';assert(!apply(data,p,mapping).ok);p.items[0].incoming=original;
 const changed=programClone(data);changed.spaces[data.activeActorId].text=M.addDocument(changed.spaces[data.activeActorId].text,{title:'다른 저장'});assert(!apply(changed,p,mapping).ok);assert(!apply(data,p,{...mapping,items:{...mapping.items,[p.items[0].itemId]:'unknown'}}).ok);
 assert(!applyProgramCreatorNativeLineage(data,{actorId:'creator-minji',requestId:'foreign',preview:p,mapping},NOW).ok);
 const result=ok(apply(data,p,mapping));assert(!ok(apply(result.data,p,mapping)).changed);assert(!apply(result.data,p,{...mapping,items:{...mapping.items,[p.items[0].itemId]:'skip'}}).ok);
 const broken=programClone(result.data);delete broken.spaces[data.activeActorId].creatorWorkspace!.nativeExecutionSources![DRAFT];assert(!apply(broken,p,mapping).ok);
});
test('NL05 quota zero-write, retry one transaction, reload and Program Undo restore exact raw owner and independent text',async()=>{
 const data=nativeLineageFixture(),p=inspect(data),mapping=defaults(p),store=new Map([['flow:operating',' protected bytes ']]),writes:string[]=[];let quota=true;
 const storage={getItem:(k:string)=>store.get(k)??null,setItem:(k:string,v:string)=>{if(quota)throw Error('quota');writes.push(k);store.set(k,v);},removeItem:()=>{throw Error('forbidden');}},controller=createProgramController({initialData:data,storage,exclusive:async work=>work()});assert(controller.ok);
 const build=(current:ProgramData)=>apply(current,p,mapping);assert(!(await controller.mutate('출처 연결',build,{actorId:data.activeActorId})).ok);assert.equal(writes.length,0);assert.deepEqual(controller.snapshot().envelope.data,data);
 quota=false;assert((await controller.mutate('출처 연결',build,{actorId:data.activeActorId})).ok);assert.deepEqual(writes,[PROGRAM_STATE_KEY]);const loaded=createProgramController({initialData:data,storage,exclusive:async work=>work()});assert(loaded.ok);assert(loaded.snapshot().envelope.data.spaces[data.activeActorId].creatorWorkspace!.nativeExecutionSources![DRAFT]);assert((await loaded.undo(data.activeActorId)).ok);assert.deepEqual(loaded.snapshot().envelope.data.spaces,data.spaces);assert.deepEqual(loaded.snapshot().envelope.data.public,data.public);assert(!apply(loaded.snapshot().envelope.data,p,mapping).ok);assert.equal(store.get('flow:operating'),' protected bytes ');
});
test('NL06 lineage enables next native field review without duplicate document or losing private history',()=>{
 let data=nativeLineageFixture();const before=data.spaces[data.activeActorId].creatorWorkspace!.executionSources![DRAFT],id=before.revisions[0].rows[0].documentLineId;data=ok(apply(data)).data;const itemId=data.spaces[data.activeActorId].creatorWorkspace!.working!.nativeDocument!.document.parseResult.canonical.items[0].itemId;
 data=edit(data,'renamed',{type:'rename',itemId,title:'Native source title'});const p=inspectProgramNativeCreatorHandoff(data,{actorId:data.activeActorId,draftId:DRAFT},NOW);assert(p.ok,p.ok?'':p.reason);assert(p.preview.rows.find(r=>r.itemId===itemId)!.fieldUpdatesAllowed);const result=ok(applyProgramNativeCreatorHandoff(data,{actorId:data.activeActorId,requestId:'source-adopt',preview:p.preview,choices:{[itemId]:{source:'incoming',date:'keep',time:'keep',children:'keep'}}},NOW));assert.equal(result.result,before.documentId);assert.equal(M.tasks(result.data.spaces[data.activeActorId].text).find(t=>t.id===id)!.title,'Native source title');
});
test('NL07 raw series retains its exact old occurrence records while new native series has a different owner',()=>{
 let data=nativeLineageFixture('# Series\n- [ ] Repeat\n  - 날짜: 2026-09-20\n  - 반복: 매일\n  - 반복 종료: 3회');const own=data.spaces[data.activeActorId].creatorWorkspace!.executionSources![DRAFT],flowRef=own.revisions[0].flow.ref,input={actorId:data.activeActorId,flowRef,localToday:'2026-09-13'},read=readProgramExecutionOccurrences(data,input);assert(read.ok,read.ok?'':read.reason);
 const changed=updateProgramOccurrenceExecution(data,{...input,identity:read.rows[0].identity,expected:null,changes:{completion:{status:'completed',completedAt:NOW}}});assert(changed.ok,changed.ok?'':changed.reason);data=changed.data;const records=programClone(data.spaces[data.activeActorId].recurrenceExecution),p=inspect(data),result=ok(apply(data,p)),space=result.data.spaces[data.activeActorId],native=space.creatorWorkspace!.nativeExecutionSources![DRAFT];assert.deepEqual(space.recurrenceExecution,records);assert(space.archivedDocumentIds.some(id=>M.getDocument(space.text,id)?.lines.some(l=>l.id===p.existing[0].lineId)));
 const next=readProgramExecutionOccurrences(result.data,{...input,flowRef:programNativeExecutionRef(native.id)});assert(next.ok,next.ok?'':next.reason);assert.equal(next.rows.length,3);assert(next.rows.every(row=>row.completion!=='completed'));assert(validateProgramData(result.data));
 const recovery=readProgramOccurrenceRecovery(result.data,{actorId:data.activeActorId,localToday:'2026-09-13',flowRefs:[flowRef]});assert.equal(recovery.length,1);assert.equal(recovery[0].stored.occurrenceId,read.rows[0].identity.occurrenceId);
});
test('NL08 archived target and corrupted lineage pointers fail closed',()=>{
 const data=nativeLineageFixture(),p=inspect(data),blocked=programClone(data);blocked.spaces[data.activeActorId].archivedDocumentIds.push(p.documentId);const read=inspectProgramCreatorNativeLineage(blocked,{actorId:data.activeActorId,draftId:DRAFT},NOW);assert(!read.ok);assert(!apply(blocked,p).ok);
 const linked=ok(apply(data,p)).data;for(const change of [(o:NonNullable<typeof linked.spaces[string]['creatorWorkspace']>)=>{o.nativeExecutionSources![DRAFT].rawLineage!.ownerId='foreign';},(o:NonNullable<typeof linked.spaces[string]['creatorWorkspace']>)=>{Object.values(o.nativeExecutionSources![DRAFT].rawLineage!.bindings)[0].rowId='unknown';},(o:NonNullable<typeof linked.spaces[string]['creatorWorkspace']>)=>{Object.values(o.executionSources![DRAFT].adoption!.selections)[0].disposition='active';}]){const bad=programClone(linked);change(bad.spaces[data.activeActorId].creatorWorkspace!);assert(!validateProgramData(bad));}
});
test('NL09 genuine CRLF source, private prose before properties, multiline edits and child history survive lineage and later field acceptance',()=>{
 const raw='# 준비\r\n- [ ] Main\r\n  - 설명: Source detail\r\n    continuation\r\n  - custom: Unknown property\r\n  - [ ] Child';let data=nativeLineageFixture(raw),space=data.spaces[data.activeActorId],source=space.creatorWorkspace!.executionSources![DRAFT],doc=M.getDocument(space.text,source.documentId)!;
 space.text=M.editText(space.text,doc.id,M.raw(doc).replace('  - 설명: Source detail','  PRIVATE-before-property\n  - 설명: Private changed detail'),{progressDate:'2026-09-13'});
 const actual=M.getDocument(space.text,doc.id)!,privateLine=actual.lines.find(l=>l.text.includes('PRIVATE-before-property'))!,privateDetail=actual.lines.find(l=>l.text.includes('Private changed detail'))!,child=M.parseDocument(actual,space.text).items.find(i=>!i.isCanonical)!;space.text=M.recordProgress(space.text,child.id,'2026-09-13',100);const history=programClone(space.text.progressRecords),original=programClone(source.revisions);
 data=ok(apply(data)).data;const itemId=data.spaces[data.activeActorId].creatorWorkspace!.working!.nativeDocument!.document.parseResult.canonical.items[0].itemId;data=edit(data,'CRLF-title',{type:'rename',itemId,title:'Incoming title'});const p=inspectProgramNativeCreatorHandoff(data,{actorId:data.activeActorId,draftId:DRAFT},NOW);assert(p.ok);
 data=ok(applyProgramNativeCreatorHandoff(data,{actorId:data.activeActorId,requestId:'after-lineage',preview:p.preview,choices:{[itemId]:{source:'incoming',date:'keep',time:'keep',children:'keep'}}},NOW)).data;space=data.spaces[data.activeActorId];assert.deepEqual(space.creatorWorkspace!.executionSources![DRAFT].revisions,original);assert.equal(original[0].raw,raw);assert.deepEqual(space.text.progressRecords,history);assert(M.getDocument(space.text,doc.id)!.lines.some(l=>l.id===privateLine.id&&l.text===privateLine.text));assert([...space.text.documents,...space.text.flows].some(d=>d.lines.some(l=>l.id===privateDetail.id&&l.text===privateDetail.text)));assert(M.getDocument(space.text,doc.id)!.lines.some(l=>l.id===child.id));assert(validateProgramData(data));
});
