import test from 'node:test';import assert from 'node:assert/strict';
import {createProgramData,validateProgramData} from './program-data';import {createProgramController,programSame} from './controller';import {PROGRAM_STATE_KEY,programClone,programResult,type ProgramData,type ProgramTransition} from './contract';
import {createTextAuthoringDocument} from './native-creator-vendor/text-authoring/parser';import {createNativeCreatorDocumentOwner} from './native-creator-document';
import {setProgramCreatorWorking,applyProgramCreatorAction} from './creator-workspace';import {inspectProgramNativeCreatorHandoff,applyProgramNativeCreatorHandoff} from './creator-native-execution-adapter';
import {prepareProgramNativeSourceInput,programNativeSourceMatches} from './creator-native-source-input';import {stageProgramNativeSourceUpdate,transitionProgramNativeSourceUpdate,readProgramNativeSourceUpdate} from './creator-native-source-store';
import {fingerprintPersonalWorkspacePocAuthoringSource as fp} from '../personal-workspace-poc-authoring';import {textWorkspaceModel as M} from './text-workspace';
import {inspectProgramPrivateOutput,makeProgramPrivateOutput} from './private-output';
const BASE='2026-09-12T08:00:00.000Z',LATER='2026-09-12T09:00:00.000Z',ID='source-private-journey';
for(const scenario of ['plain','checks','crlf'] as const)test(`${scenario==='crlf'?'CSPJ03 CRLF source and LF textarea identity':scenario==='checks'?'CSPJ02 real nested source checks':'CSPJ01 real controller'} source acceptance/save/selective private adoption/progress/source Undo preserves separate owners`,async()=>{
 const withSubchecks=scenario!=='plain',base='# 준비\n- [ ] 출발 준비\n  - 날짜: 2026-09-20\n  - 시간: 09:30\n  - 설명: 이전 설명'+(withSubchecks?'\n  - [ ] 여권 확인':''),raw=scenario==='crlf'?base.replaceAll('\n','\r\n'):base,incoming=raw.replaceAll('\r\n','\n').replace('09:30','11:00').replace('이전 설명','새 설명').replace('2026-09-20','2026-09-24');
 const doc=createTextAuthoringDocument(raw,{documentId:'genuine-parser-source',ownership:'creator',now:BASE}),source={storageKey:'flow:text-authoring:drafts:v1' as const,draftId:'original-draft',versionId:'explicit-fixture-version',revisionId:doc.revision.revisionId,documentJson:JSON.stringify(doc)};
 const native=createNativeCreatorDocumentOwner({id:ID,source},BASE);assert(native.ok);const values=new Map<string,string>([[source.storageKey,source.documentJson],['flow:protected-journey',' untouched ']]);let writes=0;
 const storage={getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>{assert.equal(k,PROGRAM_STATE_KEY);values.set(k,v);writes++;},removeItem:()=>{throw Error('no remove')}};
 const controller=createProgramController({initialData:createProgramData(),storage,exclusive:async run=>run()});assert(controller.ok);const snapshot=controller.snapshot,mutate=controller.mutate,actorId=snapshot().envelope.data.activeActorId;assert.equal(typeof mutate,'function');
 async function commit(label:string,transition:(data:ProgramData)=>ProgramTransition<string>){const result=await mutate(label,transition,{actorId});assert(result.ok,JSON.stringify(result));return result;}
 const current=()=>snapshot().envelope.data,working=()=>current().spaces[actorId].creatorWorkspace!.working!;
 const head=(d:ProgramData)=>({actorId,draftId:ID,expectedWorking:d.spaces[actorId].creatorWorkspace!.working,expectedSession:d.spaces[actorId].creatorWorkspace!.sourceUpdateSessions?.[ID]?.session??null});
 async function save(requestId:string){await commit('explicit save',d=>{const workspace=d.spaces[actorId].creatorWorkspace!,w=workspace.working!;return applyProgramCreatorAction(d,{actorId,requestId,expectedNativeDocument:w.nativeDocument!,expectedNativeSelection:w.nativeSelection??null,expectedStructure:null,action:{type:'save',draftId:ID,title:w.title,rawText:w.rawText,sourceFingerprint:fp(w.rawText),expectedLibraryRevision:workspace.library.revision,...(w.baseRecordRevision?{expectedRecordRevision:w.baseRecordRevision}:{}),now:LATER}},LATER)});}
 async function handoff(requestId:string,first=false){const p=inspectProgramNativeCreatorHandoff(current(),{actorId,draftId:ID},LATER);assert(p.ok);return commit('private handoff',d=>applyProgramNativeCreatorHandoff(d,{actorId,requestId,preview:p.preview,choices:Object.fromEntries(p.preview.rows.map(r=>[r.itemId,{source:'incoming',date:'keep',time:first?'keep':'incoming',children:'keep'}]))},LATER));}
 await commit('working',d=>setProgramCreatorWorking(d,{actorId,expectedWorking:null,working:{draftId:ID,title:'준비',rawText:raw,baseRecordRevision:null,nativeDocument:native.owner,nativeSelection:source}},BASE));await save('save-a');await handoff('handoff-a',true);
 const firstOwner=current().spaces[actorId].creatorWorkspace!.nativeExecutionSources![ID],lineId=firstOwner.revisions[0].rows[0].lineId;
 const child=withSubchecks?current().spaces[actorId].text.documents.find(d=>d.id===firstOwner.documentId)!.lines.find(line=>line.text.includes('여권 확인')):undefined;if(withSubchecks)assert(child);
 await commit('personal edits and reference',d=>{const next=programClone(d),s=next.spaces[actorId];s.text=M.updateTask(s.text,lineId,{date:'2026-10-02',note:'PRIVATE JOURNEY NOTE'});s.text=M.recordProgress(s.text,lineId,'2026-09-12',20);s.text=M.addDocument(s.text,{title:'무관 연결 문서'});s.text=M.linkTask(s.text,s.text.documents.at(-1)!.id,0,lineId);return programResult(d,next,lineId)});
 const beforeSource=programClone(current()),oldSaved=programClone(beforeSource.spaces[actorId].creatorWorkspace!.savedHistory),oldExecution=programClone(firstOwner.revisions);
 const prepared=prepareProgramNativeSourceInput(working().nativeDocument!,{rawText:incoming,version:'B',actorId},LATER);assert(prepared);const activeId=prepared.owner.document.parseResult.canonical.items[0].itemId,match=programNativeSourceMatches(prepared,{[activeId]:prepared.candidateDocument.parseResult.canonical.items[0].itemId});assert(match);
 await commit('stage',d=>stageProgramNativeSourceUpdate(d,{...head(d),envelope:prepared.envelope,candidateDocument:prepared.candidateDocument,matches:match},LATER));
 const view=readProgramNativeSourceUpdate(current(),actorId,ID);assert(view?.ok);for(const change of view.value.changes)await commit('decision',d=>transitionProgramNativeSourceUpdate(d,{...head(d),requestId:`decide-${change.changeId}`,event:{kind:'decision',changeId:change.changeId,decision:'use_incoming'}},LATER));
 await commit('source apply',d=>transitionProgramNativeSourceUpdate(d,{...head(d),requestId:'source-apply',event:{kind:'apply'}},LATER));assert(programSame(current().spaces[actorId].text,beforeSource.spaces[actorId].text));assert(programSame(current().public,beforeSource.public));assert(programSame(current().spaces[actorId].creatorWorkspace!.savedHistory,oldSaved));
 await save('save-b');await handoff('handoff-b');let task=M.tasks(current().spaces[actorId].text).find(t=>t.id===lineId)!;assert.equal(task.date,'2026-10-02');assert.equal(task.time,'11:00');assert.equal(task.note,'PRIVATE JOURNEY NOTE');assert(programSame(current().spaces[actorId].creatorWorkspace!.nativeExecutionSources![ID].revisions.slice(0,1),oldExecution));
 if(child)assert(programSame(current().spaces[actorId].text.documents.find(d=>d.id===firstOwner.documentId)!.lines.find(line=>line.id===child.id),child));
 if(scenario==='crlf'){
  const actual=current().spaces[actorId].creatorWorkspace!.nativeExecutionSources![ID],last=actual.revisions.at(-1)!;
  assert.equal(last.rows[0].itemId,firstOwner.revisions[0].rows[0].itemId);assert.equal(last.rows[0].lineId,lineId);
  assert.equal(last.rows[0].sourceItemId,last.nativeDocument.document.parseResult.canonical.items[0].itemId);assert.notEqual(last.rows[0].sourceItemId,last.rows[0].itemId);
  for(const kind of ['wrong-source','wrong-execution','missing-link'] as const){const bad=programClone(current()),row=bad.spaces[actorId].creatorWorkspace!.nativeExecutionSources![ID].revisions.at(-1)!.rows[0];if(kind==='wrong-source')row.sourceItemId='forged-source';else if(kind==='wrong-execution')row.itemId='forged-execution';else delete row.sourceItemId;assert.equal(validateProgramData(bad),false,kind);}
  const p=inspectProgramNativeCreatorHandoff(current(),{actorId,draftId:ID},LATER);assert(p.ok);assert.equal(p.preview.rows.length,1);assert.equal(p.preview.rows[0].mode,'update');assert.equal(p.preview.rows[0].itemId,last.rows[0].itemId);
 }
 await commit('additional personal progress',d=>{const next=programClone(d);next.spaces[actorId].text=M.recordProgress(next.spaces[actorId].text,lineId,'2026-09-13',45);return programResult(d,next,lineId)});
 const beforeUndo=programClone(current()),documentId=firstOwner.documentId,outputWrites=writes;
 const inspected=inspectProgramPrivateOutput(current(),{actorId,documentId});assert(inspected.ok);assert.equal(inspected.rows.length,1);
 const row=inspected.rows[0];assert.equal(row.id,lineId);assert.equal(row.date,'2026-10-02');assert.equal(row.sourceDate,'2026-09-20');assert.equal(row.time,'11:00');assert.equal(row.sourceTime,'11:00');assert.equal(row.progress,45);assert.match(row.note,/PRIVATE JOURNEY NOTE/);assert.match(row.note,/새 설명/);
 // The source-date field was explicitly kept on its earlier accepted revision.
 // Latest creator raw is not allowed to silently replace that provenance.
 const output=(format:'txt'|'csv'|'ics')=>{const result=makeProgramPrivateOutput(current(),{actorId,documentId,mode:'tasks',selectedItemIds:[lineId],format},LATER);assert(result.ok);return result.payload;};
 const outputs={txt:output('txt'),csv:output('csv'),ics:output('ics')};assert.match(outputs.txt,/실행 날짜: 2026-10-02/);assert.match(outputs.txt,/원문 날짜: 2026-09-20/);assert.match(outputs.txt,/진행: 45%/);assert.match(outputs.ics,/DTSTART:20261002T110000\r\n/);assert(!outputs.ics.includes('DTSTART;TZID='));assert(!outputs.ics.includes('DTEND'));assert.equal(writes,outputWrites);assert(programSame(current(),beforeUndo));
 await commit('source Undo',d=>transitionProgramNativeSourceUpdate(d,{...head(d),requestId:'source-undo',event:{kind:'undo'}},LATER));
 assert(programSame(current().spaces[actorId].text,beforeUndo.spaces[actorId].text));assert(programSame(current().spaces[actorId].creatorWorkspace!.nativeExecutionSources,beforeUndo.spaces[actorId].creatorWorkspace!.nativeExecutionSources));assert(programSame(current().spaces[actorId].creatorWorkspace!.library,beforeUndo.spaces[actorId].creatorWorkspace!.library));assert(programSame(current().public,beforeSource.public));assert.equal(values.get(source.storageKey),source.documentJson);assert.equal(values.get('flow:protected-journey'),' untouched ');assert(writes>0);
 const undoWrites=writes;assert.deepEqual({txt:output('txt'),csv:output('csv'),ics:output('ics')},outputs);assert.equal(writes,undoWrites);
 const reload=createProgramController({initialData:createProgramData(),storage,exclusive:async run=>run()});assert(reload.ok);assert(programSame(reload.snapshot().envelope.data,current()));
});
