import test from 'node:test';
import assert from 'node:assert/strict';
import {createTextAuthoringDocument} from './native-creator-vendor/text-authoring/parser';
import {applyAuthoringOperation} from './native-creator-vendor/text-authoring/operations';
import {resolveAuthoringSourceUpdateChange,createAuthoringSourceUpdateCandidate} from './native-creator-vendor/text-authoring/source-update';
import {createNativeCreatorDocumentOwner,applyNativeCreatorDocumentOperation,applyNativeCreatorSourceDecision,applyNativeCreatorSourceSession,validateNativeCreatorDocumentOwner,readNativeCreatorDocument} from './native-creator-document';
import {stableAuthoringJson} from './native-creator-vendor/text-authoring/identity';
import {createCreatorNativeSourceEnvelope,stageCreatorNativeSourceCandidate,transitionCreatorNativeSourceSession,readCreatorNativeSourceSession,serializeCreatorNativeSourceSession,hydrateCreatorNativeSourceSession,validateCreatorNativeSourceSession} from './creator-native-source-update';
import type {CreatorNativeSourceSession,CreatorNativeSourceAuthority} from './creator-native-source-update-contract';
import type {NativeCreatorDocumentOwner} from './native-creator-document-contract';
const BASE='2026-09-12T01:00:00.000Z',AT='2026-09-12T01:01:00.000Z',NOW='2026-09-12T01:02:00.000Z';
const RAW='# Course\r\n- [ ] Core CS\r\n  detail: old detail',INCOMING=RAW.replace('old detail','incoming detail')+'\r\n- [ ] Mathematics\r\n  detail: new item';
function fixture(){const document=createTextAuthoringDocument(RAW,{documentId:'source-doc',ownership:'creator',sourceTitle:'Explicit local fixture',sourceUrl:'https://example.test/source',sourceExternalVersion:'commit-a',now:BASE});const made=createNativeCreatorDocumentOwner({id:'source-draft',source:{storageKey:'flow:text-authoring:drafts:v1',draftId:'d2',versionId:'saved-a',revisionId:document.revision.revisionId,documentJson:JSON.stringify(document)}},BASE);assert(made.ok);const owner=made.owner,authority:CreatorNativeSourceAuthority={actorId:'creator',draftId:owner.id,lane:'creator',permission:true,archived:false};const envelope=createCreatorNativeSourceEnvelope(owner,{rawText:INCOMING,externalVersion:'commit-b',providedBy:'local-fixture',sourceOwnerClaim:'explicit example',collectedAt:AT,receivedAt:AT});assert(envelope.ok);const incoming=createTextAuthoringDocument(INCOMING,{documentId:document.documentId,ownership:'creator',sourceTitle:document.sourceTitle,sourceUrl:document.sourceUrl,sourceExternalVersion:'commit-b',now:AT});const staged=stageCreatorNativeSourceCandidate(owner,{envelope:envelope.value,candidateDocument:incoming,authority,matches:[{activeItemId:document.parseResult.canonical.items[0].itemId,incomingItemId:incoming.parseResult.canonical.items[0].itemId,basis:'explicit'}]},AT);assert(staged.ok,JSON.stringify(staged));return{owner,authority,session:staged.value,incoming,envelope:envelope.value};}
function event(s:CreatorNativeSourceSession,o:NativeCreatorDocumentOwner,a:CreatorNativeSourceAuthority,e:Parameters<typeof transitionCreatorNativeSourceSession>[2]['event'],requestId:string){const result=transitionCreatorNativeSourceSession(s,o,{expectedSession:s,authority:a,event:e,requestId},NOW);assert(result.ok,JSON.stringify(result));return result.value;}
function ready(keep=false){const f=fixture();let session=f.session;const view=readCreatorNativeSourceSession(session,f.owner,f.authority);assert(view.ok);for(const c of view.value.changes)session=event(session,f.owner,f.authority,{kind:'decision',changeId:c.changeId,decision:keep?'keep_working':'use_incoming'},c.changeId).session;return{...f,session};}
test('NS01 stage preserves full immutable owner; genuine explicit envelope and all three raw values',()=>{const f=fixture(),before=JSON.stringify(f.owner),read=readCreatorNativeSourceSession(f.session,f.owner,f.authority);assert(read.ok);assert.equal(read.value.comparison.baseRawText,RAW);assert.equal(read.value.comparison.workingRawText,RAW);assert.equal(read.value.comparison.candidateRawText,INCOMING);assert(read.value.changes.length>=2);assert.equal(JSON.stringify(f.owner),before);assert.deepEqual(read.value.resultOwner,f.owner);assert.equal(f.envelope.rawByteLength,new TextEncoder().encode(INCOMING).length);});
test('NS02 faithful no-override keep marker matches original resolver, journal reload, original operations remain valid',()=>{const f=ready(true),read=readCreatorNativeSourceSession(f.session,f.owner,f.authority);assert(read.ok);const original=readCreatorNativeSourceSession(fixture().session,f.owner,f.authority);assert(original.ok);const oracle=structuredClone(original.value.stagedOwner.document);for(const d of read.value.decisions){const state=oracle.sourceState;assert(state&&state.status!=='current');const c=state.changes.find(x=>x.changeId===d.changeId)!;if(c.kind==='changed'&&c.userValue===undefined){c.userValue=c.oldSourceValue===undefined?null:structuredClone(c.oldSourceValue);c.userOwner='creator';}resolveAuthoringSourceUpdateChange(oracle,c.changeId,c.kind==='changed'?'keep_user':c.kind==='added'?'exclude_added':'keep_previous','creator',NOW);}assert.deepEqual(read.value.stagedOwner.document,JSON.parse(JSON.stringify(oracle)));assert(validateNativeCreatorDocumentOwner(JSON.parse(JSON.stringify(read.value.stagedOwner))));const applied=event(f.session,f.owner,f.authority,{kind:'apply'},'apply');assert.throws(()=>applyAuthoringOperation(oracle,{type:'apply_source_update'},{actorLane:'creator',now:NOW}),/inconsistent/);assert.equal(applied.owner.document.parseResult.canonical.items[0].detail,'old detail');assert.equal(applied.owner.document.parseResult.canonical.items[0].sourceDetail,'incoming detail');assert.equal(applied.owner.document.parseResult.canonical.items[1].included,false);assert.equal(applied.owner.document.rawText,INCOMING);assert.equal(applied.owner.source.documentJson,f.owner.source.documentJson);});
test('NS03 apply receipt exact projection, idempotency, reload and source-only Undo restore full aggregate',()=>{const f=ready(),before=JSON.stringify(f.owner),a=event(f.session,f.owner,f.authority,{kind:'apply'},'apply');assert(a.ownerChanged);const encoded=serializeCreatorNativeSourceSession(a.session);assert(encoded.ok);const loaded=hydrateCreatorNativeSourceSession(encoded.value);assert(loaded.ok);const read=readCreatorNativeSourceSession(loaded.value,a.owner,f.authority);assert(read.ok);assert.equal(read.value.status,'undo-available');assert(read.value.receipt);assert.deepEqual(read.value.receipt.sideEffects,{publish:0,network:0,operatingWrite:0,privateExecutionWrite:0});assert(readNativeCreatorDocument(a.owner).ok);const retry=event(loaded.value,a.owner,f.authority,{kind:'apply'},'apply');assert(!retry.changed&&retry.replayed);const undone=event(loaded.value,a.owner,f.authority,{kind:'undo'},'undo');assert.deepEqual(undone.owner,f.owner);assert.equal(JSON.stringify(f.owner),before);assert(validateCreatorNativeSourceSession(undone.session));const terminal=transitionCreatorNativeSourceSession(undone.session,undone.owner,{expectedSession:undone.session,authority:f.authority,event:{kind:'apply'},requestId:'apply'},NOW);assert(!terminal.ok&&terminal.reason==='terminal-session');});
test('NS04 unresolved/later block apply; defer focus scroll survive canonical reload and fresh permission recheck',()=>{const f=fixture();let s=f.session;const read=readCreatorNativeSourceSession(s,f.owner,f.authority);assert(read.ok);s=event(s,f.owner,f.authority,{kind:'decision',changeId:read.value.changes[0].changeId,decision:'later'},'later').session;s=event(s,f.owner,f.authority,{kind:'focus',selectedChangeId:read.value.changes[0].changeId,scrollTop:420},'focus').session;s=event(s,f.owner,f.authority,{kind:'defer'},'defer').session;const encoded=serializeCreatorNativeSourceSession(s);assert(encoded.ok);const reload=hydrateCreatorNativeSourceSession(encoded.value);assert(reload.ok);const reentry=readCreatorNativeSourceSession(reload.value,f.owner,{...f.authority,permission:false});assert(reentry.ok);assert.equal(reentry.value.creatorCanApply,false);assert.equal(reentry.value.scrollTop,420);assert.equal(reentry.value.status,'deferred');for(const authority of [f.authority,{...f.authority,permission:false},{...f.authority,lane:'personal' as const},{...f.authority,archived:true}])assert(!transitionCreatorNativeSourceSession(s,f.owner,{expectedSession:s,authority,event:{kind:'apply'},requestId:'apply'},NOW).ok);});
test('NS05 stale session/head, request payload conflicts and injected failures leave inputs unchanged',()=>{const f=ready(),before=JSON.stringify(f);const changed=applyNativeCreatorDocumentOperation(f.owner,{expectedOwner:f.owner,requestId:'personal',operation:{type:'exclude',itemId:f.owner.document.parseResult.canonical.items[0].itemId}},NOW);assert(changed.ok);for(const input of [{owner:changed.owner,expectedSession:f.session},{owner:f.owner,expectedSession:fixture().session}])assert(!transitionCreatorNativeSourceSession(f.session,input.owner,{expectedSession:input.expectedSession,authority:f.authority,event:{kind:'apply'},requestId:'apply'},NOW).ok);for(const injectFailure of ['before-domain-apply','before-commit'] as const)assert(!transitionCreatorNativeSourceSession(f.session,f.owner,{expectedSession:f.session,authority:f.authority,event:{kind:'apply'},requestId:'apply',injectFailure},NOW).ok);assert.equal(JSON.stringify(f),before);});
test('NS06 envelope/candidate/event/receipt tamper and unknown persisted permissions fail closed',()=>{const f=ready(),a=event(f.session,f.owner,f.authority,{kind:'apply'},'apply');for(const mutate of [(s:any)=>s.envelope.rawText+='x',(s:any)=>s.envelope.rawByteHash='bad',(s:any)=>s.envelope.baseSnapshotId='other',(s:any)=>s.candidateDocument.rawText+='x',(s:any)=>s.events[0].changeId='other',(s:any)=>s.events.at(-1).receipt.resultOwnerHash='bad',(s:any)=>s.events.at(-1).receipt.sideEffects.publish=1,(s:any)=>s.creatorCanApply=true,(s:any)=>s.events[0].oldSourceValue='forged']){const bad=structuredClone(a.session);mutate(bad);assert(!validateCreatorNativeSourceSession(bad));}const bad=structuredClone(a.owner);const decision=bad.actions.find(x=>x.kind==='source-decision');assert(decision);(decision as any).decisionVersion=2;assert(!validateNativeCreatorDocumentOwner(bad));});
test('NS07 rejecting is terminal but preserves source and inspection, unchanged decisions are no-op',()=>{const f=ready(),r=readCreatorNativeSourceSession(f.session,f.owner,f.authority);assert(r.ok);const d=r.value.decisions[0],same=event(f.session,f.owner,f.authority,{kind:'decision',changeId:d.changeId,decision:d.decision},'same');assert(!same.changed);const rejected=event(f.session,f.owner,f.authority,{kind:'reject'},'reject');assert.deepEqual(rejected.owner,f.owner);assert(!rejected.ownerChanged);assert(!transitionCreatorNativeSourceSession(rejected.session,f.owner,{expectedSession:rejected.session,authority:f.authority,event:{kind:'apply'},requestId:'after-reject'},NOW).ok);});
test('NS08 full session path performs no global storage/network access',()=>{const names=['localStorage','sessionStorage','fetch'] as const,previous=names.map(n=>Object.getOwnPropertyDescriptor(globalThis,n));let calls=0;try{for(const n of names)Object.defineProperty(globalThis,n,{configurable:true,get(){calls++;throw Error('forbidden');}});const f=ready(true),a=event(f.session,f.owner,f.authority,{kind:'apply'},'apply');assert(serializeCreatorNativeSourceSession(a.session).ok);event(a.session,a.owner,f.authority,{kind:'undo'},'undo');assert.equal(calls,0);}finally{names.forEach((n,i)=>{if(previous[i])Object.defineProperty(globalThis,n,previous[i]!);else Reflect.deleteProperty(globalThis,n);});}});
test('NS09 exact matches, candidate linkage, denied-origin reentry and non-default receipt options are checked',()=>{const f=fixture();for(const mutate of [(s:any)=>s.matches[0].basis='guessed',(s:any)=>s.matches[0].extra=true,(s:any)=>s.matches[0].incomingItemId='foreign',(s:any)=>s.candidateDocument.documentId='foreign',(s:any)=>s.envelope.externalVersion='']){const bad=structuredClone(f.session);mutate(bad);assert(!validateCreatorNativeSourceSession(bad));}const denied=stageCreatorNativeSourceCandidate(f.owner,{envelope:f.envelope,candidateDocument:f.incoming,matches:f.session.matches,authority:{...f.authority,permission:false}},AT);assert(denied.ok);const read=readCreatorNativeSourceSession(denied.value,f.owner,f.authority);assert(read.ok&&!read.value.creatorCanApply);assert(!transitionCreatorNativeSourceSession(denied.value,f.owner,{expectedSession:denied.value,requestId:'deny',event:{kind:'apply'},authority:f.authority},NOW).ok);const options={primaryArtifact:'sheet' as const,finiteOccurrenceLimit:2,openEndedOccurrenceWeeks:4};const staged=stageCreatorNativeSourceCandidate(f.owner,{envelope:f.envelope,candidateDocument:f.incoming,matches:f.session.matches,projectionOptions:options,authority:f.authority},AT);assert(staged.ok);let session=staged.value;const view=readCreatorNativeSourceSession(session,f.owner,f.authority);assert(view.ok);for(const c of view.value.changes)session=event(session,f.owner,f.authority,{kind:'decision',changeId:c.changeId,decision:'use_incoming'},c.changeId).session;const applied=event(session,f.owner,f.authority,{kind:'apply'},'apply'),result=readCreatorNativeSourceSession(applied.session,applied.owner,f.authority);assert(result.ok);assert.deepEqual(result.value.receipt?.projectionOptions,options);const tampered=structuredClone(applied.session);tampered.projectionOptions.finiteOccurrenceLimit=3;assert(!validateCreatorNativeSourceSession(tampered));});
test('NS10 later cancels a prior keep marker and immutable-session reentry allows explicit incoming replacement',()=>{const f=ready(true),view=readCreatorNativeSourceSession(f.session,f.owner,f.authority);assert(view.ok);const changed=view.value.changes.find(c=>c.kind==='changed')!;const later=event(f.session,f.owner,f.authority,{kind:'decision',changeId:changed.changeId,decision:'later'},'later');assert(!transitionCreatorNativeSourceSession(later.session,f.owner,{expectedSession:later.session,authority:f.authority,event:{kind:'apply'},requestId:'not-yet'},NOW).ok);const selected=event(later.session,f.owner,f.authority,{kind:'decision',changeId:changed.changeId,decision:'use_incoming'},'incoming'),applied=event(selected.session,f.owner,f.authority,{kind:'apply'},'apply');assert.equal(applied.owner.document.parseResult.canonical.items[0].detail,'incoming detail');assert.equal(applied.owner.document.parseResult.canonical.items[1].included,false);});
test('NS11 cached-valid session does not bypass mutable tamper, different actor or revoked foreground authority',()=>{const f=ready();assert(validateCreatorNativeSourceSession(f.session));assert(validateCreatorNativeSourceSession(structuredClone(f.session)));for(const authority of [{...f.authority,actorId:'other'},{...f.authority,permission:false},{...f.authority,archived:true}]){assert(!transitionCreatorNativeSourceSession(f.session,f.owner,{expectedSession:f.session,authority,event:{kind:'apply'},requestId:'blocked'},NOW).ok);const read=readCreatorNativeSourceSession(f.session,f.owner,authority);assert(!read.ok||!read.value.creatorCanApply);}const bad=f.session as any;bad.events[0].changeId='forged-after-cache';assert(!validateCreatorNativeSourceSession(bad));assert(!readCreatorNativeSourceSession(bad,f.owner,f.authority).ok);});

function recurrenceStatusFixture(personalKeep:boolean){
 const raw=(count:number)=>`# Rule\n- [ ] Work\n  date: 2026-09-20\n  repeat: 매일\n  repeat_end: ${count}회`;
 const document=createTextAuthoringDocument(raw(3),{documentId:'status-rule-document',ownership:'creator',sourceExternalVersion:'a',now:BASE}),made=createNativeCreatorDocumentOwner({id:'status-rule-owner',source:{storageKey:'flow:text-authoring:drafts:v1',draftId:'status-source',versionId:'saved-a',revisionId:document.revision.revisionId,documentJson:JSON.stringify(document)}},BASE);assert(made.ok);let owner=made.owner;
 const candidate=(source:NativeCreatorDocumentOwner,count:number,version:string)=>{const incoming=createTextAuthoringDocument(raw(count),{documentId:document.documentId,ownership:'creator',sourceExternalVersion:version,now:AT}),matches=[{activeItemId:source.document.parseResult.canonical.items[0].itemId,incomingItemId:incoming.parseResult.canonical.items[0].itemId,basis:'explicit' as const}];return{incoming,matches,candidate:createAuthoringSourceUpdateCandidate(incoming,{capturedAt:AT,externalVersion:version,matches})};};
 if(personalKeep){const b=candidate(owner,5,'b'),staged=applyNativeCreatorDocumentOperation(owner,{expectedOwner:owner,requestId:'stage-b',operation:{type:'stage_source_update',candidate:b.candidate}},AT);assert(staged.ok);owner=staged.owner;const state=owner.document.sourceState;assert(state&&state.status!=='current');assert.equal(state.changes.length,0);for(const change of owner.sourceRecurrences!.pending!.changes){const d=applyNativeCreatorSourceDecision(owner,{expectedOwner:owner,requestId:'keep-'+change.changeId,decision:{decisionVersion:1,changeId:change.changeId,decision:'keep_working'}},AT);assert(d.ok);owner=d.owner;}const applied=applyNativeCreatorSourceSession(owner,{expectedOwner:owner,requestId:'apply-b'},AT);assert(applied.ok);owner=applied.owner;}
 const c=candidate(owner,7,'c'),authority:CreatorNativeSourceAuthority={actorId:'creator',draftId:owner.id,lane:'creator',permission:true,archived:false},envelope=createCreatorNativeSourceEnvelope(owner,{rawText:c.incoming.rawText,externalVersion:'c',providedBy:'explicit local fixture',sourceOwnerClaim:'creator',collectedAt:AT,receivedAt:AT});assert(envelope.ok);const session=stageCreatorNativeSourceCandidate(owner,{envelope:envelope.value,candidateDocument:c.incoming,matches:c.matches,authority},AT);assert(session.ok);return{owner,authority,session:session.value};
}
test('NS12 recurrence-only status requires real old-source/working divergence, not mandatory userOwner or incoming difference',()=>{
 for(const personalKeep of [false,true]){const f=recurrenceStatusFixture(personalKeep),before=stableAuthoringJson(f),view=readCreatorNativeSourceSession(f.session,f.owner,f.authority);assert(view.ok);assert.equal(view.value.stagedOwner.document.sourceState?.status,'source_updated');assert.equal(view.value.changes.length,1);const change=view.value.changes[0];assert(change.kind==='changed'&&change.field==='recurrence');assert.equal(change.userOwner,'creator');assert.equal(view.value.status,personalKeep?'conflict':'comparing');assert.equal(stableAuthoringJson(change.oldSourceValue)===stableAuthoringJson(change.userValue),!personalKeep);assert.equal(stableAuthoringJson(f),before);}
});
test('NS13 recurrence conflict survives decisions/later/defer/reentry without changing values, receipts, authority or owner writes',()=>{
 const f=recurrenceStatusFixture(true),base=stableAuthoringJson(f.owner),read=(s:CreatorNativeSourceSession)=>{const r=readCreatorNativeSourceSession(s,f.owner,f.authority);assert(r.ok);return r.value;};let session=f.session;
 const initial=read(session),change=initial.changes[0];assert(change.kind==='changed');const facts=(v:typeof initial)=>{const c=v.changes[0];assert(c.kind==='changed');return stableAuthoringJson({old:c.oldSourceValue,working:c.userValue,incoming:c.incomingSourceValue,comparison:v.comparison});},expected=facts(initial);
 for(const [index,decision]of (['keep_working','use_incoming','later'] as const).entries()){const result=event(session,f.owner,f.authority,{kind:'decision',changeId:change.changeId,decision},'decision-'+index);assert(!result.ownerChanged);session=result.session;const view=read(session);assert.equal(view.status,'conflict');assert.equal(facts(view),expected);assert.equal(view.decisions[0].decision,decision);}
 assert(!transitionCreatorNativeSourceSession(session,f.owner,{expectedSession:session,authority:f.authority,event:{kind:'apply'},requestId:'blocked-later'},NOW).ok);
 session=event(session,f.owner,f.authority,{kind:'defer'},'defer-conflict').session;assert.equal(read(session).status,'deferred');const saved=serializeCreatorNativeSourceSession(session);assert(saved.ok);const reloaded=hydrateCreatorNativeSourceSession(saved.value);assert(reloaded.ok);session=reloaded.value;assert.equal(read(session).status,'deferred');
 session=event(session,f.owner,f.authority,{kind:'decision',changeId:change.changeId,decision:'keep_working'},'reopen').session;assert.equal(read(session).status,'conflict');assert.equal(facts(read(session)),expected);
 const denied=transitionCreatorNativeSourceSession(session,f.owner,{expectedSession:session,authority:{...f.authority,permission:false},event:{kind:'apply'},requestId:'denied'},NOW);assert(!denied.ok);assert.equal(stableAuthoringJson(f.owner),base);
 const applied=event(session,f.owner,f.authority,{kind:'apply'},'final-apply'),view=readCreatorNativeSourceSession(applied.session,applied.owner,f.authority);assert(view.ok);assert.equal(view.value.status,'undo-available');assert.deepEqual(view.value.receipt?.sideEffects,{publish:0,network:0,operatingWrite:0,privateExecutionWrite:0});
 const encoded=serializeCreatorNativeSourceSession(applied.session);assert(encoded.ok);const loaded=hydrateCreatorNativeSourceSession(encoded.value);assert(loaded.ok);const replay=readCreatorNativeSourceSession(loaded.value,applied.owner,f.authority);assert(replay.ok);assert.deepEqual(replay.value.receipt,view.value.receipt);const undone=event(loaded.value,applied.owner,f.authority,{kind:'undo'},'source-undo');assert.equal(stableAuthoringJson(undone.owner),base);assert.equal(read(undone.session).status,'reverted');
});
