import test from 'node:test';import assert from 'node:assert/strict';
import {nativeExecutionFixture,saveNativeExecutionFixture,handoffNativeFixture,nativeExecOk,NATIVE_EXEC_NOW as NOW} from './creator-native-execution.test';
import {createTextAuthoringDocument} from './native-creator-vendor/text-authoring/parser';
import {createAuthoringSourceUpdateCandidate} from './native-creator-vendor/text-authoring/source-update';
import {applyNativeCreatorDocumentOperation,applyNativeCreatorSourceDecision,applyNativeCreatorSourceSession,readNativeCreatorDocument} from './native-creator-document';
import {setProgramCreatorWorking} from './creator-workspace';
import {programClone} from './contract';
import {validateProgramData} from './program-data';
import {programNativeExecutionDocument,programNativeExecutionItemFacts} from './creator-native-execution-facts';
import {resolveProgramNativeExecutionSource} from './creator-native-execution-source';
import {programNativeExecutionRef} from './creator-native-execution-contract';
import {readProgramExecutionOccurrences} from './recurrence-state';
import {textWorkspaceModel as M} from './text-workspace';
function absenceFixture(recurrence=false,decision:'keep_working'|'use_incoming'='keep_working'){const f=nativeExecutionFixture('# Absent\n- [ ] Work');let owner=f.data.spaces[f.actorId].creatorWorkspace!.working!.nativeDocument!;
 const incoming=createTextAuthoringDocument('# Absent\n- [ ] Work\n  date: 2026-09-20\n  time: 10:00\n  timezone: Asia/Seoul'+(recurrence?'\n  repeat: 매일\n  repeat_end: 3회':'')+'\n  completion: SOURCE COMPLETION',{documentId:owner.document.documentId,ownership:'creator',sourceExternalVersion:'b',now:NOW}),candidate=createAuthoringSourceUpdateCandidate(incoming,{capturedAt:NOW,externalVersion:'b',matches:[{activeItemId:owner.document.parseResult.canonical.items[0].itemId,incomingItemId:incoming.parseResult.canonical.items[0].itemId,basis:'explicit'}]});
 const staged=applyNativeCreatorDocumentOperation(owner,{expectedOwner:owner,requestId:'stage',operation:{type:'stage_source_update',candidate}},NOW);assert(staged.ok,JSON.stringify(staged));owner=staged.owner;const state=owner.document.sourceState;assert(state&&state.status!=='current');
 for(const change of [...state.changes,...(owner.sourceRecurrences?.pending?.changes??[])]){const chosen=applyNativeCreatorSourceDecision(owner,{expectedOwner:owner,requestId:'choose-'+change.changeId,decision:{decisionVersion:1,changeId:change.changeId,decision}},NOW);assert(chosen.ok);owner=chosen.owner;}
 const applied=applyNativeCreatorSourceSession(owner,{expectedOwner:owner,requestId:'apply-v2'},NOW,2);assert(applied.ok,JSON.stringify(applied));owner=applied.owner;if(decision==='keep_working'){assert(owner.effectiveAbsences?.entries.some(e=>e.field==='schedule'));assert(owner.effectiveAbsences?.entries.some(e=>e.field==='completion'));}
 const w=f.data.spaces[f.actorId].creatorWorkspace!.working!;f.data=nativeExecOk(setProgramCreatorWorking(f.data,{actorId:f.actorId,expectedWorking:w,working:{...w,rawText:owner.document.rawText,nativeDocument:owner}},NOW)).data;f.data=saveNativeExecutionFixture(f.data,'save-absence');return{...f,owner,incoming};
}
test('NEA01 actual v2 kept schedule/completion absence does not revive raw recurrence, date, time or completion in execution',()=>{
 const f=absenceFixture(),original=JSON.stringify(f.owner),effective=programNativeExecutionDocument(f.owner),item=effective.parseResult.canonical.items[0],facts=programNativeExecutionItemFacts(item);assert.equal(item.schedule,undefined);assert.equal(item.completion,undefined);assert.equal(facts.rule,null);assert.equal(facts.date,null);assert.equal(facts.time,null);assert.equal(facts.timeZone,null);assert.equal(facts.kind,'ordinary');
 const result=handoffNativeFixture(f.data),space=result.data.spaces[f.actorId],owner=space.creatorWorkspace!.nativeExecutionSources![f.draftId];assert.equal(owner.revisions[0].rows[0].kind,'ordinary');const tasks=M.tasks(space.text).filter(t=>t.docId===result.result);assert.equal(tasks.length,1);assert.equal(tasks[0].date,null);assert.equal(tasks[0].time,null);assert(!M.raw(M.getDocument(space.text,result.result)).includes('SOURCE COMPLETION'));assert.equal(space.text.progressRecords.length,0);assert.equal(JSON.stringify(f.owner),original);assert.deepEqual(result.data.public,f.data.public);assert(validateProgramData(JSON.parse(JSON.stringify(result.data))));
 const source=resolveProgramNativeExecutionSource(space,programNativeExecutionRef(owner.id));assert(source?.ok);assert.equal([...source.contexts.values()][0].attributes.nativeRule,null);const read=readProgramExecutionOccurrences(result.data,{actorId:f.actorId,flowRef:programNativeExecutionRef(owner.id),localToday:'2026-09-13'});assert(read.ok,read.ok?'':read.reason);assert.equal(read.rows.length,0);
});
test('NEA02 persisted native execution kind tamper cannot use the preserved source recurrence to bypass effective absence',()=>{
 const f=absenceFixture(),data=handoffNativeFixture(f.data).data,bad=programClone(data),row=bad.spaces[f.actorId].creatorWorkspace!.nativeExecutionSources![f.draftId].revisions[0].rows[0];row.kind='series';row.lines[0].text='반복 규칙: Work';assert(!validateProgramData(bad));assert(validateProgramData(data));
});
test('NEA03 actual recurring candidate three-way keep decision saves and hands off without resurrecting a single occurrence',()=>{
 const f=absenceFixture(true),before=JSON.stringify(f.data),core=readNativeCreatorDocument(f.owner);assert(core.ok);assert.deepEqual(programNativeExecutionDocument(f.owner),core.document);
 const sourceRule=f.owner.sourceRecurrences!.sourceRules.find(r=>r.itemId===f.incoming.parseResult.canonical.items[0].itemId)!;assert.equal(sourceRule.rule!.end?.mode,'count');assert.equal(sourceRule.rule!.end?.mode==='count'?sourceRule.rule!.end.count:null,3);assert.equal(sourceRule.workingRule,null);assert.equal(f.owner.source.documentJson,f.source.documentJson);
 const r=handoffNativeFixture(f.data),space=r.data.spaces[f.actorId],owner=space.creatorWorkspace!.nativeExecutionSources![f.draftId],source=resolveProgramNativeExecutionSource(space,programNativeExecutionRef(owner.id));assert(source?.ok);const facts=[...source.contexts.values()][0].attributes;assert.equal(facts.nativeRule,null);assert.equal(facts.date,null);assert.equal(facts.time,null);assert.equal(facts.timeZone,null);
 const read=readProgramExecutionOccurrences(r.data,{actorId:f.actorId,flowRef:programNativeExecutionRef(owner.id),localToday:'2026-09-13'});assert(read.ok,read.ok?'':read.reason);assert.equal(read.rows.length,0);assert.equal(owner.revisions[0].rows[0].kind,'ordinary');assert.equal(M.tasks(space.text).filter(t=>t.docId===r.result).length,1);assert.equal(space.text.progressRecords.length,0);assert.equal(JSON.stringify(f.data),before);assert(validateProgramData(JSON.parse(JSON.stringify(r.data))));
});
test('NEA04 explicit incoming recurrence/schedule choice produces the actual three source occurrences and preserves source timezone',()=>{
 const f=absenceFixture(true,'use_incoming'),r=handoffNativeFixture(f.data),space=r.data.spaces[f.actorId],owner=space.creatorWorkspace!.nativeExecutionSources![f.draftId],read=readProgramExecutionOccurrences(r.data,{actorId:f.actorId,flowRef:programNativeExecutionRef(owner.id),localToday:'2026-09-13'});assert(read.ok,read.ok?'':read.reason);assert.equal(owner.revisions[0].rows[0].kind,'series');assert.equal(read.rows.length,3);assert.deepEqual(read.rows.map(row=>row.originalDate),['2026-09-20','2026-09-21','2026-09-22']);assert(read.rows.every(row=>row.time==='10:00'&&row.timeZone==='Asia/Seoul'&&row.completion!=='completed'));assert.equal(M.tasks(space.text).filter(t=>t.docId===r.result).length,0);assert.equal(f.owner.source.documentJson,f.source.documentJson);assert.deepEqual(r.data.public,f.data.public);assert(validateProgramData(JSON.parse(JSON.stringify(r.data))));
 const bad=programClone(r.data);bad.spaces[f.actorId].creatorWorkspace!.nativeExecutionSources![f.draftId].revisions[0].nativeDocument.sourceRecurrences!.sourceRules[0].rule!.raw='매주';assert(!validateProgramData(bad));
});
