import assert from 'node:assert/strict';import test from 'node:test';
import {readFileSync} from 'node:fs';import {resolve,dirname} from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';import ts from 'typescript';
import {createTextAuthoringDocument} from './native-creator-vendor/text-authoring/parser';
import {applyAuthoringOperation} from './native-creator-vendor/text-authoring/operations';
import {buildAuthoringArtifactProjection} from './native-creator-vendor/text-authoring/artifact-projection';
import {createNativeCreatorDocumentOwner,applyNativeCreatorDocumentOperation,restoreNativeCreatorDocument,readNativeCreatorDocument,updateNativeCreatorRecordUi,validateNativeCreatorDocumentOwner,validateNativeCreatorDocument} from './native-creator-document';
import type {NativeCreatorDocumentOwner,NativeCreatorDocumentSource,TextAuthoringDocument,AuthoringCorrectionOperation} from './native-creator-document-contract';
const NOW='2026-09-12T01:00:00.000Z',NEXT='2026-09-12T01:01:00.000Z';
const RAW='# 원래 자료\n- 기준일: 2026-09-20\n## 준비\n- [ ] 첫 준비\n  - 날짜: 2026-09-20\n  - 시간: 09:00\n- [ ] 둘째 준비\n  - 상대 날짜: D-2';
function source(document:TextAuthoringDocument,versionId='actual-save-1'):NativeCreatorDocumentSource{return{storageKey:'flow:text-authoring:drafts:v1',draftId:'native-draft',versionId,revisionId:document.revision.revisionId,documentJson:JSON.stringify(document)};}
function savedSource(owner:NativeCreatorDocumentOwner){const source=owner.source;assert('versionId' in source&&source.storageKey==='flow:text-authoring:drafts:v1');return source;}
function fixture(raw=RAW){const document=createTextAuthoringDocument(raw,{documentId:'native-document',ownership:'creator',now:NOW});const result=createNativeCreatorDocumentOwner({id:'private-native-owner',source:source(document),currentRecordUi:{activeStage:'structure',selectedItemId:document.parseResult.canonical.items[0].itemId,primaryArtifact:'todo'}},NOW);assert(result.ok);return result.owner;}
function edit(owner:NativeCreatorDocumentOwner,operation:AuthoringCorrectionOperation,requestId='edit'){const result=applyNativeCreatorDocumentOperation(owner,{expectedOwner:owner,requestId,operation},NEXT);assert(result.ok);return result.owner;}
const sorted=(value:any):any=>Array.isArray(value)?value.map(sorted):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(key=>[key,sorted(value[key])])):value;

test('NC01 vendor copies pinned original bytes with a closed relative source graph and no storage/UI/network imports',()=>{
 const base=resolve(dirname(fileURLToPath(import.meta.url)),'native-creator-vendor'),manifest=JSON.parse(readFileSync(resolve(base,'manifest.json'),'utf8')),paths=new Set(manifest.files.map((f:any)=>f.path));assert.equal(paths.size,26);
 for(const file of manifest.files){const bytes=readFileSync(resolve(base,file.path));assert.equal(createHash('sha256').update(bytes).digest('hex'),file.sha256);const text=bytes.toString('utf8');const ast=ts.createSourceFile(file.path,text,ts.ScriptTarget.Latest,true);
  function visit(node:ts.Node){if(ts.isImportDeclaration(node)||ts.isExportDeclaration(node)){if(node.moduleSpecifier&&ts.isStringLiteral(node.moduleSpecifier)){const spec=node.moduleSpecifier.text;assert(spec.startsWith('.'));const target=resolve(dirname(resolve(base,file.path)),spec+'.ts').slice(base.length+1).replaceAll('\\','/');assert(paths.has(target));assert(!/storage|Workspace|controller|program-data/.test(target));}}
   if(ts.isIdentifier(node)&&['localStorage','sessionStorage','fetch','XMLHttpRequest','indexedDB'].includes(node.text))assert.fail(`forbidden runtime owner: ${file.path}:${node.text}`);ts.forEachChild(node,visit);}
  visit(ast);
 }
});
test('NC02 full saved context creation preserves exact source JSON/canonical IDs and never reparses same raw',()=>{const original=fixture(),item=original.document.parseResult.canonical.items[0],excluded=applyAuthoringOperation(original.document,{type:'exclude',itemId:item.itemId},{actorLane:'creator',now:NEXT});const created=createNativeCreatorDocumentOwner({id:'excluded-owner',source:source(excluded,'saved-excluded')},NEXT);assert(created.ok);assert.equal(created.owner.document.rawText,original.document.rawText);assert.equal(created.owner.document.parseResult.canonical.items[0].included,false);assert.equal(created.owner.source.documentJson,JSON.stringify(excluded));assert.deepEqual(created.owner.document,JSON.parse(JSON.stringify(excluded)));});
test('NC03 same raw role/inclusion/order edits match original pure operation and preserve source immutable',()=>{const initial=fixture(),before=JSON.stringify(initial),[a,b]=initial.document.parseResult.canonical.items;let actual=initial,oracle=initial.document;
 for(const [i,operation] of ([{type:'exclude',itemId:a.itemId},{type:'change_role',itemId:b.itemId,role:'guide'},{type:'reorder',itemId:b.itemId,toIndex:0}] as AuthoringCorrectionOperation[]).entries()){actual=edit(actual,operation,`op${i}`);oracle=applyAuthoringOperation(oracle,operation,{actorLane:'creator',now:NEXT});assert.deepEqual(actual.document,JSON.parse(JSON.stringify(oracle)));}
 assert.equal(actual.document.rawText,initial.document.rawText);assert.equal(actual.source.documentJson,initial.source.documentJson);assert.equal(JSON.stringify(initial),before);assert.equal(actual.actions.length,3);
});
test('NC04 full restore changes included state even when raw matches; history and current record UI remain',()=>{const initial=fixture(),a=initial.document.parseResult.canonical.items[0],changed=edit(initial,{type:'exclude',itemId:a.itemId});const restore=restoreNativeCreatorDocument(changed,{expectedOwner:changed,requestId:'restore-full',source:savedSource(initial)},NEXT);assert(restore.ok);assert(restore.changed);assert.deepEqual(restore.owner.document,initial.document);assert.deepEqual(restore.owner.recordUi,changed.recordUi);assert.equal(restore.owner.actions.length,2);assert.deepEqual(restore.owner.actions[0],changed.actions[0]);assert.equal(restore.owner.source.documentJson,initial.source.documentJson);});
test('NC05 canonical sorted serialization/reload validates exact journal and same request is idempotent',()=>{const initial=fixture(),operation={type:'exclude',itemId:initial.document.parseResult.canonical.items[0].itemId} as const,changed=edit(initial,operation);const reloaded=sorted(changed);assert(validateNativeCreatorDocumentOwner(reloaded));const retry=applyNativeCreatorDocumentOperation(reloaded,{expectedOwner:initial,requestId:'edit',operation},NEXT);assert(retry.ok);assert.equal(retry.owner,reloaded);assert(!retry.changed);const different=applyNativeCreatorDocumentOperation(reloaded,{expectedOwner:reloaded,requestId:'edit',operation:{type:'include',itemId:operation.itemId}},NEXT);assert(!different.ok);assert.equal(different.reason,'conflict');});
test('NC06 stale owner, forged canonical state/source revision, unknown operation and codec fail closed',()=>{const initial=fixture(),changed=edit(initial,{type:'exclude',itemId:initial.document.parseResult.canonical.items[0].itemId});assert(!applyNativeCreatorDocumentOperation(changed,{expectedOwner:initial,requestId:'stale',operation:{type:'undo'}},NEXT).ok);
 for(const mutate of [(o:any)=>o.document.parseResult.canonical.items[0].title='forged',(o:any)=>o.source.revisionId='foreign',(o:any)=>o.actions[0].requestId='',(o:any)=>o.document.parseResult.canonical.items.push(o.document.parseResult.canonical.items[0])]){const bad=structuredClone(changed);mutate(bad);assert(!validateNativeCreatorDocumentOwner(bad));}
 assert(!applyNativeCreatorDocumentOperation(initial,{expectedOwner:initial,requestId:'unknown',operation:{type:'clear-all'} as any},NEXT).ok);const bad=JSON.parse(initial.source.documentJson);bad.schemaVersion='future';assert(!createNativeCreatorDocumentOwner({id:'bad',source:{...initial.source,documentJson:JSON.stringify(bad)}},NEXT).ok);
});
test('NC07 no-op includes and exact restores do not add private revision/request receipts',()=>{const initial=fixture();const same=applyNativeCreatorDocumentOperation(initial,{expectedOwner:initial,requestId:'noop',operation:{type:'include',itemId:initial.document.parseResult.canonical.items[0].itemId}},NEXT);assert(same.ok);assert.equal(same.owner,initial);assert(!same.changed);const restored=restoreNativeCreatorDocument(initial,{expectedOwner:initial,requestId:'same-source',source:savedSource(initial)},NEXT);assert(restored.ok);assert.equal(restored.owner,initial);assert.equal(initial.actions.length,0);});
test('NC08 source restore cannot retarget a different original document/draft or redefine a seen saved version',()=>{const initial=fixture(),other=createTextAuthoringDocument(RAW,{documentId:'foreign',ownership:'creator',now:NOW});for(const candidate of [source(other),{...savedSource(initial),draftId:'other'},source(applyAuthoringOperation(initial.document,{type:'exclude',itemId:initial.document.parseResult.canonical.items[0].itemId},{now:NEXT}))])assert(!restoreNativeCreatorDocument(initial,{expectedOwner:initial,requestId:'retarget',source:candidate},NEXT).ok);});
test('NC09 UI record selection/artifact is separately undoable and full restore retains latest UI',()=>{const initial=fixture();const update=updateNativeCreatorRecordUi(initial,{expectedOwner:initial,requestId:'ui',recordUi:{activeStage:'result',primaryArtifact:'calendar',selectedItemId:initial.document.parseResult.canonical.items[1].itemId}},NEXT);assert(update.ok);assert.deepEqual(update.owner.document,initial.document);assert.equal(update.owner.recordUi.primaryArtifact,'calendar');assert(validateNativeCreatorDocumentOwner(sorted(update.owner)));assert.equal(readNativeCreatorDocument(update.owner).ok,true);});
test('NC10 same saved canonical context produces exact native projections for every artifact and limits',()=>{for(const raw of [RAW,'# 유한\n- [ ] 반복\n  - 날짜: 2026-09-14\n  - 반복: 매주 월\n  - 반복 종료: 2026-10-05','# 무기한\n- [ ] 반복\n  - 날짜: 2026-09-14\n  - 반복: 매주 월']){const owner=fixture(raw);for(const options of [{finiteOccurrenceLimit:2,openEndedOccurrenceWeeks:4},{finiteOccurrenceLimit:30,openEndedOccurrenceWeeks:8}]){const read=readNativeCreatorDocument(owner,options);assert(read.ok);assert.deepEqual(read.projection,buildAuthoringArtifactProjection(owner.document,{primaryArtifact:'todo',...options}));assert.deepEqual(read.document,owner.document);}}});
test('NC11 malformed projection limits/dates fail without mutation and fixed-date options do not mutate canonical',()=>{const initial=fixture(),before=JSON.stringify(initial);for(const options of [{finiteOccurrenceLimit:0},{openEndedOccurrenceWeeks:Infinity},{anchor:'2026-02-30'},{primaryArtifact:'unknown' as any}])assert(!readNativeCreatorDocument(initial,options).ok);assert.equal(JSON.stringify(initial),before);});
test('NC12 source review gates and UI state survive import/edit/restore without approving a held source',()=>{const doc=createTextAuthoringDocument(RAW,{documentId:'native-document',ownership:'creator',reviewRequirements:[{kind:'safety',reasonKey:'medical'}],now:NOW});const owner=createNativeCreatorDocumentOwner({id:'held',source:source(doc)},NOW);assert(owner.ok);const changed=edit(owner.owner,{type:'exclude',itemId:doc.parseResult.canonical.items[0].itemId});assert.deepEqual(changed.document.reviewGates,doc.reviewGates);assert.deepEqual(changed.document.uiState,doc.uiState);assert.equal(changed.document.lifecycleStatus,'needs_review');const restored=restoreNativeCreatorDocument(changed,{expectedOwner:changed,requestId:'restore-held',source:savedSource(owner.owner)},NEXT);assert(restored.ok);assert.deepEqual(restored.owner.document.reviewGates,doc.reviewGates);});
test('NC13 core create/edit/read/restore uses zero global storage or network access',()=>{const names=['localStorage','sessionStorage','fetch'] as const,previous=names.map(name=>Object.getOwnPropertyDescriptor(globalThis,name));let calls=0;try{names.forEach(name=>Object.defineProperty(globalThis,name,{configurable:true,get(){calls++;throw Error('forbidden global');}}));const owner=fixture(),changed=edit(owner,{type:'exclude',itemId:owner.document.parseResult.canonical.items[0].itemId});assert(readNativeCreatorDocument(changed).ok);assert(restoreNativeCreatorDocument(changed,{expectedOwner:changed,requestId:'restore',source:savedSource(owner)},NEXT).ok);assert.equal(calls,0);}finally{names.forEach((name,i)=>{if(previous[i])Object.defineProperty(globalThis,name,previous[i]!);else Reflect.deleteProperty(globalThis,name);});}});
test('NC14 malformed native context remains unsupported rather than raw-only successful recovery',()=>{const document=fixture().document;for(const mutate of [(v:any)=>delete v.parseResult.canonical.sourceRows,(v:any)=>v.extraContext={notSupported:true},(v:any)=>v.ownership='personal',(v:any)=>v.rawText='x'.repeat(100001)]){const bad=structuredClone(document);mutate(bad);assert(!validateNativeCreatorDocument(bad));}});
test('NC15 raw input sync reuses actual native revision operation and immutable captured source',()=>{const initial=fixture(),operation={type:'sync_working_text_from_input',rawText:RAW.replace('첫 준비','수정한 첫 준비')} as const;const next=edit(initial,operation);const oracle=applyAuthoringOperation(initial.document,operation,{actorLane:'creator',now:NEXT});assert.deepEqual(next.document,JSON.parse(JSON.stringify(oracle)));assert.equal(next.source.documentJson,initial.source.documentJson);assert.deepEqual(next.document.sourceState?.active,initial.document.sourceState?.active);assert.equal(next.document.parseResult.canonical.items[0].itemId,initial.document.parseResult.canonical.items[0].itemId);assert(validateNativeCreatorDocumentOwner(sorted(next)));});
test('NC16 finite until projection exact dates and expansion limits retain stable occurrence identity',()=>{const owner=fixture('# 유한\n- [ ] 반복\n  - 날짜: 2026-09-14\n  - 반복: 매주 월\n  - 반복 종료: 2026-10-05');const first=readNativeCreatorDocument(owner,{finiteOccurrenceLimit:2}),all=readNativeCreatorDocument(owner,{finiteOccurrenceLimit:30});assert(first.ok&&all.ok);const a=first.projection.artifacts.calendar,b=all.projection.artifacts.calendar;assert.deepEqual(a.rows.map(r=>r.date),['2026-09-14','2026-09-21']);assert.deepEqual(b.rows.map(r=>r.date),['2026-09-14','2026-09-21','2026-09-28','2026-10-05']);assert.equal(a.recurrenceSummaries[0].totalCount,4);assert.equal(a.recurrenceSummaries[0].hasMore,true);assert.equal(b.recurrenceSummaries[0].hasMore,false);assert.deepEqual(a.rows.map(r=>r.rowId),b.rows.slice(0,2).map(r=>r.rowId));assert.equal(new Set(b.rows.map(r=>r.rowId)).size,4);});
test('NC17 open-ended 4/8-week previews match real expander exact windows without pretending completion',()=>{const owner=fixture('# 계속\n- [ ] 반복\n  - 날짜: 2026-09-14\n  - 반복: 매주 월');const short=readNativeCreatorDocument(owner,{openEndedOccurrenceWeeks:4}),long=readNativeCreatorDocument(owner,{openEndedOccurrenceWeeks:8});assert(short.ok&&long.ok);const a=short.projection.artifacts.calendar,b=long.projection.artifacts.calendar;assert.deepEqual(a.rows.map(r=>r.date),['2026-09-14','2026-09-21','2026-09-28','2026-10-05']);assert.deepEqual(b.rows.map(r=>r.date),['2026-09-14','2026-09-21','2026-09-28','2026-10-05','2026-10-12','2026-10-19','2026-10-26','2026-11-02']);assert.equal(b.recurrenceSummaries[0].mode,'open_ended');assert.equal(b.recurrenceSummaries[0].hasMore,true);assert.equal(b.recurrenceSummaries[0].totalCount,undefined);assert.deepEqual(a.rows.map(r=>r.occurrenceId),b.rows.slice(0,4).map(r=>r.occurrenceId));});
test('NC18 two private owners share immutable provenance but editing one never mutates the other',()=>{const a=fixture(),created=createNativeCreatorDocumentOwner({id:'independent-b',source:a.source,currentRecordUi:a.recordUi},NOW);assert(created.ok);const before=JSON.stringify(created.owner),changed=edit(a,{type:'set_property',itemId:a.document.parseResult.canonical.items[0].itemId,key:'time',value:'11:30'});assert.equal(JSON.stringify(created.owner),before);assert.equal(changed.source.documentJson,a.source.documentJson);assert.notDeepEqual(changed.document,a.document);assert.equal(readNativeCreatorDocument(changed).ok,true);});
test('NC19 native operation Undo and Program owner snapshot Undo remain separate exact histories',()=>{const original=fixture(),changed=edit(original,{type:'exclude',itemId:original.document.parseResult.canonical.items[0].itemId});const undone=edit(changed,{type:'undo'},'native-undo');assert.equal(undone.document.parseResult.canonical.items[0].included,true);assert.equal(undone.actions.length,2);assert.deepEqual(undone.document,JSON.parse(JSON.stringify(applyAuthoringOperation(changed.document,{type:'undo'},{actorLane:'creator',now:NEXT}))));const programUndo=sorted(changed);assert(validateNativeCreatorDocumentOwner(programUndo));assert.equal(programUndo.document.parseResult.canonical.items[0].included,false);assert.equal(programUndo.actions.length,1);});
