import assert from 'node:assert/strict';import test from 'node:test';
import {createNativeOwnerReplayCache,NATIVE_OWNER_CACHE_MAX_ENTRY_BYTES,NATIVE_OWNER_CACHE_MAX_TOTAL_BYTES} from './native-owner-replay-cache';
import {createTextAuthoringDocument} from './native-creator-vendor/text-authoring/parser';
import {createNativeCreatorDocumentOwner,validateNativeCreatorDocumentOwner,readNativeCreatorDocument} from './native-creator-document';
test('NOR01 exact content, mutable input and returned result isolation',()=>{let calls=0;const cache=createNativeOwnerReplayCache((v:any)=>{calls++;return v.valid?{nested:{text:v.text}}:null});const input={valid:true,text:'A'};const first=cache.read(input)!;first.nested.text='tampered';assert.equal(cache.read({...input})!.nested.text,'A');assert.equal(calls,1);input.valid=false;assert.equal(cache.read(input),null);assert.equal(cache.read(input),null);assert.equal(calls,3);assert.equal(cache.stats().hits,1);});
test('NOR02 descriptor-safe checks precede a hit and never invoke getters',()=>{let invoked=0;const cache=createNativeOwnerReplayCache(()=>({ok:true}));assert(cache.read({a:1}));const getter=Object.defineProperty({},'a',{enumerable:true,get(){invoked++;return 1}});assert.equal(cache.read(getter),null);assert.equal(invoked,0);for(const value of [new Date(),[,,],{a:undefined},{a:NaN},Object.assign({a:1},{[Symbol('x')]:1})])assert.equal(cache.read(value),null);const cycle:any={};cycle.self=cycle;assert.equal(cache.read(cycle),null);});
test('NOR03 key order change is a miss, not a canonical hash collision',()=>{let calls=0;const cache=createNativeOwnerReplayCache(v=>{calls++;return {v}});cache.read({a:1,b:2});cache.read({b:2,a:1});assert.equal(calls,2);cache.read({a:1,b:2});assert.equal(calls,2);assert.equal(cache.stats().hits,1);});
test('NOR04 LRU/count/byte bounds and oversized values keep full validation',()=>{let calls=0;const cache=createNativeOwnerReplayCache(()=>{calls++;return {ok:true}});for(let i=0;i<20;i++)assert(cache.read({i,text:'x'.repeat(120000)}));assert(cache.stats().entries<=8);assert(cache.stats().bytes<=NATIVE_OWNER_CACHE_MAX_TOTAL_BYTES);const before=calls,large={text:'x'.repeat(NATIVE_OWNER_CACHE_MAX_ENTRY_BYTES)};assert(cache.read(large));assert(cache.read(large));assert.equal(calls,before+2);});
test('NOR05 genuine parser owner survives canonical reload; forged current/history stays invalid after warm hit',()=>{const now='2026-09-12T08:00:00.000Z',document=createTextAuthoringDocument('# 원문\n- [ ] 준비\n  - 날짜: 2026-09-20',{documentId:'cache-source',ownership:'creator',now});const created=createNativeCreatorDocumentOwner({id:'cache-owner',source:{storageKey:'flow:text-authoring:drafts:v1',draftId:'cache-draft',versionId:'saved-fixture-1',revisionId:document.revision.revisionId,documentJson:JSON.stringify(document)}},now);assert(created.ok);const owner=created.owner,original=JSON.stringify(owner);assert(validateNativeCreatorDocumentOwner(owner));const reorder=(v:any):any=>Array.isArray(v)?v.map(reorder):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,reorder(v[k])])):v;assert(validateNativeCreatorDocumentOwner(JSON.parse(JSON.stringify(reorder(owner)))));owner.document.parseResult.canonical.items[0].title='forged';assert.equal(validateNativeCreatorDocumentOwner(owner),false);const restored=JSON.parse(original);assert(validateNativeCreatorDocumentOwner(restored));restored.revision++;assert.equal(validateNativeCreatorDocumentOwner(restored),false);const read=readNativeCreatorDocument(JSON.parse(original));assert(read.ok);assert.equal(JSON.stringify(created.owner.source),JSON.stringify(JSON.parse(original).source));});
test('NOR06 an applied source owner and its replay result reuse validation within the unchanged total budget',()=>{
 let calls=0;const cache=createNativeOwnerReplayCache((value:any)=>{calls++;return value.valid?{text:'r'.repeat(128_068)}:null;});
 // Genuine post-apply source/private owner: 168126 chars + replay 128068 chars.
 // The former 512 KiB per-entry limit caused every retained Undo to replay it.
 const input={valid:true,text:'s'.repeat(168_126)};
 const first=cache.read(input)!;first.text='caller mutation';
 assert.equal(cache.read(structuredClone(input))!.text.length,128_068);assert(cache.read(input));
 assert.equal(calls,1);assert.equal(cache.stats().hits,2);
 assert(cache.stats().bytes>512*1024);assert(cache.stats().bytes<=NATIVE_OWNER_CACHE_MAX_TOTAL_BYTES);
 input.valid=false;assert.equal(cache.read(input),null);assert.equal(calls,2);
});
