import { toPersonalWorkspacePocFlowRef,type PersonalWorkspacePocFlow } from '../personal-workspace-poc-contract';
export type ProgramLegacyMapChildMode = { mode:'follow-group' } | { mode:'fixed-child'; anchor:string };
export type ProgramLegacyMapPlanSelection = { ownerId:string; sourceToken:string; childFlowRefs:string[]; personalAnchor?:string; childModes:Record<string,ProgramLegacyMapChildMode>; retainedChildren?:Record<string,{sourceToken:string;mode:ProgramLegacyMapChildMode}> };
const record=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v)&&[Object.prototype,null].includes(Object.getPrototypeOf(v))&&Object.entries(Object.getOwnPropertyDescriptors(v)).every(([k,d])=>!['__proto__','constructor','prototype'].includes(k)&&'value'in d);
const id=(v:unknown):v is string=>typeof v==='string'&&v.length>0&&v.length<=1200&&!['__proto__','constructor','prototype'].includes(v);
const date=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d\d-\d\d$/.test(v)&&Number.isFinite(Date.parse(v+'T00:00:00Z'))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v;
const validMode=(mode:unknown)=>record(mode)&&(mode.mode==='follow-group'?Object.keys(mode).length===1:mode.mode==='fixed-child'&&Object.keys(mode).length===2&&date(mode.anchor));
export function validateProgramLegacyMapPlanGroups(v:unknown):v is Record<string,ProgramLegacyMapPlanSelection>{
 return record(v)&&Object.entries(v).every(([ref,g])=>id(ref)&&record(g)&&Object.keys(g).every(k=>['ownerId','sourceToken','childFlowRefs','personalAnchor','childModes','retainedChildren'].includes(k))&&id(g.ownerId)&&typeof g.sourceToken==='string'&&g.sourceToken.length>0&&g.sourceToken.length<=8000000&&Array.isArray(g.childFlowRefs)&&g.childFlowRefs.length>0&&g.childFlowRefs.every(id)&&new Set(g.childFlowRefs).size===g.childFlowRefs.length&&(g.personalAnchor===undefined||date(g.personalAnchor))&&record(g.childModes)&&Object.keys(g.childModes).length===g.childFlowRefs.length&&Object.entries(g.childModes).every(([child,mode])=>(g.childFlowRefs as string[]).includes(child)&&validMode(mode))&&(g.retainedChildren===undefined||record(g.retainedChildren)&&Object.entries(g.retainedChildren).every(([child,row])=>id(child)&&!(g.childFlowRefs as string[]).includes(child)&&record(row)&&Object.keys(row).length===2&&typeof row.sourceToken==='string'&&row.sourceToken.length<=8000000&&validMode(row.mode)&&tokenOwns(row.sourceToken,ref,g.ownerId as string,child))));
}
function tokenOwns(token:string,groupRef:string,ownerId:string,childRef:string):boolean{try{const parsed=JSON.parse(token);if(parsed.groupRef!==groupRef||parsed.ownerId!==ownerId||!Array.isArray(parsed.children))return false;const child=parsed.children.find((c:any)=>c.ref===childRef);if(!child||typeof child.sourceToken!=='string')return false;const flow=JSON.parse(child.sourceToken).flow;return id(flow.savedCopyId)&&id(flow.flowId)&&toPersonalWorkspacePocFlowRef(flow.savedCopyId,flow.flowId)===childRef&&flow.ref===childRef&&flow.presentation?.mapGroup?.groupRef===groupRef&&flow.presentation.mapGroup.ownerId===ownerId;}catch{return false;}}
/** Catalog membership comes from the genuine saved Map, never titles or child order. */
export function programLegacyMapPlanGroupsMatchSources(groups:Record<string,ProgramLegacyMapPlanSelection>|undefined,flows:readonly PersonalWorkspacePocFlow[]):boolean{
 return !groups||Object.entries(groups).every(([ref,g])=>g.childFlowRefs.every(child=>{const f=flows.find(f=>f.ref===child);return f?f.presentation?.mapGroup?.groupRef===ref&&f.presentation.mapGroup.ownerId===g.ownerId:tokenOwns(g.sourceToken,ref,g.ownerId,child);}));
}
